### ISSUE TITLE
Plugin Request: Localized Strings

### ISSUE THREAD

**Issue by arielgelbard** [ionic-team/ionic-native#1020]
I am currently developing an app that has both french and english. I want to be able to have localizable strings for app names on Android & iOS and for iOS usage descriptions. 

[Usuage Description Cocoa Keys](https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

[cordova-plugin-localization-strings](https://github.com/kelvinhokk/cordova-plugin-localization-strings)

**Comment by ihadeed** [comment]
I recommend you look into https://github.com/ocombe/ng2-translate. You can see how it's used here: https://github.com/driftyco/ionic-starter-super

**Comment by arielgelbard** [comment]
We are using ng2-translate in our app already for the web content...but for the native requirements that need some customization such as the visible app name on the home screen (CFBundleDisplayName) 
![screen shot 2017-02-01 at 1 45 38 pm](https://cloud.githubusercontent.com/assets/5472973/22521219/52960aa2-e885-11e6-9beb-c0d8595f7438.png)
![screen shot 2017-02-01 at 1 48 56 pm](https://cloud.githubusercontent.com/assets/5472973/22521221/5299a22a-e885-11e6-9ad3-e378e4bdf16c.png)
![screen shot 2017-02-01 at 1 49 18 pm](https://cloud.githubusercontent.com/assets/5472973/22521220/5297c2d4-e885-11e6-9a68-d285ca3fe8bd.png)

 or the location description which you can customize in the info.plist (NSLocationUsageDescription) allowances
![screen shot 2017-02-01 at 1 50 37 pm](https://cloud.githubusercontent.com/assets/5472973/22521256/6ec9f18e-e885-11e6-8fb6-64129eb07777.png)
![screen shot 2017-02-01 at 1 57 57 pm](https://cloud.githubusercontent.com/assets/5472973/22521618/974a559e-e886-11e6-95a7-3e28de54cbbe.png)
![screen shot 2017-02-01 at 1 58 49 pm](https://cloud.githubusercontent.com/assets/5472973/22521617/97499c08-e886-11e6-96a4-ab2f35c77693.png)

need a Cordova plugin similar to the one in the link above.

**Comment by ihadeed** [comment]
Just had a look at the plugin. It looks like there aren't any methods that we need to wrap. Looks like everything is configured using the json  files.
