### ISSUE TITLE
Plugin Request: Back as Home

### ISSUE THREAD

**Issue by arielgelbard** [ionic-team/ionic-native#1021]
use this plugin to trigger the home button functionality by pressing back button. Means you can minimize the app by pressing back button instead of calling``` this.platform.exitApp();``` which kills the app. Of course this plugin would only be for android.

[Back as Home](https://github.com/amitsinha559/cordova-plugin-back-as-home)

**Comment by aamir1995** [comment]
Why not use ionic 2 built in method for registering Back button action?
http://ionicframework.com/docs/v2/api/platform/Platform/#registerBackButtonAction

**Comment by arielgelbard** [comment]
I do use the back button method in platform then call the 'back as home' trigger method to trigger a minimize...the plugin you suggest accomplishes the same thing...I am suggesting that a 'minimize' plugin be integrated into Ionic Native....
