### ISSUE TITLE
TODO: RTC plugin

### ISSUE THREAD

**Issue by RazaLabs** [ionic-team/ionic-native#1245]
Any idea or eta when webrtc will be available in ionic-native?

**Comment by ihadeed** [comment]
Could you please provide a link to the repo of this plugin?

**Comment by RazaLabs** [comment]
I preffer this shim to be included
https://github.com/webrtc/adapter
or another
https://github.com/alongubkin/phonertc

**Comment by chetanbnaik** [comment]
+1

**Comment by danielsogl** [comment]
This plugin is not longer in development. Feel free to reopen this feature request with an up to date repository.
