### ISSUE TITLE
NativeAudio.preloadSimple throws `cordova_not_found` error

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-native#1287]
Doing NativeAudio.preloadSimple on browser throws a cordova_not_found error. Can be catched, but if I understand correctly you are catching it yourself so you can `console.warn` instead, right?

**Comment by ihadeed** [comment]
Yes, you're right.

**Comment by AmitMY** [comment]
I am right - so is this expected to be catched, or I am right that you are catching most errors from most plugins?

**Comment by ihadeed** [comment]
We only catch the errors that our decorators generate: `cordova_not_found` and `plugin_not_installed`.

**Comment by AmitMY** [comment]
So, letting you know:
`Error: Uncaught (in promise): cordova_not_available`
When using native audio plugin on serve

**Comment by ihadeed** [comment]
I'm unable to reproduce this with latest version of `@ionic-native/core` and `@ionic-native/native-audio'.

What version of Ionic Native are you using?

**Comment by AmitMY** [comment]
Perhaps it is the way I am doing it..
Version:`3.4.3`

I am using it outside of angular context, so I import the injector, and then:
```
const nativeAudio = injector.get(NativeAudio);
nativeAudio.preloadSimple("ding", "assets/sounds/ding.mp3").then(() => {
    nativeAudio.setVolumeForComplexAsset("ding", 0.3);
});
```

*The injector is the angular injector

**Comment by ihadeed** [comment]
I don't think it makes a difference.

**Comment by AmitMY** [comment]
@ihadeed Repro:
https://github.com/AmitMY/ionic-native-audio-error
How:
- `ionic start` a menu app
- add `@ionic-native/native-audio` to package, module, and app
- inject the `injector`
- when platform ready, inject `NativeAudio` and load something

**Comment by royipressburger** [comment]
@ihadeed This is also relevant to GoogleAnalytics plugin. Should I open a new issue?

**Comment by ihadeed** [comment]
Is this still an issue in latest version?
