### ISSUE TITLE
Plugin request: Network Activity Indicator on iOS

### ISSUE THREAD

**Issue by itsvee** [ionic-team/ionic-native#1330]
I want to use Network Activity Indicator on iOS for show use when downloading something. I see repo https://github.com/ohh2ahh/NetworkActivityIndicator but can't use in Ionic 2 because it doesn't have Type. Create it for me and everybody, please. Thank you very much 😃

**Comment by danielsogl** [comment]
Looks like this plugin is not maintained anymore. Feel free to open a new feature request with an updated plugin source.
