### ISSUE TITLE
Upgrade from ionic-native 2.2.16 to 2.9.0 breaks Ionic v1 app

### ISSUE THREAD

**Issue by waynebloss** [ionic-team/ionic-native#1360]
In my Ionic v1 project, I upgraded from ionic-native@2.2.16 to ionic-native@2.9.0 and now I get an empty object error when I call $cordovaFile.readAsText. Also, $cordovaGeolocation.getCurrentPosition never returns.

Does anyone know what version of ionic-native is compatible with Ionic v1?

The docs say that the 2.x version should be compatible, but it's not (or there was a breaking change that I can't figure out).

**Comment by almothafar** [comment]
I'm using version 2.9.0 here and no problem, for now, I'm not sure what do you mean with "breaking" app, it seems you have issue just with specific plugin maybe the way you call it or get the value is wrong, not something with the version, you need to check breaking changes I think, also, it better to provide your code.

**Comment by waynebloss** [comment]
@almothafar In code that was working before the upgrade, "I get an empty object error when I call $cordovaFile.readAsText. Also, $cordovaGeolocation.getCurrentPosition never returns." is what I mean.

Here is my code to call `$cordovaFile.readAsText`:

```js
function readTextFile(fileName) {
  console.log('Reading text file ' + fileName);
  return $cordovaFile
    .readAsText(directory.base, fileName)
    .catch(failedReadFile(fileName));
}
```

Here is my code to call `$cordovaGeolocation.getCurrentPosition`:

```js
function getPosition() {
  var options = {
    enableHighAccuracy: true,
    maximumAge: 60000,
    timeout: 0
  };
  return $cordovaGeolocation.getCurrentPosition(options);
}
```

It's pretty straightforward code and I don't think I'm calling anything incorrectly, but I could be wrong.

**Comment by almothafar** [comment]
`.readAsText(directory.base, fileName)` returns a promise.
and `$cordovaGeolocation.getCurrentPosition(options)` returns observable so I'm not sure how you call `getPosition()` ...

You seems following ngCordova documentation not ionic-native, it is a big difference with calls.

refer to: https://ionicframework.com/docs/native/geolocation/  and https://ionicframework.com/docs/native/file/

**Comment by waynebloss** [comment]
Thank you @almothafar . As I mentioned - `.readAsText` returns an *empty object* to my promise `catch` handler. There is no need to see any other code for that one.

Also, `.getCurrentPosition` returns a `Promise`, not an observable. This is evidenced by [the code](https://github.com/driftyco/ionic-native/blob/v2.9.0/src/plugins/geolocation.ts#L162), [the documentation](https://ionicframework.com/docs/native/geolocation/#getCurrentPosition) and [an example in the code](https://github.com/driftyco/ionic-native/blob/v2.9.0/src/plugins/geolocation.ts#L125) for v2.9.0.

My app is already using `ionic-native` v2.2.16 and everything works fine. When I looked for a list of breaking changes between v2.2.16 and v2.9.0 I don't see any. Can you point to one documented breaking change between those versions? If none are documented that is a problem.

**Comment by ihadeed** [comment]
Closing this issue since Ionic Native v5 includes all bug fixes/features and it supports Ionic 2.x apps.
