### ISSUE TITLE
ionic-native karma browserify, provide commonjs modules

### ISSUE THREAD

**Issue by frankkoenigstein** [ionic-team/ionic-native#1363]
For Karma tests I need to extra compile ionic-native with babelify and browserify since browserify does not understand es6 modules:
```ts
        browserify: {
            debug: true,
            plugin: [["tsify", {
                project: "tsconfig-test.json"
            }]],
            transform: [["babelify", {
                extensions: [".js", ".ts"],
                global: true,
                only: /node_modules\/\@ionic-native/,
                presets: ["es2015"]
            }]],
        },
```

Because of the imports:
```ts
import { Network } from "@ionic-native/network";
```

it is not possible to omit ionic native plugins during tests.

Could you please provide ionic native in different es versions .
package.json
```json
{
  "main": "dist/es5/index.js",
  "module": "dist/esm/index.js",
  "typings": "dist/es5/index.d.ts",
}
```

tsconfig-esm:
```json
{
  "extends": "./tsconfig",
  "compilerOptions": {
    "module": "es2015",
    "outDir": "dist/esm"
    }
  }
}
```

tsconfig-es5:
```json
{
  "extends": "./tsconfig",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "dist/es5"
  }
}
```

**Comment by amerzad** [comment]
This is also needed for Meteor also.
I am trying to use Meteor as the builder tool, and it needs commonjs.

**Comment by danielsogl** [comment]
Im closing this issue because with the v5 release this shouldn't be a problem anymore.

**Comment by amerzad** [comment]
@danielsogl 
Great news, but would you please clarify how v5 will solve this? I don't see it is going to support commonjs modules, so do you imply we will use the vanilla javascript support, or I am mistaken?

**Comment by danielsogl** [comment]
Yes V5 will support vanilla javascript!
