### ISSUE TITLE
Feature Request - Braintree Plugin

### ISSUE THREAD

**Issue by wwallace** [ionic-team/ionic-native#1373]
Although it is possible to use the Braintree JS Sdk, it is somewhat limited and lacking certain features or is more difficult to integrate with a hybrid app, specifically the Braintree dropin ui

Dropin:
iOS: https://developers.braintreepayments.com/guides/drop-in/ios/v4
Android: https://developers.braintreepayments.com/guides/drop-in/android/v2

Cordova Plugin?
https://github.com/Taracque/cordova-plugin-braintree

**Comment by borntodesign** [comment]
@wwallace could you provide a rough overview of how you currently have it integrated as I am looking into Braintree Marketplace.

**Comment by danielsogl** [comment]
@wwallace I will add this plugin later this week

**Comment by dcesca** [comment]
@danielsogl any news about the plugin for braintree?

**Comment by codinronan** [comment]
Hey guys,

I have put this together and opened a PR:
https://github.com/ionic-team/ionic-native/pull/2073

Hopefully we can get this in. Works great locally.
