### ISSUE TITLE
Camera.PictureSourceType: Private member is not accessible

### ISSUE THREAD

**Issue by mo-mueller** [ionic-team/ionic-native#1397]
I am using the Camera Plugin from ionic-native. I am importing it with `import {Camera} from 'ionic-native';`.

When I want to use for example "Camera.PictureSourceType.PHOTOLIBRARY" my editor (PhpStorm) marks "PictureSourceType" in red and when I go with my mouse over it it tells me "Private member is not accessible". The code still works but it's not so cool that PhpStorm always tells me there is an error in the document.

Should PictureSourceType really have the flag "``@``private"? Or is there an other way for me to fix it?

**Comment by ihadeed** [comment]
We had those `@private` flags for docs purposes. We can take them out in the next 2.x release.

**Comment by ihadeed** [comment]
Closing this issue since Ionic Native v5 includes all bug fixes/features and it supports Ionic 2.x apps.
