### ISSUE TITLE
ImageResizer v3.5.0 iOS

### ISSUE THREAD

**Issue by pacMakaveli** [ionic-team/ionic-native#1409]
Hy guys,

I was going to make a pull request to add this information in the docs directly. However, I'm not familiar as to how you'd like this to be handled.

The bottom line is, on iOS, `fileName` is required. Otherwise it will fail silently and cause a lot of frustration because there will be no errors.

Although the value gets ignored, is very much required to make it work.

See: https://github.com/JoschkaSchulz/cordova-plugin-image-resizer/issues/16 as a reference.

**Comment by danielsogl** [comment]
Fixed: https://github.com/ionic-team/ionic-native/commit/7c6b117643bf7a01cf62f29a1aa6075b00d3b2f4
