### ISSUE TITLE
Feature request: FTP 

### ISSUE THREAD

**Issue by robinbonnes** [ionic-team/ionic-native#1575]
Can we add a wrapper for https://github.com/xfally/cordova-plugin-ftp to ionic-native?

**Comment by danielsogl** [comment]
Hey @robinbonnes,
this plugin is on my list!

**Comment by danielsogl** [comment]
@robinbonnes I will add this plugin today. They release version 1.0 last week

**Comment by danielsogl** [comment]
@ihadeed can be closed
