### ISSUE TITLE
New Ionic-Native WiFi Plugin

### ISSUE THREAD

**Issue by savanvadalia** [ionic-team/ionic-native#1599]
[ ] bug report
[x] feature request

Requesting to add a new WiFi based plugin for Android & ios applications.

IoT is going to be the next big thing in the coming years and many IoT devices are WiFi based. A cordova WiFi plugin should provide functionalities for a plugin user to interact with some below WiFi based activities like from an ionic app :

1) Scanning WiFi networks available near by
2) Connect/Disconnect a particular WiFi network
3) Retrieve IP Address/Mac Address for the devices in the same WiFi network
4) Retrieve IP Address/Mac Address of the currently connected WiFi network

An example of already existing similar plugin with limited ios functionality is here:
https://github.com/hoerresb/WifiWizard

Would be great if we can have a new plugin with all functionalities above plugin has plus overcoming its  current ios limitations.

**Comment by piotrowski** [comment]
@savanvadalia Ionic Native only helps to implement existing Cordova plugins in Ionic applications. So Ionic Native would require a Wifi Cordova plugin that already has all the functionality, and then would make sure it is nice and easy to be used inside Ionic apps. Do you know a Cordova plugin that has all the required functionality?

**Comment by savanvadalia** [comment]
@piotrowski ,

Thank  you for your response. So far with my google search I have found very few Cordova Wifi plugins.

The one I have mentioned in my request [WifiWizard ](https://github.com/hoerresb/WifiWizard) is quite popular and it has all functionalities for Android.

When I mentioned about the limitations with plugin for ios, I am not sure if that will be the case for any Cordova Wifi plugin due to Apple not exposing it as Public API (See below Screenshot).

If it is Apple enforcing this limitation, I am happy with whatever this plugin provides. In that case I will change my app flow for ios mode and still use this plugin for Android application. 

I hate Apple for the same reasons, it seems they always try to prevent the web to take over native apps!!!

![image](https://cloud.githubusercontent.com/assets/17091755/26476038/34579532-41ff-11e7-8d29-e551b173cf49.png)

**Comment by piotrowski** [comment]
This is quite the opposite: No apps can use these APIs, not even native ones.

**Comment by savanvadalia** [comment]
Oh ok!! thanks for that clarification. I am not sure then how the native apps that I have seen so far does those WiFi functionalities under the hood e.g. (Listing available WiFi access points and connecting to a particular WiFi access point)

An example of the functionality I am referring to is in this youtube video
https://youtu.be/hYMGHIv5eIY

Can we still have the WifiWizard plugin as part of ionic-native ?

**Comment by piotrowski** [comment]
The YouTube video you linked to is doing it manually, isn't it?
https://youtu.be/hYMGHIv5eIY?t=66

And yes, there is no reason why this plugin shouldn't be added to Ionic Native.

**Comment by savanvadalia** [comment]
You are partially correct there, connection is done manually in the 1st part of the video where the phone is connecting to WiFi plug's access-point. In the 2nd part you will see that it scans the home router and connects it by providing the router password from within the App.

Thanks for considering this request to make it as part of ionic-native.

This my first request with ionic-native, I am unaware about how these type of requests are prioritized in the development workflow. 
Is it milestone based like ionic-framework or is it based on number of requests for a particular feature?

**Comment by danielehrhardt** [comment]
Something new here?

**Comment by danielehrhardt** [comment]
https://ionicframework.com/docs/native/hotspot/

**Comment by danielsogl** [comment]
Im closing this issue because the requested plugin is no longer maintained.

**Comment by somq** [comment]
Maybe someone dedicated could wrap this one?
https://github.com/tripflex/WifiWizard2

**Comment by deepakiotworld** [comment]
- [ ] 

> 

> 

> 

> 

> 

> 

> 

> `[](url)`
