### ISSUE TITLE
feature(plugin): cordova-plugin-nsuserdefaults-for-app-groups

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic-native#1602]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

Please add support for the cordova-plugin-nsuserdefaults-for-app-groups plugin:
https://github.com/protonet/cordova-plugin-nsuserdefaults-for-app-groups

**Comment by danielsogl** [comment]
Im closing this issue because tis plugin is not longer maintained.
