### ISSUE TITLE
One Signal - postNotification is not working/

### ISSUE THREAD

**Issue by arsy29** [ionic-team/ionic-native#1605]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
-the parameter for postNotification is OSNotification which should just be the collection of parameter explained in the create notification part of the one signal documentation, https://documentation.onesignal.com/reference#create-notification.

-An error occurs upon submission using postNotification stating that an Authorization using the REST API key is needed for it to continue, even though any alteration to the Header is not accessible.

**package.json info:**

```json
"@ionic-native/onesignal": "^3.8.0", // current version of one signal
"@ionic-native/core": "^3.6.1", // current version of native core
```

**Comment by guizmo** [comment]
I also have issue using postNotification... Typescript won't compile saying the argument supplied is not assignable to parameter of type 'OSNotification';

    let notificationObj = {
      contents: {
        en: "message body",
      },
      app_id: "123456",
      include_player_ids: ['654321']
    };

this.oneSignal.postNotification(notificationObj).then((success) => {
    }).catch((error) => {
    })

Looking  in node_modules/@ionic-native/onesignal/index.d.ts i tried matching the interface but nothing works...

**Comment by kotran88** [comment]
please correct this error...
I have same Issue

**Comment by kotran88** [comment]
I think this plugin dosen't work...
please use below way to send notification in apps

window["plugins"].OneSignal
    .startInit("xxx, "xxx")
   .handleNotificationOpened(notificationOpenedCallback)
    .endInit();
    var notificationObj = { contents: {en: "message body"},
                          include_player_ids: ['xxxxxxxxxxxxxx']};
    window["plugins"].OneSignal.postNotification(notificationObj,
    function(successResponse) {
      alert(successResponse);
    },
    function (failedResponse) {
      console.log("Notification Post Failed: ", failedResponse);
      alert("Notification Post Failed:\n" + JSON.stringify(failedResponse));
    }
  );﻿

**Comment by guizmo** [comment]
Here is my work around.
Can't say if it is a good way but basically i set the type of my object to 'any' and it passes typescript build


`
let notificationObj:any = {
      include_player_ids: userIds,
      data: payload,
      template_id: template
    };

 this.oneSignal.postNotification(notificationObj);

`
