### ISSUE TITLE
possible to add this list of firebase plugin

### ISSUE THREAD

**Issue by arsewizz** [ionic-team/ionic-native#1615]
- [x] realtime message => https://github.com/hbmartin/cordova-plugin-firebase-realtime-database
- [x] for analytics =>  https://github.com/chemerisuk/cordova-plugin-firebase-analytics
- [x] for remoteconfig =>  https://github.com/chemerisuk/cordova-plugin-firebase-remoteconfig
- [x] for firebase hooks => https://github.com/chemerisuk/cordova-plugin-firebase-hooks
- [x] for dynamicLinks => https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks

**Comment by stormwin** [comment]
and all in one
https://github.com/jsayol/cordova-plugin-firebase-sdk

**Comment by ihadeed** [comment]
What are you asking for here exactly?

**Comment by arsewizz** [comment]
to add the list of plugin to ionic-native please!!!

**Comment by danielsogl** [comment]
@ihadeed you can assign me if you want to add the plugins.

@arsewizz but you can always use the firebase web ask to access all the firebase functions. But I will take a look into your suggested plugins.

**Comment by arsewizz** [comment]
okey thanks @danielsogl .

**Comment by arsewizz** [comment]
want to know if there is a roadmap for ionic-native plugin?

**Comment by patrickr** [comment]
Does http://ionicframework.com/docs/native/firebase/ cover your needs?
and for realtime DB and auth I recommend [angularfire2](https://github.com/angular/angularfire2) which doesnt need an ionic-native wrapper

**Comment by arsewizz** [comment]
hey @patrickr, thanks for your comment but the firebase plugin don't cover my need. just time to read this post [i'll](https://javebratt.com/ionic-social-login-firebase ) have a answer.

**Comment by danielsogl** [comment]
@arsewizz I try to implement the plugins this week.

**Comment by arsewizz** [comment]
@danielsogl thanks for the great work
