### ISSUE TITLE
discussion: allow using plugins which work in the browser via bundling cordova.js

### ISSUE THREAD

**Issue by NoNameProvided** [ionic-team/ionic-native#1616]
**I'm submitting:** a feature request.

I open this issue here as it's related to ionic-native, but to make this works, changes will be needed in ionic-app-scripts as well to bundle plugin's js files and `cordova.js` into the bundle when running `ionic serve`.

**Current behavior:**
Ionic Native prevents any call to plugins when running in the browser, it also prevents accessing the original reference for the plugin. This happening because when running Ionic through `ionic serve` only the ionic app is built and `cordova.js` is not provided for the runtime (as it would be on a real device).

**Expected behavior:**
Ionic Native allows calls to plugins which works in the browser. (So `cordova.js` and plugin.js files are included.) An example for such a plugin is the  [TheCocoaProject/cordova-plugin-nativestorage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage) plugin.

**Steps to reproduce:**

To make the failing ionic version:

1. create an ionic starter
2. install the native storage plugin as documented in it's [ionic-native docs](https://ionicframework.com/docs/native/native-storage/)
3. add a call to any command like `this.nativeStorage.setItem`.
4. run the app with `ionic serve`

Check in the browser the errors thrown by ionic-native: 

> Native: tried calling NativeStorage.setItem, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

> ERROR Error: Uncaught (in promise): cordova_not_available

To make a working demo in vanilia cordova: 

1. run `cordova create hello com.example.hello HelloWorld && cd ./hello`
2. run `cordova platform add android`
3. run `cordova plugin add cordova-plugin-nativestorage`
4. run `cordova build android`
5. go to `cd ./platforms/android/assets/www`

Open `index.html` in the browser, and see it supports browsers with fallback to local storage.

**Comment by ihadeed** [comment]
@danbucholtz do we have a way to serve from the cordova browser platform directory instead of `www` ?

**Comment by piotrowski** [comment]
`ionic cordova run browser` should do the job.

**Comment by ihadeed** [comment]
@piotrowski is there a way to enable livereload with that?

**Comment by piotrowski** [comment]
No idea, sorry. Should as it is the exact same command run in the background etc.

**Comment by tryadelion** [comment]
This would be lovely, many plugins already provide fallbacks to web if they could be executed.

**Comment by jamesparkes** [comment]
where is the status on this?

**Comment by jamesparkes** [comment]
@janpio @ihadeed i was able use cordova plugins successfully with `ionic cordova run browser`, but had issues with livereload. modifying and saving project files, did not force a rebuild and refresh of the browser

**Comment by ihadeed** [comment]
@jamesparkes did you try `ionic cordova run browser -l` ?

**Comment by jamesparkes** [comment]
I did, no luck 😐. I think the solution I'm looking for is what @NoNameProvided is suggesting

**Comment by ihadeed** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1044

**Comment by danbucholtz** [comment]
@ihadeed, not presently, no. `www` dir vs `platform` dir.

Thanks,
Dan
