### ISSUE TITLE
Safari-view-controller  : Only resolve one result

### ISSUE THREAD

**Issue by tgensol** [ionic-team/ionic-native#1619]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
The show function only returns one result.event (opened)

**Expected behavior:**
Maybe an Observable would to a better job than a promise ?

**Related code:**

```
 this.safariViewController.isAvailable()
        .then((available: boolean) => {
          if (available) {
            this.safariViewController.show({
              url: 'http://www.google.com',
            })
              .then((result: any) => {
// only one result will be resolved
})
```

**Comment by danielsogl** [comment]
Hey @tgensol,
as you can see from the plugin repo page, the function wants one parameter (options) and can return a success or error callback. 

```javascript
  show: function (options, onSuccess, onError) {
    options = options || {};
    if (!options.hasOwnProperty('animated')) {
      options.animated = true;
    }
    exec(onSuccess, onError, "SafariViewController", "show", [options]);
  },
```
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/master/www/SafariViewController.js#L12

**Comment by tgensol** [comment]
Hey @danielsogl ,

I know, and this is where the ionic-native plugin is not working as expected,

https://ionicframework.com/docs/native/safari-view-controller/

The promise only resolved once (the result.opened), and then, it doesn't resolve again for "loaded" or closed. The doc is maybe wrong, or... ?

**Comment by ihadeed** [comment]
Yeah, `show` should return an Observable instead of a Promise. I didn't notice that the callback is multi-purpose...
