### ISSUE TITLE
Looking for feedback: Premium Ionic Native Plugins

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-native#1622]
Hi everyone,

The Ionic team is hoping for some feedback from you if you have a few minutes to spare:

One of the biggest challenges with large plugin communities like Cordova is keeping important plugins maintained, and also making sure new plugins are built to take advantage of new functionality and native APIs.

We've received feedback from the community that plugins are one of the biggest challenges Ionic developers have, both with finding plugins that are stable/high quality, but also finding ones that have the functionality they need. Mostly these issues are with 3rd party (i.e. not the core Cordova plugins) plugins. Developers using other non-Cordova frameworks also face the same issue, making it clear that more needs to be done across the industry.

We're exploring offering premium plugins at a monthly price, built and/or maintained by the Ionic team, with support and maintenance. We would focus our efforts on the non-Apache Cordova plugins, instead focusing on the long tail 3rd party plugins that are often built by single volunteers.

Pricing is still an open question, but it could vary from a low monthly price for individuals/hobbyists to a higher price for teams and/or those using a lot of plugins.

Is this something you or your team would be interested in? Would love your thoughts below.

**Comment by sambengtson** [comment]
Our team would be open to subscribing to something like this.  We've been burned a couple of times already from using plugins that are no longer supported.  I realize that maintenance is a ton of work and appreciate those keeping their libraries up to date :+1:

**Comment by jfi** [comment]
:+1:, we've had a few situations where not having supported plugins has really burnt us and would certainly pay for a subscription.

**Comment by modemlooper** [comment]
Absolutely. Plugin incompatibility is a common issue.

**Comment by theaccordance** [comment]
My team would be open to premium plugins, particularly those which are more targeted towards enterprise (oAuth, SSO, MDM) or SOC2 compliance.

**Comment by mlynch** [comment]
Thanks everyone, appreciate the feedback. @theaccordance are you using any ones right now I could take a look at?

**Comment by theaccordance** [comment]
[cordova-plugin-sslcertificatechecker](https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin) is one we're using as part of our SOC2 compliance.  

MDM is something we haven't found a plugin for yet.

I know one of my team members is looking into oAuth plugins, and we recently added [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/) to address SSO needs of our customers, but that approach isn't necessarily ideal.

**Comment by sdsanders** [comment]
I would 100% be in favor of this. The unreliability of the Cordova plugin ecosystem is IMO one of the biggest drawbacks of using Ionic.

**Comment by EddyVerbruggen** [comment]
The problem with (plugin( maintenance is it needs to fight with paid work, and during "hobby hours" it needs to fight with other hobbies. And for most developers maintenance is not really a hobby in the first place.

I think key in your proposal is trying to involve other ((potential) plugin) developers to share in the profits, just like your marketplace offers 3rd party devs to make a little money from sharing UI plugins/themes.

Personally I have no $$$ interest in creating Cordova plugins, it's just that I like the framework and its maintainers so damn much. So even today I created [a new Cordova plugin](https://github.com/EddyVerbruggen/cordova-plugin-app-icon-changer) that anyone can use and report issues on, but without any financial backing there's just no guarantee issues will be solved.

God speed on this one!

**Comment by theaccordance** [comment]
Ha, had a feeling @EddyVerbruggen would be the one to create the plugin that changes the iOS icon at runtime

**Comment by JymmiHQ** [comment]
Hi Max. Yes, we'd certainly be in favour of this! We're releasing two related Ionic apps at the moment and having plugin support peace of mind would be awesome.

**Comment by Bandito11** [comment]
I would be  interested in this. But will this work as a subscription package or a buy it once and use it whenever you want? 

If I have to buy it once I believe it would be better to sell it by plugin and not as a package.

**Comment by KerryRitter** [comment]
Absolutely. I agree with the issue of plugins being a problem. I'd be happy to pay for Ionic to get these problems out of my way.

**Comment by shimjudavid** [comment]
1. Offer an individual premium plugin at a fixed annual price (like most premium Wordpress plugins).
This is for users who only wanted one or two plugins.

2. Offer a subscription monthly/annual plan for a group of premium plugins at an affordable rates for developer and premium rates for corporates.

**Comment by oraneedwards** [comment]
100% would subscribe to high quality, well documented plugins

**Comment by gaurav-chandra** [comment]
Yes, this is absolutely needed. Have 2 models: sell a premium plugin per app for one tome cost and a subscription model for more than one app. 

If subscription model is the inlybway, small time cordova developers will hesitate. Many of us charge one time fee for the app and not monthly from our clients.

**Comment by rdesimone** [comment]
Yes, definitely needed!

**Comment by patrickr** [comment]
While I'm not 100% against this and might pay if the offering is worth it.. I really love that ionic is open, and I would rather see this new work shared in a way that grows the ionic community. Would you be open to some sort of patronage model for early access, input,  and priority support?

**Comment by dpa99c** [comment]
I agree with @EddyVerbruggen: i.e. your proposal should seek to engage existing/potential 3rd party plugin developers to share in the burden and the profits. 

As the author of several plugins currently wrapped by Ionic Native (Diagnostic, Launch Navigator, Location Accuracy, SQLite Porter), I've spent probably hundreds of hours over the past few years developing and maintaining these for the benefit of the community, as well as for my own needs.

Myself, I have no interest in monetising my plugins via "premium" versions as some plugin authors have chosen to do, but at the same time I (and probably other plugin devs) would be a little miffed if you took my beloved plugins and starting selling them for a profit from which I didn't benefit. I think if you do go down this route, sharing any profits with plugin authors/contributors would be the fair thing to do, even if those authors are not being motivated by money.

Another way to look at this is that some plugins are quite specialised and their authors have an in-depth knowledge of a specific area which may be a lot for you to take on yourselves, if you are also dealing with many other plugins. In this instance, it would be better to engage that plugin author with his specific area of knowledge to continue maintaining/extending the plugin.

OK, that's my 5 cents worth :)

**Comment by meltuhamy** [comment]
We're lacking high quality cordova plugins (e.g. local notifications didnt officially support ios10 for several months! had to rely on a fork :( ) but I agree with @patrickr  that if it's paid, it's closed. I think it's better to go for a donation / support type model, like https://opencollective.com/webpack

**Comment by mlynch** [comment]
@meltuhamy we can't build a business on that so we wouldn't be able to invest in doing this in the first place, so it has to have some level of monthly recurring revenue to make it worth it. I agree it's something badly needed but it's a major effort.

**Comment by mlynch** [comment]
@dpa99c makes sense. Unsure how to do that but it'd certainly be unique. The only downside is that money coming to an author doesn't give them more _time_ to work on it, so it might not actually solve the problem.

**Comment by dpa99c** [comment]
@mlynch I agree that simply paying money to the original plugin author regardless of whether they continue to maintain/develop the plugin is not a solution. There would need to be some motivation for them to make time to work on it, be that financial or reputational. In the case where a plugin is maintained by more than 1 author, the proceeds should be allocated to the contributor who added the feature or fixed the issue. Some kind of work-incentivized reward system (like feeding mice cheese when they make it to the end of the maze). 
I think if you can figure out how to cut an active plugin author in on your monthly proceeds, you can effectively have a whole bunch of plugin drones working for you on the premise they'll receive some nice cheese.
Not sure how that could be implemented either though :)

**Comment by tryadelion** [comment]
i'd be open to it but depending on the price ( as always ). Would the plugins stop working if we stopped paying, or it would just not allow to download newer versions from the CLI? how would it work? Wouldn't a single payment ( or a yearly payment per "Ionic Native Team Development Liscense", google & apple style ) do the trick?

**Comment by shimjudavid** [comment]
I second- annual payment option. Plugins wont stop working, but future updates wont be getting after expiry.

**Comment by jrmcdona** [comment]
Totally open to it.   Trying to build  a chat app and having issues with the keyboard.  Been exploring the paid keyboard plugin but definitely weary to go down that path if it loses support.   But if this is what we have to have to have an ionic chat app then we would be open to paying for sure.

**Comment by battika** [comment]
Very good idea, and would be very interested...

**Comment by simonbrazell** [comment]
Having just made my first Ionic app and experiencing the pain that plugins brought to the process I would certainly consider this.

**Comment by jrmcdona** [comment]
@mlynch any type of timeframe you are thinking about? Please tweet out the plans for visibility!

**Comment by selected-pixel-jameson** [comment]
@mlynch Is Ionic Native open source?

**Comment by mlynch** [comment]
Hi all, I forgot to update this thread, but we are working on this right now, in tandem with our new Capacitor project. We are looking for a few larger teams (enterprises, etc.) that are interested in having premium, supported plugins to start. We plan on expanding those plugins for smaller teams and indie developers down the road. These plugins will work in Cordova and Capacitor (they are being built to run in both out of the box).

Interested? Please send me an email at max@ionicframework.com.

Closing for now. Cheers!

**Comment by mlynch** [comment]
@selected-pixel-jameson yes, it's MIT licensed. PRs always welcome!

**Comment by selected-pixel-jameson** [comment]
@mlynch Where is it located? I don't know why I can't find it.

**Comment by mlynch** [comment]
@selected-pixel-jameson here ya go: https://github.com/ionic-team/ionic-native

**Comment by selected-pixel-jameson** [comment]
Oh, thanks. I guess I didn't realize how the code was setup. Thought that was just showing the documentation.
