### ISSUE TITLE
Media Plugin won't create media objects in background-mode iOS(wkwebview 3.0)

### ISSUE THREAD

**Issue by baksagimm** [ionic-team/ionic-native#1623]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

Media Plugin won't create media objects in background-mode iOS (ionic wkwebview 3.0)

**Expected behavior:**

Media Plugin should create media objects in background-mode in iOS when using ionic wkwebview 3.0

**Steps to reproduce:**

1. install ionic wkwebview 3.0.
2. install ionic cordova plugin add cordova-plugin-background-mode@0.7.1 (since 0.7.2 wont run with wkwebview 3.0 with media plugins installed.
3. let app dynamically create new media object in background mode.
4. run it on iOS.

**Related code:**
N/A
```
insert any relevant code here
```

**Other information:**

**package.json info:**
N/A
```json
insert the content here
```

**Comment by ihadeed** [comment]
Not an Ionic Native issue.

I suggest you do further debugging and figure out who is causing this problem (WKWebview, Media plugin, or Background mode) and open an issue at their repo.
