### ISSUE TITLE
Secure Storage in Ionic Native missing secureDevice function

### ISSUE THREAD

**Issue by surajrao** [ionic-team/ionic-native#1625]
**I'm submitting a ...**  (check one with "x")
[] bug report
[x ] feature request

**Current behavior:**
The current [SecureStorage](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/secure-storage/index.ts) wrapper does not support `secureDevice(successHandler,errorHandler)` function which is present in the [cordova plugin](https://github.com/Crypho/cordova-plugin-secure-storage#users-must-have-a-secure-screen-lock-set) for android platform.

Also check this [stackoverflow question](https://stackoverflow.com/questions/44156522/how-to-open-the-secure-settings-of-the-android-phone-with-my-ionic-2-app)

**Expected behavior:**
Should be able to do:

```
var ss = this.secureStorage.create('myStorage')
                .then((storage: SecureStorageObject) => {
                    storage.set('var', 'toto')
                        .then(
                        () => ss.secureDevice(()=>{},()=>{}),
                        (e) => console.log('error');
                        );
                }).catch((err) => {
                    console.error('The device is not secured');
                })

```
**Steps to reproduce:**

Use the latest ionic blank app and try to access `secureDevice` function.

Apologies if I should have raised this with main ionic repo or at the cordova plugin repo. Please let me know.

**Comment by danielsogl** [comment]
@surajrao I added the missing function. Wait for the next release

**Comment by surajrao** [comment]
thank you @danielsogl

**Comment by irundaia** [comment]
Hi guys,

Unless I'm mistaken, this feature will not work. The promise that returns the `SecureStorageObject` (`SecureStorage.create('secure_storage')`) already fails with a `Device is not secure` error. Therefore, we never get the `SecureStorageObject` on which we can call the `secureDevice` method.

**Comment by surajrao** [comment]
@irundaia I guess there is slight error in the expected behaviour part.
Try
```
var ss = this.secureStorage.create('myStorage')
                .then((storage: SecureStorageObject) => {
                      console.log('ok');
                }).catch((err) => {
                          ss.secureDevice(()=>{},()=>{});
                })
```

**Comment by irundaia** [comment]
@surajrao How would this work? The `ss` variable is a `Promise<void>`. So there isn't a function called `secureDevice` on `ss`?

**Comment by surajrao** [comment]
@irundaia Oh you are right.. https://github.com/Crypho/cordova-plugin-secure-storage/blob/master/www/securestorage.js#L266 The function does need `SecureStorageObject` which you will not have in `catch`.

**Comment by Servuc** [comment]
Hey everybody,

Does this bug will be close ? 
More over, it's seem that solution works : https://stackoverflow.com/questions/46520464/ionic-secure-storage-ask-the-user-to-set-a-lock-screen/46583135#46583135

Have a good day ;)

**Comment by irundaia** [comment]
The solution implies that you’d have to patch the javascript code from ionic-native. To me, that does not sound like a solution but a hack.

**Comment by Servuc** [comment]
Right, after doing some tests, it seems not work on iOS ...
I don't exactly how Ionic "wrapper" from Cordova works, somebody knows ?

**Comment by Servuc** [comment]
Hey,

After some projects update to last version (in package.json), I've a new problem. Apple detection is weak. 95% of the time, app said that phone is unsecure. I do not have that bug on Android
Am I the only one ? 

I will give more information if I success to debug iOS app from Linux (with Remote IOS Debug)

Have a good coding day
