### ISSUE TITLE
Ionic2 copyFile moveFile Error, Zone state notScheduled

### ISSUE THREAD

**Issue by AUSdomgarcia** [ionic-team/ionic-native#1637]
here's my code either I use copyFile or moveFile it always goes to catch handler outside my promise fuction

```
moveFileToStorage(uri) {
        const _extension = '.' + this.getFileExtension(uri);
        const _name = this.getFileName(uri) + _extension;
        const _newPath = this.myStoragePath;
        const _newName = 'camera_' + this.hashName() + _extension;
        const _uri = uri.substring(0, uri.lastIndexOf('/') + 1);
        return this.file.moveFile(_uri, _name, _newPath, _newName);
    }

moveFileToStorage(uri).then((res) => { } ).catch( (err) =>{ err } ) <-- goes here catch handler
```

heres what it display, actually I don't get what it mean, just a newbie in ionic 2 development.

{"__zone_symbol_currentTask": {"type":"microTask", "state":"notScheduled", "source":"Promise.then", "zone":"angular","cancelFn":null,"runCount"0}}

you can also refer to the whole project to see the actual error here's my repo 
https://github.com/AUSdomgarcia/crud-ionic2/

I already submitted an issue to zonejs and according one of the collaborator it wasnt a zone.js issue
https://github.com/angular/zone.js/issues/796#issuecomment-305613625

**Comment by rapropos** [comment]
This looks like a better fit for [the support forums](https://forum.ionicframework.com/) to me.

**Comment by isaacOjeda** [comment]
Hey guys, what was the solution for this?

Greetings
