### ISSUE TITLE
iOS writeFile not working , it is working in android

### ISSUE THREAD

**Issue by Anilinfo2015** [ionic-team/ionic-native#1662]
Hello Team,
          writeFile not working in iOS , it is working file in android 

iOS version 10.3

            this.fileManager.writeToFile(fileName, response["_body"]).subscribe(sss => {
});

**Comment by piotrowski** [comment]
Please add the name of the plugin you are referring to in the issue title. Thanks.

**Comment by ihadeed** [comment]
@Anilinfo2015 please open a new issue and make sure to fill out the issue template. The information you provided isn't enough for us to help you.
