### ISSUE TITLE
 MobileAccessibility states it is not installed

### ISSUE THREAD

**Issue by oborudko** [ionic-team/ionic-native#1666]
Hi, trying to use MobileAccessibility plugin, but it does not seem to work for me. Using latest ionic-native 3.12.1 with ionic 3.3.0

`Native: tried calling MobileAccessibility.usePreferredTextZoom, but the MobileAccessibility plugin is not installed.`

have in config.xml

`    <plugin name="phonegap-plugin-mobile-accessibility" spec="https://github.com/phonegap/phonegap-mobile-accessibility.git" />
`
and in packages.json

`    "@ionic-native/mobile-accessibility": "3.12.1",
`

it is added as service in app.module.ts and called on platform.ready(), but nothing happens.

Thanks.

**Comment by ihadeed** [comment]
Just pushed a commit to fix this. Will be available in the next patch release.

Thanks for reporting this!

**Comment by janpio** [comment]
Unfortunately this fix wasn't enough I think. I created a new issue at #1860

**Comment by tgangso** [comment]
What is the awesome-cordova-plugins replacement for @ionic-native/mobile-accessibility?
Specifically need the usePreferredTextZoom(false)
@ihadeed 

Thanks
