### ISSUE TITLE
Themeable Browser: Does not open on iPhone5 [__NSCFString charValue]

### ISSUE THREAD

**Issue by GloriaTM** [ionic-team/ionic-native#1673]
**I'm submitting a ...**  
[x ] bug report
[ ] feature request

**Current behavior:**
Themeable Browser does not open on iphone5 (32bit). On iPhone 5s (64bit) and above everything is fine. OS not relevant (tested with iOS 9.3 and 10)
Xcode says on click: ERROR [__NSCFString charValue]: unrecognized selector sent to instance

**Expected behavior:**
Click opens the wanted url in themed inAppBrowser

**Steps to reproduce:**
Any emulation on iPhone5 should show this error.

**Related code:**
themeable-browser/index.d.ts

```
export interface ThemeableBrowserOptions {
    statusbar?: {
        color: string;
    };

    location?: string; // that seems to cause the error -> boolean works fine
   
    }
```
in my ThemeableBrowserOptions: 
```
ThemeableBrowserOptions = {
  location:false 
  }
```

**Other information:**
https://stackoverflow.com/questions/31408909/nscfstring-charvalue-unrecognized-selector-sent-to-instance

**package.json info:**

```
   "ionic-angular": "3.0.1",
   "@ionic-native/themeable-browser": "3.4.4"
```

So, I got it working with changing plugin code to location?:boolean and adding location:false in my options. Can you @ihadeed check this please and maybe change plugin or find a better solution? That would be great. Thank you!

**Comment by ihadeed** [comment]
This doesn't seem like an issue with Ionic Native.

Ionic Native is just a wrapper and it has no effect on how the plugin performs. I recommend asking for support at the plugin's repo or at the Ionic Forums.
