### ISSUE TITLE
Ionic 3 is crashing just after opening splash on IOS (iphone & simulator)

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#1674]
_From @abumuwaz on June 9, 2017 6:4_

I am getting the app crashing issue with Ionic 3.3.0 for IOS 10.32 iphone as well as simulator. Even it does not show home page, just crashing after opening splashing but android app using same code base is working very fine as i want. 

**What is going to IOS**

Not only that , i do not get any debug file named console.log at 

**my_mac_project_path/platforms/ios/cordova/console.log**
There is only  log as 
```
CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)

tail -f "$CORDOVA_PATH/console.log"
```

Additional:
I have tried only the blank app to confirm with **fcm**  ionic-native plugin only but same result.

so now not only app is crashed but also my head with the pain after trying severals try.

i am really looking forward reply from the ionic team ASAP.

Thanks in advance after all.

_Copied from original issue: ionic-team/ionic#11987_

**Comment by jgw96** [comment]
_From @plul on June 9, 2017 13:45_

Try this: https://github.com/arnesson/cordova-plugin-firebase/issues/275#issuecomment-301818002

**Comment by ihadeed** [comment]
This doesn't seem like an issue with Ionic Native.

Ionic Native is just a wrapper and has no effect on how the plugin performs. I recommend asking for support at the plugin's repo or at the Ionic Forums.

**Comment by prajesh97** [comment]
i have the same issue. i just created a new project then i am trying to run in ios and the app is not opening.
So please look into it.
