### ISSUE TITLE
Ionic-native support for Google Maps 2.0

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ionic-team/ionic-native#1676]
Google maps have been released in version2.0 (Beta because lack of some documentation).
When can I expect Ionic-native to support that version?

**Comment by ihadeed** [comment]
We have an issue open for this here: https://github.com/ionic-team/ionic-native/issues/751 .. subscribe to it to get updates on the progress.

We also have a couple of PRs open for this update. We will merge it soon with the next major release  4.x.
