### ISSUE TITLE
Update OneSignal plugin

### ISSUE THREAD

**Issue by neoassyrian** [ionic-team/ionic-native#1677]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X] feature request

**Current behavior:**

OneSingal plugin is out of date. Need to be refreshed. Some new functions are added and is required by developers. 

**Expected behavior:**

All functions available here(https://documentation.onesignal.com/docs/cordova-sdk) should also be available here. 
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by danielsogl** [comment]
@neoassyrian I will take a look!

**Comment by ihadeed** [comment]
This should be closed now? since your recent PR fixed it?

**Comment by neoassyrian** [comment]
Not really. I only added one method. I believe there are more newer functions.
