### ISSUE TITLE
[feature request] - Update HTTP plugin to add DELETE, PUT and PostJSON methods

### ISSUE THREAD

**Issue by kevinhuron** [ionic-team/ionic-native#1679]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request

<strong>HI !</strong>
The plugin <strong>cordova HTTP</strong> is under interesting pull request Like add <strong>DELETE</strong>, <strong>PUT</strong> and <strong>PostJSON</strong> methods and haven't any update over  <strong>11 month</strong> so I Will want to know if it's possible to Update the plugin and then the  <strong>ionic-native/http</strong> to add these features ?
 <strong>(I really think these features will be loved by many, me first 👍 )</strong>

Sorry if it's not the place to speak about that but I would appreciate these updates...

 <strong>Thanks you for reading me :)</strong>

 <strong>Have a nice day :)</strong>

 <strong>Cordially :)</strong>

**Comment by ihadeed** [comment]
Can you provide links to the fork(s) that you recommend?

**Comment by kevinhuron** [comment]
Yeah 
After read each files I think this pull request could be usefull [https://github.com/wymsee/cordova-HTTP/pull/105](https://github.com/wymsee/cordova-HTTP/pull/105) work with this fork
[https://github.com/spuentesp/cordova-HTTP](https://github.com/spuentesp/cordova-HTTP)

After, this fork could be nice too 
https://github.com/Telerik-Verified-Plugins/SecureHTTP

And this fork (only postJSON unfortunately)
https://github.com/Switch168/cordova-HTTP

Thanks you

Cordially

**Comment by ihadeed** [comment]
I personally was using https://github.com/Switch168/cordova-HTTP for awhile. Worked well. I replaced it recently with a new HTTP plugin that I wrote (not publicly available yet).

If each repo has one good thing about it, we can create a new fork and combine them together, then publish to NPM.

**Comment by kevinhuron** [comment]
Hi !
Well... I develop an Ionic Application for my society so I really need these updates. But I am a student yet... :no_mouth:

I learned many language and develop since 4 years. 
And, even if this experience with you could be really interesting for me, for learn and mostly for my professional future, I don't know if I have the ability to do that kind of thing with you... :disappointed_relieved:

What do you think ?

**Comment by ihadeed** [comment]
I can take care of it.. what is the Switch168 fork missing?

**Comment by kevinhuron** [comment]
Thank you very much

In the Switch168 fork I see only postJson method (if it works well and the others too, its a good news), but if we want to update this plugin to a great version I think we will must add : Put and Delete methods
