### ISSUE TITLE
InAppBrowser messes up active tab of Tabs layout

### ISSUE THREAD

**Issue by scoottrick** [ionic-team/ionic-native#1681]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
After opening and closing an InAppBrowser and navigating to a Tabs page, the active/inactive state of the tabs is not updated correctly. The navigation of the tabs still works correctly, i.e., the components associated with the tabs still open as intended. However, the color of the active tab and the active icon are not updated correctly.

**Expected behavior:**
After opening and closing an InAppBrowser and navigating to a Tabs page, the active tabs should be correctly displayed as active or inactive.

**Steps to reproduce:**
1. Open an InAppBrowser.
2. Close the InAppBrowser.
3. Navigate to a page with the Tabs layout.
4. Switch tabs a few times.

**Related code:**
Github repo to demonstrate the issue here: [https://github.com/scoottrick/tabs-with-in-app-browser](https://github.com/scoottrick/tabs-with-in-app-browser)

**Comment by ihadeed** [comment]
I sense an issue with change detection here.

I've had this problem before with one of my apps. Can't remember if/how I fixed it. The issue occurred when opening an InAppBrowser instance, typing something in there, then closing the IAB window. Things just start to act weird afterwards.

**Comment by scoottrick** [comment]
I've tried manually trigger change detection in the Tabs component with `changeDetectorRef.detectChanges()` with no luck. And the issue occurs even with no actions taken within the InAppBrowser instance.
I have also noticed that the active tab button (the actual `a` element for the button) normally gets the attribute `aria-selected="true"` while the inactive tabs get `aria-selected="false"`. After opening an IAB window those attributes are not updated correctly.
