### ISSUE TITLE
One signal error in ionic2 app

### ISSUE THREAD

**Issue by francoro** [ionic-team/ionic-native#1682]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

thats my error when i do ionic run android, after adding the one signal plugin

**Comment by ihadeed** [comment]
The information you provided isn't enough to diagnose this issue. 

Also, Ionic Native issues can only impact the process of compiling your Ionic app, and not your Cordova project (Android/iOS platforms.. etc). So, it looks like this isn't an issue with Ionic Native and it is possibly an issue with the plugin, or some other plugin that is conflicting with it.
