### ISSUE TITLE
Geolocation plugin gives inaccurate results even after using 'enableHighAccuracy'

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionic-native#1691]
**I'm submitting a ...**  (check one with "x")
[ X ] bug report

**Current behavior:**
The lat long I receive are not accurate, sometimes It gives coords that are near to my current location by 700 or 800 meters. Not sure but I believe it does not use the GPS to give a precise location. 

**Expected behavior:**
It should give a precise location

**Steps to reproduce:**
I used an iOS device to run the test, not sure if it will show something similar in iOS.

**Related code:**

```
    this.platform.ready().then((ready) => {
      this.geolocation.getCurrentPosition({ enableHighAccuracy: true, timeout: 20000, maximumAge: 0 }).then((resp) => {

         if (resp.coords) {
        console.log(resp.coords.latitude, resp.coords.longitude)
         } else {
           console.log('cant retrieve coords')
        }
      }).catch((error) => {
        console.log('Error getting location', error.code, ' msg ', error.message);
      });

    })
```

**package.json info:**

```json
"dependencies": {
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/diagnostic": "^3.12.1",
    "@ionic-native/geolocation": "^3.12.1",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.11"
  }
```

**Comment by reinhardholl** [comment]
I am seeing similar results on an iOS device. Did you manage to solve this issue?

**Comment by meggillespie** [comment]
I am getting the same...highly variable. sometimes 2-5 meters...sometimes the equivalent of a couple hundred feet. Today I got the equivalent of 7k plus feet??? This does not seem like the expected behavior of 'highAccuracy'.

**Comment by ajoykarmakar** [comment]
What is the solution to this problem? I am facing the same issue.

**Comment by anterodev** [comment]
Same issue here.

**Comment by Carlosps** [comment]
How did you guys solve this issue? I noticed the geolocation is not accurate when I am using the mobile data network (3G)
