### ISSUE TITLE
ionic-native/contacts

### ISSUE THREAD

**Issue by joansafr** [ionic-team/ionic-native#1695]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Appears this error:

> Runtime Error
> Can't resolve all parameters for ContactField: (?, ?, ?).

**Expected behavior:**
It should run nornmally I just use the sample code that appears here https://ionicframework.com/docs/native/contacts/ 

**Other information:**
Ionic Framework: 3.3.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.2
Angular Compiler CLI: 4.1.2
Node: 6.11.0
OS Platform: Windows 10
Navigator Platform: Win32

**package.json info:**

```{
  "name": "demo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@ionic-native/contacts": "^3.12.1",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/splash-screen": "3.10.2",
    "@ionic-native/status-bar": "3.10.2",
    "@ionic/storage": "2.0.1",
    "cordova-plugin-contacts": "^2.3.1",
    "ionic-angular": "3.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.11"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-cordova": "1.4.0",
    "@ionic/cli-plugin-ionic-angular": "1.3.1",
    "typescript": "2.3.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-contacts": {}
    }
  }
}
```

**Comment by janpio** [comment]
This sounds more like a support problem, not a real bug in the plugin that is used by dozens of people. Please open a topic at the Ionic Forum: https://forum.ionicframework.com

**Comment by joansafr** [comment]
@janpio thank you, I thought the same but the error shows up without coding, just add the plugin and include in the imports in "app.module.ts" and the ts page, then compile and appears that message.

**Comment by janpio** [comment]
So no changes at your app at all?

**Comment by joansafr** [comment]
yes sir, just include the plugin and include the import.

**Comment by namnguyen289** [comment]
I also got the same problem, is there anybody can help?

**Comment by sabarinathen** [comment]
Can't resolve all parameters for ContactField: (?, ?, ?). i got this issue.I followed ionic/native contact

**Comment by janpio** [comment]
Same as I posted a month ago:
This sounds more like a support problem. Please open a topic at the Ionic Forum: forum.ionicframework.com
