### ISSUE TITLE
Latest Spinner dialog not available

### ISSUE THREAD

**Issue by guizmo** [ionic-team/ionic-native#1700]
When i install ionic-native/spinner-dialog "npm install --save @ionic-native/spinner-dialog"
I don't get the latest one with these changes https://github.com/ionic-team/ionic-native/pull/1675/files

What am i doing wrong ?

**Comment by greybax** [comment]
fix here https://github.com/ionic-team/ionic-native/pull/1859

**Comment by greybax** [comment]
I suppose this issue can be closed?
