### ISSUE TITLE
DateTime modal close with hardware back button wont work

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#1707]
_From @craftpip on June 17, 2017 20:28_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using the DateTime plugin, when the date time selector is open, the user cannot use the hardware back button to close the date time modal.

**Expected behavior:**
The date time modal should close when back button is pressed.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

_Copied from original issue: ionic-team/ionic#12079_

**Comment by ihadeed** [comment]
This doesn't seem like an issue with Ionic Native.

Ionic Native is just a wrapper and has no effect on how the plugin performs. I recommend asking for support at the plugin's repo or at the Ionic Forums.

**Comment by craftpip** [comment]
Okay thanks.

**Comment by alexnu** [comment]
Any news on that? I am also looking for a fix.
