### ISSUE TITLE
docs(onesignal): documentation doesn't match method

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-native#1710]
https://github.com/ionic-team/ionic-native/blob/master/src/@ionic-native/plugins/onesignal/index.ts#L582

documentation has parameter, method doesn't.

**Comment by AntonioMenti** [comment]
See https://forum.ionicframework.com/t/one-signal-problem/94981/17

The documentation present here 

[https://ionicframework.com/docs/native/onesignal/ ](url)

describe unreleased method getPermissionSubscriptionState

package.json:
`{
  "name": "Cremona_Circuit",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/background-geolocation": "^3.12.1",
    "@ionic-native/core": "3.10.2",
    "@ionic-native/facebook": "^3.12.1",
    "@ionic-native/geofence": "^3.12.1",
    "@ionic-native/geolocation": "^3.12.1",
    "@ionic-native/in-app-browser": "^3.12.1",
    "@ionic-native/onesignal": "^3.12.1",
    "@ionic-native/splash-screen": "^3.10.2",
    "@ionic-native/status-bar": "^3.10.2",
    "@ionic-native/youtube-video-player": "^3.12.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.4.2",
    "ionicons": "3.0.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-plugin-cordova": "1.4.0",
    "@ionic/cli-plugin-ionic-angular": "1.3.1",
    "typescript": "2.3.3"
  },
  "description": "An Ionic project"
}
`

**Comment by neoassyrian** [comment]
Should be resolved with this PR #1742

**Comment by rafbgarcia** [comment]
So this should be resolved, right?

**Comment by neoassyrian** [comment]
I believe so

**Comment by janpio** [comment]
I made the mistake of linking to master instead of to a commit - so I can't check what I was talking about back then. Shame.
