### ISSUE TITLE
feature(plugin) request: WiFiWizard

### ISSUE THREAD

**Issue by sajTempler** [ionic-team/ionic-native#1717]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request

**Expected behavior:**

Able to use plugin with Ionic Native

**Related code:**

`
https://github.com/hoerresb/WifiWizard/blob/master/README.md
`

**Comment by NodeKing** [comment]
I use WifiWizard, works great in my Ionic project. However, would be great to include in Ionic Native. Also, the project looks abandoned, the Ionic team should pick it up! :)

**Comment by danielsogl** [comment]
This plugin is out of date. Can you provide me an up-to-date fork? Then I will take a look into this plugin this week.

**Comment by NodeKing** [comment]
I'm not aware of any up-to-date fork, but v2.11 seems to work flawlessly with ionic even though it hasn't been updated for two years.

**Comment by danielsogl** [comment]
Im closing this issue because of duplicated feature request.
