### ISSUE TITLE
readAsArrayBuffer is returning empty on success or not working at all

### ISSUE THREAD

**Issue by malsf21** [ionic-team/ionic-native#1720]
**I'm submitting a ...**
[ x ] bug report
[ ] feature request

**Current behavior:**

`File.readAsArrayBuffer(path, file)` is returning an empty object on success, even when the file exists. I've been using this on an MP3 file, though I've found similar issues others have had such as #505 (which is not exactly the same thing, but a same outcome). Essentially, it's not working as intended.

I've tried swapping around URLs and such for the properties of `File.readAsArrayBuffer(path, file)`, but nothing has worked out. Unfortunately, the documentation on it is [quite sparse](https://ionicframework.com/docs/native/file/#readAsArrayBuffer). 

**Expected behavior:**

`File.readAsArrayBuffer(path, file)` should return an ArrayBuffer of the requested MP3 file. 

**Steps to reproduce:**

In emulator:

1. Create local audio file
2. Attempt to use `File.readAsArrayBuffer(path, file)` on local audio file
3. View returned promise file; find it's empty

**Related code block:**

*Note: in both of these code blocks, I use `this.File`; that is just an instance of `File`. Same thing with `this.context` and `AudioContext`.

This is the code block that is triggering the error
```javascript

getFileNative(){
    let fsurl = cordova.file.applicationDirectory + "www/assets/audio/";
    this.file.readAsArrayBuffer(fsurl, "file.mp3").then(
        (fileData: ArrayBuffer) => {
              console.log(fileData); // this is just {}, which it shouldn't be
              ....
        }
    )
}
...
```

This is what I'm doing with the "created" `ArrayBuffer`. It's not even being called though, as decodeAudioData stalls on the non-existent `fileData`.
```javascript

getFileNative(){
    let fsurl = cordova.file.applicationDirectory + "www/assets/audio/";
    this.file.readAsArrayBuffer(fsurl, "file.mp3").then(
        (fileData: ArrayBuffer) => {
              console.log(fileData); // this is just {}, and is the last thing that is called
              this.context.decodeAudioData(fileData).then(function(decodedData){
                console.log("Calling SetupBuffer Callback"); // this never gets called
                this.setupBuffer(decodedData); // setupBuffer() is a custom function, but it is not being called
...
```

**Other information:**

This is what appears in the iOS debugger as the last line before the app stalls.

```json
{
  "line":63191,
  "column":50,
  "sourceURL":"file:///Users/<username>/Library/Developer/CoreSimulator/Devices/16E62CEC-0A89-41F1-BC6E-89AAF767E80A/data/Containers/Bundle/Application/1A90C90F-DF7D-481C-845E-AA034E542053/MyApp.app/www/build/main.js",
  "__zone_symbol__currentTask":{
    "type":"microTask",
    "state":"notScheduled",
    "source":"Promise.then",
    "zone":"angular",
    "cancelFn":null,
    "runCount":0
  }
}
```

It seems as if `zone.js` is having problems with the file wrapper, which is consistent with #505 .

#505 has similar issues with `File.readAsArrayBuffer(path, file)`, though I'm getting the promise event to fire, it's just not returning anything. I've tried the solutions from @stalniy and @joewoodhouse but they aren't working out for me, nor is wrapping my code in `this.platform.ready` . 

**package.json info:**

```json
{
    "name": "App",
    "version": "0.0.1",
    "author": "App Team",
    "homepage": "http://random.website/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.10.2",
        "@ionic-native/file": "^3.12.1",
        "@ionic-native/splash-screen": "3.10.2",
        "@ionic-native/status-bar": "3.10.2",
        "@ionic/storage": "2.0.1",
        "chart.js": "^2.6.0",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.4.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.3.7",
        "@ionic/cli-plugin-cordova": "1.4.0",
        "@ionic/cli-plugin-ionic-angular": "1.3.1",
        "typescript": "2.3.3"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-file": {}
        },
        "platforms": [
            "ios"
        ]
    }
}
```

**Comment by malsf21** [comment]
Hey, it's been about a month; just wondering if anybody has had similar problems or a solution!

**Comment by joewoodhouse** [comment]
Why has this been closed? I'm still having this problem and still waiting for a solution.

**Comment by SellvakumarSS** [comment]
This issue still exists please help on this.

**Comment by malsf21** [comment]
Ah sorry, I apologize. To @joewoodhouse and @SellvakumarSS , I wasn't able to fully figure out the problem, so I implemented a different solution in my app. But, I did discover that the ArrayBuffer returned wasn't empty; rather, `console.log(ArrayBuffer)` returns an ArrayBuffer object that isn't properly readable by the console, which is why it seems empty.

I think (but don't know for sure) that the problem actually has to do with audioContext.decodeAudioData; it's actually not properly decoding the data and **not throwing an error**, making it seem like readAsArrayBuffer isn't working. [Here's an SO post](https://stackoverflow.com/questions/10365335/decodeaudiodata-returning-a-null-error) on it.

**Comment by SellvakumarSS** [comment]
I have tried the same for reading a video file and converting it to ArrayBuffer but empty response is coming in alert as well as console.I think there is some problem with File.ReadAsArrayBuffer().
@malsf21 What is the alternative u did for this???I need to convert video file into ArrayBuffer.
Any help from cordova or ionic team will be appreciable.

**Comment by malsf21** [comment]
@SellvakumarSS `alert()` and `console.log()` can't actually output the contents of the ArrayBuffer; just because the response is `{}` doesn't necessarily mean its empty.

If you specifically need the video in an ArrayBuffer, try creating an invisible `<video>` tag containing your video file and then grabbing the file/arraybuffer from there. If that doesn't work, then it's not a problem with `File.ReadAsArrayBuffer()`
