### ISSUE TITLE
[feature request]Add wrapper for cordova-plugin-file-transfer

### ISSUE THREAD

**Issue by iron9light** [ionic-team/ionic-native#1728]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

It will be great to add wrapper for [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer).
I need this plugin for downloading content and save to local as cache.
Since you guys have implemented cordova-plugin-file wrapper, this plugin is the best companion.

**Comment by ghenry22** [comment]
It already exists, check the ionic native docs

**Comment by ihadeed** [comment]
See http://ionicframework.com/docs/native/transfer/

**Comment by iron9light** [comment]
Oh! My...
Thank you all!!
