### ISSUE TITLE
Issues w/ InAppBrowser and WKWebView

### ISSUE THREAD

**Issue by jrmcdona** [ionic-team/ionic-native#1733]
Hello-

It looks like WKWebView responds to the app window closing and not loadStop event on iOS device.  (seems ok in simulator).

Is the recommended approach to use @manucorporat fork of the InAppBrowser plugin which works with WKWebView?  https://github.com/manucorporat/cordova-plugin-inappbrowser

Can you give guidance on how you would install this forked version?

Issue is mentioned here:
https://github.com/ionic-team/ionic-native/issues/522

And here:
https://stackoverflow.com/questions/38118311/cordova-inappbrowser-cannot-be-closed-because-of-wkwebview-plugin-in-ios#_=_

It might be good to update the ionic docs with this information as it takes some time to realize and research what is going on.   I'd be glad to PR a doc update once I figure out what is going on here!

Thanks

**Comment by jrmcdona** [comment]
Verified that https://github.com/manucorporat/cordova-plugin-inappbrowser works in WKWebView

**Comment by sputn1k** [comment]
@jrmcdona does is https://github.com/manucorporat/cordova-plugin-inappbrowser fork a WKWebView version of InAppBrowser?

**Comment by jrmcdona** [comment]
Yes

**Comment by sputn1k** [comment]
thanks for confirming.

**Comment by sputn1k** [comment]
@jrmcdona just ran a test doesn't look like wkwebview is running on inappbrowser open _blank. also no performance boost.

**Comment by jrmcdona** [comment]
It is working for me.  

I just needed InAppBrowser to work with WKwebview and this branch by Manu is for that.  Worked well for me.  

Perf boost probably different subject.

**Comment by jrmcdona** [comment]
Actually now that I think about I may have switched to use Cordova directly .  Will send code later

**Comment by sputn1k** [comment]
Cordova InAppBrowser uses UIWebView (4.0 over) not WKWebView (I am looking for a version of InAppBrowser that uses WKWebView engine - not along side it).

**Comment by jrmcdona** [comment]
Ok, the issue I had with the version in the docs is that it would not close for people using WKWebView.

This version addresses that.  

Here was the commit;
https://github.com/manucorporat/cordova-plugin-inappbrowser/commit/f3a8fbe1c0737138d4b0e1b358b1c2d6d5d2c16b

So that is why I found it.    @manucorporat maybe help to help you further since he wrote this and works for Ionic
