### ISSUE TITLE
404 Not found while installing ionic native modules

### ISSUE THREAD

**Issue by rehannawab** [ionic-team/ionic-native#1735]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

npm install of ionic native modules results in a 404 not found message as below

npm install --save @ionic-native/in-app-browser
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@ionic-native/in-app-browser"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Not found : @ionic-native/in-app-browser
npm ERR! 404
npm ERR! 404  '@ionic-native/in-app-browser' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\NSM-UI\trunk\NSM\npm-debug.log

**Comment by ihadeed** [comment]
The error message you provided doesn't contain any specific package name that I can use to reproduce this issue with. Therefore, I can't verify if this is an actual issue with Ionic Native.
