### ISSUE TITLE
SQL porter unnecessary depends on cordova

### ISSUE THREAD

**Issue by Robertbaelde** [ionic-team/ionic-native#1739]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**Current behavior:**

The SQLPorter doesn't work with ionic serve because it requires cordova to be present. This while it doesn't make any use of cordova at all. 
**Expected behavior:**

It should be relative easy to make the plugin not depend on cordova. 

**Related code:**
This code should work with ionic serve.. 
```
let db = window.openDatabase('Test', '1.0', 'TestDB', 1 * 1024);
let sql = 'CREATE TABLE Artist ([Id] PRIMARY KEY, [Title]);' +
           'INSERT INTO Artist(Id,Title) VALUES ("1","Fred");';
this.sqlitePorter.importSqlToDb(db, sql)
  .then(() => console.log('Imported'))
  .catch(e => console.error(e));
```

**Comment by ihadeed** [comment]
Ionic Native wraps Cordova plugins. Even though this plugin doesn't require any native code, it still runs on a native platform. You need to run your app on Cordova Browser platform if you wish to take advantage of the browser capabilities. Alternatively, you can copy their code and inject it in your app manually.
