### ISSUE TITLE
FCM Plugin in Ionic Native Doesn't Fail Gracefully

### ISSUE THREAD

**Issue by stalinkay** [ionic-team/ionic-native#1745]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
FCM Plugin does not fail gracefully in the browser,
<img width="397" alt="screen shot 2017-06-29 at 9 27 28 pm" src="https://user-images.githubusercontent.com/198020/27708885-2e689c2e-5d12-11e7-90e2-04c53744761d.png">

**Expected behavior:**
FCM Plugin should fail gracefully

**Steps to reproduce:**
Simply use this code in a project and run in it in the browser

**Related code:**

```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { TabsPage } from '../pages/tabs/tabs';

import { FCM } from '@ionic-native/fcm';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage: any = TabsPage;
  isIOS: boolean = false;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, private fcm: FCM) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.isIOS = platform.is('ios');

      if (this.isIOS) {
        // disable status bar overlay webview
        statusBar.overlaysWebView(false);
      } else {
        // let status bar overlay webview
        statusBar.overlaysWebView(true);
      }

      // set status bar to white
      statusBar.backgroundColorByHexString('#8c0f1a');

      // use light content
      statusBar.styleLightContent();

      splashScreen.hide();

        fcm.subscribeToTopic('marketing');

        fcm.getToken().then(token => {
          // backend.registerToken(token);
          console.log(token);
        });

        fcm.onNotification().subscribe(data => {
          if (data.wasTapped) {
            console.log("Received in background");
          } else {
            console.log("Received in foreground");
          };
        });

        fcm.onTokenRefresh().subscribe(token => {
          // backend.registerToken(token);
          console.log(token);
        });
      }

  }
}
```

**Other information:**
The only way I managed to resolve this was by wrap the FCM code below in a `if (platform.is('cordova')){...}`

**package.json info:**

``{
    "name": "my-app",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve",
        "test:coverage": "ng test --code-coverage",
        "test": "ng test",
        "test:ci": "ng test --single-run --code-coverage",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor",
        "postinstall": "webdriver-manager update",
        "nuke": "./clean-project.sh"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.10.2",
        "@ionic-native/fcm": "^3.12.1",
        "@ionic-native/geolocation": "^3.12.1",
        "@ionic-native/google-maps": "^3.12.1",
        "@ionic-native/splash-screen": "3.10.2",
        "@ionic-native/status-bar": "3.10.2",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.4.0",
        "cordova-ios-plugin-no-export-compliance": "0.0.2",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.7",
        "cordova-plugin-device": "^1.1.6",
        "cordova-plugin-fcm": "^2.1.2",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-googlemaps": "^1.4.1",
        "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
        "cordova-plugin-ios-no-export-compliance": "~0.0.2",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.3",
        "cordova-plugin-whitelist": "^1.3.2",
        "cordova-plugin-wkwebview-engine": "git+https://github.com/ionic-team/cordova-plugin-wkwebview-engine.git",
        "ionic-angular": "3.4.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@angular/cli": "^1.1.2",
        "@angular/router": "^4.2.3",
        "@ionic/app-scripts": "1.3.7",
        "@ionic/cli-plugin-cordova": "1.4.0",
        "@ionic/cli-plugin-ionic-angular": "1.3.1",
        "@types/jasmine": "^2.5.52",
        "@types/node": "^7.0.31",
        "jasmine-core": "^2.6.4",
        "jasmine-spec-reporter": "^4.1.0",
        "karma": "^1.7.0",
        "karma-chrome-launcher": "^2.1.1",
        "karma-cli": "^1.0.1",
        "karma-coverage-istanbul-reporter": "^1.3.0",
        "karma-jasmine": "^1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "mkdirp": "^0.5.1",
        "protractor": "^5.1.2",
        "ts-node": "^3.0.6",
        "typescript": "2.3.3",
        "webdriver-manager": "^12.0.6"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-ios-no-export-compliance": {},
            "cordova-plugin-googlemaps": {
                "API_KEY_FOR_ANDROID": "secret",
                "API_KEY_FOR_IOS": "secret",
                "NSLOCATIONWHENINUSEUSAGEDESCRIPTION": "Show your location on the map",
                "NSLOCATIONALWAYSUSAGEDESCRIPTION": "Trace your location on the map"
            },
            "cordova-plugin-wkwebview-engine": {},
            "cordova-plugin-geolocation": {
                "GEOLOCATION_USAGE_DESCRIPTION": " "
            },
            "cordova-plugin-fcm": {}
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}
```

ionic info

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.0.3 

```

**Comment by ihadeed** [comment]
You need to add a catch block to the promise. 

```ts
// noop catch block
fcm.subscribeToTopic('marketing').catch(() => {});

// useful catch block
fcm.subscribeToTopic('marketing').catch(e => console.log('Error subscribing to topic', e));
```
