### ISSUE TITLE
@ionic-native/network onConnect() not getting triggered.

### ISSUE THREAD

**Issue by polcham** [ionic-team/ionic-native#1746]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**

When the app loads, turn the wifi-off. The onDisconnect alert pop up will show up. However, turning the wifi-on DOES NOT show the alert pop up for onConnect.

**Expected behavior:**

The popup "Online" should show up when the user went back Online.

**Steps to reproduce:**

Load the app, then disconnect on the internet then connect to the internet.

**Related code:**
```
this.network.onConnect().subscribe(() => {
    //not getting called
    alert("Online!");
});
this.network.onDisconnect().subscribe(() => {
    //getting called
    alert("Offline!");
});
```

**Other information:**

global packages:
@ ionic/cli-utils : 1.4.0
Cordova CLI      : 7.0.1 
Ionic CLI        : 3.4.0

local packages:
@ ionic/app-scripts              : 1.3.8
@ ionic/cli-plugin-cordova       : 1.4.0
@ ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : ios 4.4.0
Ionic Framework                 : ionic-angular 3.4.2

System:
Node       : v8.1.3
OS         : macOS Sierra
Xcode      : Xcode 8.3.3 Build version 8E3004b 
ios-deploy : 1.9.1 
ios-sim    : 6.0.0 
npm        : 5.0.3 

**package.json info:**

```json
"@ionic-native/network": "^3.12.1"
"cordova-plugin-network-information": "^1.3.3"
```

**Comment by ihadeed** [comment]
1. are you waiting for `platform.ready()` or `deviceready` event?
2. Does this work:
```
document.addEventListener('online', () => console.log('Online!'), false);
```

**Comment by polcham** [comment]
I'm calling the onConnect() and onDisconnect functions inside my NetworkProvider class. 
During the constructor of the NetworkProvider class, I create the listeners.

It seems to work inconsistently; I tested again today and it is able to trigger onConnect() once. Disconnecting and connecting the internet again doesn't trigger the onConnect() again. 

    constructor(private platform: Platform,
    private network: Network,
    private events: Events) {
        this.platform.ready().then(() => {
            this.networkOnlineSubscription = this.network.onConnect().subscribe(() => {
            this.events.publish('network:online', true);
            this.connected = true;
          });
          this.networkOfflineSubscription = this.network.onDisconnect().subscribe(() => {
            this.events.publish('network:online', false);
            this.connected = false;
          });
      });
    });
  }

**Comment by ihadeed** [comment]
You didn't answer my second question, does that code snippet work as expected? or are you having the same issues with it?

Also, if you are running this code on app startup, try adding a 1 second delay before executing it. Sometimes `platform.ready()` fires too early.

**Comment by polcham** [comment]
Same effect with document.addEventListener('online', () => console.log('Online!'), false); I deployed the app via Xcode to an iPhone-6. And everything is working as expected, could be an issue with the iOS Simulator?

**Comment by cmargulhano** [comment]
Hi guys, I'm having the same problem right now.
Any news?
Thanks

**Comment by tonysamperi** [comment]
Same here.
And "network status" returns always "unknown"
