### ISSUE TITLE
SWIFT Version

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ionic-team/ionic-native#1749]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**

After building my app with the command
ionic cordova build Ios and uploading the generated ipa-file to app-store i get a validation error from Apple

Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it. 

**Expected behavior:**
I expect to be able to upload the generated ipa-file without having to use xcode to create the package file

**Steps to reproduce:**
I can start xcode and select SWIFT 3.0 and have a work-around, but it is important for new users that this works out of the box

**Comment by danielsogl** [comment]
This has nothing tondo with Ionic native.

**Comment by ThorvaldAagaard** [comment]
You are probably right, but as https://github.com/ionic-team/ionic-native/tree/master/src/%40ionic-native/plugins/native-geocoder is wrapping native-geocoder, and that plugin is using Swift 3.0, I think that it needs to be looked at. If not any suggestions about where to report this will be appriciated

**Comment by danielsogl** [comment]
Report it here (the source repo): https://github.com/sebastianbaar/cordova-plugin-nativegeocoder
