### ISSUE TITLE
How to get geolocation in IONIC 2 for android 7 and higher

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [ionic-team/ionic-native#1753]
Ionic version:
Ionic Framework Version: 3.0.1

Currently I am using 
https://github.com/apache/cordova-plugin-geolocation

Cordova geolocation does not support android 7.0 and higher

Current behavior:
 Working on 6 but not on android 7.0 and higher

Expected behavior:
Should work on 7.0 and higher

Kindly suggest me another plugin which can support the latest version of android eg. 7.0

**Comment by ihadeed** [comment]
Not an Ionic Native issue. Please ask your question on the forums.

I personally can use this plugin on Android 7+ without any issues. You just need to make sure that the location services are enabled before requesting the location. You can use the Diagnostic plugin for that.
