### ISSUE TITLE
Media Plugin  FAILED renaming audioFile

### ISSUE THREAD

**Issue by zhujunwei** [ionic-team/ionic-native#1754]
**Related code:**

```
    if (AppGlobal.getInstance().isIos) {
      this.newFile = this.file.documentsDirectory;
      this.fileName = this.newFile.replace(/file:\/\//g, '') + this.toId + (new Date().getTime())+'.wav';
    } else {
      this.newFile = this.file.dataDirectory;
      this.fileName = this.newFile + this.toId + (new Date().getTime())+'.3gp';
    }    
    this.mediaObject = this.media.create(this.fileName,
                  onStatusUpdate, onSuccess, onError);
    this.mediaObject.startRecord();
    this.mediaObject.stopRecord();                
    this.mediaObject.release();
```

**Other information:**

**package.json info:**

Hello,i'm using ionic/native media plugin;Everything go well,but when I exec  stopRecord() ,there is an error 'E/AudioPlayer: FAILED renaming /storage/emulated/0/tmprecording-1499067182257.3gp to /data/user/0/com.itsnow.app.serviceexpert/files/09445BB43BEC0C2E7C0CD883C0798CA01499067182231.3gp' on Android;So, I cannot get the file I named ;Is there anyone who can help me?

**Comment by ihadeed** [comment]
Doesn't seem like an Ionic Native specific issue. I suggest you ask for help on the forums.

**Comment by enraiser** [comment]
Which forum we should ask?

**Comment by francovp** [comment]
@enraiser I can't find a solution for this :( do you have it? please

**Comment by enraiser** [comment]
I answered at [stackoverflow](https://stackoverflow.com/questions/42870171/cordova-6-5-0-fails-recording-audio-using-cordova-plugin-media-failed-renaming/46278809#46278809)
