### ISSUE TITLE
Bad description for Ionic Native ActionSheet

### ISSUE THREAD

**Issue by Smoke1987** [ionic-team/ionic-native#1755]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
On the site with the documentation for the framework, namely the link: [https://ionicframework.com/docs/native/action-sheet/](https://ionicframework.com/docs/native/action-sheet/) in the usage section, an example of using this plugin is given. But! Interface **ActionSheetOptions** has one "mandatory" field (not optional) - **buttonLabels**. Perhaps this feature is observed only in me, but: when enumerating the parameters of **ActionSheetOptions** my PHPStorm swears (red waves appear). Everthing is working just fine, but only the red stuff is strange.

**Expected behavior:**
-

**Steps to reproduce:**
-

**Related code:**

```
import { ActionSheet, ActionSheetOptions } from '@ionic-native/action-sheet';
...
let buttonLabels = ['Выбрать файл', 'Сделать фото'];

        const options: ActionSheetOptions = {
            buttonLabels: buttonLabels,
            title: 'Выберите способ',
            addCancelButtonWithLabel: 'Отмена',
            androidTheme: this.actionSheet.ANDROID_THEMES.THEME_HOLO_DARK
        };
```

**Other information:**
![1](https://user-images.githubusercontent.com/26324597/27784419-f9ca1d18-5fea-11e7-8283-f64e4153d1a9.jpg)
![screenshot_2017-07-03-11-22-08](https://user-images.githubusercontent.com/26324597/27784718-2cc29514-5fec-11e7-8828-db7269b8c78d.png)

**package.json info:**

```json
{
  "name": "name",
  "description": "description",
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.0",
    "@angular/compiler": "4.1.0",
    "@angular/compiler-cli": "4.1.0",
    "@angular/core": "4.1.0",
    "@angular/forms": "4.1.0",
    "@angular/http": "4.1.0",
    "@angular/platform-browser": "4.1.0",
    "@angular/platform-browser-dynamic": "4.1.0",
    "@ionic-native/action-sheet": "^3.12.1",
    "@ionic-native/camera": "^3.12.1",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/device": "^3.7.0",
    "@ionic-native/geolocation": "^3.7.0",
    "@ionic-native/http": "^3.12.1",
    "@ionic-native/in-app-browser": "^3.7.0",
    "@ionic-native/keyboard": "^3.12.1",
    "@ionic-native/local-notifications": "^3.12.1",
    "@ionic-native/native-audio": "^3.12.1",
    "@ionic-native/splash-screen": "3.6.1",
    "@ionic-native/status-bar": "3.6.1",
    "@ionic/storage": "2.0.1",
    "angular-activity-monitor": "^1.1.0",
    "ionic-angular": "3.2.0",
    "ionicons": "3.0.0",
    "lodash": "^4.17.4",
    "ng2-cookies": "^1.0.12",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.10"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "typescript": "2.2.1"
  },
  "config": {}
}
```

**Comment by ihadeed** [comment]
I just tried creating a similar object in WebStorm without issues.

It could be an issue with the IDE... use `any` as a type instead of `ActionSheetOptions`.
