### ISSUE TITLE
How to get geolocation in IONIC 2 for android 7 and higher

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#1757]
_From @Gurjit-ONEBCG on July 3, 2017 5:28_

Ionic version:
Ionic Framework Version: 3.0.1

Currently I am using 
https://github.com/apache/cordova-plugin-geolocation

Cordova geolocation does not support android 7.0 and higher

Current behavior:
 Working on 6 but not on android 7.0 and higher

Expected behavior:
Should work on 7.0 and higher

Kindly suggest me another plugin which can support the latest version of android eg. 7.0

_Copied from original issue: ionic-team/ionic#12237_

**Comment by jgw96** [comment]
_From @AmitMY on July 3, 2017 6:6_

- Please fill the issue template
- This should be opened against`ionic-native` or that plugin's repo, as it is not a problem with the framework but with a native plugin

**Comment by ihadeed** [comment]
@Gurit-ONEBCG just tested it on a Nexus 5x device with Android 7.1.x. It works well. You just need to make sure that the location services are enabled before requesting location. You can use the Diagnositcs plugin to this.

**Comment by sunil237216** [comment]
@gurit-onebcg not working in my case checking the location service using Diagnositcs plugin still the same issue please help..

**Comment by Jeet0027** [comment]
@sunil237216  Please make sure that you have enabled the location setting of your device.
Do it mannualy to test.

**Comment by sunil237216** [comment]
@Jeet0027 Can you please provide me working code... I  have  tried everything,  Nothing is working out. Ionic framework does not make any sense if plugin doesn't work....

**Comment by Gurjit-ONEBCG** [comment]
@sunil237216 
To check if location enabled 

 ` checkLocation(IfAlreadyOpenPunch: boolean = false) {

    return this.diagnostic.getLocationAuthorizationStatus().then(r => {
      let openPunchMsg = "";
      if (IfAlreadyOpenPunch) {
        openPunchMsg = " As you have already open punch.";
      }
      if (r == 'DENIED_ALWAYS' || r.toString().toLowerCase() == 'denied') {
        let message = "Please enable your app location.";
        this.locationAlert(message + openPunchMsg, false);
        return false;
      }
      else {
        if (this.platform.is('android')) {
          return this.diagnostic.isGpsLocationAvailable().then(chk => {

            if (!(chk)) {
              let message = "Please set your location to High accuracy." + openPunchMsg;
              //  let message = "Please set your location Mode to Device Only. Location > Mode > Device Only"+IfAlreadyOpenPunch;
              this.locationAlert(message, true);
              return false;
            }
            else {
              return true;
            }
          });

        }
         
      }
    }).catch(e => {
      return false;
    });
  }`


After that get location by this

 let options = {
        enableHighAccuracy: true,
        maximumAge: 0,
      };
      this.geolocation.getCurrentPosition({ enableHighAccuracy: true }).then((position) => {

})

**Comment by sunil237216** [comment]
@Gurjit-ONEBCG  Thank you, I got this issue resolve by deleting the entire npm_module folder and then doing npm install...still I have an issue with xiaomi mi5 which runs on Android version 7, Work on other devices.

**Comment by Jeet0027** [comment]
sunil I checked in xiomi mi5 as well and its working.. Please check your application permission for location

**Comment by sunil237216** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.NETWORK_ACCESS" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />

@Jeet0027  those are permission  I am currently using

**Comment by mfouadegy** [comment]
same problem with me :(

**Comment by raphaelluiz128** [comment]
do you finish your project?
