### ISSUE TITLE
Failed to load resource file:///android_asset/www/build/core.es5.js.map

### ISSUE THREAD

**Issue by zenismaharjan** [ionic-team/ionic-native#1761]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by ihadeed** [comment]
Not sure what the issue is here, or if it's even related to Ionic Native. 

Once you've have narrowed down the cause of the problem, or gathered more info. You can open a new issue at the appropriate repo. Also, make sure to fill out the issue template.
