### ISSUE TITLE
Ionic Native v2 documentation

### ISSUE THREAD

**Issue by emir-harbinja** [ionic-team/ionic-native#1762]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Other information:**
The site http://ionicframework.com/docs/v2/native/ redirects to the documentation for Ionic Native v3.x. I haven't managed to find any live version of the v2 docs which contains documentation on how to use Ionic Native plugins with version 2.x of the library.

Given the fact that the mainline v3 branch of Ionic native presents a breaking change (given its dependency on Angular), and your pledge to further support the 2.x branch, could you please publish the v2 docs again?

Thanks!

**Comment by ihadeed** [comment]
Attn. @mlynch @perrygovier

**Comment by ihadeed** [comment]
@emir-harbinja for now, you can visit the 2.x branch and go through the definitions to find the docs there.

Also, may I ask what is the reason you are still using Ionic Native 2.x?

**Comment by janpio** [comment]
Just a sidenote: `v2` in the URL here once referred to version 2 of Ionic, not Ionic Native. Ionic Native documentation has never been archived on ionicframework.com unfortunately.

**Comment by emir-harbinja** [comment]
@ihadeed 

We have several existing projects which don't use Ionic and/or Angular but make extensive use of cordova plugins. We integrated Ionic Native because of its leightweight, uniform interface and use of mechanisms such as ES Modules, Promises and Observables, which tie in neatly into the rest of the application.

The tie-in with Angular in the newest release is a unfortunately a deal breaker for us because it brings to much overhead in regard to its initial purpose, which for us was basically a stable plugin facade.

**Comment by danielsogl** [comment]
Ionic Native V5 will fix that.
