### ISSUE TITLE
email-composer: Different repo?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-native#1763]
Email Composer in Ionic Native is using https://github.com/hypery2k/cordova-email-plugin with 37 stars, but there exists https://github.com/katzer/cordova-plugin-email-composer with 268 stars and more functionality.

Maybe this should be switched over?

**Comment by ihadeed** [comment]
katzer's repo was not maintained for awhile, and the plugin wasn't functioning properly. That's why we switched.

I guess we can switch back to katzer's repo now.

**Comment by janpio** [comment]
Ah, didn't look into the history.

(Somehow this "I have to look at forks manually to find an actively supported version" situation is making me uncomfortable.... there has to be a better way.)

**Comment by ihadeed** [comment]
The better way is what max talked about here #1622 ... or alternatively, what Telerik is kinda doing. Fork plugins, make sure they're stable, and support them privately (rather than relying on the developer). This ensures that the framework's users are happy with functional plugins.
