### ISSUE TITLE
How to keep running application even if the user close the application 

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [ionic-team/ionic-native#1765]
**I need to keep running application even if the user close the application forcefully. 
 Actually I want to keep getting the current location of user even when the application is completely closed eg. There is an application available on iOS store and play store named as "Runtastic Running.."
In this app, it will keep tracking your location even when you close the application forcefully after starting the walk. **   

Using IONIC 2

**Current behavior:**
  If I use background mode. Application works but only if application is not  closed but running in background  

**Expected behavior:**
  Application should work if I want, when its closed

**Comment by renatoalencar** [comment]
Did you try service worker?

**Comment by ihadeed** [comment]
Closing this since it's not an issue with an Ionic Native wrapper.

Please ask for support in the Ionic Forums instead.
