### ISSUE TITLE
LatLng Bounds google maps

### ISSUE THREAD

**Issue by francoro** [ionic-team/ionic-native#1772]
With this code i can get the zoom and lat and lng, but i need the latLngBounds. Someone knows a way to get them.
```
map.on(GoogleMapsEvent.CAMERA_CHANGE).subscribe(data => {
            console.log("camarachange",data);
});
```

`CameraPosition {zoom: 14.15488052368164, tilt: 0, target: Object, bearing: 0, hashCode: -1384107267…}`

Inside target object there is the lat and lng object it doenst say anything about the bounds.

The documentation says : 
```
export interface CameraPosition {
  target?: LatLng | LatLngBounds | LatLng[];
  zoom?: number;
  tilt?: number;
  bearing?: number;
}
```

Apparantly it has the bounds but how can i get them instead of latLng

**Comment by ihadeed** [comment]
The `target` property is the LatLngBounds.

**Comment by francoro** [comment]
No, it doesn't . it only contains lat and lng, and what i need is something like this: 

(this is the javascript sdk way, i need the native way)
let bounds = map.getBounds();
let NE = bounds.getNorthEast()
let SW = bounds.getSouthWest();
parameters.NELat = NE.lat();
parameters.NELng = NE.lng();
parameters.SWLat = SW.lat();
parameters.SWLng = SW.lng();

**Comment by ihadeed** [comment]
You can do the same with Ionic Native..
```ts
map.getBounds();
```

**Comment by ihadeed** [comment]
Sorry I was wrong.

You can do the following for now:
```ts
map._objectInstance.getBounds();
```

`map._objectInstance` returns the original map object.

**Comment by ihadeed** [comment]
I don't see `map.getBounds()` in the plugin's docs https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v1.4.0/class/Map

I'm not sure where you got that example from. The plugin doesn't follow the JavaScript SDK.

**Comment by francoro** [comment]
map.getBounds() and map._objectInstance.getBounds(); none of the two worked. i get this error : typeerror map.getbounds is not a function.

The example that i show you is using google maps but without the plugin, i need a solution with the plugin , a solution for the native map

**Comment by ihadeed** [comment]
Ionic Native wraps the Cordova Plugin. It doesn't work with the JavaScript SDK provided by Google.

**Comment by francoro** [comment]
I found it! 
map.getVisibleRegion().then((data) => {
    
 })

this method returns the bounds for native way

**Comment by Deliph13** [comment]
> I found it!
> map.getVisibleRegion().then((data) => {
> 
> })
> 
> this method returns the bounds for native way

example ??

**Comment by kentastudillo** [comment]
@Deliph13 here's what you'll get when ```using map.getVisibleRegion()```

<img width="540" alt="screen shot 2018-12-10 at 8 33 22 am" src="https://user-images.githubusercontent.com/11402312/49705086-6d8acc80-fc56-11e8-803f-8c15458b5f47.png">
