### ISSUE TITLE
UNMET PEER DEPENDENCY @ionic/app-scripts@2.0.0

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-native#1783]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

`ionic start`

then

`npm install --save @ionic-native/android-permissions`

gives

```
+-- @ionic-native/android-permissions@3.14.0
-- UNMET PEER DEPENDENCY @ionic/app-scripts@2.0.0
```

Source:
https://forum.ionicframework.com/t/cant-install-any-native-extensions/97520

**Expected behavior:**
No errors with starter projects.

**Comment by ihadeed** [comment]
Ionic native modules do not depend on `@ionic/app-scripts`. That error is probably caused by another module. If there is an unmet dependency, the warning is displayed on every command.
