### ISSUE TITLE
docs: clarify Image Picker install docs

### ISSUE THREAD

**Issue by NoNameProvided** [ionic-team/ionic-native#1787]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

Description mention two plugin, one of them is uninstallable. The `ionic cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker.git --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="your usage message"` command cannot be run.

**Expected behavior:**

Clear, steps what to install, and expect installation to succeed.

**Steps to reproduce:**

Try install the `https://github.com/Telerik-Verified-Plugins/ImagePicker.git` plugin.

**Related code:**

n/a

**Other information:**

**package.json info:**

```json

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 5.1.0 
```

**Comment by ihadeed** [comment]
Are you having issues because you're trying to install from a git repo? try installing from `cordova-plugin-telerik-imagepicker` instead of that git repo link

**Comment by NoNameProvided** [comment]
Yeah, figured out. Docs should be updated right?

**Comment by ihadeed** [comment]
Already pushed a commit to update it. It will be published to the production site some time soon.

**Comment by NoNameProvided** [comment]
Thanks
