### ISSUE TITLE
Could not install from "cordova-plugin-useragent" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by MaheshKannaR** [ionic-team/ionic-native#1789]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

**Current behavior:**

This package is not getting installed.

**Expected behavior:**

cordova plugin add https://github.com/LouisT/cordova-useragent should work fine

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**package.json info:**

```json
[2017-07-11T16_03_57_422Z-debug.txt](https://github.com/ionic-team/ionic-native/files/1139577/2017-07-11T16_03_57_422Z-debug.txt)
[2017-07-11T15_55_10_861Z-debug.txt](https://github.com/ionic-team/ionic-native/files/1139578/2017-07-11T15_55_10_861Z-debug.txt)


insert the content here
```

**Comment by danielsogl** [comment]
@MaheshKannaR I updated the npm release. Can you check it again?

**Comment by Darkaoi** [comment]
Installed following the steps but when i fired the get method it says that the native plugin is not installed.

**Comment by Darkaoi** [comment]
@MaheshKannaR i installed the plugin but when i fired the method .get , it says that there's no plugin installed.

**Comment by dtmp** [comment]
+1

**Comment by mateo666** [comment]
same here... Any fix ?

**Comment by alalca** [comment]
Same here. After install it, plugin is not installed.

**Comment by RealTJ** [comment]
same here.

**Comment by codewise-nicolas** [comment]
hate to say it, but me too.

**Comment by codewise-nicolas** [comment]
See here for the fix to the not installed error [https://github.com/ionic-team/ionic-native/issues/2287](https://github.com/ionic-team/ionic-native/issues/2287)
