### ISSUE TITLE
ble observable data not updating template variables

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#1794]
_From @PurpleEdge2214 on July 12, 2017 2:55_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
There have been several reports on the Ionic support forum about variables within a ble observable not updating the display variables on a template...

https://forum.ionicframework.com/t/page-wont-refresh-in-ionic/97100
https://forum.ionicframework.com/t/results-from-ble-scan-not-invoking-angular-update/91935

Basically, when a declared variable is assigned a value within a ble observable the screen doesn't get updated until there is some interaction with the screen - e.g. tapping a button.

**Expected behavior:**
Values assigned within a ble observable should update the template display variables immediately.

**Steps to reproduce:**
See code below, ble needs a device so can't reproduce on plunker.

**Related code:**

```
import { Component, NgZone } from '@angular/core';
import { NavController } from 'ionic-angular';
import { BLE } from '@ionic-native/ble';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  private deviceId: string;
  private characteristics = [];
  private heartRate = 50;
  private connected = false;
  
  constructor(
    public navCtrl: NavController,
    private ble: BLE,
    private zone: NgZone
  ) {

  }

  getConnection() {
    this.connectToDevice()
    .then((connected) => {
      this.connected = connected;  // this gets updated in template
    })
  }

// this is a hack to get the data from the observable to a promise
// so the variable DOES get updated
  connectToDevice(): Promise<any> {
    console.log('clicked');
    return new Promise(resolve => {
      this.ble.scan([], 5)
        .subscribe((data) => {
          if (data.id) {
            this.deviceId = data.id;
            this.ble.connect(data.id)
              .subscribe((subData) => {
                this.characteristics = subData.characteristics;
                console.log('this.characteristics', this.characteristics);
                resolve(true);
              })
          }
        })
    })
  }

  readHR() {
    this.startHrNotification()
      .subscribe((response) => {
        var data = new Uint8Array(response);

// this is a WORKAROUND to resolve the issue
        this.zone.run(() => this.heartRate = data[1]);  // this gets updated
        console.log(this.heartRate);
      })
  }

  startHrNotification(): Observable<any> {
    if (!this.connected) {
      console.log('Not Connected');
    } else {
      return this.ble.startNotification(this.deviceId, "180d", "2a37")
    }
  }

  disconnect() {
    this.ble.disconnect(this.deviceId);
  }

}

```

**Other information:**

WORKAROUND - use ngZone and zone.run() to update display

```
 ordova CLI: 7.0.1
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

_Copied from original issue: ionic-team/ionic#12324_

**Comment by ihadeed** [comment]
can you replace `readHR` and `startHrNotification` methods with the following:

```ts
  readHR() {
    console.log('Is readHR in NGZone?', NgZone.isInAngularZone());
    this.startHrNotification()
      .subscribe((response) => {

        console.log('Is Observable Callback in NgZone?', NgZone.isInAngularZone());
        var data = new Uint8Array(response);

        // this is a WORKAROUND to resolve the issue
        this.zone.run(() => this.heartRate = data[1]);  // this gets updated
        console.log(this.heartRate);
      })
  }

  startHrNotification(): Observable<any> {
    console.log('Is startHrNotification in Angular Zone?', NgZone.isInAngularZone());
    if (!this.connected) {
      console.log('Not Connected');
    } else {
      return this.ble.startNotification(this.deviceId, "180d", "2a37")
    }
  }

```

Let me know what the results are.

**Comment by PurpleEdge2214** [comment]
Thanks ihadeed...

```
Is readHR in NGZone? true
main.js:55879 Is startHrNotification in Angular Zone? true
main.js:55872 Is Observable Callback in NgZone? false
main.js:55875 52
main.js:55872 Is Observable Callback in NgZone? false
main.js:55875 53
main.js:55872 Is Observable Callback in NgZone? false
main.js:55875 53
main.js:55872 Is Observable Callback in NgZone? false
main.js:55875 53
main.js:55872 
```

**Comment by PurpleEdge2214** [comment]
Ibby, can you please update the status, or do I need to create a new report in my own name for the reply to be visible - sorry, not sure how this process works?

**Comment by ihadeed** [comment]
@PurpleEdge2214 

I looked at the wrapper and I couldn't find anything wrong with it, can't tell why you're experiencing this issue. I'll investigate it further when I get a chance. I can't give you a time estimate. This isn't going to be a top priority since it's not a major issue, and also because I don't have a BLE based application

It seems like you have a nice work around (`NgZone.run()`). So, I'm assuming that your app should be functioning well until there's a fix for this issue.

**Comment by PurpleEdge2214** [comment]
Thanks Ibby, No problem, just wanted to be sure you got what you requested. The workaround works fine - might be easier to update the documentation.

**Comment by cgrall4cloud** [comment]
I have the same issue with ionic native network and other Observables ... in the browser(ionic serve) everything works as expected but on the devide or browser platform not.

**Comment by jovanialferez** [comment]
i got similar issue with [using in-app-purchase](https://github.com/j3k0/cordova-plugin-purchase). the workaround works great! thanks!

**Comment by federhico** [comment]
@jgw96 I have this same bug, ¿ Milestone 4 ? (The workarround is fine but...)
