### ISSUE TITLE
Google Analytics -- startTrackerWithId promise never called

### ISSUE THREAD

**Issue by stevehanson** [ionic-team/ionic-native#1803]
**I'm submitting a**
[x] bug report
[ ] feature request

**Current behavior:**

[The Ionic Native docs](http://ionicframework.com/docs/native/google-analytics/) indicate that the Google Analytics plugin method `startTrackerWithId` returns a promise and can be interacted with like so:

```js
this.ga.startTrackerWithId('YOUR_TRACKER_ID')
   .then(() => console.log('GA ready'))
   .catch(err => console.error(err))
```

However, My promise never seems to be resolved or rejected. The following code only outputs "Platform ready, starting GA...":

```js
this.platform.ready().then(() => {
  console.log('Platform ready, starting GA...')
  this.ga.startTrackerWithId('MY_TRACKER_ID')
    .then(() => console.log('GA ready'))
    .catch(err => console.error(err))
})
```

Additionally, I've noticed that the Cordova Google Analytics Plugin that this wraps does not indicate that this method returns a promise or accepts a callback function [in their docs](https://github.com/danwilson/google-analytics-plugin#javascript-usage).

It works correctly if I just treat `startTrackerWithId` as a synchronous function:

```
this.ga.startTrackerWithId('YOUR_TRACKER_ID')
this.ga.trackView('My Page')
```

**My question:** Is `startTrackerWithId` definitely an async function that returns a promise? If not, should the wrapper and docs be updated to indicate that it is synchronous?

**Other information:**

I'm using Ionic Native 3.14.0

**Comment by ihadeed** [comment]
Their docs don't mention the callbacks, but they are present in the source code: 
https://github.com/danwilson/google-analytics-plugin/blob/master/www/analytics.js#L3
The callbacks are also used on the native side. 
- Android: https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L158
- iOS: https://github.com/danwilson/google-analytics-plugin/blob/master/ios/UniversalAnalyticsPlugin.m#L34

It looks to me that the Ionic Native wrapper is written correctly, and it is passing the `resolve`/`reject` methods of the promise to the method as callbacks. I'm not sure why they're not being fired. 

I doubt that it has anything to do with the plugin not being ready, if that was the case, you would get Ionic Native error `plugin_not_installed`.

**Comment by stevehanson** [comment]
Thanks for looking into that, @ihadeed!

I just realized I am using version 1.6.0 of the Cordova GA plugin, which was released last year. It looks like in that version the `startTrackerWithId` function [didn't accept a `dispatch` parameter](https://github.com/danwilson/google-analytics-plugin/blob/1.6.0/www/analytics.js#L3) like it does now. Is it possible that that is what was causing the issue?

I can just go ahead and upgrade the Cordova plugin in my project. Feel free to close this issue, and I will report back if I find steps to reproduce using a current version.

On a somewhat related note, is there a matrix somewhere where I can find out which versions of the underlying Cordova plugins are supported in Ionic Native? Thanks again!

**Comment by ihadeed** [comment]
Ah yeah, if you're using the older version of the plugin things wouldn't work. The successCallback param will receive `undefined`, and errorCallback will receive the actual success callback. 

We updated the API for v2.2.7 ... https://github.com/ionic-team/ionic-native/blob/master/CHANGELOG.md#227-2016-11-24 which was a long time ago.
