### ISSUE TITLE
Media Plugin bug since 4.0.0

### ISSUE THREAD

**Issue by soramister** [ionic-team/ionic-native#1806]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Since the update 4.0.0, the Observables for the Media Plugin does not work anymore. They are not triggered, even with using the example.
The sound is working.

**Expected behavior:**
The following observables onStatusUpdate, onSuccess and onError should display the console.log as in the example.

**Steps to reproduce:**
Just use the example code. Below what I used. Replace the variable url by a stream.

**Related code:**
const file: MediaObject = this.media.create(url);

file.onStatusUpdate.subscribe(function(status) { console.log(status) }); // fires when file status changes

file.onSuccess.subscribe(() => console.log('Action is successful'));

file.onError.subscribe(error => console.log('Error!', error));

**package.json info:**
{
    "name": "application_v2",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/admob-free": "^3.12.1",
        "@ionic-native/app-rate": "^3.12.1",
        "@ionic-native/app-version": "^3.12.1",
        "@ionic-native/background-mode": "^3.12.1",
        "@ionic-native/core": "3.10.2",
        "@ionic-native/deeplinks": "^3.12.1",
        "@ionic-native/device": "^3.12.1",
        "@ionic-native/facebook": "^3.12.1",
        "@ionic-native/file": "^3.12.1",
        "@ionic-native/in-app-browser": "^3.12.1",
        "@ionic-native/media": "^4.0.0",
        "@ionic-native/music-controls": "^4.0.0",
        "@ionic-native/native-storage": "^3.12.1",
        "@ionic-native/push": "^3.12.1",
        "@ionic-native/safari-view-controller": "^3.12.1",
        "@ionic-native/social-sharing": "^3.12.1",
        "@ionic-native/splash-screen": "3.10.2",
        "@ionic-native/status-bar": "3.10.2",
        "@ionic-native/toast": "^3.12.1",
        "@ionic-native/transfer": "^3.12.1",
        "@ionic-native/youtube-video-player": "^3.12.1",
        "@ionic-native/zip": "^3.12.1",
        "@ionic/storage": "2.0.1",
        "@ngx-translate/core": "^7.0.0",
        "@ngx-translate/http-loader": "^0.1.0",
        "cordova-admob-sdk": "^0.7.0",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-admob-free": "^0.9.0",
        "cordova-plugin-app-version": "^0.1.9",
        "cordova-plugin-apprate": "^1.3.0",
        "cordova-plugin-background-mode": "^0.7.2",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-dialogs": "^1.3.3",
        "cordova-plugin-facebook4": "^1.9.1",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-file-transfer": "^1.6.3",
        "cordova-plugin-globalization": "^1.0.7",
        "cordova-plugin-inappbrowser": "^1.7.1",
        "cordova-plugin-media": "^3.0.1",
        "cordova-plugin-music-controls": "^2.0.0",
        "cordova-plugin-nativestorage": "^2.2.2",
        "cordova-plugin-safariviewcontroller": "^1.4.7",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "cordova-plugin-x-socialsharing": "^5.1.8",
        "cordova-plugin-x-toast": "^2.6.0",
        "cordova-plugin-youtube-video-player": "^1.0.6",
        "cordova-plugin-zip": "^3.1.0",
        "cordova-promise-polyfill": "0.0.2",
        "es6-promise-plugin": "^4.1.0",
        "ionic-angular": "3.4.2",
        "ionic-plugin-deeplinks": "^1.0.15",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "phonegap-plugin-push": "^1.10.5",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "^2.0.2",
        "@ionic/cli-plugin-cordova": "1.4.1",
        "@ionic/cli-plugin-ionic-angular": "1.3.2",
        "typescript": "2.3.3"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-youtube-video-player": {},
            "cordova-plugin-admob-free": {},
            "cordova-plugin-app-version": {},
            "cordova-plugin-apprate": {},
            "cordova-plugin-facebook4": {
                "APP_ID": "261352257390465",
                "APP_NAME": "Appsidious"
            },
            "cordova-plugin-file": {},
            "cordova-plugin-file-transfer": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-nativestorage": {},
            "cordova-plugin-safariviewcontroller": {},
            "cordova-plugin-x-socialsharing": {},
            "cordova-plugin-x-toast": {},
            "cordova-plugin-zip": {},
            "ionic-plugin-deeplinks": {
                "URL_SCHEME": "appsidious",
                "DEEPLINK_SCHEME": "https",
                "DEEPLINK_HOST": "appsidious.com",
                "ANDROID_PATH_PREFIX": "/"
            },
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-background-mode": {},
            "phonegap-plugin-push": {
                "SENDER_ID": "223508460853"
            },
            "cordova-plugin-music-controls": {},
            "cordova-plugin-media": {
                "MICROPHONE_USAGE_DESCRIPTION": " "
            }
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}

**Comment by ihadeed** [comment]
Sorry about that, I made a mistake when updating this plugin. I will publish an update soon with a fix.
