### ISSUE TITLE
Not really supported on IOS

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ionic-team/ionic-native#1807]
I am using @ ionic-native/background-mode, that is a wrapper for 

https://github.com/katzer/cordova-plugin-background-mode

And all is working fine, but Apple will not approve my App, because this plugin is using Background Audio - so the any app using this will not be released in the App Store.

I have seen a few getting thru the loop hole with this plugin, but most have failed and had to find another 3rd party software for background mode.

The full story: https://github.com/katzer/cordova-plugin-background-mode/issues/122

I think we either should find another plugin, or at least remove IOS as supported platform, unless someone has an idea of how to solve this

**Comment by ihadeed** [comment]
The plugins repo already has a note regarding app store compliance. 

There only thing that should be done here is copying that note to our docs to make sure everybody sees it.

If you find another plugin that is compliant with the app store policy and achieves the same functionality, feel free to submit a new feature request.
