### ISSUE TITLE
getVisibleRegion throws [deprecated] and app stops working with ionic-native 4.0.1 and google maps plugin v2

### ISSUE THREAD

**Issue by kuzman** [ionic-team/ionic-native#1809]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
After ugrade to ionic-native 4.0.1 and the v2 of the google maps plugin, the `getVisibleRegion` function from the google maps plugin throws in cosole: ```console.log: [deprecated] getVisibleRegion() is changed. Please check out the https://goo.gl/yHstHQ```
The app should continue to work, but is doesn't start. If you follow the link in the console log, you can see that there are changes in thethe `getVisibleRegion`function.
**Expected behavior:**
before updating i was using the latest 3.14.0 ionic-native library and the 1.4.3 version of the google maps plugin and everything worked OK
**Steps to reproduce:**

1. Create a simple app that uses the google maps plugin
2. Create a function where you try to get the visible region with a promise and call that function

**Comment by ihadeed** [comment]
This should be fixed by #1815
