### ISSUE TITLE
ionic cordova plugin - fail

### ISSUE THREAD

**Issue by Jhonnybmx** [ionic-team/ionic-native#1810]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
All command ionic cordova fail.
I tried
Uninstall / install node js
Uninstall / install ionic
Uninstall / install cordova
**But the problem persists in all projects**
<img src="http://www.abbylab.net/bug.jpg" />

**Expected behavior:**
Must install without problems

**Steps to reproduce:**

**Related code:**

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.11.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by ihadeed** [comment]
The error is thrown by Cordova CLI. It's saying that the current directory isn't a Cordova project. This is probably because you didn't run `npm run build` to generate the `www` directory.

**Comment by Jhonnybmx** [comment]
Hello, let's start with something. Because when I create a project with ionic **"ionic start app1 blank"** it does not create the folder **"node_modules"** if it indicates that I create it successfully. When I access the project directory and I want to execute the command **"ionic serve"** this continues asking me to install the **"node_modules"** content **"YES"** but never install it but if I do not use the ionic command example **"npm install"** the folder is created correctly . So it happens with the native ionic commands exposed in this bug.

**Comment by ihadeed** [comment]
Sorry @Jhonnybmx, this problem is not linked to Ionic Native in any way. I suggest you post your issue on the forums or the appropriate Github repo.
