### ISSUE TITLE
Onesignal postNotification parameters type wrongly defined or not documented

### ISSUE THREAD

**Issue by guizmo** [ionic-team/ionic-native#1811]
[x] bug report

**Current behavior:**

When trying to use this.oneSignal.postNotification(notificationObj), to send notification from a user to another,  typescript compiler throws the following error
Argument of type '{ contents: { en: string; }; app_id: string; include_player_ids: string[]; }' is not
            assignable to parameter of type 'OSNotification'. Property 'isAppInFocus' is missing in type '{ contents: {
            en: string; }; app_id: string; include_player_ids: string[]; }'
Which is normal when looking at the source code (postNotification(notificationObj: OSNotification): Promise<any>;) 
But even when adding all required props from interface i cannot compile

**Expected behavior:**

when testing the following the message got sent
postNotification(notificationObj: any): Promise<any>;

**Steps to reproduce:**

**Related code:**

```
    let notificationObj = {
      contents: {
        en: "message body",
      },
      app_id: "123-456",
      include_player_ids: ['654-321']
    };


    this.oneSignal.postNotification(notificationObj).then((success) => {
      // handle received here how you wish.
      alert('success')
      console.log(JSON.stringify(success));
    }).catch((error) => {
      alert('error')
      console.log(JSON.stringify(error));
    })
```

**Other information:**

cordova version : 7.0.1
ionci version : 3.5.0
node version : 6.9.5
@ionic-native/onesignal verion : "^4.0.1"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"

**package.json info:**

```json
insert the content here
```

**Comment by eduardolopesUFJF** [comment]
Did you found some answer?
