### ISSUE TITLE
Plugin is not installed using onesignal plugin

### ISSUE THREAD

**Issue by anivaisu** [ionic-team/ionic-native#1818]
I am using one signal plugin for push notification.

First i installed the one signal plugin.
```

ionic cordova plugin add onesignal-cordova-plugin
npm install --save @ionic-native/onesignal
```

Here is my code

```
this.platform.ready().then(() => {
      this.oneSignal.getIds().then((ids)=>{
          console.log("USER ID");
          console.log(ids.userId);
        }).catch((e)=>{
          console.log("error")
          console.log(e);
        })
    })
```
But does not get app id.why?

The error is `plugin_not_installed`.

I remove this plugin again added.

But still get the same error.

Kindly advice me,

Thanks.

**Comment by matthieu80** [comment]
hi @anivaisu,
did you fix the problem.
i have the same.
thanks

**Comment by Avislux** [comment]
Is the initializing code for onesignal included? Put it after `this.platform.ready().then(() => {`
