### ISSUE TITLE
Local Notifications Ionic Native Not working

### ISSUE THREAD

**Issue by iskydive** [ionic-team/ionic-native#1819]
**I'm submitting an ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

No notifications shows up when it should.

**Expected behavior:**

A notificaiton should pop up on my phone.

**Steps to reproduce:**

Just try to install the Local Notifications plugins as described here :

https://ionicframework.com/docs/native/local-notifications/

And you won't be able to build the app anymore or the plugin won't work.

**Related code:**

Here is a git I uploaded with a blank Ionic project, just Local Notifications installed, and as you can see you can't build the app.

https://github.com/iskydive/LocalNotificationPluginBug

**Other information:**

**package.json info:**

```json
{
    "name": "blank",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/local-notifications": "^4.0.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-device": "file:node_modules\\cordova-plugin-device",
        "de.appplant.cordova.plugin.local-notification": "^0.8.5",
        "ionic-angular": "3.5.3",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.0.2",
        "@ionic/cli-plugin-cordova": "1.4.1",
        "@ionic/cli-plugin-ionic-angular": "1.3.2",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "de.appplant.cordova.plugin.local-notification": {}
        }
    }
}

```

Thanks for all the fix you'll be able to do :D

**Comment by ThorvaldAagaard** [comment]
I have cloned the repository and ran
```
npm install
```
Then added the platform 

```
ionic cordova platform add android
```

And finally executed it on my phone
```
ionic cordova run android
```
It both compiles and work as expected
![image](https://user-images.githubusercontent.com/10560652/32455000-38cb871a-c321-11e7-9da1-4d5504108fef.png)

and this is how the notification looks

![image](https://user-images.githubusercontent.com/10560652/32455027-4d279988-c321-11e7-87b3-4752bab50e83.png)

Comparing package.json from your git-project with the one I have after installing the needed plugins, tells me that you probably just need to add the needed plugins
![image](https://user-images.githubusercontent.com/10560652/32455123-a2f13fc2-c321-11e7-8785-6b6ba4d99f52.png)

I recommend closing this unless we get some more details about the actual build errors
