### ISSUE TITLE
App Availability '(yes: string) => void' is not assignable to parameter of type '(value: boolean) => void |              PromiseLike<void>'

### ISSUE THREAD

**Issue by CK110** [ionic-team/ionic-native#1820]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

the error information
```
Argument of type '(yes: string) => void' is not assignable to parameter of type '(value: boolean) => void | 
            PromiseLike<void>'. Types of parameters 'yes' and 'value' are incompatible. Type 'boolean' is not assignable 
            to type 'string'. 
```

i change the ` (yes: string) ` to ` (yes: number) `, it's ok

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
      this.appAvailability.check('iosamap://')
        .then(
          (yes: string) => console.log(' is available'),
          (no: string) => console.log(' is NOT available')
        );
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by amitkumar1992** [comment]
Try this (use boolean instead of string) : 
 this.appAvailability.check('iosamap://')
        .then(
          (yes: boolean) => console.log(' is available'),
          (no: boolean) => console.log(' is NOT available')
        );

It worked for me.

**Comment by fermedina** [comment]
Why is this error closed? This continues to happen. The documentation is wrong:
https://ionicframework.com/docs/native/app-availability/
