### ISSUE TITLE
restore funcs not in @ionic-native/in-app-purchase-2

### ISSUE THREAD

**Issue by kiko555** [ionic-team/ionic-native#1827]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
I want to restore a purchase within "In App Purchase 2", but I can't call iap2.restore()
**Expected behavior:**
It should have restore In the `@ionic-native/in-app-purchase-2`

**Comment by Theng** [comment]
I don't event know how to use this plugin
