### ISSUE TITLE
@ionic-native/google-maps has more MapTypes than the plugin

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ionic-team/ionic-native#1841]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**Current behavior:**

Defined in the wrapper

export declare type MapType = 'MAP_TYPE_NORMAL' | 'MAP_TYPE_ROADMAP' | 'MAP_TYPE_SATELLITE' | 'MAP_TYPE_HYBRID' | 'MAP_TYPE_TERRAIN' | 'MAP_TYPE_NONE';

Used in the Plugin

      mapTypeId = typeStr.equals("MAP_TYPE_NORMAL") ? GoogleMap.MAP_TYPE_NORMAL : mapTypeId;
      mapTypeId = typeStr.equals("MAP_TYPE_HYBRID") ? GoogleMap.MAP_TYPE_HYBRID : mapTypeId;
      mapTypeId = typeStr.equals("MAP_TYPE_SATELLITE") ? GoogleMap.MAP_TYPE_SATELLITE : mapTypeId;
      mapTypeId = typeStr.equals("MAP_TYPE_TERRAIN") ? GoogleMap.MAP_TYPE_TERRAIN : mapTypeId;
      mapTypeId = typeStr.equals("MAP_TYPE_NONE") ? GoogleMap.MAP_TYPE_NONE : mapTypeId;

**Expected behavior:**

I expect the types to match, so 'MAP_TYPE_ROADMAP' should probably be removed from the wrapper

**Comment by wf9a5m75** [comment]
This is already implemented.
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts#L489
