### ISSUE TITLE
Native-push does not support Browser push notification

### ISSUE THREAD

**Issue by mariohmol** [ionic-team/ionic-native#1847]
Hi there!

I guess i found a BUG on Ionic v3.

In official docs it says that native-push has browser support

* http://ionicframework.com/docs/native/push/

But when i try to configure with `browser` key it gives me an error, because there is not a implementation for browser in `PushOptions`

https://github.com/ionic-team/ionic-native/blob/328e5de3f31ed6b71c5f3fa0caef1a50097a32b2/src/%40ionic-native/plugins/push/index.ts#L191

Expected: This should support browser push as is in docs.

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 2.1.0
ios-deploy version: 1.9.1
ios-sim version: 3.1.1
OS: macOS Sierra
Node Version: v6.3.1
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by mariohmol** [comment]
See if that helps 

* https://github.com/ionic-team/ionic-native/pull/1848

**Comment by raxim1** [comment]
I have bumped into the same problem. I haven't reached the point when the notification is coming through (as i need to implement some sort of crazy message encryption), but i have made some fix, and it seems to me registering the device.

1, download ionic-native project - git clone something
2, add interface to the index.d.ts - it's missing from the phonegap-push-plugin also (maybe there is some dynamic load, i'm not sure)
export interface BrowserPushOptions {
    /**
    * Optional. URL for the push server you want to use.
    */
    pushServiceURL?: string;
    /**
    * Optional. Your GCM API key if you are using VALID keys.
    */
    applicationServerKey?: string;
}

export interface PushOptions {
    ios?: IOSPushOptions;
    android?: AndroidPushOptions;
    browser?: BrowserPushOptions;
    windows?: any;
}

3, npm run build push on ionic-native (don't forget npm install before do this, it's not explained, and thrown me several exception before i realized)

4, copy over the files of node_modules/@ionic-native/push - leave the package.json,
just compare the 5 files in a sensible way.

5, ionic run browser

You can follow the tutorial after that.

It will show that the device has been registered, and when you check the network tab in the browser,
it sends some sort of json payload to the http://push.api.phonegap.com/v1/push/keys, what you can override to your own server (it's just a post), i have tested that. (unfortunatelly there is no way to use some sort of CSRF header, just if you override - so browser version would be nice if there is some extra header option)

Now as it sends some sort of json payload with registrationId and keys (some sort of public key)
In chrome is using FCM, in firefox is using a different one.

**Comment by mariohmol** [comment]
PR was merged.. thanks!

**Comment by bhavinwebdesk** [comment]
Sorry, it is closed but @raxim1, can we use Firebase Cloud Messaging for browser notification?

**Comment by redphoenix2k** [comment]
i second the last question, is there firebase cloud messaging support for browsers ?
