### ISSUE TITLE
OneSignal docs script not working

### ISSUE THREAD

**Issue by Iyashu5040** [ionic-team/ionic-native#1850]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
There is a block of code for a script called `030_copy_android_notification_icons.js` in the docs at http://ionicframework.com/docs/native/onesignal/. This script is posted there to help developers set up an automatic copying of OneSignal push icons. It attempts to copy the icon files to `platforms/android/res/drawable-hdpi/`, `platforms/android/res/drawable-mdpi/` etc. If these directories don't exist the script does nothing.

**Expected behavior:**
The script should create the necessary directories when copying the icons.

**Steps to reproduce:**
Make sure the folders mentioned above don't exist. Run `ionic cordova prepare android` and go look if the icons are where they are supposed to be.

**Other information:**
I've fixed the script with the following bit of code, easy fix (commented lines are my new code):
```
var destdir = path.dirname(destfile);
        //if (!fs.existsSync(destdir))
        //    fs.mkdirSync(destdir);
        if (fs.existsSync(srcfile) && fs.existsSync(destdir)) {
            fs.createReadStream(srcfile).pipe(
                fs.createWriteStream(destfile));
        }
```

**Comment by simonhaenisch** [comment]
Same issue for me, the folders `drawable-<res>` don't exist anymore, cordova uses `drawable-land-<res>` and `drawable-port-<res>` instead.

Another problem for me is that the `rootdir` is also wrong, because I use a locally installed ionic and have an alias for `node_modules/.bin/ionic` (same for `cordova` and `ios-deploy`).

`process.argv` gives me:

```
/usr/local/Cellar/node/8.9.1/bin/node
/Users/<root-dir>/node_modules/.bin/cordova
run
android
```

but `run` definitely isn't my root directory 🤓  Using `process.cwd()` as project root works for me, but I've heard that windows has issues with it.

Anyway, here is my fixed and improved (ES6) script:

```js
#!/usr/bin/env node

const { existsSync, mkdirSync, createReadStream, createWriteStream } = require('fs');
const { join, dirname } = require('path');

const root = process.cwd();

const filesToCopy = [
  {
    from: 'resources/android/icon/drawable-hdpi-icon.png',
    to: 'platforms/android/res/drawable-hdpi/ic_stat_onesignal_default.png',
  },
  {
    from: 'resources/android/icon/drawable-mdpi-icon.png',
    to: 'platforms/android/res/drawable-mdpi/ic_stat_onesignal_default.png',
  },
  {
    from: 'resources/android/icon/drawable-xhdpi-icon.png',
    to: 'platforms/android/res/drawable-xhdpi/ic_stat_onesignal_default.png',
  },
  {
    from: 'resources/android/icon/drawable-xxhdpi-icon.png',
    to: 'platforms/android/res/drawable-xxhdpi/ic_stat_onesignal_default.png',
  },
  {
    from: 'resources/android/icon/drawable-xxxhdpi-icon.png',
    to: 'platforms/android/res/drawable-xxxhdpi/ic_stat_onesignal_default.png',
  },
];

for (const { from, to } of filesToCopy) {
  const src = join(root, from);
  const dest = join(root, to);

  if (!existsSync(dirname(dest))) {
    mkdirSync(dirname(dest));
  }

  if (existsSync(src)) {
    createReadStream(src).pipe(createWriteStream(dest));
  }
}
```

**Comment by simonhaenisch** [comment]
I just looked at the [OneSignal docs for notification icon customization](https://documentation.onesignal.com/v3.0/docs/customize-notification-icons), and it seems that all the sizes are actually wrong and the generation/copying of the large icon is missing as well. I was looking into fixing it, but two of the required sizes (`24px` and `256px`) are not being generated by `ionic resources`.

**Comment by simonhaenisch** [comment]
I ended up generating a white-only icon and using `sharp ` to generate the required sizes manually:

```sh
cd hooks
npm install sharp
```

_**`hooks/generate-onesignal-notification-icons-for-android.js`:**_

```js
#!/usr/bin/env node

const icon = 'resources/android/icon-white.png';

// see:
//	* https://documentation.onesignal.com/v3.0/docs/customize-notification-icons
//	* https://ionicframework.com/docs/native/onesignal/

const { existsSync, mkdirSync } = require('fs');
const { join, dirname } = require('path');
const sharp = require('sharp');

const root = process.cwd();
const SMALL_ICON_NAME = 'ic_stat_onesignal_default.png';
const LARGE_ICON_NAME = 'ic_onesignal_large_icon_default.png';

const filesToCopy = [
  {
    // small icon - mdpi (24 px)
    size: 24,
    to: `platforms/android/res/drawable-mdpi/${SMALL_ICON_NAME}`,
  },
  {
    // small icon - hdpi (36 px)
    size: 36,
    to: `platforms/android/res/drawable-hdpi/${SMALL_ICON_NAME}`,
  },
  {
    // small icon - xhdpi (48 px)
    size: 48,
    to: `platforms/android/res/drawable-xhdpi/${SMALL_ICON_NAME}`,
  },
  {
    // small icon - xxhdpi (72 px)
    size: 72,
    to: `platforms/android/res/drawable-xxhdpi/${SMALL_ICON_NAME}`,
  },
  {
    // small icon - xxxhdpi (96 px)
    size: 96,
    to: `platforms/android/res/drawable-xxxhdpi/${SMALL_ICON_NAME}`,
  },
  {
    // large icon - xxxhdpi (256 px)
    size: 256,
    to: `platforms/android/res/drawable-xxxhdpi/${LARGE_ICON_NAME}`,
  },
];

for (const { size, to } of filesToCopy) {
  const destination = join(root, to);

  if (!existsSync(dirname(destination))) {
    mkdirSync(dirname(destination));
  }

  if (!existsSync(destination)) {
    sharp(join(root, icon))
      .resize(size)
      .toFile(destination)
      .then(res => console.log(`onesignal icon generated (${res.width}px): ${to}`))
      .catch(err => console.error(err));
  }
}
```

_**`config.xml`:**_

```xml
<hook src="hooks/generate-onesignal-notification-icons-for-android.js" type="after_prepare" />
```

**Comment by danielsogl** [comment]
Script updated
