### ISSUE TITLE
ionic-native/web-intent always run an error

### ISSUE THREAD

**Issue by mobicraft-am** [ionic-team/ionic-native#1882]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

When i want to use the Ionic Native WebIntent plugin, i always have this error "Install the WebIntent plugin: 'ionic cordova plugin add com-darryncampbell-cordova-plugin-intent'".

but it's already installed like this :
$ ionic cordova plugin add com-darryncampbell-cordova-plugin-intent
$ npm install --save ionic-native/web-intent

code:
import { WebIntent } from '@ionic-native/web-intent';

constructor(private webIntent: WebIntent) { }

const options = {
  action: this.webIntent.ACTION_VIEW,
  url: 'path/to/file',
  type: 'application/pdf'
};

this.webIntent.startActivity(options).then(onSuccess, onError);

Infos :
: 1.6.2
: 1.4.1
: 1.7.0
ionic (Ionic CLI) : 3.7.0

global packages:

Cordova CLI : 7.0.1 
local packages:

@ionic/app-scripts : 1.3.12
Cordova Platforms  : android 6.2.3 ios 4.4.0
Ionic Framework    : ionic-angular 3.5.0
System:

Node       : v6.6.0
OS         : macOS Sierra
Xcode      : Xcode 8.3.3 Build version 8E3004b 
ios-deploy : 1.9.0 
ios-sim    : 6.0.0 
npm        : 5.3.0

**Comment by joshiabk** [comment]
I am also getting an error. Does any one looking into this ? I think WebIntent is a core feature.

**Comment by Don-G** [comment]
Am getting Error Always
Any help?

**Comment by ihadeed** [comment]
Doesn't seem like an issue with Ionic Native, please confirm by replacing this:
```ts
this.webIntent.startActivity(options).then(onSuccess, onError);
```

with this:
```ts
WebIntent.getPlugin().startActivity(options).then(onSuccess, onError);
```

**Comment by stepupithubapp** [comment]
i have tried "WebIntent.getPlugin().startActivity(options).then(onSuccess, onError)"  this
 not working

**Comment by TeamBrahma** [comment]
Hoping that this will help someone

Following code works. I am using Ionic 5.x with capacitor 3.x

`    const options = {
      action: WebIntent.ACTION_VIEW,
      url: 'geo:23.5264055,148.1594006',
      package: 'com.google.android.apps.maps'
    }
    WebIntent.startActivity(options).then(
      () => {
        console.log('Intent Launched');
      },
      (e) => {
        console.log('Error', e);
      }
    );`

**Comment by givemesumthing** [comment]
Still encountering same issue with capacitor. Can someone please help with  the code snippet at https://bit.ly/3aopyog
