### ISSUE TITLE
Plugin Request - Cordova FabricPlugin

### ISSUE THREAD

**Issue by billygerhard** [ionic-team/ionic-native#1887]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

Fabric has teamed up with Firebase to include crash reporting. There is a Cordova Plugin created for it that would be great to include in Ionic Native. Please look into adding this. This wouldn't really help crashes in the angular part of the apps, but could really help troubleshoot Ionic Native plugin issues.

https://github.com/sarriaroman/FabricPlugin

**Comment by patrickr** [comment]
Support for Fabric would be great and will probably happen eventually.
Until then you might consider the [Firebase plugin](http://ionicframework.com/docs/native/firebase/) which supports the old Firebase error and crash reporting API they had before the Fabric integration

**Comment by patrickr** [comment]
The fabric plugin [already has typings](https://github.com/sarriaroman/FabricPlugin/blob/master/typings/cordova-fabric-plugin.d.ts) an ionic-native wrapper should take no time at all.

**Comment by danielsogl** [comment]
Duplicate: https://github.com/ionic-team/ionic-native/issues/1665
