### ISSUE TITLE
Stream Plugin Error

### ISSUE THREAD

**Issue by aliosmanyuksel** [ionic-team/ionic-native#1889]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/com.hutchind.cordova.plugins.streamingmedia
npm ERR! 404
npm ERR! 404  'com.hutchind.cordova.plugins.streamingmedia' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by karansharma27** [comment]
I get the same error everytime. Did you find any solution?

**Comment by danielsogl** [comment]
Plugin npm source fixed
