### ISSUE TITLE
ZeroconfResult.action should include also the 'resolved' string

### ISSUE THREAD

**Issue by fttx** [ionic-team/ionic-native#1897]
[x ] bug report
[ ] feature request

It seems that the new version includes a new event: [Changelog](https://github.com/becvert/cordova-plugin-zeroconf/blob/master/CHANGELOG.md#126---2017-08-07), [Example](https://github.com/becvert/cordova-plugin-zeroconf#watchtype-domain-success-failure)
[ZeroconfResult.action](https://github.com/ionic-team/ionic-native/blob/9ab458bba2ab0dd43f9d8ff4c7c6978f935763bd/src/%40ionic-native/plugins/zeroconf/index.ts#L17) should include also the 'resolved' string

I don't know if there are more

**Comment by danielsogl** [comment]
added
