### ISSUE TITLE
Docs are incomplete about google-maps

### ISSUE THREAD

**Issue by jvcsizilio** [ionic-team/ionic-native#1898]
**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
Actually there is not a bug. In the docs (https://ionicframework.com/docs/native/google-maps/) has a variable named "ionic" but it's not defined and I need know how declare it

**Related code:**

```
// create new marker
 let markerOptions: MarkerOptions = {
   position: ionic,
   title: 'Ionic'
 };
```
Someone knows how define that variable "ionic" in "position"? I will learn that and make a pull request to the docs project.

Cheers,

**Comment by wf9a5m75** [comment]
The doc page was updated last week.
