### ISSUE TITLE
Add delete option to native health (it's available in plugin)  

### ISSUE THREAD

**Issue by kabus202** [ionic-team/ionic-native#1905]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
delete is not available in native health
[ts] Property 'delete' does not exist on type 'Health'.

**Expected behavior:**

navigator.health.delete({
	startDate:  new Date(new Date().getTime() - 3 * 60 * 1000), // three minutes ago
	endDate: new Date(),
	dataType: 'steps'
}, successCallback, errorCallback)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by pravincarvalho** [comment]
Additionally the interface HealthKitOptions is also missing an optional key 
`type?: string;`
Should I test and submit a pull request?

**Comment by kabus202** [comment]
Yes sure, why not

**Comment by pravincarvalho** [comment]
Just want to check with the maintainers that I'm not duplicating effort. I should be able to do this early next week, if no one else is working on it.
