### ISSUE TITLE
Cannot read property 'then' of undefined` when I use map.clear().then(() => {});

### ISSUE THREAD

**Issue by carvemerson** [ionic-team/ionic-native#1915]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

When I use the `map.clear()` method, it should work as a promise (like the Ionic documentation https://ionicframework.com/docs/native/google-maps/#clear). 
But when I use `map.clear().then(() => { /*do something*/ })` I got this error:

`Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined` 

**Expected behavior:**

The `map.clear().then(() => { /*do something*/ })`  works.

**Comment by wf9a5m75** [comment]
This is already fixed.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1669

**Comment by BassamHabash** [comment]
Hi, 
I have the same issue in secureStorage plugin, when I use the secureStorage.create('key') method.
@wf9a5m75 
@carvemerson
