### ISSUE TITLE
File transfer download no react in production build

### ISSUE THREAD

**Issue by moh3n9595** [ionic-team/ionic-native#1925]
Hi, I use filetransfer.download very good in dev mode (`ionic cordova run android`). But when I want use it in production mode (`ionic cordova run android --prod`), I don't see anything. actually, both of entry and error not called. 
my code : 
   ```
   this.fileTransfer.download(encodeURI(url), <file-path> ,  false , some header ).then((entry) => {

             this.messageCtrlService.showAlert(JSON.stringify(entry.toURL()), 'Success');

          }, (error) => {
            this.messageCtrlService.showAlert(JSON.stringify(error), 'Error');

          });
```

**Comment by angryfang** [comment]
I hava a similar problem when I use File
```
this.file.readAsText(this.file.externalRootDirectory, "data.json").then(
      data => {
      },
      error => {
        this..create({
          message: 'open data.json error：' + JSON.stringify(error),
          duration: 10000,
          position: 'top'
        }).present();
      });
```
it works well in debug build, but not in production build and the error toast message is "open data.json error : **plugin_not_installed**"

**Comment by moh3n9595** [comment]
@angryfang , My problem is very weird!When I use `--prod` I see this message in chrome debugger : 
`native: tried accessing the FileTransfer plugin but it's not installed     vendor.js:1`
but when I run app in debud mode everything is ok and I don't see this message.

**Comment by alexnu** [comment]
I am facing the same issue but @angryfang 's solution did not work for me.
Which version of ionic-native are you using?

**Comment by angryfang** [comment]
@alexnu sorry for reply you so late!
here is my project dependencies,
` "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/android-full-screen": "^4.2.0",
        "@ionic-native/autostart": "^4.1.0",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/file": "^4.2.1",
        "@ionic-native/splash-screen": "^3.14.0",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic-native/streaming-media": "^4.1.0",
        "@ionic/app-scripts": "^2.1.4",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-autostart": "^2.0.1",
        "cordova-plugin-compat": "^1.0.0",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-crosswalk-webview": "^2.3.0",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-fullscreen": "^1.2.0",
        "cordova-plugin-screen-orientation": "^2.0.1",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "es6-promise-plugin": "git+https://github.com/vstirbu/PromisesPlugin.git",
        "ionic-angular": "3.6.0",
        "ionic-native": "^2.9.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    }`
