### ISSUE TITLE
Diagnostic Plugin

### ISSUE THREAD

**Issue by hardouinyann** [ionic-team/ionic-native#1929]
Hi everyone !

I am currently working on an ionic 2 app and i need to get my user allow us using his device's GPS.

Thus, i tried to install Diagnotic plugin ... and encountered some issues.

Indeed, after installing : 
`ionic plugin add cordova.plugins.diagnostic`
 `npm install --save @ionic-native/diagnostic`
 
and building an apk,  i got some error about style??
So i checked and installed  the `.api-22` version

And now i got the error, when debuging my application : 
`plugin not installed` whereas when displaying  "this.diagnostic" (initialized in constructor as a service) we can access the "Diagnostic" class.

it is pretty much like we have the plgin's files (.js/.ts) but still dont really have the plugin.

So if you have any idea ...  i'd be really glad  !

Thanks for help !

**Comment by hardouinyann** [comment]
Does anyone know ? :(

**Comment by hardouinyann** [comment]
Anyone ? :'(

**Comment by jbgtmartin** [comment]
Are you calling it after the platform is ready?
`this.platform.ready().then(() => { this.diagnostic.... });`

**Comment by dpa99c** [comment]
> and building an apk, i got some error about style??

Posting the error would be helpful.

**Comment by sureshgowd1321** [comment]
I'm facing this issue. please help
console.warn: Native: tried calling Diagnostic.getPermissionAuthorizationStatus, but the Diagnostic plugin 
            is not installed. 
[01:27:36]  console.warn: Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic'
