### ISSUE TITLE
Error during install google maps in ionic 3

### ISSUE THREAD

**Issue by gtzinos** [ionic-team/ionic-native#1943]
Hi

I am following this guide (https://ionicframework.com/docs/native/google-maps/)

When i am trying to install npm install --save @ionic-native/google-maps

it returns me

├── UNMET PEER DEPENDENCY @angular/common@4.1.3
├── UNMET PEER DEPENDENCY @angular/core@4.1.3
└── @ionic-native/google-maps@4.2.1

**Comment by ihadeed** [comment]
The warning you included doesn't explain much. Can't tell what's the unmet peer dependency. But my guess is that one of your angular packages is `4.2.1` while the rest are still `4.1.3`. It shouldn't be an issue anyways, and it's most likely not related to Ionic Native.

Closing this issue, but if you believe this is an Ionic Native issue and you have more details, let me know and I'll take a look.
