### ISSUE TITLE
Change the UI Language (Camera)

### ISSUE THREAD

**Issue by juanjoseadan** [ionic-team/ionic-native#1947]
**I'm submitting a ...**  (check one with "x")
[ * ] bug report
[ * ] feature request

**Current behavior:**
I'm developing an application for users in Mexico and we are using this plugin. At the moment all is working good, but we are not able to change the camera language (in iOS it shows "Use photo", "Retake", "Cancel" and "Photo" but our clients will be spanish speakers, so we are searching for a way to change the plugin language.

**Expected behavior:**
It may be cool if there is a feature or someone could add a feature to change the language programmatically.

**Comment by mqasem92** [comment]
+1

**Comment by mqasem92** [comment]
After search, I find two solution I don't try it yet.

1- By change settings in the xcode ( Ref. [https://stackoverflow.com/questions/34286524/how-to-change-cordova-camera-plugin-language-in-ios](url) )

2- use custom camera plugin or by this custom one ( [https://github.com/Shakir-Khan/cordova-plugin-custom-camera](url) )

Update me when you try one of previous solution.

**Comment by mateusduraes** [comment]
Sorry for my comment here, but here is my solution that worked very well.

```config.xml```

```html
<platform name="ios">
  <!-- omitted other configs -->
  <edit-config file="*-Info.plist" mode="merge" target="CFBundleLocalizations">
    <array>
      <string>pt</string>
    </array>
  </edit-config>
  <!-- omitted other configs -->
</platform>
