### ISSUE TITLE
How to use my own custom js plugin with ionic3 app?

### ISSUE THREAD

**Issue by rashedshaon** [ionic-team/ionic-native#1949]
I created a js plugin using jQuery which I already used in my web application. Now I want use it on my **IONIC 3** mobile app. 
I installed typings and jquery in my project then how I can use my custom jquery plugin in my project.

**Comment by ihadeed** [comment]
This is the wrong place to ask this question as it's not related to Ionic Native. I suggest you seek help at the Ionic forums. 

You should be able to use the same way you do anywhere else. 

My personal advice: convert your plugin to an Angular component/directive and then use it in your Ionic app. jQuery doesn't perform that well on mobile based on my personal experience.
