### ISSUE TITLE
Health on Android - "cannot find symbol" when I run ionic cordova build android

### ISSUE THREAD

**Issue by faldunate** [ionic-team/ionic-native#1950]
I'm using @ionic-native/health for android and IOS, In IOS this plugin works fine and I can do queries without problems, but When I try to build my app for android I have this error:

        (truncated) ... d/mobile-app/platforms/android/src/org/apache/cordova/health/HealthPlugin.java:950: error:
        cannot find symbol
        if (temp_to_meal == HealthFields.FIELD_TEMPORAL_RELATION_TO_MEAL_AFTER_MEAL) {
        ^
        symbol: variable HealthFields
        location: class HealthPlugin
        /Users/me/Developments/vivosalud/mobile-app/platforms/android/src/org/apache/cordova/health/HealthPlugin.java:952:
        error: cannot find symbol
        } else if (temp_to_meal == HealthFields.FIELD_TEMPORAL_RELATION_TO_MEAL_BEFORE_MEAL) {...
`
My versions

`    

    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 6.4.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.1.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.2.1

System:

    Node       : v7.1.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : 5.0.13
    npm        : 3.10.9`

**Comment by gotters** [comment]
Did you resolve this? I am having the same issues?
