### ISSUE TITLE
Web intent: passing extras

### ISSUE THREAD

**Issue by danilopolani** [ionic-team/ionic-native#1959]
**I'm submitting a ...**
[x] bug report
[ ] feature request

**Current behavior:**
The `Web Intent` package doesn't allow extras.

**Expected behavior:**
Passing extra parameters to `startActivity` method.

**Other information:**

My goal is to create a "native share", like the example from the [Android documentation](https://developer.android.com/training/sharing/send.html):

```java
Intent sendIntent = new Intent();
sendIntent.setAction(Intent.ACTION_SEND);
sendIntent.putExtra(Intent.EXTRA_TEXT, "This is my text to send.");
sendIntent.setType("text/plain");
startActivity(sendIntent);
```

As we can see, there's an action, an extra (_EXTRA_TEXT_) and a _type_. This can be achieved from the [cordova plugin](https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent) with something like this (from the README of the repo): 

```js
window.plugins.intentShim.startActivity({
    action: 'android.intent.action.SEND',
    extras: {
        'android.intent.extra.TEXT': 'My text here'
    }
});
```

Now, looking at the declaration of the `startActivity` method from **ionic native** package we can see that the url is __required__ (why?) and there's no way to define extras.

```js
startActivity(options: {
        action: any;
        url: string;
        type?: string;
    })
```

The only method which has an `extras` field is `sendBroadcast`, but I think it's a little weird:

```js
sendBroadcast(options: {
    action: string;
    extras?: {
       option: boolean;
    };
})
```

`option: boolean`? What? And all the "convenience constants" like `ACTION_SEND`  and  `EXTRA_TEXT` are declareted but not filled (but maybe they are somewhere else).

I know it's marked as "Beta", but I think it hasn't the basic functionalities. Should I use the cordova plugin "without" the ionic native part?

**Comment by ajeet0725** [comment]
Hi,
i want to pass options like bellow please help me

 var pidOption = "<?xml version=\"1.0\"?> <PidOptions ver=\"1.0\"> <Opts fCount=\"1\" fType=\"0\" iCount=\"0\" pCount=\"0\" format=\"0\" pidVer=\"2.0\" timeout=\"10000\" posh=\"UNKNOWN\" env=\"P\" /> <CustOpts><Param name=\"mantrakey\" value=\"\" /></CustOpts> </PidOptions>";
    var options = {
      action: 'in.gov.uidai.rdservice.fp.CAPTURE',//in.gov.uidai.rdservice.fp.CAPTURE"
      EXTRA_TEXT:pidOption
    };

**Comment by JuanFCVal** [comment]
5 years later and we got no answers... 😢
