### ISSUE TITLE
HTTP PUT and POST doesn't support JSON data in the body

### ISSUE THREAD

**Issue by aymeric56** [ionic-team/ionic-native#1961]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
With ionic-native/http, if you try to send a JSON in a body of a PUT or POST request, it's serialized as URLENCODED and not JSON.
so if I trace with Wireshark the message, I have something like this:
Message%5BRecord%5D%5BFirstName%5D=GUILLAUME&Message%5BRecord%5D%5BTelExtension%5D=0123344556&Message%5BRecord%5D%5BZipCode%5D=34000

**Expected behavior:**
where I expect something like this:
{"Message":{"Record":{"FirstName":"GUILLAUME","TelExtension":"0123344556","ZipCode":"34000"}}}

**Related code:**
I changed the advanced-http.js in the cordova-plugin-advanced-http where:
...
var validSerializers = ['urlencoded', 'json'];
...
dataSerializer: 'urlencoded'
...
for PUT and POST, I change the this.dataSerializer to 'json', and now the request works well.

I don't know where the code needs to trap the content-type='application/json' and change the serializer accordingly!
Do the body needs to be serialized ? I understand for parameters in the URI, but for the body ???

ionic-native/http@4.2.1
cordova-plugin-advanced-http@1.5.9

**>ionic info**
cli packages: (/usr/local/lib/node_modules)
    ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
global packages:
    Cordova CLI : 7.0.1 
local packages:
    ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0
System:
    Node  : v6.9.4
    npm   : 3.10.10 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b

**Comment by PSCapng** [comment]
I second this. We are running into the same issue. If the content-type is set explicitly before making the call, the http module should respect that setting and encode the data accordingly. If you are passing a JSON string to the call and you set the content-type as application/json, there should not need to be any action on the content that is sent.

**Comment by m1aw** [comment]
Is there any updated on the issue?

We are having the same problem. Post is always URL encoded, and we are not able to send data has string to workaround the issue.

**Comment by m1aw** [comment]
Update: in my case I was forgot to use setDataSerializer('json').

Thought I still think it should infer the type based on Content-Type header. I think the problem should be solved upstream.
