### ISSUE TITLE
PositionError type missing code constants

### ISSUE THREAD

**Issue by lhunath** [ionic-team/ionic-native#1962]
[ ] bug report
[x] feature request

HTML5's `PositionError` has a `code` property which can contain one of three spec-defined values:
PERMISSION_DENIED (1)
POSITION_UNAVAILABLE (2)
TIMEOUT (3)

These constants are declared on the JS PositionError type, however, in ionic-native's `PositionError` interface the declarations are missing.  As a result, applications are forced to hard-code the integer values into their application rather than relying on named identifiers.

These constants should be included in `@ionic-native/geolocation`

**Other information:**
https://developer.mozilla.org/en-US/docs/Web/API/PositionError

**Comment by sebaferreras** [comment]
@danielsogl why did you close this issue? I guess we'd expect the constants to be available in the Ionic Native definition, right?

**Comment by sebaferreras** [comment]
@danielsogl  why did you close this issue? I guess we'd expect the constants to be part of the plugin's definition, right?
