### ISSUE TITLE
Export unsubscribeRawData function to BluetoothSerial native plugin

### ISSUE THREAD

**Issue by seb-bisson** [ionic-team/ionic-native#1965]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X] feature request

**Current behavior:**

In the bluetooth serial cordova plugin (https://github.com/don/BluetoothSerial). the unsubscribeRawData can stop subscribtion to rawdata.

**Expected behavior:**

With bluetoothserial provider of ionic-native package, this function is not visible.

It can be helpfull to subscribe/unscribe rawdata to get data on demand.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by danielsogl** [comment]
Just unsubscribe the observable. The wrapper automatically calls the unsubscribeRawData function
