### ISSUE TITLE
Missing onBackButton method

### ISSUE THREAD

**Issue by rasaturyan** [ionic-team/ionic-native#1967]
Camera preview plugin was updated and added onBackButton method.

Here is the pull request link: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/pull/359

Usage:
### onBackButton(successCallback, [errorCallback])

<info>Callback event for the back button tap</info><br/>

```javascript
CameraPreview.onBackButton(function() {
  console.log('Back button pushed');
});
```

Add the same method to the Ionic Native.

**Comment by khsmaxim** [comment]
That cause the problem with some devices
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview#android-quirks-older-devices
