### ISSUE TITLE
push plugin missing while using --prod to build

### ISSUE THREAD

**Issue by Barathwaja** [ionic-team/ionic-native#1979]
Getting WARNING like this during --prod but in debug mode its working..

![image](https://user-images.githubusercontent.com/5066436/30568141-424925aa-9cf1-11e7-9566-3d2adf3f82c3.png)

**Native: tried calling Push.hasPermission, but the Push plugin is not installed.
Install the Push plugin: 'ionic cordova plugin add phonegap-plugin-push'
Native: tried calling PushNotification.init, but the PushNotification plugin is not installed.**

**Comment by AndreasGassmann** [comment]
I had the same problem and then noticed that I tried to execute the code outside of the "platform.ready" event. Did you check if it's inside of it?

**Comment by Barathwaja** [comment]
@AndreasGassmann yes it should be inside platformready only.. using that way only i'm getting this error

**Comment by malick7** [comment]
I'm also facing the same issue for normal build. Any update on this would be great, thanks!
