### ISSUE TITLE
Ionic Deploy snapshots being applied to updated binary (ios)

### ISSUE THREAD

**Issue by media4learning** [ionic-team/ionic-native#1981]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Install version 1.0.0 of app on ios. 
Update app with Ionic Deploy snapshot. Snapshot versions set to min and max 1.0.0
Install version 1.0.1 - download from .plist link on remote server (Enterprise program)
Launch version 1.0.1 - most recent snapshot from version 1.0.0 is applied. AppVersion plugin is showing 1.0.1, but all other files are from the latest snapshot that shouldn't apply to 1.0.1
Close and relaunch version 1.0.1 - app now loads correct files for v 1.0.1 (ignores any snapshots from 1.0.0)

**Expected behavior:**
When installing  new .ipa over an older version, no snapshot from previous versions should be loaded.

**Steps to reproduce:**
Install ipa.
ionic upload -n 'update for version 1.0.1' --nobuild
apply snapshot to app
change version number in config xml, export new ipa and install over previous version
launch new version - snapshot from previous version is loaded
Close and relaunch app, old snapshot is not longer loaded, and everything is loaded as expected

**Related code:**

```
insert any relevant code here
```

**Other information:**
cli packages: (/Users/chrisdelambert/Documents/stjohncpg/node_modules)

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    Node              : v8.1.4
    npm               : 5.1.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

**package.json info:**
{
    "name": "CPGs",
    "version": "1.0.1",
    "author": "St John Learning Media",
    "homepage": "http://www.stjohn.org.nz/",
    "private": true,
    "scripts": {
        "start": "ionic serve --browser 'google chrome canary'",
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve",
        "emi": "ionic cordova emulate ios -lcs --target iPhone-6s",
        "ema": "ionic cordova emulate android -lcs"
    },
    "config": {
        "ionic_copy": "./config/copy.config.js",
        "ionic_sass": "./config/sass.config.js"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/app-version": "^3.9.2",
        "@ionic-native/core": "3.7.0",
        "@ionic-native/in-app-browser": "^4.0.1",
        "@ionic-native/keyboard": "^4.0.1",
        "@ionic-native/native-storage": "^3.9.2",
        "@ionic-native/network": "^4.2.1",
        "@ionic-native/screen-orientation": "^3.14.0",
        "@ionic-native/splash-screen": "3.7.0",
        "@ionic-native/status-bar": "3.7.0",
        "@ionic-native/three-dee-touch": "^4.2.1",
        "@ionic/cloud-angular": "^0.12.0",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-3dtouch": "^1.3.5",
        "cordova-plugin-app-version": "~0.1.9",
        "cordova-plugin-console": "~1.0.7",
        "cordova-plugin-device": "^1.1.6",
        "cordova-plugin-inappbrowser": "^1.7.1",
        "cordova-plugin-inappbrowser-custom": "^1.2.0",
        "cordova-plugin-ios-disableshaketoedit": "^1.0.0",
        "cordova-plugin-nativestorage": "^2.2.2",
        "cordova-plugin-network-information": "^1.3.3",
        "cordova-plugin-screen-orientation": "^2.0.1",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "~2.2.3",
        "cordova-plugin-whitelist": "^1.3.2",
        "devices": "^0.1.0",
        "es6-promise-plugin": "git+https://github.com/vstirbu/PromisesPlugin.git",
        "font-awesome": "^4.7.0",
        "ionic-angular": "^3.6.0",
        "ionic-plugin-deploy": "^0.6.7",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "ios-sim": "^6.0.0",
        "lodash": "^4.17.4",
        "lodash._baseassign": "^3.2.0",
        "lodash._createassigner": "^3.1.1",
        "nl.x-services.plugins.backgroundaudio": "git+https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio.git",
        "rxjs": "5.1.1",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.10"
    },
    "devDependencies": {
        "@ionic/app-scripts": "^2.1.3",
        "ionic": "3.10.3",
        "typescript": "2.4.0"
    },
    "cordovaPlugins": [
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "cordova-plugin-device",
        "cordova-plugin-splashscreen",
        "ionic-plugin-keyboard"
    ],
    "cordovaPlatforms": [
        "ios",
        {
            "platform": "ios",
            "version": "",
            "locator": "ios"
        }
    ],
    "description": "St John Clinical Procedures and Guidelines",
    "cordova": {
        "platforms": [
            "android",
            "ios"
        ],
        "plugins": {
            "cordova-plugin-app-version": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-nativestorage": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-deploy": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-screen-orientation": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-ios-disableshaketoedit": {},
            "nl.x-services.plugins.backgroundaudio": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-3dtouch": {}
        }
    }
}

**Comment by media4learning** [comment]
How do I get these issues assigned?

**Comment by mlynch** [comment]
Hi, this is not the appropriate place to file issues for Deploy. In the future the best path is to contact support: https://ionic.zendesk.com/hc/en-us

If you haven’t contacted support already I’ll ping the appropriate engineer to take a look at the above.
