### ISSUE TITLE
Publishing version 3.5.0 to npmjs.com

### ISSUE THREAD

**Issue by Mr-Anonymous** [ionic-team/ionic-native#1999]
I am using `ionic-native@^3.5.0` but when I run the package.json file to create the node_modules, I get the error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ionic-native@^3.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'App'
npm ERR! notarget 
```

Looking at the versions published in npmjs.com, I noticed it only goes upto version `2.9.0`. Would you be able to publish the higher version of ionic-native in npmjs.com please?

```
{ name: 'ionic-native',
  description: 'Native plugin wrappers for Cordova and Ionic with TypeScript, ES6+, Promise and Observable support',
  'dist-tags': { latest: '2.9.0', test: '2.2.8' },
  versions: 
   [ '1.0.7',
     '1.0.8',
     '1.0.9',
     '1.0.10',
     '1.0.11',
     '1.0.12',
     '1.1.0',
     '1.1.1',
     '1.2.0',
     '1.2.1',
     '1.2.2',
     '1.2.3',
     '1.2.4',
     '1.3.0',
     '1.3.1',
     '1.3.2',
     '1.3.3',
     '1.3.4',
     '1.3.5',
     '1.3.6',
     '1.3.7',
     '1.3.8',
     '1.3.9',
     '1.3.10',
     '1.3.11',
     '1.3.12',
     '1.3.13',
     '1.3.14',
     '1.3.15',
     '1.3.16',
     '1.3.17',
     '1.3.18',
     '1.3.19',
     '1.3.20',
     '1.3.21',
     '1.3.22',
     '1.3.23',
     '1.3.24',
     '1.3.25',
     '1.3.26',
     '1.3.27',
     '2.0.0',
     '2.0.1',
     '2.0.2',
     '2.0.3',
     '2.1.2',
     '2.1.3',
     '2.1.4',
     '2.1.5',
     '2.1.6',
     '2.1.7',
     '2.1.8',
     '2.1.9',
     '2.2.0',
     '2.2.1',
     '2.2.2',
     '2.2.3',
     '2.2.4',
     '2.2.5',
     '2.2.6',
     '2.2.7',
     '2.2.8',
     '2.2.9',
     '2.2.10',
     '2.2.11',
     '2.2.12',
     '2.2.13',
     '2.2.14',
     '2.2.15',
     '2.2.16',
     '2.2.17',
     '2.3.0',
     '2.3.1',
     '2.3.2',
     '2.4.0',
     '2.4.1',
     '2.5.0',
     '2.5.1',
     '2.6.0',
     '2.7.0',
     '2.8.0',
     '2.8.1',
     '2.9.0' ],
...
```

**Comment by MarcoOliva** [comment]
I have the same problem.
``
{ name: 'ionic-native',
  description: 'Native plugin wrappers for Cordova and Ionic with TypeScript, ES6+, Promise and Observable support',
  'dist-tags': { latest: '2.9.0', test: '2.2.8' },
  versions: 
   [ '1.0.7',
     '1.0.8',
     '1.0.9',
     '1.0.10',
     '1.0.11',
     '1.0.12',
     '1.1.0',
     '1.1.1',
     '1.2.0',
     '1.2.1',
     '1.2.2',
     '1.2.3',
     '1.2.4',
     '1.3.0',
     '1.3.1',
     '1.3.2',
     '1.3.3',
     '1.3.4',
     '1.3.5',
     '1.3.6',
     '1.3.7',
     '1.3.8',
     '1.3.9',
     '1.3.10',
     '1.3.11',
     '1.3.12',
     '1.3.13',
     '1.3.14',
     '1.3.15',
     '1.3.16',
     '1.3.17',
     '1.3.18',
     '1.3.19',
     '1.3.20',
     '1.3.21',
     '1.3.22',
     '1.3.23',
     '1.3.24',
     '1.3.25',
     '1.3.26',
     '1.3.27',
     '2.0.0',
     '2.0.1',
     '2.0.2',
     '2.0.3',
     '2.1.2',
     '2.1.3',
     '2.1.4',
     '2.1.5',
     '2.1.6',
     '2.1.7',
     '2.1.8',
     '2.1.9',
     '2.2.0',
     '2.2.1',
     '2.2.2',
     '2.2.3',
     '2.2.4',
     '2.2.5',
     '2.2.6',
     '2.2.7',
     '2.2.8',
     '2.2.9',
     '2.2.10',
     '2.2.11',
     '2.2.12',
     '2.2.13',
     '2.2.14',
     '2.2.15',
     '2.2.16',
     '2.2.17',
     '2.3.0',
     '2.3.1',
     '2.3.2',
     '2.4.0',
     '2.4.1',
     '2.5.0',
     '2.5.1',
     '2.6.0',
     '2.7.0',
     '2.8.0',
     '2.8.1',
     '2.9.0' ],
  maintainers: 
   [ 'ihadeed <i.hadeed@zyra.ca>',
     'ionicjs <hi@ionicframework.com>',
     'maxlynch <max@ionic.io>',
     'tlancina <tim@ionic.io>' ],
  time: 
   { modified: '2017-09-16T05:23:56.352Z',
     created: '2015-11-28T05:08:50.329Z',
     '1.0.7': '2015-11-28T05:08:50.329Z',
     '1.0.8': '2015-12-02T02:39:26.758Z',
     '1.0.9': '2016-02-18T18:52:43.914Z',
     '1.0.10': '2016-03-05T21:41:34.721Z',
     '1.0.11': '2016-03-06T13:47:47.579Z',
     '1.0.12': '2016-03-06T14:38:44.533Z',
     '1.1.0': '2016-03-17T20:01:53.020Z',
     '1.1.1': '2016-04-08T21:54:25.282Z',
     '1.2.0': '2016-04-30T04:05:34.354Z',
     '1.2.1': '2016-05-11T05:51:45.357Z',
     '1.2.2': '2016-05-20T21:04:11.138Z',
     '1.2.3': '2016-06-01T10:57:15.906Z',
     '1.2.4': '2016-06-01T20:37:20.232Z',
     '1.3.0': '2016-06-13T17:32:07.553Z',
     '1.3.1': '2016-06-26T17:07:59.667Z',
     '1.3.2': '2016-06-27T12:43:49.619Z',
     '1.3.3': '2016-07-11T22:37:24.403Z',
     '1.3.4': '2016-07-14T15:17:02.715Z',
     '1.3.5': '2016-07-17T06:44:59.296Z',
     '1.3.6': '2016-07-17T08:55:37.051Z',
     '1.3.7': '2016-07-18T03:13:29.541Z',
     '1.3.8': '2016-07-20T11:14:23.372Z',
     '1.3.9': '2016-07-23T11:20:18.811Z',
     '1.3.10': '2016-08-01T06:33:25.533Z',
     '1.3.11': '2016-08-11T11:39:34.660Z',
     '1.3.12': '2016-08-13T15:24:42.971Z',
     '1.3.13': '2016-08-13T15:36:41.522Z',
     '1.3.14': '2016-08-15T09:14:46.412Z',
     '1.3.15': '2016-08-15T15:51:09.844Z',
     '1.3.16': '2016-08-15T17:38:49.190Z',
     '1.3.17': '2016-08-23T01:49:42.626Z',
     '1.3.18': '2016-08-26T16:37:02.102Z',
     '1.3.19': '2016-08-27T06:19:23.843Z',
     '1.3.20': '2016-08-27T19:11:25.457Z',
     '1.3.21': '2016-09-07T03:39:17.125Z',
     '1.3.22': '2016-09-21T20:08:52.613Z',
     '1.3.23': '2016-09-21T20:11:26.209Z',
     '1.3.24': '2016-09-21T20:13:06.620Z',
     '1.3.25': '2016-09-22T18:13:13.482Z',
     '2.0.0': '2016-09-22T18:25:25.860Z',
     '1.3.26': '2016-09-22T18:37:14.243Z',
     '1.3.27': '2016-09-22T18:40:05.859Z',
     '2.0.1': '2016-09-22T19:03:00.692Z',
     '2.0.2': '2016-09-22T20:10:53.111Z',
     '2.0.3': '2016-09-24T22:34:17.021Z',
     '2.1.0': '2016-10-03T21:06:35.989Z',
     '2.1.1': '2016-10-03T21:39:24.296Z',
     '2.1.2': '2016-10-06T01:04:25.345Z',
     '2.1.3': '2016-10-06T02:37:29.722Z',
     '2.1.4': '2016-10-06T02:49:38.555Z',
     '2.1.5': '2016-10-06T03:21:19.621Z',
     '2.1.6': '2016-10-06T04:28:22.409Z',
     '2.1.7': '2016-10-07T00:39:26.982Z',
     '2.1.8': '2016-10-08T22:51:29.959Z',
     '2.1.9': '2016-10-09T00:58:37.100Z',
     '2.2.0': '2016-10-11T08:31:23.730Z',
     '2.2.1': '2016-10-12T00:19:57.424Z',
     '2.2.2': '2016-10-12T01:07:29.481Z',
     '2.2.3': '2016-10-14T10:07:44.171Z',
     '2.2.4': '2016-10-15T17:18:30.600Z',
     '2.2.5': '2016-10-27T13:19:14.753Z',
     '2.2.6': '2016-10-27T23:06:15.373Z',
     '2.2.7': '2016-11-24T10:26:42.061Z',
     '2.2.8': '2016-12-01T20:56:46.990Z',
     '2.2.9': '2016-12-01T23:54:55.417Z',
     '2.2.10': '2016-12-04T19:05:52.069Z',
     '2.2.11': '2016-12-06T12:36:23.243Z',
     '2.2.12': '2016-12-16T19:15:41.472Z',
     '2.2.13': '2016-12-27T13:44:03.546Z',
     '2.2.14': '2017-01-07T13:04:36.442Z',
     '2.2.15': '2017-01-11T00:19:55.423Z',
     '2.2.16': '2017-01-11T01:39:44.469Z',
     '2.2.17': '2017-01-20T20:53:48.246Z',
     '2.3.0': '2017-01-20T21:35:30.436Z',
     '2.3.1': '2017-01-22T22:34:49.222Z',
     '2.3.2': '2017-01-24T03:20:32.128Z',
     '2.4.0': '2017-01-24T05:54:13.890Z',
     '2.4.1': '2017-01-24T20:15:04.551Z',
     '2.5.0': '2017-02-07T12:28:01.385Z',
     '2.5.1': '2017-02-07T16:33:11.276Z',
     '2.6.0': '2017-03-02T02:31:03.005Z',
     '2.7.0': '2017-03-02T04:32:14.697Z',
     '2.8.0': '2017-03-04T13:21:43.771Z',
     '2.8.1': '2017-03-10T15:32:54.660Z',
     '2.9.0': '2017-03-18T22:35:16.864Z',
     '3.5.0': '2017-04-18T21:49:50.842Z' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users: 
   { ihadeed: true,
     kbezold: true,
     sebastianbaar: true,
     asaupup: true,
     sujan12: true,
     nuwaio: true },
  homepage: 'https://github.com/driftyco/ionic-native',
  repository: 
   { type: 'git',
     url: 'git+https://github.com/driftyco/ionic-native.git' },
  bugs: { url: 'https://github.com/driftyco/ionic-native/issues' },
  version: '2.9.0',
  main: 'dist/es5/index.js',
  module: 'dist/esm/index.js',
  typings: 'dist/es5/index.d.ts',
  files: [ 'dist' ],
  dependencies: { rxjs: '5.0.1' },
  devDependencies: 
   { browserify: '^13.3.0',
     'canonical-path': '0.0.2',
     'conventional-changelog-cli': '^1.2.0',
     'conventional-github-releaser': '^1.1.3',
     cpr: '^2.0.2',
     'cz-conventional-changelog': '^1.2.0',
     decamelize: '^1.2.0',
     dgeni: '^0.4.2',
     'dgeni-packages': '^0.10.18',
     'es6-shim': '~0.35.2',
     glob: '^7.1.1',
     gulp: '^3.9.1',
     'gulp-rename': '^1.2.2',
     'gulp-replace': '^0.5.4',
     'gulp-tslint': '^6.1.2',
     'gulp-uglify': '^2.0.0',
     'jasmine-core': '~2.5.2',
     karma: '~1.3.0',
     'karma-browserify': '~5.1.0',
     'karma-jasmine': '~1.1.0',
     'karma-phantomjs-launcher': '~1.0.2',
     lodash: '4.17.4',
     minimist: '^1.1.3',
     mkdirp: '^0.5.1',
     'node-html-encoder': '0.0.2',
     q: '1.4.1',
     semver: '^5.3.0',
     tsify: '~3.0.0',
     tslint: '^3.15.1',
     'tslint-ionic-rules': '0.0.7',
     typescript: '2.0.09',
     watchify: '~3.7.0' },
  scripts: 
   { test: 'karma start',
     'test:watch': 'npm test -- --watch',
     start: 'npm run test:watch',
     lint: 'gulp lint',
     build: 'npm run lint && npm run build:js && npm run build:esm && npm run build:bundle && npm run build:minify',
     'build:js': 'tsc -p tsconfig-es5.json',
     'build:esm': 'tsc -p tsconfig-esm.json',
     'build:bundle': 'browserify dist/es5/index.js > dist/ionic.native.js',
     'build:minify': 'gulp minify:dist',
     shipit: 'npm run build && npm publish && bash ./scripts/bower.sh',
     changelog: 'conventional-changelog -p angular -i CHANGELOG.md -s -r 0',
     'plugin:create': 'gulp plugin:create' },
  config: 
   { commitizen: { path: './node_modules/cz-conventional-changelog' } },
  gitHead: '97ba9b4fe14febcd90edaa3e9f7550c8ba3e981e',
  dist: 
   { shasum: 'e9a36c850eda180918407c288e5d634978e32052',
     tarball: 'https://registry.npmjs.org/ionic-native/-/ionic-native-2.9.0.tgz' },
  directories: {} }
``

**Comment by ihadeed** [comment]
The `ionic-native` package is for Ionic Native 2.x only ... If you wish to use versions greater than 3.x, you need to start using the `@ionic-native/` scope. 

Please follow the latest docs for instructions.
