### ISSUE TITLE
docs: native android-permissions plugin usage is wrong

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-native#2000]
_From @smoral on September 27, 2017 14:23_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>browser</span>

<span ionic-description>De usage documentation in https://ionicframework.com/docs/native/android-permissions/ its wrong. Success response on checkPermission method has as result an object indicating if the app has permission, for example: {"hasPermission":false}.</span>

<span is-issue-template></span>

_Copied from original issue: ionic-team/ionic#12998_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This is not an Ionic Framework issue. I am moving this to the https://github.com/ionic-team/ionic-native repository. Please follow the issue over there.

Thank you for using Ionic

**Comment by weldermarcosxd** [comment]
+1 for this

**Comment by joshbabb** [comment]
When I `.requestPermission()`, no request is presented whatsoever...  No warnings, no errors, no permission request, the promise just resolves as described above.
