### ISSUE TITLE
wrapper for private plugin question

### ISSUE THREAD

**Issue by mateo666** [ionic-team/ionic-native#2004]
If writing a private wrapper for a private plugin, what should go in the @Plugin ?
can the repo be file:/ ?

@Plugin({
  pluginName: 'MyPrivatePlugin',
  plugin: 'cordova-plugin-private-plugin,
  pluginRef: 'privateplugin',
  repo: 'file:../../../somwhere/privateplugin'
  platforms: ['Android', 'iOS']
})

**Comment by danielsogl** [comment]
You could write your own plugin wrapper. Just follow the DEVELOP docs. But I won't publish a private wrapper to our repository.
