### ISSUE TITLE
SplashScreen fired to early on Browser platform

### ISSUE THREAD

**Issue by Gemeapp** [ionic-team/ionic-native#2007]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**

When using the splashscreen on the browser platform I often get this error

```Typescript
polyfills.js:3 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.show (SplashScreenProxy.js:79)
    at SplashScreenProxy.js:159
```
The problem seems to be these staments

```typescript
            localSplash.appendChild(localSplashImage);
            document.body.appendChild(localSplash);
```
as document.body is null

So it seems that the call to SplashScreen.Show() is executed to early

**Expected behavior:**

I would like the SplashScreen to display properly

**Steps to reproduce:**

This is normally related to reloading the application, and often it is possible to press Ctrl-F5 a couple of times to get the SpalshScreen deisplayed properly

On this URL https://geme-cce67.firebaseapp.com/ it should be reproducable if pressing F5

**Other information:**

I have upgraded to the lastest commit of the plugin
**package.json info:**

```json
"cordova-plugin-splashscreen": "git+https://github.com/apache/cordova-plugin-splashscreen.git"
```
In my config.xml I have the following configuration

```json
    <platform name="browser">
        <preference name="SplashScreen" value="./assets/img/logo1024x1024.png" />
        <preference name="SplashScreenDelay" value="10000" />
        <preference name="SplashScreenBackgroundColor" value="green" />
        <preference name="ShowSplashScreen" value="true" />
        <preference name="SplashScreenWidth" value="1024" />
        <preference name="SplashScreenHeight" value="1024" />
    </platform>
```
increasing the SplashScreenDelay does apparently not help

**Comment by danielsogl** [comment]
Related to the plugin source.
