### ISSUE TITLE
"utf_offset" typo, should be "utc_offset" in Globalization plugin

### ISSUE THREAD

**Issue by joshstrange** [ionic-team/ionic-native#2015]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Typo in types causes TypeScript to complain if you use the (correct) "utc_offset"

https://github.com/ionic-team/ionic-native/blob/536a90636663a5cc536a0078ed86ad4e5e9bdbb0/src/%40ionic-native/plugins/globalization/index.ts#L80

**Expected behavior:**
getDatePattern() return object property is "utc_offset"

**Steps to reproduce:**
Install Globalization plugin, attempt to use ut[fc]_offset from the resolved promise from getDatePattern()

**Other information:**
I know this is a single character fix and I would create a pull request but I can't do that right now. I'm sorry.

**Comment by philipp-reich** [comment]
I found the same issue... 

hour of my lifetime... 

My "solution":
`
globalization.getDatePattern(null).then((pattern:any) => {
//this.utcOffset = pattern.utf_offset;
this.utcOffset = pattern.utc_offset;
});
`

now i can use pattern like i want.
