### ISSUE TITLE
[file-transfer] Cordova is deprecating cordova-plugin-file-transfer

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-native#2026]
https://issues.apache.org/jira/browse/CB-13052
https://github.com/apache/cordova-docs/pull/746/files

How could/should/wants Ionic Native handle this?

Deprecate the wrapper as well? 
Replace the implementation with what the Cordova blog post will contain? 
Transition to a new `@ionic/file-transfer` (or similar) that has the same API as the current Ionic Native wrapper?

**Comment by janpio** [comment]
Blog post is out: https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html

**Comment by westphalen** [comment]
I have already been forced to migrate off Cordova file-transfer for some of my projects, but using HttpClient has significant worse performance.

**Comment by alirezavafaee** [comment]
I use httpClient for file download and save it on storage (android device), but speed is low for copy temp file to target place!

**Comment by ihadeed** [comment]
They stopped development/maintenance only.. the plugin is still functional. The plugin wrapper can stay as-is, we can add a deprecation notice.
