### ISSUE TITLE
[google-maps]: HtmlInfoWindow missing .on and .one methods

### ISSUE THREAD

**Issue by stormwin** [ionic-team/ionic-native#2034]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
HtmlInfoWindow missing .on and .one methods

**Expected behavior:**
HtmlInfoWindow should have .on and .one methods

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**
From HtmlInfoWindow.js from plugin repo, HtmlInfoWindow extends from BaseClass (where .on and .one methods exists), but in ionic-native wrapper it extends from IonicNativePlugin

**package.json info:**

```json
insert the content here
```
I'm using latest version of ionic-native

**Comment by stormwin** [comment]
@wf9a5m75 can you check this and confirm that extending from IonicNativePlugin class instead of BaseClass can cause this problem?

**Comment by stormwin** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/HtmlInfoWindow.js#L232

https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts#L1956

**Comment by wf9a5m75** [comment]
Ah..

**Comment by wf9a5m75** [comment]
I sent a PR to fix this bug.
https://github.com/ionic-team/ionic-native/pull/2035

**Comment by wf9a5m75** [comment]
The PR is merged. Please reinstall the `@ionic-native/google-maps@4.3.3` and `@ionic-native/core@4.3.3`.

@ihadeed You can close this thread.

**Comment by wf9a5m75** [comment]
This is already solved issue. 

@ihadeed you can close this thread.
