### ISSUE TITLE
[Music-Controls] Subscription don't fire 

### ISSUE THREAD

**Issue by fdambrosio** [ionic-team/ionic-native#2039]
I’m using Ionic 3 + Ionic Native Media + Ionic Native Music Controls but music controls doesn’t works. Clicking Play / Pause using Music Controls (on LockedScreen/ControlCenter) nothing happen. Media streaming works well.

I’m testing it on iOS (10.3 / 11) simulator and device, and on Android (5.1) tablet.

I’ve installed all cordova plugins required, of course.
I’ve switched ON the ‘Audio’ option in Capabilities -> ‘Background Modes’ using XCODE 9.

I’ve created a minimal ionic blank app from ionic starter, with Media stream (works) and Music Controls (not works), it’s available on github for testing :
https://github.com/fdambrosio/ionic-media-controls

Home.html

```
<ion-content padding>
  <!-- Bind the click event to a method -->
<button ion-button (click)="play()">
  play file!
</button>
<button ion-button (click)="pause()">
  pause file!
</button>
</ion-content>
```

Home.ts 

```
  import { Component } from '@angular/core';
    import { NavController } from 'ionic-angular';
    import { Media, MediaObject } from '@ionic-native/media';
    import { MusicControls } from '@ionic-native/music-controls';

    @Component({
      selector: 'page-home',
      templateUrl: 'home.html'
    })    
    export class HomePage {
          file: MediaObject;
          constructor(private musicControls: MusicControls, private media: Media, public navCtrl: NavController) {
          }
          play(){
            this.file = this.media.create('https://archive.org/download/db2007-05-20.rm.flac16/db2007-05-20d1t01.mp3');
            this.file.play();

            this.musicControls.destroy(); // it's the same with or without the destroy 
            this.musicControls.create({
              track       : 'Test track',        // optional, default : ''
              artist      : 'test artist',                       // optional, default : ''
              cover       : '',      // optional, default : nothing
              // cover can be a local path (use fullpath 'file:///storage/emulated/...', or only 'my_image.jpg' if my_image.jpg is in the www folder of your app)
              //           or a remote url ('http://...', 'https://...', 'ftp://...')
              isPlaying   : true,                         // optional, default : true
              dismissable : true,                         // optional, default : false

              // hide previous/next/close buttons:
              hasPrev   : false,      // show previous button, optional, default: true
              hasNext   : false,      // show next button, optional, default: true
              hasClose  : true,       // show close button, optional, default: false

            // iOS only, optional
              album       : 'test album',     // optional, default: ''
              duration : 0, // optional, default: 0
              elapsed : 0, // optional, default: 0
              hasSkipForward : true,  // show skip forward button, optional, default: false
              hasSkipBackward : true, // show skip backward button, optional, default: false
              skipForwardInterval: 15, // display number for skip forward, optional, default: 0
              skipBackwardInterval: 15, // display number for skip backward, optional, default: 0

              // Android only, optional
              // text displayed in the status bar when the notification (and the ticker) are updated
              ticker    : 'Now playing test'
             });
             this.musicControls.subscribe().subscribe(action => {
                 function events(action) {
                  console.log('action', action);
                   const message = JSON.parse(action).message;

                       switch(message) {
                           case 'music-controls-pause':
                               console.log('musc pause'); // not work
                               this.pause();
                               break;
                           case 'music-controls-play':
                               console.log('music play'); // not work
                           case 'music-controls-destroy':
                               // Do something
                               break;

                            default:
                                break;
                        }
                   }

               this.musicControls.listen(); // activates the observable above
               this.musicControls.updateIsPlaying(true);

            });
        }

          pause(){
            this.file.pause();
          }
        }
```

Ionic Info:

```
@ionic/cli-utils : 1.12.0
ionic (Ionic CLI) : 3.12.0

global packages:

cordova (Cordova CLI) : 7.0.1 
local packages:

@ionic/app-scripts : 3.0.0
Cordova Platforms  : ios 4.5.1
Ionic Framework    : ionic-angular 3.7.1
System:

ios-deploy : 1.9.2 
ios-sim    : 6.1.2 
Node       : v6.11.2
npm        : 5.4.2 
OS         : macOS Sierra
Xcode      : Xcode 9.0 Build version 9A235
```

**Comment by fdambrosio** [comment]
I’ve tested a lot of plugins versions, It’s working on iOS only using 1.4.1.
I've used this environment:

cordova-plugin-music-controls@1.4.1
ionic-native/music-controls@4.2.1
cordova-ios@4.5.2

Play/pause is clickable and works, but hasPrev/hasNext buttons are always showed on iOS 11.

Ionic Docs are wrong: on subscribe you have to change the code with this:
```

this.musicControls.subscribe().subscribe((action) => {
          switch(action) {
```

I’ve added a repo with ‘downgrade’ branch that works: 
https://github.com/fdambrosio/ionic-media-controls

**Comment by ghenry22** [comment]
I've just started looking at this as well.

Had the same problem with 2.x versions.  I get metadata in control center but play/pause/next/prev are completely non-functional.  Scrubbing forwards with the progress bar works though.

reverted to 1.4.1 and now I get play/pause/next/prev buttons again.  Play/pause works but next/previous send an action of null so now I can't skip forward or back.

Cordova -ios 4.5.3
ios11
ionic-native 4.3.3
music controls 1.4.1

**Comment by ghenry22** [comment]
I submitted updates for the music controls plugin that have been merged
Please try installing the latest version of the music controls plugin from the github repo and it should work fine with latest ionic-native using the standard instructions.

**Comment by fdambrosio** [comment]
thanks @ghenry22 the latest 2.1.3 music control plugin works fine. 
My sample repo works: https://github.com/fdambrosio/ionic-media-controls

**Comment by fdambrosio** [comment]
the latest 2.1.4 is not working with Native Music Controls 4.3.3: the control buttons are not clickable. Reverting to 2.1.3 control works.

**Comment by ghenry22** [comment]
@fdambrosio - on iOS or android?

The only change on iOS between those versions is the removal an debug log statement that was left in by mistake.  Looks like there was a change to allow custom icons for android though.

**Comment by fdambrosio** [comment]
@ghenry22 I've tested it on iOS 11.1

**Comment by abitul** [comment]
@fabiodursoexin , i have the same issues, when i try to downgrade to music control 2.1.3 , i get message plugin version 2.1.3 not found (404)

**Comment by abitul** [comment]
plese help

**Comment by abitul** [comment]
i get this error when using version plugin music control ,ERROR Error: Uncaught (in promise): Attempt to write to field 'boolean com.homerours.musiccontrols.MusicControlsInfos.isPlaying' on a null object reference

**Comment by abitul** [comment]
yeah, i success using plugin music control version 2.1.4 with this code below 
    this.musicControls.subscribe().subscribe((action) => {
      let message = JSON.parse(action).message;
      switch(message) {
                    case 'music-controls-next':
                        this.next();
                        break;
                    case 'music-controls-previous':
                        this.previous();
                        break;
                    case 'music-controls-pause':
                        this.playorpause();
                        break;
                    case 'music-controls-play':
                        this.playorpause();
                        break;
                    case 'music-controls-destroy':
                       // Do something
                        break;
                    case 'music-controls-media-button' :
                            // Do something
                        break;
                    case 'music-controls-headset-unplugged':
                            // Do something
                        break;
                    case 'music-controls-headset-plugged':
                            // Do something
                        break;
                    default:
                        break;
        }
    });
