### ISSUE TITLE
Audit plugin list

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-native#2045]
Its time we do a quick audit of plugins for the next major release. There's already a good list of plugins that are either buggy or no longer maintained, like the Naive-transitions plugin (buggy) and Zip plugin ([unmaintained](https://github.com/MobileChromeApps/cordova-plugin-zip/issues/75#issuecomment-327042960))

Most of the work is just checking out the plugin link, look at the commit history/issues and do a quick test of plugin functionality. 

cc @ihadeed @mlynch

**Comment by einicher** [comment]
does ionic maintain an up-to-date version of this plugin now?

**Comment by kensodemann** [comment]
@einicher - Ionic is not the one responsible for maintaining _most_ of these plugins. Ionic does indeed maintain some plugins, such as `cordova-plugin-ionic-webview`, but the vast majority of the plugins you see here have their own maintainers. The Ionic Native project maintains a list of wrappers for the plugins. These wrappers make it easier to use the plugin within your project, but that is _not_ the same thing as maintaining the plugin itself.
