### ISSUE TITLE
@ionic-native/onesignal: on iOS the notification callback is not executed on coldstart

### ISSUE THREAD

**Issue by abuechler** [ionic-team/ionic-native#2049]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**

When setting up the notification received callbacks as described in the [documentation](http://ionicframework.com/docs/native/onesignal/) the callback is being executed when

- the application is in the foreground
- the application is in the background and the user taps on the notification

**but** the callback is **not** executed when
- the user kills the app, later on receives a notification and taps on it which will start the application but the callback is not executed.

**Expected behavior:**

The callback should be executed in all cases or if this is not possible on the platform (e.g. iOS) the documentation should state this in a big red box at the begining ;-)

**Steps to reproduce:**

1. Set up a callback as described in the [documentation](http://ionicframework.com/docs/native/onesignal/) and do something in it so you can verify it has been executed
2. Deploy the app on a real device
3. When the application is running verify your setup by sending a OneSignal notification - the callback should be executed in this case
3. Kill the application
4. Send another OneSignal notification
5. Tap on the notification
6. The application is started but the callback not executed

**Related code:**
in the constructor of app.components.ts do something like
```
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      splashscreen.hide();
      statusBar.styleDefault();
      if (this.platform.is('cordova')) {
        this.oneSignal.startInit('your-onesignal-app-id');
  
        this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);
  
        this.oneSignal.handleNotificationReceived().subscribe(() => {
          // Writing the notifications to PouchDB on the device to inspect whether we got something
          this.dbService.addLogEntry(new LogEntry('do something when notification is received'));
        });
  
        this.oneSignal.handleNotificationOpened().subscribe(() => {
          this.dbService.addLogEntry(new LogEntry('do something when a notification is opened'));
        });
  
        this.oneSignal.endInit();
  
        this.oneSignal.getIds().then((result) => {
          // No the device is registered...
          this.toastService.showToast('Push Token: ' + result.pushToken);
        }, (err) => { this.toastService.showToast(err); });
      } else {
        // skip push registration on desktop devices
        console.log('skipping device token registration since running on desktop device');
  
      }
    });
```

**Other information:**

Related issues:

- phonegap/phonegap-plugin-push#1677
- OneSignal/OneSignal-Cordova-SDK#253

**package.json info:**

```json
{
   "name":"SomeApp",
   "version":"0.9.0",
   "private":true,
   "scripts":{
      "clean":"ionic-app-scripts clean",
      "build":"ionic-app-scripts build",
      "ionic:build":"ionic-app-scripts build",
      "ionic:build:prod":"NODE_ENV=prod ionic-app-scripts build",
      "ionic:serve":"ionic-app-scripts serve",
      "ionic:serve:prod":"NODE_ENV=prod ionic-app-scripts serve"
   },
   "dependencies":{
      "@angular/common":"4.0.0",
      "@angular/compiler":"4.0.0",
      "@angular/compiler-cli":"4.0.0",
      "@angular/core":"4.0.0",
      "@angular/forms":"4.0.0",
      "@angular/http":"4.0.0",
      "@angular/platform-browser":"4.0.0",
      "@angular/platform-browser-dynamic":"4.0.0",
      "@ionic-native/camera":"^4.3.0",
      "@ionic-native/core":"^4.3.0",
      "@ionic-native/device":"^4.3.0",
      "@ionic-native/diagnostic":"^4.3.0",
      "@ionic-native/onesignal":"^4.3.0",
      "@ionic-native/splash-screen":"^4.3.0",
      "@ionic-native/status-bar":"^4.3.0",
      "@ionic/cloud-angular":"^0.12.0",
      "@ionic/storage":"^2.0.1",
      "@types/pouchdb":"5.4.28",
      "bourbon":"^4.3.4",
      "cordova-android":"~5.1.1",
      "cordova-ios":"^4.4.0",
      "cordova-plugin-camera":"~2.3.1",
      "cordova-plugin-console":"~1.0.4",
      "cordova-plugin-device":"~1.1.3",
      "cordova-plugin-splashscreen":"~4.0.0",
      "cordova-plugin-statusbar":"~2.2.0",
      "cordova-plugin-whitelist":"~1.3.0",
      "cordova-sqlite-storage":"~2.0.1",
      "ionic-angular":"3.0.1",
      "ionic-plugin-keyboard":"~2.2.1",
      "ionicons":"3.0.0",
      "moment":"^2.17.1",
      "pouchdb":"^6.1.1",
      "rxjs":"5.1.1",
      "sw-toolbox":"3.4.0",
      "zone.js":"^0.8.4",
      "onesignal-cordova-plugin":"~2.2.1"
   },
   "devDependencies":{
      "@ionic/app-scripts":"1.3.0",
      "ionic":"3.12.0",
      "typescript":"~2.2.1"
   },
   "cordovaPlugins":[
      "cordova-plugin-device",
      "cordova-plugin-console",
      "cordova-plugin-whitelist",
      "cordova-plugin-splashscreen",
      "cordova-plugin-statusbar",
      "ionic-plugin-keyboard"
   ],
   "cordovaPlatforms":[
      {
         "platform":"ios",
         "version":"",
         "locator":"ios"
      },
      {
         "platform":"android",
         "version":"",
         "locator":"android"
      }
   ],
   "config":{
      "ionic_sass":"./config/sass.config.js",
      "ionic_webpack":"./webpack.config.js"
   },
   "cordova":{
      "platforms":[
         "android",
         "ios"
      ],
      "plugins":{
         "cordova-plugin-camera":{

         },
         "cordova-plugin-console":{

         },
         "cordova-plugin-device":{

         },
         "cordova-plugin-splashscreen":{

         },
         "cordova-plugin-statusbar":{

         },
         "cordova-plugin-whitelist":{

         },
         "cordova-sqlite-storage":{

         },
         "ionic-plugin-keyboard":{

         },
         "onesignal-cordova-plugin":{

         }
      }
   }
}
```

**Comment by jkasten2** [comment]
@abuechler The `handleNotificationOpened` callback should be firing when the app is cold started when tapping on a notification. There was an issue where the cold start case was not working on iOS 11 but this was fixed in version 2.2.2 of the [`onesignal-cordova-plugin`](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.2.2).
Also noted in these 2 issues.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/121
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/253

If you continue to see an issue you can try using the `onesignal-cordova-plugin` through `window["plugins"].OneSignal` to rule out `@ionic-native/onesignal`. If it is reproducible this way you can open an issue below.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues

**Comment by abuechler** [comment]
@jkasten2 

The problem with this approach is that this.dbService evaluates to null:

```
2017-10-19 21:22:50.718604+0200 SomeApp[733:223606] Error in Success callbackId: OneSignalPush908871472 : TypeError: null is not an object (evaluating 'this.dbService')
```
I changed above code to:

```
platform.ready().then(() => {
      ...
      if (this.platform.is('cordova')) {

        var notificationOpenedCallback = function(jsonData){
          this.dbService.addLogEntry(new LogEntry('do something when notification is openend'));
        }

        var notificationReceivedCallback = function(jsonData){
          this.dbService.addLogEntry(new LogEntry('do something when notification is received'));
        }
        window["plugins"].OneSignal.setLogLevel({logLevel: 4, visualLevel: 4});

        window["plugins"].OneSignal
        .startInit('your-onesignal-app-id')
        .handleNotificationOpened(notificationOpenedCallback)
        .handleNotificationReceived(notificationReceivedCallback)
        .endInit();

        }, (err) => { this.toastService.showToast(err); });
      } else {
        // skip push registration on desktop devices
        console.log('skipping device token registration since running on desktop device');
  
      }
    });
```

**Comment by jkasten2** [comment]
@abuechler The `this` in the context of the `notificationOpenedCallback` and `notificationReceivedCallback` isn't the object you are thinking it is.
I recommend checking out the blog post below that explains how `this` changes depending on your current scope in javascript.
http://javascriptissexy.com/understand-javascripts-this-with-clarity-and-master-it/

**Comment by abuechler** [comment]
@jkasten2 Thanks a lot for the help and pointers! I updated the code example in the comment...

**But** I still experience the exact same problem when ruling out @ionic-native/onesignal. I tested on iOS 11.0.3 with the upgraded version 2.2.2 of onesignal-cordova-plugin.

**Comment by abuechler** [comment]
We were able to figure it out. We've upgraded the onesignal-cordova-plugin, but after a while we've found out that the Podfile was still pointing to the old version. The resolution was to delete the plugins and platforms folders...
