### ISSUE TITLE
HTTP PATCH request

### ISSUE THREAD

**Issue by irundaia** [ionic-team/ionic-native#2052]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
The ionic-native/http plugin does not support the PATCH HTTP method. I think it would be trivial to add it though. Would you be open for a PR?

```typescript
  /**
   * Make a PATCH request
   * @param url {string} The url to send the request to
   * @param body {Object} The body of the request
   * @param headers {Object} The headers to set for this request
   * @returns {Promise<HTTPResponse>} returns a promise that resolve on success, and reject on failure
   */
  @Cordova()
  patch(url: string, body: any, headers: any): Promise<HTTPResponse> { return; }
```

**Comment by sykaeh** [comment]
This issue has been resolved, hasn't it?

**Comment by irundaia** [comment]
It seems like it has been. I’m closing thiis issue :) Thanks!
