### ISSUE TITLE
HTTP validateDomainName not supported anymore

### ISSUE THREAD

**Issue by silkimen** [ionic-team/ionic-native#2053]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

**Current behavior:**
The ionic-native/http plugin does provide "validateDomainName" method, but I've removed this method in the cordova plugin (v1.6.2+).

**Expected behavior:**
Just remove this method in ionic-native/http.

I'll provide you an PR.

**Comment by sykaeh** [comment]
This issue has been resolved, hasn't it?

**Comment by silkimen** [comment]
Yes, my PR was merged. Closing this one.
