### ISSUE TITLE
IonicNative not see Appodeal plugin on Android

### ISSUE THREAD

**Issue by mifkys** [ionic-team/ionic-native#2065]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

IonicNative not see Appodela plugin with next error on any Appodeal's method call:

> Native: tried calling Appodeal.setLogging, but the Appodeal plugin is not installed.
> pluginWarn @ vendor.js:59258
> checkAvailability @ vendor.js:78222
> callCordovaPlugin @ vendor.js:78303
> (anonymous) @ vendor.js:78332
> (anonymous) @ vendor.js:59236
> t @ polyfills.js:3
> tryNativePromise @ vendor.js:59235
> getPromise @ vendor.js:59243
> wrapPromise @ vendor.js:78315
> (anonymous) @ vendor.js:78469
> value @ vendor.js:119497
> (anonymous) @ main.js:183
> t.invoke @ polyfills.js:3
> onInvoke @ vendor.js:4509
> t.invoke @ polyfills.js:3
> r.run @ polyfills.js:3
> (anonymous) @ polyfills.js:3
> t.invokeTask @ polyfills.js:3
> onInvokeTask @ vendor.js:4500
> t.invokeTask @ polyfills.js:3
> r.runTask @ polyfills.js:3
> o @ polyfills.js:3
> e.invokeTask @ polyfills.js:3
> i.isUsingGlobalCallback.invoke @ polyfills.js:3
> n @ polyfills.js:2
> 12:38:59.760 vendor.js:59264 Install the Appodeal plugin: 'ionic cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git'
> 
> 

**Expected behavior:**

**Steps to reproduce:**

```
ionic start test
blank
ionic cordova platform add android
cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git
npm install --save @ionic-native/appodeal
ionic cordova run android --device
```

**Related code:**
insert next code in app.component.ts
```
    const appKey = '123';
    appodeal.initialize(appKey, appodeal.AD_TYPES.REWARDED_VIDEO);
    appodeal.show(appodeal.AD_TYPES.REWARDED_VIDEO);
    appodeal.setTesting(true);
    appodeal.setLogging(true);
```

**Other information:**

> @ionic/cli-utils  : 1.15.1
>     ionic (Ionic CLI) : 3.15.1
> 
> global packages:
> 
>     cordova (Cordova CLI) : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 3.0.1
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.7.1
> 
> System:
> 
>     Android SDK Tools : 26.0.2
>     Node              : v6.5.0
>     npm               : 3.10.3
>     OS                : Windows 10
> 
> Environment Variables:
> 
>     ANDROID_HOME : C:\dev\android-sdk
> 
> Misc:
> 
>     backend : legacy

**package.json info:**

```json
{
    "name": "test",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.4.3",
        "@angular/compiler": "4.4.3",
        "@angular/compiler-cli": "4.4.3",
        "@angular/core": "4.4.3",
        "@angular/forms": "4.4.3",
        "@angular/http": "4.4.3",
        "@angular/platform-browser": "4.4.3",
        "@angular/platform-browser-dynamic": "4.4.3",
        "@ionic-native/appodeal": "^4.3.2",
        "@ionic-native/core": "4.3.2",
        "@ionic-native/splash-screen": "4.3.2",
        "@ionic-native/status-bar": "4.3.2",
        "@ionic/storage": "2.0.1",
        "com.appodeal.plugin": "git+https://github.com/appodeal/appodeal-cordova-plugin.git",
        "cordova-android": "^6.2.3",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-ionic-webview": "^1.1.11",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.3",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.7.1",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.3",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.0.1",
        "typescript": "2.3.4"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-device": {},
            "cordova-plugin-ionic-webview": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "com.appodeal.plugin": {},
            "cordova-plugin-statusbar": {}
        },
        "platforms": [
            "android"
        ]
    }
}
```

**Comment by mifkys** [comment]
Any news about this issue? This is problem of IonicNative or Appodeal plugin?

**Comment by oguzhansevim** [comment]
Any solution?

**Comment by lahed** [comment]
Solution?? pls

**Comment by mifkys** [comment]
Solution is not use IonicNative for Appodeal. Declare Appodeal like `declare let Appodeal: any;` then use official documentation

**Comment by ArunadeviR** [comment]
Hi Please provide a solution for installation of appodeal with ionic, i am facing issues with that. Not able to build properly
