### ISSUE TITLE
Native Image Cache

### ISSUE THREAD

**Issue by pavini** [ionic-team/ionic-native#2066]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

**Expected behavior:**
Please, add a native image cache. It will be amazing for users experence

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**package.json info:**

```json
insert the content here
```

**Comment by danielsogl** [comment]
If you can link me a plugin I will add it
