### ISSUE TITLE
Ionic natife file not working on browser

### ISSUE THREAD

**Issue by jondediego** [ionic-team/ionic-native#2068]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

**Current behavior:**
When I try to write a file using writeFile function, it is created properly on Android device, but when running on Chrome browser a security error is thrown:"It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources.". This error is thrown despite I launch Chrome using --allow-file-access-from-files flag. If I use cordova-plugin-file directly, it works properly on Chrome browser.

**Expected behavior:**
Not error thrwon and file written.

**Steps to reproduce:**
create a simple app that imports ionic-native and writes a file. Run it on Chrome browser.

**Related code:**
 try{
       await this.file.writeFile(this.file.dataDirectory, "test.txt", "some text here");
   
    } catch(err) {
      console.log('Error: '+ err+ "err message: "+err.message);
    }
```

**Comment by Shane98c** [comment]
Same issue being discussed (or was...) over here: https://github.com/ionic-team/ionic-native/issues/1379

**Comment by danielsogl** [comment]
duplicate
