### ISSUE TITLE
iPhone X - iOS Ionic Pro App & Ionic Dev App Crash on open

### ISSUE THREAD

**Issue by nolanmclark** [ionic-team/ionic-native#2102]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
App shows the ionic splash screen for ~1 second and crashes. The app remains open in the background, but on re-entry from app switcher it immediately kicks back out.

**Expected behavior:**
App should open completely.

**Steps to reproduce:**
Both apps worked flawlessly on my iPhone 7+. After switching to iPhone X, the apps immediately crash on open.

Currently on iOS 11.2 Beta on the iPhone X.

**Other information:**
Only able to find a handful of users with the same issue. 

**package.json info:**

{
    "name": "project",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "^4.4.3",
        "@angular/compiler": "^4.4.3",
        "@angular/compiler-cli": "^4.4.3",
        "@angular/core": "^4.4.3",
        "@angular/forms": "^4.4.3",
        "@angular/http": "^4.4.3",
        "@angular/platform-browser": "^4.4.3",
        "@angular/platform-browser-dynamic": "^4.4.3",
        "@auth0/cordova": "^0.2.0",
        "@firebase/webchannel-wrapper": "0.2.1",
        "@ionic-native/camera": "^4.2.1",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/facebook": "^4.2.1",
        "@ionic-native/file": "^4.2.1",
        "@ionic-native/file-chooser": "^4.2.1",
        "@ionic-native/file-path": "^4.2.1",
        "@ionic-native/geolocation": "^4.2.1",
        "@ionic-native/keyboard": "^4.2.1",
        "@ionic-native/native-page-transitions": "^4.3.2",
        "@ionic-native/safari-view-controller": "^4.2.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "^3.12.1",
        "@ionic/storage": "2.0.1",
        "@mapbox/mapbox-gl-directions": "^3.1.2",
        "angularfire2": "^5.0.0-rc.0",
        "animate.css": "^3.5.2",
        "auth0-js": "^8.9.3",
        "cities.json": "^1.1.0",
        "com.telerik.plugins.nativepagetransitions": "^0.6.5",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.5.0",
        "cordova-plugin-add-swift-support": "^1.7.0",
        "cordova-plugin-browsertab": "^0.2.0",
        "cordova-plugin-buildinfo": "^1.1.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-crosswalk-webview": "^2.3.0",
        "cordova-plugin-customurlscheme": "^4.3.0",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-facebook4": "^1.9.1",
        "cordova-plugin-file": "^4.3.3",
        "cordova-plugin-filechooser": "^1.0.1",
        "cordova-plugin-filepath": "^1.0.2",
        "cordova-plugin-inappbrowser": "^1.7.1",
        "cordova-plugin-ionic": "^1.1.8",
        "cordova-plugin-ionic-keyboard": "^1.0.5",
        "cordova-plugin-ionic-webview": "^1.1.16",
        "cordova-plugin-safariviewcontroller": "^1.4.7",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
        "cordova-plugin-whitelist": "^1.3.1",
        "cordova-universal-links-plugin": "^1.2.1",
        "firebase": "^4.6.0",
        "ionic-angular": "^3.8.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionic-tags-input": "0.0.6",
        "ionic2-rating": "^1.2.2",
        "ionicons": "3.0.0",
        "jshint": "^2.9.5",
        "node-sass": "^4.5.3",
        "promise-polyfill": "6.0.2",
        "rxjs": "^5.4.3",
        "sw-toolbox": "3.6.0",
        "typescript": "^2.4.0",
        "zone.js": "^0.8.17"
    },
    "devDependencies": {
        "@ionic/app-scripts": "^3.0.1",
        "ionic": "3.17.0",
        "mapbox-gl": "^0.40.1"
    },
    "description": "",
    "cordova": {
        "plugins": {
            "cordova-plugin-safariviewcontroller": {},
            "cordova-plugin-customurlscheme": {
                "URL_SCHEME": "",
                "ANDROID_SCHEME": "",
                "ANDROID_HOST": "",
                "ANDROID_PATHPREFIX": ""
            },
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-facebook4": {
                "APP_ID": "1999497083599156",
                "APP_NAME": ""
            },
            "cordova-plugin-buildinfo": {},
            "cordova-universal-links-plugin": {},
            "cordova-plugin-browsertab": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-ionic": {
                "APP_ID": "",
                "CHANNEL_NAME": "Development",
                "UPDATE_METHOD": "background",
                "UPDATE_API": "https://api.ionicjs.com",
                "MAX_STORE": "2"
            },
            "cordova-plugin-camera": {
                "CAMERA_USAGE_DESCRIPTION": " ",
                "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
            },
            "cordova-plugin-filechooser": {},
            "cordova-plugin-filepath": {},
            "cordova-plugin-file": {},
            "cordova-plugin-ionic-keyboard": {},
            "com.telerik.plugins.nativepagetransitions": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-ionic-webview": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-crosswalk-webview": {
                "XWALK_VERSION": "23+",
                "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
                "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
                "XWALK_MODE": "embedded",
                "XWALK_MULTIPLEAPK": "true"
            }
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}

**Comment by mlynch** [comment]
Hi @nolanmclark, this doesn't appear to be related to `ionic-native`. I'd suggest removing each one of those plugins and trying to boot the app. If you do find one causing the crash, we'd love to know which one!

Going to close as it pertains to ionic-native.
