### ISSUE TITLE
Error: Metadata version mismatch @ionic-native/http/index.d.ts , found version 4, expected 3

### ISSUE THREAD

**Issue by Ladeiras** [ionic-team/ionic-native#2106]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[    ] feature request
[    ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I was waiting for [this](https://github.com/ionic-team/ionic-native/pull/2054/commits/8a8db7892f6950ee9662011d0312c2f91f6bf477) PR so I could use http.patch with the _ionic-native/http_. Today was merged in version 4.4.0 and I've updated the package, but when building with _--aot_ flag I get this error on ngc:
![image](https://user-images.githubusercontent.com/5716992/32667791-a39336d2-c633-11e7-9afd-fdff89750383.png)

**Expected behavior:**
No errors

**Steps to reproduce:**
Any current build using a ionic-native 4.4.0 plugin with _--aot_ flag gives me this error

```bash
ionic cordova build android --aot
```
or
```bash
ionic cordova build android --prod
```

**Comment by pherris** [comment]
I resolved this by removing the `^` from my package.json for all of the `ionic-native` dependencies:

```
        "@ionic-native/app-version": "4.2.1",
        "@ionic-native/background-fetch": "4.2.1",
        "@ionic-native/badge": "4.0.1",
        "@ionic-native/contacts": "4.2.1",
        "@ionic-native/core": "4.2.1",
        "@ionic-native/date-picker": "4.2.1",
        "@ionic-native/deeplinks": "4.2.1",
        "@ionic-native/file": "4.2.1",
        "@ionic-native/geolocation": "4.2.1",
        "@ionic-native/keyboard": "4.2.1",
        "@ionic-native/local-notifications": "4.2.1",
        "@ionic-native/mixpanel": "4.2.1",
        "@ionic-native/native-geocoder": "4.2.1",
        "@ionic-native/network": "4.2.1",
        "@ionic-native/screen-orientation": "4.2.1",
        "@ionic-native/social-sharing": "4.2.1",
        "@ionic-native/speech-recognition": "4.1.0",
        "@ionic-native/splash-screen": "4.2.1",
        "@ionic-native/status-bar": "4.2.1",
```

There must have been some release from today that caused the issue - definitely was able to run the same command last night with no issues.

**Comment by Ladeiras** [comment]
Ya. I did end up installing the previous version (4.3.3) for the native plugins with no issues.

**Comment by ihadeed** [comment]
Sorry about that, I didn't realize that modules compiled with `@angular/compiler-cli@5.0.0` are not compatible with `@angular/*@4.x.x`. Please downgrade your Ionic Native dependencies to version `4.3.3` for now, or upgrade your Angular version. Hopefully we'll have a better solution in the next release.

**Comment by ihadeed** [comment]
Please upgrade your Ionic Native dependencies to `4.4.2`
