### ISSUE TITLE
Metadata version mismatch for model , node_modules/@ionic-native/in-app-browser/index.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by Vicky443** [ionic-team/ionic-native#2108]
****Issue while running " ionic cordova run  android --prod --device"  mode**** 

i have issue while run ionic in product mode , its working fine with ionic serve 

**version info in details** 
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0
    cordova (Cordova CLI) : 7.1.0
    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1
     Node  : v6.11.2
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0
   cordova (Cordova CLI) : 7.1.0
   @ionic/app-scripts : 3.0.0
   Cordova Platforms  : android 6.3.0 ios 4.5.2
   Ionic Framework    : ionic-angular 3.7.1

**Comment by Sampath-Lokuge** [comment]
Can you show your `package.json` file?

**Comment by sakthideveloper** [comment]
Hi Vicky,

Could you check your package.json file to make sure all angular core and sub package should in 5.0.0 like below ..?

   "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0"

**Comment by Vicky443** [comment]
here is below dependencies i'm using 

![screen shot 2017-11-11 at 8 56 18 pm](https://user-images.githubusercontent.com/3095955/32690814-cd55af46-c722-11e7-9959-1220ba1b94aa.png)

**Comment by Sampath-Lokuge** [comment]
I cannot see where you have installed the `native wrapper`? 

`npm install --save @ionic-native/in-app-browser`

**Comment by ihadeed** [comment]
Sorry about that, I didn't realize that modules compiled with `@angular/compiler-cli@5.0.0` are not compatible with `@angular/*@4.x.x`. Please downgrade your Ionic Native dependencies to version `4.3.3` for now, or upgrade your Angular version. Hopefully we'll have a better solution in the next release.

**Comment by ihadeed** [comment]
Please upgrade your Ionic Native dependencies to `4.4.2`
