### ISSUE TITLE
Please include action buttons in local notifications

### ISSUE THREAD

**Issue by vpotluri1217** [ionic-team/ionic-native#2109]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Right now you can't include action buttons in local notifications. 

**Expected behavior:**
Show actions button in local notifications

**Steps to reproduce:**
https://forum.ionicframework.com/t/local-notifications-with-multiple-actions-buttons/33430/2

**Related code:**
include feature similar to https://github.com/elizabethrego/cordova-plugin-local-notifications
```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by vnovakovits** [comment]
+1, we need action buttons in local notifications!

**Comment by alexmazza** [comment]
I added actions in index.ts in the plugin and it works.

```typescript
export interface ILocalNotification {
...
actions?: any[]
}```

And then just to test it:

```typescript
export class HomePage {

  constructor(public navCtrl: NavController, private localNotifications: LocalNotifications) {
    this.localNotifications.schedule({
      id: 1,
      text: 'Single ILocalNotification',
      actions: [
        { id: 'yes', title: 'Yes' },
        { id: 'no',  title: 'No' }
      ]
    });
    this.localNotifications.on('yes', ()=>{
      this.navCtrl.push(ListPage)
    })

  }

}```
It only works installing the app on a device, with the DevApp it doesn't work (and I lost all morning because of this.). I tested it on Android on a Galaxy S8+

**Comment by danielsogl** [comment]
I added the actions options

**Comment by FilipK23** [comment]
> I added actions in index.ts in the plugin and it works.
> 
> ```ts
> export interface ILocalNotification {
> ...
> actions?: any[]
> }
> ```
> 
> And then just to test it:
> 
> ```ts
> export class HomePage {
> 
>   constructor(public navCtrl: NavController, private localNotifications: LocalNotifications) {
>     this.localNotifications.schedule({
>       id: 1,
>       text: 'Single ILocalNotification',
>       actions: [
>         { id: 'yes', title: 'Yes' },
>         { id: 'no',  title: 'No' }
>       ]
>     });
>     this.localNotifications.on('yes', ()=>{
>       this.navCtrl.push(ListPage)
>     })
> 
>   }
> 
> }
> ```
> 
> It only works installing the app on a device, with the DevApp it doesn't work (and I lost all morning because of this.). I tested it on Android on a Galaxy S8+

I am testing it, but If I have closed app I get basic notification. I have to create prod apk and than install it? or I could install debug app? Thank you
