### ISSUE TITLE
Local Notifications. Please include in param - progressBar.

### ISSUE THREAD

**Issue by klochko7** [ionic-team/ionic-native#2111]
Hi all ! Could anyone include please in param - progressBar.  We could see progressBar in [https://github.com/katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) but not in Ionic native Local Notifications documentation.

**Comment by jbagaresgaray** [comment]
Any update on this issue??

**Comment by danielsogl** [comment]
I will add the new features together with releases 5.0.
