### ISSUE TITLE
Version 4.4.1 does not exists

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-native#2116]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
On trying to install latest version which does backward compatibility to ng4 in this way I get an error
`npm install @ionic-native/core@4.4.1 --save`

`No matching version found for @ionic-native/core@4.4.1`

Having a look on npm info there is no 4.4.1 as latest or versions

**Comment by swaheed2** [comment]
please update npm, its still at 2.9.0

**Comment by ihadeed** [comment]
Use 4.4.2.. Version 4.4.1 was unpublished.

**Comment by swaheed2** [comment]
the latest version is 2.9.0 on npm 

https://www.npmjs.com/package/ionic-native

**Comment by danielsogl** [comment]
@swaheed2 ionic-native != @ionic-native/core

**Comment by swaheed2** [comment]
ooh ok, my bad. Thanks.
