### ISSUE TITLE
When calling to file.readAsDataURL (or any other read) WITHOUT livereload the promise never resolves.

### ISSUE THREAD

**Issue by yosigolan** [ionic-team/ionic-native#2117]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When calling to file.readAsDataURL (or any other read) the promise never resolves. it happens only when running WITHOUT live reload. it happens when loading few images to the storage (to the applicationData directory) and then trying to load them and display them.

**Expected behavior:**
the promise should resolve or reject.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
ionic
```
cli packages: (C:\Users\SeeVoov-Developer\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.6.0
    npm  : 5.5.1
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by paulsouche** [comment]
Hi,

Same issue here !

I've noticed the problem is that [this](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/file/index.ts#L1129) is never called when [cordova FileReader](https://github.com/apache/cordova-plugin-file/blob/master/www/FileReader.js) is [patched by zone.js](https://github.com/angular/zone.js/blob/dcc285aab37bdd90b6d7133fc73045100861c61c/lib/browser/browser.ts#L64)

Sometimes (I can't find a way to reproduce each time) File plugin script is loaded before zone.js patch and it breaks something.

My workaround was to move cordova.js script after zone one and it seems to be working...

Hope it helps

Thanks anyway for the great job

**Comment by yosigolan** [comment]
Thank you @paulsouche ! i moved the cordova.js after vendor.js script (in the index.html) and it did solved it.
thank you very much!

**Comment by vzharkov** [comment]
I have the same problem when i use ReadAsText method from FileReader. `onloadend` event does not fired. Issue starts from update ionic up to 3.9.2 version.
Fix from @paulsouche works, but it is not a right way to solve this issue.

**Comment by paulsouche** [comment]
Hi @vzharkov ,

I think we should find a solution between cordova / Zone / file-plugin on [this thread](https://github.com/ionic-team/ionic2-app-base/issues/126)

**Comment by yosigolan** [comment]
@danielsogl why do you close this? is it fixed?

**Comment by franbueno** [comment]
We are on May and it works randomly. So it wasn't fixed. Thanks @paulsouche for your workaround.

**Comment by pistou** [comment]
Yep, definitly not fixed.

**Comment by lordgreg** [comment]
should be reopen.

**Comment by CarlosAyala** [comment]
Hi,
I had the same issue, i fixed it moving the cordova.js after vendor.js,
Thx!

**Comment by CarlosAyala** [comment]
@danielsogl
Hi, this needs to be reopen. Not fixed.

**Comment by CarlosAyala** [comment]
Update cordova-android to version 7.1.1 and zone.js to 0.8.26 to fix this issue in Ionic3.

**Comment by TaiJinYuan** [comment]
Thanks , @paulsouche and @CarlosAyala 
It works like a charm! 
Moved the **cordova.js** after the **vendor.js** in **index.html** file

**Comment by wilguevara** [comment]
Thank you @paulsouche ! i moved the cordova.js after vendor.js script (in the index.html) and it did solved it for me too.

**Comment by kispi** [comment]
You don't need to suffer if you just don't use Ionic or you will suffer from bunch of nightmares forever

**Comment by roiko** [comment]
Thank you @paulsouche , you saved me from an afternoon of pain!

**Comment by shanmukss66** [comment]
> Thank you @paulsouche ! i moved the cordova.js after vendor.js script (in the index.html) and it did solved it.
> thank you very much!



> Hi,
> 
> Same issue here !
> 
> I've noticed the problem is that [this](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/file/index.ts#L1129) is never called back when [cordova FileReader](https://github.com/apache/cordova-plugin-file/blob/master/www/FileReader.js) is [patched by zone.js](https://github.com/angular/zone.js/blob/dcc285aab37bdd90b6d7133fc73045100861c61c/lib/browser/browser.ts#L64)
> 
> Sometimes (I can't find a way to reproduce each time) File plugin script is loaded before zone.js patch and it breaks something.
> 
> My workaround was to move cordova.js script after zone one and it seems to be working...
> 
> Hope it helps
> 
> Thanks anyway for the great job
> 
> EDIT
> 
> seems to be same problem as #1174 and [ionic-team/ionic-native#505](https://github.com/ionic-team/ionic-native/issues/505) discussion is open here [ionic-team/ionic2-app-base#126](https://github.com/ionic-team/ionic2-app-base/issues/126)
> 
> So maybe it can be closed and we'll continue on it

im using ionic ver 5 here there is no cordova.js or vendor.js what should i do? please help me

**Comment by julian-bruening-wiadok** [comment]
This seems to still be an issue. Is there a workaround?
Filesytem from Capacitor is working, but I dont know how to use it with the Video Capture Plus Plugin.

**Comment by igormieski27** [comment]
> > Thank you @paulsouche ! i moved the cordova.js after vendor.js script (in the index.html) and it did solved it.
> > thank you very much!
> 
> > Hi,
> > Same issue here !
> > I've noticed the problem is that [this](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/file/index.ts#L1129) is never called back when [cordova FileReader](https://github.com/apache/cordova-plugin-file/blob/master/www/FileReader.js) is [patched by zone.js](https://github.com/angular/zone.js/blob/dcc285aab37bdd90b6d7133fc73045100861c61c/lib/browser/browser.ts#L64)
> > Sometimes (I can't find a way to reproduce each time) File plugin script is loaded before zone.js patch and it breaks something.
> > My workaround was to move cordova.js script after zone one and it seems to be working...
> > Hope it helps
> > Thanks anyway for the great job
> > EDIT
> > seems to be same problem as #1174 and [ionic-team/ionic-native#505](https://github.com/ionic-team/ionic-native/issues/505) discussion is open here [ionic-team/ionic2-app-base#126](https://github.com/ionic-team/ionic2-app-base/issues/126)
> > So maybe it can be closed and we'll continue on it
> 
> im using ionic ver 5 here there is no cordova.js or vendor.js what should i do? please help me


I'm going through the same problem, do you happen to find a solution?
