### ISSUE TITLE
Pro: Reversed return types for "check" and "extract"

### ISSUE THREAD

**Issue by DavidTalamona** [ionic-team/ionic-native#2127]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
- `pro.deploy.check` returns Observable instead of Promise.
- `pro.deploy.extract` causes "pluginObj.constructor.getPluginName is not a function" error because it's not an Observable, as it should be.

**Expected behavior:**
Returned values should be as documented.

**Steps to reproduce:**
Just implement the live update process with the native plugin wrapper.

**Related code:** (https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/pro/index.ts)

```
/**
   * Check a channel for an available update
   * @return {Promise<string>} Resolves with 'true' or 'false', or rejects with an error.
   */
  @CordovaInstance({
    observable: true
  })
  check(): Promise<string> { return; }

  /**
   * Download an available version
   * @return {Observable<any>} Updates with percent completion, or errors with a message.
   */
  @CordovaInstance({
    observable: true
  })
  download(): Observable<any> { return; }

  /**
   * Unzip the latest downloaded version
   * @return {Observable<any>} Updates with percent completion, or errors with a message.
   */
  @CordovaInstance()
extract(): Observable<any> { return; }
```
should be:
```
/**
   * Check a channel for an available update
   * @return {Promise<string>} Resolves with 'true' or 'false', or rejects with an error.
   */
  @CordovaInstance()
  check(): Promise<string> { return; }

  /**
   * Download an available version
   * @return {Observable<any>} Updates with percent completion, or errors with a message.
   */
  @CordovaInstance({
    observable: true
  })
  download(): Observable<any> { return; }

  /**
   * Unzip the latest downloaded version
   * @return {Observable<any>} Updates with percent completion, or errors with a message.
   */
  @CordovaInstance({
    observable: true
  })
extract(): Observable<any> { return; }
```

**Note the `{observable: true}` that I moved from `check` to `extract`!**

**Comment by DavidTalamona** [comment]
The error assigned to it is `Error: Uncaught (in promise): TypeError: _this.pro.deploy.check(...).then is not a function`.
Just for others to find this issue and not open another one.

**Comment by DavidTalamona** [comment]
Everyone looking for a solutoin / manual fix, see https://github.com/ionic-team/ionic-native/issues/2136#issuecomment-352209943

**Comment by timbru31** [comment]
Can we have a fix for this? Seems like Ionic (again) is advertising a half baked/unfinished/buggy product called Ionic Pro 🙄

Thanks a lot @DavidTalamona for the fix though!

**Comment by mlynch** [comment]
Hi all, can you try version 4.5.3 of [@ionic-native/pro](https://www.npmjs.com/package/@ionic-native/pro)? Both of these issues should be resolved.
