### ISSUE TITLE
Geolocation PositionError 3

### ISSUE THREAD

**Issue by jbelcastro** [ionic-team/ionic-native#2128]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When installing the geolocation plugin per these instructions: https://ionicframework.com/docs/native/geolocation/

and building on an ios simulator (iphone x ios11.1)

The error returned is a PositionError 3 (please note without using the timeout option as outlined below it would not return a response nor an error code).

This issue was resolved by adding the following to my ios plist:
<key>NSLocationWhenInUseUsageDescription</key>
<string>Your message goes here</string>

**Expected behavior:**
To return current GPS coords

**Steps to reproduce:**
Follow the steps outlined in https://ionicframework.com/docs/native/geolocation/

Versions:
cordova-plugin-geolocation 3.0.0
ionic 3.18.0
Xcode 9.1

**Related code:**

The following code was used when trouble shooting the install. The timeout was attempted based on a recommendation and was necessary for the PositionError to display - otherwise it returned nothing.
```
this.geolocation.getCurrentPosition({timeout:50000}).then((resp) => {
            console.log(resp.coords.latitude);
            console.log(resp.coords.longitude);
        }).catch((error) => {
            console.log('Error getting location', error);
        });
```

**Other information:**
This issue was resolved on my end by adding the following key to my ios .plist file:
<key>NSLocationWhenInUseUsageDescription</key>
<string>Your message goes here</string>

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/josh/Ionic/peekya/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.3.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v6.10.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/josh/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by Spanchal21** [comment]
this.geolocation.getCurrentPosition().then((resp) => {
								this.lattitude = resp.coords.latitude;
								this.longitude = resp.coords.longitude;
							}).catch((error) => {
					 			console.log('Error getting location', error);
					 		});

please try this one.
it's works for me.
also check your device location setting.

**Comment by kapilSoni101** [comment]
@Spanchal21 : I  have used same code but it is not working if our GPS is off then enable the GPS again now getCurrentPosition is not triggered ?
