### ISSUE TITLE
after ionic add ionic cordova plugin add cordova-plugin-file-transfer form ionic official site. not making build  getting some error. install everything is official wesite pls help me 

### ISSUE THREAD

**Issue by dkandari** [ionic-team/ionic-native#2132]
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  C:\Users\Parangat_PT_W3\Desktop\Ionic\DF EVENTS\DFEventFinal\platforms\android\app\src\debug\google-services.json
  C:\Users\Parangat_PT_W3\Desktop\Ionic\DF EVENTS\DFEventFinal\platforms\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
(node:6916) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  C:\Users\Parangat_PT_W3\Desktop\Ionic\DF EVENTS\DFEventFinal\platforms\android\app\src\debug\google-services.json
  C:\Users\Parangat_PT_W3\Desktop\Ionic\DF EVENTS\DFEventFinal\platforms\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
(node:6916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chiragebiztrait4** [comment]
Hey @dkandari,
have you find any solution??
I have same issue

my ionic info output:
`
cli packages: (C:\Users\admin\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.2
    npm               : 3.10.10
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\admin\AppData\Local\Android\sdk

Misc:

    backend : legacy`

**Comment by alexvibealex** [comment]
anyone any solution please ???

**Comment by subham18meme** [comment]
same issue here after that change "transfer" to "file-transfer"

**Comment by adigeleon** [comment]
same error here i found something in this [https://github.com/Microsoft/cordova-plugin-code-push/issues/322](url) 
<plugin name="cordova-plugin-file-transfer" spec="~1.6.1"/>  someone said it works but when i build project for android it changed to <plugin name="cordova-plugin-file-transfer" spec="1.7.0"/>

**Comment by pyummm** [comment]
no solutions yet ?

**Comment by subham18meme** [comment]
first of all remove the compat plugin by using "ionic cordova plugin remove cordova-plugin-compat --force" 
then remove the platform "ionic cordova platform remove cordova-platform-android"
then use "ionic cordova platform update android@6.3.0"
cause below this android version those mentioned plugins are deprecated and another thing after removing the platform delete the plugin folder from your project root then update the android version.
Another impotent thing File and FileTransfer version 4.5.0 is stable so try to use this version
