### ISSUE TITLE
stop() method on text to speech does not work

### ISSUE THREAD

**Issue by epicfaace** [ionic-team/ionic-native#2137]
**I'm submitting a ...**
[x] bug report

**Current behavior:**
When I try to run the stop() method on text to speech, it is not working. (Although it is speaking properly).

It gives me these errors in the Chrome developer console:

.../node_modules/@ionic-native/core/util.js:49 Native: tried calling Text To Speech.stop, but the Text To Speech plugin is not installed.
pluginWarn @.../node_modules/@ionic-native/core/util.js:49
C:/Users/arama/git/Tycho/node_modules/@ionic-native/core/util.js:55 Install the Text To Speech plugin: 'ionic cordova plugin add cordova-plugin-tts'

**Comment by kudchikarsk** [comment]
stop()
  {
    this.tts.speak("").then((value)=>{
      this.playing=false;
    });
  }

you can use this it works
