### ISSUE TITLE
FTP Plugin Success callback executed once

### ISSUE THREAD

**Issue by centos94** [ionic-team/ionic-native#2147]
**I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Tested only on Android Devices.
Success callback is executed once. Never reach value 1 but the file is uploaded.

**Expected behavior:**
Multiple calls that allow us to know when the upload/download as finished like the documentation says.

> Returns a promise. It will be triggered many times according the file’s size. The arg 0, 0.1xx, 0.2xx … 1 means the upload percent. When it reach 1, means success.

**Steps to reproduce:**
I had simply add the FTP plugin following the documentation instructions in [here](https://ionicframework.com/docs/native/ftp/). 

**Related code:**

```
    this.fTP.upload(localFile, remoteFile).then(
      (uploadPercentage) => {
        console.log(uploadPercentage);
      },
      (error)=>{
        console.log(error);
      }
    );
```

**Other information:**
I found others with this problem and seems like it's a problem related to ionic native wrapper.
https://github.com/xfally/cordova-plugin-ftp/issues/21
https://forum.ionicframework.com/t/file-download-using-ftp/105376

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.0
    ios-sim    : 5.0.11
    Node       : v6.10.3
    npm        : 3.10.10
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : legacy
```

**Comment by poldiwa** [comment]
I just made a PR, I'm a newbie so I really don't know what to do next. But you could try it, by cloning the repo. then build the ftp plugin and copy paste the dist files of the ftp plugin.
