### ISSUE TITLE
Missing new methods background geolocation

### ISSUE THREAD

**Issue by mbakker96** [ionic-team/ionic-native#2158]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently the ionic native plugin make use of the older version of background geolocation. In the newer version there are new methods like `checkStatus()` and other. Users get a method not found error when they want to implement these new methods.

**Todo**
[ ] Update documentation
[ ] Update cordova plugin

**Comment by guillermogfer** [comment]
And also there is no way to access to the 'activity' event (or is it?), there is no onActivity() like the onStationary()

**Comment by vptcnt** [comment]
+1
