### ISSUE TITLE
Help us help you please!

### ISSUE THREAD

**Issue by Remco75** [ionic-team/ionic-native#2159]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am (and lot's of others) submitting issues to this repo. Except some very rare cases, no contributer or member reacts or responds, even if solutions / PR are being made

**Expected behavior:**
Someone reacts and reviews our code, helping us to help you and keep this code updated

**Steps to reproduce:**
File an issue, resolve it, comment back, fork and then wait for weeks and weeks

Sorry for taking this approach, but I have multiple issues open with multiple users reacting, I have created solutions, trying to help out. But this is really demotivating. So I just wanna ask: 
can we help out? what needs to be done to get things moving on this repo?
greetz, remco

**Comment by Jahrenski** [comment]
+1 Yes indeed. It feels somehow abandoned.
Documentation has outdated parts and won't explain basic things like why should I use ionic's background location instead of the Mauron85's plugin directly and other stuff.

**Comment by janpio** [comment]
As an onlooker:

- Most PRs are unreviewed. Help the maintainers by checking the code and content of other PRs (of other users) and test the changes locally, comment if you successfully used it in your app.
- Add links to the code/source of the plugin if you make changes to the Ionic Native wrapper where one can see that you are using the correct methods
- If there is a list of PRs you are sure are good to merge, create an issue where you list them. Mention if code was reviewed, locally tested, if the changes are documented with link to the plugin source - this will make it much easier for a maintainer to go through all of them.

**Comment by Remco75** [comment]
@janpio Cool thnx, wherever I can I help out. This is a very broad repo, so only a few now about a subject (the maintainers prob have the most knowledge!)

Problem is not that the community is not reacting: They do, and they help each other out. 
Once there is some more reaction from the maintainers I (and others) will be prepared to contribute / get involved even more. But for now it really seems a waste of my time

**Comment by janpio** [comment]
Looking at the closed PRs and issues it was ~3 weeks ago that a maintainer did a load of work. My guess is they are currently working on something else (different project, new stuff) and will come back to this repo later. No sign at all that this is actually abandoned or anything.

**Comment by Remco75** [comment]
hehe, I think we will just have to agree to disagree here. I have issues open for months, created a fork for a dependency that many user now use, I have asked in my issues many times if there was a maintainer who would step in. Other issues are confirmed by other users, again with the same result. 

And just look at the comments in the issue que: it's pretty hard to even find a contributer reacting / helping out, let alone a member.

It is just not maintained. (btw: I really appreciate the effort you put in here!) At least someone is reacting :-)

**Comment by janpio** [comment]
And page 1 is also reviewed/commented. Let's see what happens.

**Comment by mlynch** [comment]
The project isn't abandoned at all, it's used in every single default Ionic app. We're incredibly busy right now and we don't spend all of our time on ionic-native. A PR being submitted is incredibly helpful for the community, and we very much appreciate it, but we never guarantee that we'll merge them. 

We would love to find additional maintainers to focus on the project. If that interests you, please let me know and we can talk about getting you on the repo and our long term plans.

**Comment by darthdie** [comment]
@mlynch I'd be glad to be a maintainer to help out.

**Comment by joshbabb** [comment]
Ionic Native is a core piece of Ionic.  If you need additional hands, just ask.  I can (and try to) help when I encounter an issue in the wild, anyways.

**Comment by mlynch** [comment]
Thanks @darthdie and @joshbabb. I think I got an email from one of you but could you two email me again so we can chat privately about next steps? max@ionicframework.com
