### ISSUE TITLE
Diagnostics: method missing: getRemoteNotificationsAuthorizationStatus() 

### ISSUE THREAD

**Issue by jQrgen** [ionic-team/ionic-native#2164]
The method getRemoteNotificationsAuthorizationStatus() is listed [here](https://github.com/dpa99c/cordova-diagnostic-plugin#getlocationauthorizationstatus) for the cordova diagnostics plugin.

The method getRemoteNotificationsAuthorizationStatus() is not listed in the ionic native docs [here](https://ionicframework.com/docs/native/diagnostic/)

**Comment by cyptus** [comment]
why is this closed? the method is still missing.

**Comment by fermedina** [comment]
Any reason to close the issue?

**Comment by cyptus** [comment]
@danielsogl this should be reopened.
