### ISSUE TITLE
Make document viewer available in view app

### ISSUE THREAD

**Issue by Lazarus9000** [ionic-team/ionic-native#2169]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

Document viewer is not available in the view app, which is an issue for my testing where the user needs to read pdf files. Could it be included in the view app?
https://ionicframework.com/docs/native/document-viewer/

**Comment by Remco75** [comment]
I don't think this can or will be solved by posting an issue here-> If there is a repo for the view-app-> post it there.
As this isn't an issue for this repo, I would recommend closing it
