### ISSUE TITLE
Firebase Analytics: setEnabled() not working

### ISSUE THREAD

**Issue by JaneDawson** [ionic-team/ionic-native#2173]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Using the Ionic Native wrapper `Ionic Native Firebase Analytics`, the `setEnabled(enabled)` method is not working. Calling `setEnabled(true)` or `setEnabled(false)` doesn't return either a Promise nor an Error, but is running infinitely.

Using the plugin directly, without the Ionic Native wrapper works fine.

**Expected behavior:**
Wrapper works like the cordova plugin.

**Steps to reproduce:**
/

**Related code:**
Not working:
```
@Injectable()
export class AnalyticsService {

  constructor(private firebaseAnalytics: FirebaseAnalytics) {
  }

  setEnabled(bool){
    return this.firebaseAnalytics.setEnabled(bool);
  }
```

Working:
```
declare var cordova;

@Injectable()
export class AnalyticsService {

  constructor(private firebaseAnalytics: FirebaseAnalytics) {
  }

  setEnabled(bool){
    return cordova.plugins.firebase.analytics.setEnabled(bool);
  }
```

**Other information:**
```
"@ionic-native/firebase-analytics": "^4.4.2"
"cordova-plugin-firebase-analytics": "^0.12.1"
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    npm               : 5.5.1
    OS                : Windows 10

Misc:

    backend : legacy
```

**Comment by arsewizz** [comment]
same problem here ? hoh did you work with the plugin ? without ionic-native

**Comment by JaneDawson** [comment]
@arsewizz: In a provider this may look like this:

```
import { Injectable } from '@angular/core';
import { FirebaseAnalytics } from '@ionic-native/firebase-analytics';

declare var cordova;

@Injectable()
export class AnalyticsService {

  constructor(private firebaseAnalytics: FirebaseAnalytics) {
  }

  setEnabled(bool){
    return cordova.plugins.firebase.analytics.setEnabled(bool);
  }
```
Hope this helps.

**Comment by arsewizz** [comment]
how to track view ?

**Comment by arsewizz** [comment]
cordova is not defined, same code like yours

**Comment by arsewizz** [comment]
i'll try it on the phone later, i'm on browser. sorry

**Comment by phonic** [comment]
take a look here, the ionic native wrapper does not return any callback. Use the Plugin without ionic-native:
