### ISSUE TITLE
[BLE] startScanWithOptions([], {reportDuplicates: true}) not emitting duplicates

### ISSUE THREAD

**Issue by scalpel4k** [ionic-team/ionic-native#2181]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
when subscribing to the observable it only fires once for each discovered device

**Expected behavior:**
according to the options multiple adverts should be forwarded

**Steps to reproduce:**
this.dataSource$ = this.ble.startScanWithOptions([], {reportDuplicates: true});

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.1-dev (cordova-lib@7.1.0)

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : Warning: using prerelease version 7.1.1-dev (cordova-lib@7.1.0)  android 6.3.0 browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.2.0
    npm               : 5.5.1
    OS                : Linux 4.14

Environment Variables:

    ANDROID_HOME : /usr/local/share/android-sdk

Misc:

    backend : pro
```

**Comment by Remco75** [comment]
In order to help you out: 
please describe 
- what native plugin you are using
- some context (with code) on what you want to achieve
- why you are expecting duplicates
