### ISSUE TITLE
ENCODING_ERR on Ionic File after updated to iOS 11.2

### ISSUE THREAD

**Issue by sss2sssss** [ionic-team/ionic-native#2185]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
After passed the file url from Camera to File to resolve local file system url after normalize URL from camera, it keep displaying ENCODING_ERR error.

**Expected behavior:**
It should able to resolve the file system url and then convert to blob like what it does on Android and before iOS 11.2

**Steps to reproduce:**
1) If have any iOS device, just update to iOS 11.2
2) Construct simple apps to capture a photo and convert it to blob
3) The ENCODING_ERR error will be caught once it reach resolveLocalFileSystem function

**Related code:**
```
    this.camera.getPicture(options).then((imageData) => {
      let imageURI = normalizeURL(imageData);
      this.onResolvePath(imageURI, mainCategoryIndex, expenditureIndex);
    }, (err) => {
      if(err.message.toUpperCase() != "CLOSE"){
        this.notificationService.presentToast(err.message);
      }
    });
```
At here I already did normalize the Url.

But Once it enter here:
```
    console.log(url);
    this.file.resolveLocalFilesystemUrl(url).then(res=>(<FileEntry>res).file(file=>{
```
It straight jump to catch and show ENCODING_ERR message, this is never happened before I updated to iOS 11.2 on the iPad Pro 

**Other information:**
This error never occur before I update to iOS 11.2 and as well as Android device.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
cli packages:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v6.11.3
    npm        : 3.10.10
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by sss2sssss** [comment]
After story:
OK somehow I did found that at iOS 11.2, the File API doesn't resolve the url come from normalizeURL from ionic-angular instead, but it can resolve the url direct come from the camera
Also I'm not sure it always like this or it change behaviour in iOS 11.2, the normalizeURL convert the file:// to http://localhost:8080 instead, make the file api can't resolve the path after using that normalizeURL.

**Comment by ashotnew97** [comment]
The same problem on iOS 11.4. I don't use normalizeURL I give direct path from camera or gallery and got {code: 5, message: "ENCODING_ERR"} error
