### ISSUE TITLE
Firebase Analytics: no callbacks but works

### ISSUE THREAD

**Issue by phonic** [ionic-team/ionic-native#2192]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
The ionic native wrapper 

**Expected behavior:**
ionic native wrapper sends no callbacks, but the plugin works wihtout ionic-native as expected

**Steps to reproduce:**
         
Just run the cordova firebase plugin with the ionic native wrapper, in result you are getting no callbacks, app hangs if you await the results. Error callbacks are also not provided. However, values are passed correctly  and can be found in firebase analytics!

**Related code:**
_Works:_

```
cordova.plugins.firebase.analytics.logEvent("MyClickEvent", { Action: "test" })
            .then((res) => { alert(res) })
            .catch((err) => { alert(err) })
```

_Does not work:_

```
this.firebaseAnalytics.logEvent("MyClickEvent", { Action: "test" })
            .then((res) => { alert(res) })
            .catch((err) => { alert(err) })
```

You get no promise callback

_just like_ 

`await this.firebaseAnalytics.logEvent("MyClickEvent", { Action: "test" })`

**Ionic info:**

cli packages:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.2
    npm               : 3.10.7
    OS                : Windows 10

**Comment by musou1500** [comment]
I got the same problem.
cause of the problem is here.
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-analytics/index.ts#L46

`sync` option should be used for all methods in this case.
```typescript
  @Cordova({ sync: true })
  logEvent(name: string, params: any): Promise<any> { return; }
```
