### ISSUE TITLE
NFC for IOS crashes the application after a tap is registered

### ISSUE THREAD

**Issue by Jackthomsonn** [ionic-team/ionic-native#2193]
**I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

When using the NFC functionality of the Ionic Native library for IOS, the app crashes after a tap has been registered using the beginSession method which has just been introduced to the Ionic Native NFC library.

**Expected behavior:**

When a tap is registered the application should not just crash, it should throw some error back so we understand what steps to take to fix the issue

**Steps to reproduce:**

* Make sure you have an IOS device
* Create a simple ionic boilerplate setup and import the NFC and ndef modules

In your app place this code:

```
this.nfc.beginSession().subscribe(() => {
  this.nfc.addNdefListener((data) => {
    console.log(data) // You will not see this, at this point the app will crash
  })
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.9.1
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by fedegarlo** [comment]
I have the same problem. Any progress on this issue?

**Comment by Devleaf-IT** [comment]
@fedegarlo @Jackthomsonn 
The problem is with the old way cordova used to speak to the iDevices. Prior to iOS 10/11 I believe, the UIWebView was used to display the app. In the newer version WKWebview is used allowing more modern features to be enabled. The NFC plugin tried to deal with UIWebview when in actual fact your app is using WKWebview. A pull request & merge was submitted to the plugin github the other day (V0.7.2) which is fully compatible still with the ionic native wrapper, however the NPM link hasn't been updated yet, so you'll have to wait for the version to be updated or download the zip from the github page and manually add it to your plugins folder.

**Comment by jamesanglin** [comment]
@Devleaf-IT , how do we get the NPM link updated?

**Comment by Devleaf-IT** [comment]
Not to sure, assuming the repo creator has to do it. I can make a sub branch and a quick NPM link for the time being, but i'm hoping the creator will update it soon enough. If it's not done by the Wednesday this week i'll make a new one myself for temporary use. For now use my instructions above to get it working.

**Comment by jamesanglin** [comment]
@Devleaf-IT , makes sense. I also added a comment to the recent pull request on the phonegap-nfc repo.

**Comment by don** [comment]
Version 0.7.2 of [phonegap-nfc](https://github.com/chariotsolutions/phonegap-nfc) supports WKWebView. I'm not sure how Ionic installs this but you should be able to use Cordova to manually uninstall and reinstall the new version.

    cordova plugin rm phonegap-nfc 
    cordova plugin add phonegap-nfc@0.7.2

**Comment by don** [comment]
The correct versions are published to NPM so this should work now.

**Comment by rayron** [comment]
Hi guys, does anyone know how to invoke the invalidateSession in ionic-native nfc?
I have my ionic app scanning nfc tags now but without the invalidateSession function, the iphone will not return control back to app so I can process it.
Any examples or solution would be excellent .
Thanks.

**Comment by don** [comment]
@rayron the iOS nfc.beginSession wrapper has problems and is deprecated in phonegap-nfc 1.1.0.

Use nfc.scanNdef as a replacement for iOS which returns a Promise. The NFCReaderSession is automatically invalidated when a tag is scanned, an error occurs, or it times out. If you need to programmatically invalidate the session, use nfc.cancelScan.
