### ISSUE TITLE
PushOption Android Not Working

### ISSUE THREAD

**Issue by raessafathulalim** [ionic-team/ionic-native#2194]
Please help me to solve this issue .
![image](https://user-images.githubusercontent.com/11817321/33922018-6c4599e6-dffa-11e7-856f-603846d10582.png)

**Comment by medi-y-sato** [comment]
You may re-install OLD version of phonegap-plugin-push plugin .

```sh
ionic cordova plugin remove phonegap-plugin-push
ionic cordova plugin add phonegap-plugin-push@1.10.5
```
