### ISSUE TITLE
Unable to Install the cordova-plugin-file in cordova-android :6.2.0

### ISSUE THREAD

**Issue by naumanahmad17** [ionic-team/ionic-native#2203]
I am installing the plugin using the following command

 `ionic cordova plugin add cordova-plugin-file`
which produced the following logs.

**> cordova plugin add cordova-plugin-file --save
√ Running command - done!
Installing "cordova-plugin-file" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.0, failed version requirement: >=6.3.0
Skipping 'cordova-plugin-file' for android
Adding cordova-plugin-file to package.json
Saved plugin info for "cordova-plugin-file" to config.xml**

but when used in app
calling any method on file
cause the following warning in chrome console.

`Native: tried accessing the File plugin but it's not installed.`
`vendor.js:58344 Install the File plugin: 'ionic cordova plugin add cordova-plugin-file`

following is the environment details

`cli packages: (C:\Users\Designbee\Documents\GitHub\cutomerApp\node_modules)`

    `@ionic/cli-utils  : 1.13.0`
   ` ionic (Ionic CLI) : 3.13.0`

`global packages:`

    `cordova (Cordova CLI) : not installed`

`local packages:

   ` @ionic/app-scripts : 3.1.5`
  `  Cordova Platforms  : android 6.2.0`
    `Ionic Framework    : ionic-angular 3.7.1`

`System:`

   ` Android SDK Tools : 26.1.1`
   ` Node              : v6.11.3`
   ` npm               : 5.5.1`
   ` OS                : Windows 10`

`Misc:`

   ` backend : pro`

**Comment by vzharkov** [comment]
@naumanahmad17 hi. You trying to install newer version of cordova-plugin-file. Try to use specific version, for example:
`ionic cordova plugin add cordova-plugin-file@4.3.3`

**Comment by naumanahmad17** [comment]
@vzharkov  thanks for the answer.
yeah that approach help me.

**Comment by ihadeed** [comment]
> Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.0, failed version requirement: >=6.3.0

Make sure you're using the correct platform version.

**Comment by yhyenifer** [comment]
Muchas gracias, si son las versiones, el plugin debe ser version 4 para versiones android desde la 6, la  version 6 del plugin solo funciona en versiones android igual o superior a la 7
