### ISSUE TITLE
uncaught (in promise)  plugin_not_installed in screen orientation

### ISSUE THREAD

**Issue by matsujunjun** [ionic-team/ionic-native#2208]
Hello. I created new ionic project and try to use screen-orientation plugin, but error occurs.
**Current behavior:**
I installed screen orientation as plugin as below:
```
$ ionic cordova plugin add cordova-plugin-screen-orientation
$ npm install --save @ionic-native/screen-orientation
```
after writing cord referring to https://ionicframework.com/docs/native/screen-orientation/,  I started the emulator:`ionic cordova emulate ios -lc`
And the error occurred: `uncaught (in promise) plugin_not_installed `
I wonder that my app operates normally(it looks normally) and  the screen rotates after close the error report.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.2
    npm   : 5.5.1
    OS    : OS X El Capitan
    Xcode : Xcode 7.3 Build version 7D175

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by iamisti** [comment]
did you figure it out? Since this repo has 0 support and I have the same issue

**Comment by matsujunjun** [comment]
I did not figure it out, but I found that this error does not occur when I do not use livereload option:
`ionic cordova emulate ios`
