### ISSUE TITLE
firebase dynamiclink (deeplink)

### ISSUE THREAD

**Issue by ramkrishna70** [ionic-team/ionic-native#2216]
**I'm submitting an issue with the firebase dynamic link. please verify with the following configurations.**  
While running in android firebase dynamiclink working fine, but in case of the IOS I am getting empty value as:
{matchType: "Weak", deepLink: ""}

my manually created dynamic url

https://xxxx.XXXX.goo.gl/?link=&apn=com.XXXXX.app&ibi=com.XXXXXX.app

The provided link is returning HTTP 200 status, when opening in browser.

Shared url which getting clicked: 
https://XXXX.XXXX.goo.gl/?link=http://deeplink.com/deeplink/ViewLocation?user_id%26user_group%26mentor_info%26distance&apn=com.XXXXX.app&afl=https://www.XXXXX.com/app/download&isi=1XXXX&ibi=com.XXXXXX.app&ifl=https://www.XXXXX.com/

**Current behavior:**
{matchType: "Weak", deepLink: ""}

**Expected behavior:**
{matchType: "Strong", deepLink: "http://deeplink.com/deeplink/ViewLocation?user_id%26user_group%26mentor_info%26distance&apn=com.XXXXX.app&afl=https://www.XXXXX.com/app/download&isi=1XXXX&ibi=com.XXXXXX.app&ifl=https://www.XXXXX.com/"}

**Related code:**

```
	        this.firebaseDynamicLinks.onDynamicLink()
	        .then((dynamicLink: any) => {
	            console.log("^^D^");
	            console.log(dynamicLink);
	            console.log("^^^^^^^component^^^^^^^");
	            this.dynamic_link = dynamicLink.deepLink; 
				return Promise.resolve("ok");
	        }).catch((firebaseError: any) => {  
	            console.log("##########################");
	            console.log("FIREBASE DYNAMIC LINK: component outer error");
	            console.log("##########################");
	            console.error(firebaseError); 
				return Promise.resolve("ok");
        	});
```

**Ionic info:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.1.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.2.1
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
![screen shot 2017-12-20 at 8 23 21 pm](https://user-images.githubusercontent.com/26932403/34245626-b808434a-e650-11e7-880c-e6dfb04defb3.png)

```

**Comment by rummykhan** [comment]
I'm also facing the same issue, but not with all requests, it's intermittent, I've collected logs of ip and devices but nothing is matching. still looking for answers

**Comment by danielsogl** [comment]
Related to the plugin source.

**Comment by ramkrishna70** [comment]
@danielsogl 
So, the issue is fixed in new plugin update.
