### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by bbdangar** [ionic-team/ionic-native#2217]
**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
I have installed Printer plugin, the steps followed as shown in official doc.
When tried to call 
`this.printer.pick()`, 
it shows plugin_not_installed error in the log.
NOTE: I tried it in inside `this.platfom.ready()` but got the same error every time.
**Expected behavior:**
Should open list of available printers in the network.

**Steps to reproduce:**
Install Printer plugin as shown in official doc.

**Related code:**

```
 constructor( private printer: Printer,  private toastCtrl: ToastController platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
        platform.ready().then(() => {
            // Okay, so the platform is ready and our plugins are available.

            // Here you can do any higher level native things you might need.
            statusBar.styleDefault();
            splashScreen.hide();

            this.printer.check().then(success => {
                console.log(success)
            }, error => console.error(error)) ;

```

**Other information:**
I am running it on Redmi Note 1 Kitkat 4.4 device.

message: "Object [object Object] has no method 'check'"
stack: "TypeError: Object [object Object] has no method 'check'↵    at file:///android_asset/www/build/vendor.js:62044:18↵    at new t (file:///android_asset/www/build/polyfills.js:3:21506)↵    at Printer.check (file:///android_asset/www/build/vendor.js:62042:16)↵    at Printer.value (file:///android_asset/www/build/vendor.js:132354:45)↵    at file:///android_asset/www/build/main.js:2214:27↵    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)↵    at Object.zone._inner.zone._inner.fork.onInvoke (file:///android_asset/www/build/vendor.js:4983:33)↵    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14916)↵    at r.run (file:///android_asset/www/build/polyfills.js:3:10143)↵    at file:///android_asset/www/build/polyfills.js:3:20242"
__proto__: Error

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.0
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/bhagirth/Android/Sdk

Misc:

    backend : pro


```

**Comment by Nitingadhiya** [comment]
same problem here. any one help me please?
thanks

**Comment by mebibou** [comment]
Which version of the plugin are you using?

**Comment by pufanalexandru** [comment]
I have the same problem:

```
cli packages: (C:\Users\Pufi\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\Pufi\AppData\Local\Android\sdk

Misc:

    backend : pro
```

The plugin version in package.json is this:
 `"@ionic-native/printer": "^4.5.3",`
`"de.appplant.cordova.plugin.printer": "^0.7.3"`

I also have this problem with cordova-plugin-mauron85-background-geolocation plugin

**Comment by mebibou** [comment]
Hum okay by checking the plugin definition and the original js file, there is no `check` nor `pick` method there. Can you confirm if you only call pick, it works? no matter the arguments, but does it tell you plugin not installed? let me know and I can PR the plugin to match the methods in the plugin

**Comment by mebibou** [comment]
The reference on the plugin points to https://github.com/katzer/cordova-plugin-printer, which redirects to another one which has different definitions than the one in the @ionic-native. Could you try using `print`? I'm guessing it would be the only one that would work. The definition needs to be updated

**Comment by danielsogl** [comment]
Fixed
