### ISSUE TITLE
ionic-native/calendar plugin throwing error "errorCallback is not a function"

### ISSUE THREAD

**Issue by amility** [ionic-team/ionic-native#2244]
**I'm submitting a bug report**  (check one with "x")

**Current behavior:**

I installed the ionic native calendar using instructions from https://ionicframework.com/docs/native/calendar/.  When I call createEvent method using 5 parameters (as doc has specified, however they are optional), I got an error in console that "errorCallback" is not a function. 
I tried to debug it and found that cordova plugin is calling this function in their calendar.js file and they are taking 7 parameters. Last 2 parameters are errorCallback and successCallback. But when I try to pass these 2 more functions as parameters, i can't compile because in native calendar library they have specified 5 parameters in this function. 

**Expected behavior:**
Calendar should be added

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\Amility\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.2
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\ANDROID-SDK

Misc:

    backend : pro
```

**Comment by codinronan** [comment]
@amility Can you post the code you are using?

I make extensive use of this plugin without issue.

**Comment by amility** [comment]
@codinronan Seriously.. I don't know what happened bro but I tried it again today to make screenshots for you so that I can explain the problem but it worked :)

Thank you so much for time and reply though. Appreciate 👍

**Comment by fjvalles** [comment]
I have this issue now. When I try to add a new event, ir throws:

```
ionic.bundle.js:26799 TypeError: errorCallback is not a function
    at Object.Calendar.createEventWithOptions (Calendar.js:97)
    at Calendar.createEvent (Calendar.js:129)
    at o (ionic.native.min.js:7)
    at ionic.native.min.js:7
    at ionic.native.min.js:7
    at Q (ionic.bundle.js:29396)
    at i (ionic.native.min.js:7)
    at s (ionic.native.min.js:7)
    at Function.<anonymous> (ionic.native.min.js:7)
    at Function.value [as createEvent] (ionic.native.min.js:7)
```
My ionic info stats

```
Ionic:

   ionic (Ionic CLI) : 4.10.1 (/usr/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.3
   @ionic/v1-toolkit : 1.0.17

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : no whitelisted plugins (15 plugins total)

System:

   Android SDK Tools : 25.2.5 (/home/fjvalles/android-sdk)
   NodeJS            : v9.11.2 (/usr/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.4
```
It happened after I added ionic native. I'm using "cordova-plugin-calendar": "^5.1.4".

Any ideas?

**Comment by AlpeshT** [comment]
@fjvalles - did you resolved the issue, because I have same issue

**Comment by JNBG** [comment]
Something I noticed for my App was, this Error only appeared when using the createEvent() function - solved it by switching to createEventInteractively()
