### ISSUE TITLE
indexappcontent-Plugin onItemPressed() not working

### ISSUE THREAD

**Issue by felixbroehl** [ionic-team/ionic-native#2255]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Calling onItemPressed-Method produces Error: `WARN: Native: tried calling IndexAppContent.onItemPressed, but the IndexAppContent plugin is not installed.`
Calling other Methods of the Plugin works as expected => the Plugin is installed.

**Expected behavior:**
Let me call a subscribe on the Observable.

**Steps to reproduce:**
Install https://ionicframework.com/docs/native/index-app-content/. Instead of `ionic cordova plugin add cordova-plugin-indexappcontent` install the plugin with `ionic cordova plugin add https://github.com/johanblomgren/cordova-plugin-indexappcontent.git` to get working version 0.5.0 . (0.1.0 leads to build errors)

Include following code in your AppComponent-Constructor:

**Related code:**

```
this.platform.ready().then(() => {
  this.indexAppContent.onItemPressed().subscribe(() => {
    console.log('called when a item is pressed');
  });
});
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.10.2
    npm        : 5.6.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by NiklasMerz** [comment]
Why did you decide to delete that function? It was working fine for me?

**Comment by danielsogl** [comment]
I think that was a mistake by me. I added the function again.

**Comment by NiklasMerz** [comment]
Thanks for fixing that. Aside from that problem I am happy with the new version :+1:
