### ISSUE TITLE
Problem with geolocation on Safari and Ios

### ISSUE THREAD

**Issue by dualshote** [ionic-team/ionic-native#2260]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi, i have a little problem with ionic native geolocation. It work on chrome, but when i want test on safari or on a device it didn't work. I have the related error : [Error] [blocked] Access to geolocation was blocked over insecure connection to http://localhost:8080. I read on internet that the new safari need a https connection... Some on can help me ? :) Thx

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
There is my code : 

<img width="839" alt="capture d ecran 2018-01-10 a 16 58 11" src="https://user-images.githubusercontent.com/5940350/34781951-8350a3cc-f627-11e7-9faa-a1b1646b5e1a.png">

There is the error than i have : 
<img width="670" alt="capture d ecran 2018-01-10 a 16 36 22" src="https://user-images.githubusercontent.com/5940350/34781777-0570a43e-f627-11e7-9826-cc7db37c0376.png">

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    Node       : v7.6.0
    npm        : 4.3.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by danielsogl** [comment]
If you read the error message correctly, you need HTTPS to test Geolocation with Safari. You can testet with Chrome.

**Comment by distvan** [comment]
you should run local tests with localhost domain name
