### ISSUE TITLE
Ionic Native - Crop

### ISSUE THREAD

**Issue by rockycabaero** [ionic-team/ionic-native#2263]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The "targetWidth" & "targetHeight" parameters are still not there when I install the plugin from npm

This is the code I have on @ionic-native/crop/index.d.ts

```
crop(pathToImage: string, options?: {
        quality: number;
}): Promise<string>;
```

**Comment by rajeshtbabu** [comment]
We cannot give fixed width and height of this plugin, only available quality..
