### ISSUE TITLE
InnAppBrowser - Hidden Option not working

### ISSUE THREAD

**Issue by prasanthnv** [ionic-team/ionic-native#2265]
**Type** : bug

**Ionic Version** : 3.x

` let browser_options:InAppBrowserOptions = {
      location: 'no',
      hidden:'yes',
      clearcache: 'yes',
      toolbar: 'no',
    }`
`let browser = this.innAppBrowser.create('http://www.google.com/', '_blank', browser_options);`

The hidden option is not working, I tried every possible way but doesn't work for me.

**Comment by prasanthnv** [comment]
i tried it with cordova code directrly and works fine 
`cordova.InAppBrowser.open("http://www.google.com",'_blank','hidden=no,location=yes');`

**Comment by huoguoislife** [comment]
I guess in the options the format should be like
options=['location=no','hidden=yes','clearcache=yes','toobar=no']
Not sure if it is the problem.
