### ISSUE TITLE
Publish PRed plugins before merging into master

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic-native#2277]
I don't know if this is something doable or asked before, but would it be possible to publish the new added plugins from PRs if they pass all the checks? like if I create a new PR about a plugin called `my-plugin`, then it will publish it as `@ionic-native/my-plugin@4.5.1-beta` or something like that. It will help developers test and debug their implementation.

Or if anyone has other ways of testing their plugins... it would be nice to see it in the developer guide

**Comment by ihadeed** [comment]
Not sure if that's a good idea, that would basically allow anyone to publish anything they want under the `@ionic-native` scope.

You can test plugins by:
1. Using `npm link`
2. OR, copy & paste the generated directory under `dist` to `node_modules/@ionic-native` in your app
