### ISSUE TITLE
Not working with bright codes on dark background

### ISSUE THREAD

**Issue by VanillaWhey** [ionic-team/ionic-native#2280]
**I'm submitting a ...** 
[x] feature request

**Current behavior:**

Trying to scan a bright QR-code doesn't work at all.

**Expected behavior:**

Scanning any kind of QR-code should be possible.

**Steps to reproduce:**

Scan a bright QR-code on dark background.

**Other information:**

**Comment by danielsogl** [comment]
Relaxed to the plugin source.

**Comment by homeportcz** [comment]
Try to set window['QRScanner_SCAN_INTERVAL'] = 10; or another similar value.

**Comment by homeportcz** [comment]
This improves scanning sensitivity. Just try it, it might help.

Set it after scanner initialization.
