### ISSUE TITLE
Google Map set/get center not implemented

### ISSUE THREAD

**Issue by kotromeo** [ionic-team/ionic-native#2281]
**I'm submitting a ...**  (check one with "x")
[x] bug report
**Current behavior:**
I'm using google map ionic native plugin and there is no functions map.getCenter, map.setCenter, but they described in documentation https://ionicframework.com/docs/native/google-maps/

**Expected behavior:**
get map center and set map center

**Steps to reproduce:**
1) install google map plugin https://ionicframework.com/docs/native/google-maps/
2) call this.map.getCenter() or this.map.getCetner()

```
property 'setCenter' does not exist on type 'GoogleMap'.
```

**Comment by weequan93** [comment]
I got this problem also, but after do some research, I got this ( setcenter is rename to setCameraTarget) . 

Below is the link for your reference.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/migrate-from-v1/README.md

**Comment by kotromeo** [comment]
Thanks
