### ISSUE TITLE
APP Crahes on iOS when choosing image from library when using option saveToPhotoAlbum: true

### ISSUE THREAD

**Issue by fzamperin** [ionic-team/ionic-native#2293]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When I choose to select an image with the option `saveToPhotoAlbum: true`, the app crashes it exits totally, this behavior only happens on emulator, tested in iPhone-X, iPhone-6s and iPhone-SE. When set to false it works as expected.

**Expected behavior:**
The app would not crash.

**Steps to reproduce:**
In my problem, I just enabled saveToPhotomAlbum option to true 

**Related code:**
This is my provider with the Camera function;
```
takePicture(options: { source: string, height: number, width: number }): Observable<string> {
    return Observable.create(observer => {
      let sourceType = null
      if (options.source == "PHOTOLIBRARY") {
        sourceType = this.camera.PictureSourceType.PHOTOLIBRARY;
      } else {
        sourceType = this.camera.PictureSourceType.CAMERA;
      }
      this.camera.getPicture({
        quality: 85,
        destinationType: this.camera.DestinationType.DATA_URL,
        sourceType: sourceType,
        allowEdit: true,
        encodingType: this.camera.EncodingType.JPEG,
        targetWidth: options.width,
        targetHeight: options.height,
        saveToPhotoAlbum: true,
        mediaType: this.camera.MediaType.PICTURE
      }).then(image => {
        let foto = ('data:image/jpeg;base64,' + image);
        observer.next(foto);
        observer.complete();
      }, (error) => {
        console.log(error);
        observer.error(error)
      });
    })
  }
```

**Other information:**
No stacks shown.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.1.0 
    Gulp CLI    : CLI version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v8.6.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 
```
I'm using ionic-native "4.5.3", maybe it could be something related to the cordova plugin.

**Comment by ihadeed** [comment]
Seems like an issue with the plugin and not with Ionic Native.

Ionic Native problems might cause errors to be displayed in the console.. it won't crash your app.
