### ISSUE TITLE
Geocoder:getFromLocation Error: Service not Available

### ISSUE THREAD

**Issue by amyogiji** [ionic-team/ionic-native#2296]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:** Geocoder:getFromLocation Error: Service not Available

**Expected behavior:** Should return address location

**Steps to reproduce:**
https://ionicframework.com/docs/native/native-geocoder/

**Related code:**

```
    this.geocoder.reverseGeocode(52.5072095, 13.1452818)
        .then((result: NativeGeocoderReverseResult) => {
          console.log(JSON.stringify(result));
        }).catch((error: any) => console.log(error));
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.5.0
    npm               : 5.3.0
    OS                : Windows 8.1
```

**Comment by weequan93** [comment]
I got this problem also, but solve after reboot my phone.

**Comment by goinnn** [comment]
Me too. Another solution that reboot the phone?
