### ISSUE TITLE
Network plugin is not installed

### ISSUE THREAD

**Issue by thiphariel** [ionic-team/ionic-native#2302]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

The plugin `@ionic-native/network` won't install correctly since 4.5.3. I always get the error `WARN: Native: tried calling Network.downlinkMax, but the Network plugin is not installed.` while the plugin is correctly installed.

I tried many times to remove the platform and reinstall it but I always get the error...

EDIT : Ok, it's only `downlinkMax` that does not works...

**Expected behavior:**

The plugin should work

**Other information:**
Config.xml : 
```
<plugin name="cordova-plugin-network-information" spec="^2.0.1" />
```
Package.json : 
```
"cordova-plugin-network-information": "^2.0.1",
...
"cordova": {
        "plugins": {
                "cordova-plugin-network-information": {}
       }
}
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/thomas/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v9.3.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/thomas/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by NikhilKumarBehera** [comment]
Did anyone get any update on this?
