### ISSUE TITLE
Remove senderId from PushOptions

### ISSUE THREAD

**Issue by Todmy** [ionic-team/ionic-native#2312]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am forced to specify senderId into option for android, but probably this is unnecessary

**Expected behavior:**
SenderId comes from google-services.json file

**Other information:**
Please look at https://github.com/ionic-team/ionic-native/pull/2060

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.0.0
    npm               : 5.5.1
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/todmy/Android/Sdk

Misc:

    backend : pro
```

**Comment by danielsogl** [comment]
@Todmy I created a PR.
