### ISSUE TITLE
getVar is not implemented in @ionic-native/google-analytics plugin

### ISSUE THREAD

**Issue by chinlun** [ionic-team/ionic-native#2313]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
getVar() method is not available in @ionic-native/google-analytics plugin, but it is available in the Cordova google-analytics plugin.

**Expected behavior:**
getVar() method available in @ionic-native/google-analytics plugin

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.4.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    ios-deploy : 1.9.2
    ios-sim    : 5.0.13
    Node       : v7.8.0
    npm        : 4.2.0
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by Snead** [comment]
Bump

**Comment by danielsogl** [comment]
@chinlun I created a PR to fix that issue.
