### ISSUE TITLE
shareViaEmail not working on ios > 9.3 error: not available

### ISSUE THREAD

**Issue by ramkrishna70** [ionic-team/ionic-native#2322]
I am using the sharing plugin and all working fine on android and ios below v10.
It works till ios v9.3 but not above. 
I also used shareVia, but the app crashed on ios v9.3.
```
Code I used:
this.socialsharing.shareVia("Mail",shareMsg, subject, img); where, Mail is package name.

Also tried with "com.apple.mobilemail" instead of Mail, but same crash happend.
```

Please help me to find the issue asap.
Installed version of native plugin: cordova-plugin-x-socialsharing 5.2.1 "SocialSharing".
Thank you.

**Comment by danielsogl** [comment]
Not related to the native-wrapper. I also use this plugin without that kind of problem. Please open an new issue here: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
