### ISSUE TITLE
hygieiasoft/cordova-plugin-uid is not working and not supported anymore

### ISSUE THREAD

**Issue by rgex** [ionic-team/ionic-native#2324]
The Ionic Uid documentation installation instructions are:
$ ionic cordova plugin add https://github.com/hygieiasoft/cordova-plugin-uid
$ npm install --save @ionic-native/uid

However hygieiasoft/cordova-plugin-uid is not supported anymore.

The solution is to use "ionic cordova plugin add cordova-plugin-uid"

Can the documentation as well as the @ionic-native/uid plugin be updated so that it doesn't point to hygieiasoft/cordova-plugin-uid anymore?

**Comment by danielsogl** [comment]
fixed
