### ISSUE TITLE
Update to background-geolocation v3

### ISSUE THREAD

**Issue by hbc8141** [ionic-team/ionic-native#2328]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
This version is only v2 supported. Please support to background-geolocation v3.

**Comment by danielsogl** [comment]
@hbc8141 I will create a PR for V3.
