### ISSUE TITLE
Can't get geolocation plugin to work on android device

### ISSUE THREAD

**Issue by thanapongp** [ionic-team/ionic-native#2335]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The geolocation plugin always throw an empty error when calling getCurrentPosition(). No matter what do, it just won't work. I've tried wrapping inside platform().ready(), I've tried giving it timeout option. I've tried updated cordova to 7.1.0.

**Expected behavior:**
The plugin give me current device location.

**Steps to reproduce:**
Just install the plugin in and call getCurrentPosition() on android device such as Samsung Galaxy S7 or Samsung Galaxy J7

**Related code:**

```
this.platform.ready().then(() => {
      this.getLocation();
});

private async getLocation(): Promise<void> {
    try {
      let locAuthorized = await this.diagnostic.isLocationAuthorized();
      let locAvailable = await this.diagnostic.isLocationAvailable();

      console.log('locAuthorized', locAuthorized); // true
      console.log('locAvailable', locAvailable); // true

      let resp = await this.geolocation.getCurrentPosition({timeout: 30000, maximumAge: 15000});

      this.coord = resp.coords;

      console.log(JSON.stringify(this.coord)); // should give the device's location

    } catch (e) {
      console.log(JSON.stringify(e)); // always catch an empty object { }
    } 
  }
```

**Other information:**
none

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.3.1
    ios-deploy        : 1.9.2
    Node              : v8.3.0
    npm               : 5.3.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/thanapongp/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by thanapongp** [comment]
Running without "--livereload" flag seems to fix the problem (somehow). Is this a security issue?

**Comment by ihadeed** [comment]
@thanapongp yes it's a security thing. 

When you run in livereload, you're loading a site on the `http://` protocol. Chrome & Chrome WebView (and I think other browsers) block access to sensitive APIs (such as Geolocation) over insecure connections. When you run the app without livereload, you're accessing it via `file:///` protocol, which is considered secure, since the data isn't being transmitted anywhere.

**Comment by thanapongp** [comment]
@ihadeed Ah, I get it now. Thank you so much for additional info.
