### ISSUE TITLE
An on event on @ionic-native/browser-tab

### ISSUE THREAD

**Issue by SunilRumbaLama** [ionic-team/ionic-native#2338]
**I'm submitting a 
[x] feature request

**Current behavior:**

ionic-native/browser-tab currently doesn't have any event to get whats happening in the browser url like ionic-native/in-app-browser

**Expected behavior:**

Possibly an on event on the browser-tab as well 

**Steps to reproduce:**

**Related code:**

```
this.browserTab.isAvailable().then((isAvailable: boolean) => {
  this.browserTab.openUrl('google.com');
this.browserTab.on('loadstop').subscribe(
data =>{
console.log(data.url);
}
)
})
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.2.1
    npm  : 5.2.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy


```

**Comment by danielsogl** [comment]
Hey,

if you want this kind of feature for this plugin you have top open an feature request here: https://github.com/google/cordova-plugin-browsertab

We don't develop the plugins and only surround them with the ionic-native wrapper.
