### ISSUE TITLE
Geofence plugin is not working for iOS, reported many but no solution yet

### ISSUE THREAD

**Issue by shinuvs** [ionic-team/ionic-native#2347]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by danielsogl** [comment]
Related to the plugin source.

**Comment by shinuvs** [comment]
May i know why it is closed without having any solution or reply.

**Comment by danielsogl** [comment]
As I mentioned, this bug has nothing to do with the ionic native wrapper but with the plugin itself.
