### ISSUE TITLE
I want to translate this doc to Chinese.

### ISSUE THREAD

**Issue by kernight** [ionic-team/ionic-native#2357]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I want to translate this doc to Chinese. And I fork this project and build it successfully,but i can't find the way to build the website as the  [https://ionicframework.com/docs/native/](https://ionicframework.com/docs/native/). can Anybody help me?

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

**Other information:**

**Comment by danielsogl** [comment]
cc @mhartington
