### ISSUE TITLE
Reg:Installation of push plugin.

### ISSUE THREAD

**Issue by SellvakumarSS** [ionic-team/ionic-native#2360]
Hai guys

Am trying to install push plugin in cordova platform 6.2.3 but its failing.I want to use particularly cordova platform 6.2.3 because i have project dependency.

Output:
When i try installing the plugin am getting the below error/warning and the plugin doesn't get installed..

Installing "phonegap-plugin-push" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.3, failed version requirement: >=7.1.0

Skipping 'phonegap-plugin-push' for android

Adding phonegap-plugin-push to package.json

Saved plugin info for "phonegap-plugin-push" to config.xml

My ionic info:
Your system information:

Cordova CLI: 7.1.0
Ionic Framework Version: 3.6.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 3.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v7.4.0
Xcode version: Not installed

Expected behaviour:
The plugin should be installed.

**Comment by bhavinwebdesk** [comment]
You should upgrade your Cordova version or downgrade Cordova to 6.2.3.
