### ISSUE TITLE
Cordova Geolocation API

### ISSUE THREAD

**Issue by vijaysutaria** [ionic-team/ionic-native#2361]
I am using cordova geolocation api to get current location of user so that I can decide in which direction user is moving. API is giving me response but heading is null value. I read the document and found that heading will be null if device is not capable of giving heading value. I tried this in multiple mobile models like Motorola,  Samsung , Lenovo, but everywhere I am getting heading value null, this seems like some issue with geolocation api.

Please help me.

Thanks in advance

**Comment by danielsogl** [comment]
Related to the plugin source.
