### ISSUE TITLE
@ionic-native/Printer Documentation wrong Plugin name

### ISSUE THREAD

**Issue by BigJenson** [ionic-team/ionic-native#2363]
**I'm submitting a ...**
[x] bug report

**Current behavior:**
Documentation for https://ionicframework.com/docs/native/printer/ seems to refrence a wrong Plugin name. It says, that you have to install the 'de.appplant.cordova.plugin.printer' Cordova Plugin. This Plugin leads to this repository: https://github.com/citylims/cordova-plugin-printer. The correct Plugin name for the referenced Git Repository (https://github.com/katzer/cordova-plugin-printer) would be 'cordova-plugin-printer'. With the de.appplant.cordova.plugin.printer Plugin the Code crashes because Functions like 'check' are missing on the Plugin side.
There are currently 2 NPM Packages for this Plugin:
https://www.npmjs.com/package/de.appplant.cordova.plugin.printer 
https://www.npmjs.com/package/cordova-plugin-printer

**Comment by danielsogl** [comment]
@BigJenson I created a PR to fix this problem.

Thanks for opening this issue.
