### ISSUE TITLE
ADMOB PRO problem  position

### ISSUE THREAD

**Issue by eomonteiro** [ionic-team/ionic-native#2364]
**I'm submitting a ...**  (check one with "x")
IONIC 3 - ADMOB PRO
[x] bug report
[ ] feature request
[x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
-Problem with banner position showBannerAtXY on different mobiles
-Banner are positioned on the menu when open

**Expected behavior:**
-Insert the banners within components

**Steps to reproduce:**
Wrong
[https://puu.sh/zCzcV/4e2d4a1216.jpg](https://puu.sh/zCzcV/4e2d4a1216.jpg)

Expected
[https://puu.sh/zCzfo/349c8375b9.jpg](https://puu.sh/zCzfo/349c8375b9.jpg)

Wrong
[https://puu.sh/zCzuD/630939fc44.jpg](https://puu.sh/zCzuD/630939fc44.jpg)
Other mobiles
[https://puu.sh/zCzCb/bc3cef0204.jpg](https://puu.sh/zCzCb/bc3cef0204.jpg)

Expected in all mobille using component
[https://puu.sh/zCzyJ/0421ffc41f.jpg](https://puu.sh/zCzyJ/0421ffc41f.jpg)

`cli packages: (C:\Users\pc\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.7.1
    npm               : 5.6.0`

**Comment by danielsogl** [comment]
Related to the plugin source.
