### ISSUE TITLE
FCM Browser support?

### ISSUE THREAD

**Issue by nvirth** [ionic-team/ionic-native#2368]
[Ionic Native FCM](https://ionicframework.com/docs/native/fcm/) does not support Browser platform, but at [https://console.firebase.google.com](https://console.firebase.google.com) I can see FCM already supports "Web" next to Android and iOS.
Is it planned in the near future for the plugin to support the Browser platform?

**Comment by danielsogl** [comment]
We don't develop the plugins. You should open a feature request at the plugin source repository.

**Comment by nvirth** [comment]
Sorry for my mistake.
Here is the opened issue:
https://github.com/fechanique/cordova-plugin-fcm/issues/482
