### ISSUE TITLE
cordova-plugin-gelocation - Android Oreo - dont work

### ISSUE THREAD

**Issue by NurGuz23** [ionic-team/ionic-native#2372]
Hi guys,

in other devices , for exmaple S67 o S7, getCurrentPosition  run correctly and fast, but in S9 doesn't work.

Any idea?

Thanks

**Comment by NurGuz23** [comment]
I think that the problem was in Android Oreo 8.0

**Comment by danielsogl** [comment]
Related to the plugin source.
