### ISSUE TITLE
Ionic native code updation from git url

### ISSUE THREAD

**Issue by HardikDG** [ionic-team/ionic-native#2407]
I want a help regarding the ionic-native plugin update. 
I have read the Developer.md file which says you can do changes in the ionic-native repo and then run `npm run build` to get the output in the dist folder.

How can I make global for all the developers for my project? 
For ex: 3 developers are working on the same project. I made changes in the Ionic-native plugin code I have copied the code in the node modules of ionic-native, now another developer is doing work on the project but he is not getting the updated plugin code as it will download the code from the main ionic-native repo and my node module is not getting committed in the git as it is in the gitignore. 
So how can I make it global like install from the GitHub URL like we can do for the Cordova plugins so all the developers on the same project get my updated ts file

Sorry for the duplicate post. this is the issue may be posted before many times but I was not able to find it on the issues. 

If I need to fork the ionic-native repo, every plugin will come from my repo and I need to frequently merge the latest changes in the main repo run npm run build and copy paste all the plugin updates in my node modules folders. I think there should be some better way for changing a single plugin ts file.

**Comment by danielsogl** [comment]
You can install packages with npm from git sources: `npm install <git remote url>`.
Publish your private native wrapper to any git repository to share it with your developers.

**Comment by HardikDG** [comment]
Yes. my question is can I install a specific plugin from the git URL like this. 
npm install --save @ionic-native/contacts

I have uploaded my modified package on this git repo: https://github.com/HardikDG/ionic-native
Now I want to install the specific contacts plugin from my repo and all other plugins from main ionic-native plugin repo how can I achieve this? 

Does it something like npm install https://github.com/HardikDG/ionic-native/plugins/contacts  --save ? If I want to install the 'ionic-native/contacts'

**Comment by danielsogl** [comment]
You have to build the plugin and host the list folder
