### ISSUE TITLE
[request] Spin-out or discontinue @ionic-native/google-maps

### ISSUE THREAD

**Issue by wf9a5m75** [ionic-team/ionic-native#2410]
As the `cordova-plugin-googlemaps` author, I request to spin-out the `@ionic-native/google-maps` from the `@ionic-native` plugin family,  or discontinue it.

First of all, I have never asked to create `@ionic-native/google-maps` plugin, but the ionic team created it.

Well, I don't mind if the ionic team maintains the `@ionic-native/google-maps` very well, but they don't at all. As the result, many ionic users claimed to me many bugs which are `@ionic-native/google-maps` itself.

I contributed to fix the bugs a lot in my private time. However I faced couple of unreliable things from the ionic-team, and they stops updating the ionic-native plugins, also ignore my e-mails.
Therefore, I have no reason to support the `@ionic-native/google-maps` plugin.

However I understand there are tons of users of `@ionic-native/google-maps` plugin.
If I don't support the `@ionic-native/google-maps`, nobody support it, and the tons of users would claim to me. This would be stressful also.

So, there are three choices:.
- 1. please spin-out the `@ionic-native/google-maps` from the `@ionic-native` family.
      In that case, I will take over, and keep updating it.
- 2. remove the `@ionic-native/google-maps` everything.
- 3. release the current master version to npm, and support the `@ionic-native/google-maps` by community. In that case, I don't send updates, but I support the issue reports to my repo.

Until the discussion would reach to the satisfactory goal, I simply refuse the supporting of `@ionic-native/google-maps` plugin, including who use it, at my repo.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2162

Since the ionic-team ignores my contacts everything, this is only my choice.

If the ionic team ignores this discussion, I will implement the code which blocks ionic framework in code level.

**Comment by danielsogl** [comment]
cc @ihadeed

**Comment by battika** [comment]
Ionic team, to put an end to this entire saga, can you please go with option 3 and release the current @ionic-native/google-maps version to npm? Google Maps is a vital plugin to Ionic (and Cordova) if we lose support of @wf9a5m75 I am not sure what sort of alternative we will have. Unfortunately, Javascript Google Maps is not a real replacement as it does not feel native at all.

**Comment by mlynch** [comment]
I see no reason why we can’t put it in a separate repo and manage updates separately and add you as a maintainer @wf9a5m75

**Comment by wf9a5m75** [comment]
That's good choice, @mlynch . I can release the new version with the `cordova-plugin-googlemaps` at the same time. Thus, the users don't need to wait the `@ionic-native/google-maps` update.

**Comment by wf9a5m75** [comment]
@mlynch Thank you for releasing the new version at least.

**Comment by mlynch** [comment]
Okay I made a new, empty repo here: https://github.com/ionic-team/ionic-native-google-maps/

Probably just need to have `@ionic-native/core` as a dependency and copy over the tsconfig/typescript deps

Let me know if I can help, let's continue to conversation here

**Comment by wf9a5m75** [comment]
Thank you for creating the repo. How about the releasing scheme? Should I still ask the plugin releasing?
Well, to align the version number of all plugins helps understanding which version is the latest, but this kills the benefit that individual plugin can release their timing.

In order to align the version number with other plugins, or review the code to keep the quality as `@ionic-native` series  I can wait one week. I understand this.
But two week, or further, many users get stressful.
(And your team should reply my contacts at least)

**Comment by wf9a5m75** [comment]
If you don't mind the version number that only the `@ionic-native/google-maps` separate different version number, please add me as collaborators to npm.
I will release the new version when I am ready.

If you mind the version number, or if you want to check the code with the member ionic-native team,  please suggest better scheme.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
My npm user name is wf9a5m75. Did you try my e-mail address also?

**Comment by mlynch** [comment]
@wf9a5m75 thanks, I think npm has a bug and is throwing a 500. I contacted their support

**Comment by mlynch** [comment]
k Should be resolved and you should have gotten an email notification about being added to the org

**Comment by wf9a5m75** [comment]
Thanks, @mlynch 
I appreciate for your understanding and help. I will continue the supporting for the ionic-native/google-maps.

**Comment by wf9a5m75** [comment]
Hi, @mlynch 

Could you add CircleCI to https://github.com/ionic-team/ionic-native-google-maps?

**Comment by mlynch** [comment]
Sorry, missed this. Just pinged the team to see about adding Circle CI to that, as that's not something I know how to do.

**Comment by wf9a5m75** [comment]
Okay, thanks.

**Comment by wf9a5m75** [comment]
Since the ionic team does not manage the plugin in proper, I take over the management, but the repository is still under the ionic team control. Because the repository owner is ionic team.

Thus, you should not delete the google maps page.
https://ionicframework.com/docs/native/google-maps/

**Comment by wf9a5m75** [comment]
I have an idea.

Under this url, there is one page, and link to another url.
https://ionicframework.com/docs/native/google-maps/

Then on the link, I will create a document site.
How about this?

**Comment by wf9a5m75** [comment]
I created documentation. Please link to here.
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/README.md

**Comment by wf9a5m75** [comment]
ping @mlynch

**Comment by wf9a5m75** [comment]
ping @ihadeed

**Comment by wf9a5m75** [comment]
The issue has been fixed finally. I close this issue thread.
https://github.com/ionic-team/ionic-native/pull/2490#event-1601723379
