### ISSUE TITLE
background geolocation depreciation api change

### ISSUE THREAD

**Issue by mkeung** [ionic-team/ionic-native#2424]
https://github.com/mauron85/cordova-plugin-background-geolocation

The newer versions will use checkStatus(success, fail). ionic-native/background-geolocation does not support this call.

isLocationEnabled(success, fail) is depreciated for checkStatus moving forward. 

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
call checkStatus does not exist.

**Expected behavior:**
checkStatus exists and works as documented.

**Steps to reproduce:**
Attempt to use this.backgroundGeolocation.checkStatus after standard background geolocation setup.

**Comment by mkeung** [comment]
actually a change in general from v2 to v3.

**Comment by collindutter** [comment]
It looks like the types still haven't been updated to V3? Is this on the roadmap?
