### ISSUE TITLE
"plugin_not_installed"  

### ISSUE THREAD

**Issue by kykcyusuf** [ionic-team/ionic-native#2425]
**Current behavior:**
When I try to run with ionic view and I open app with ionic view after I get this message with alert.
plugin_not_installed

**Expected behavior:**
I need to open pdf file when platform ready.

**Related code:**
//app.module.ts
import { FileOpener } from '@ionic-native/file-opener';
providers: [
    FileOpener
  ]
//app.component.ts
import { FileOpener } from '@ionic-native/file-opener';
constructor(public platform: Platform,public fileopener:FileOpener, ) {
this.platform.ready().then(() => {
      this.fileopener.open('file:///storage/emulated/0/Download/document.pdf', 'application/pdf')
        .then(() => alert('File is opened'))
        .catch(e => alert(e));
});
}

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (C:\Windows\System32\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.3
    npm  : 5.5.1
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by danielsogl** [comment]
The Ionic View App does not support all Cordova plugins. You can find all supported plugins here: https://ionicframework.com/docs/pro/view.html#plugin-support
