### ISSUE TITLE
CallNumber's `.isCallSupported()` throws "plugin_not_installed" error, but the functionality still works

### ISSUE THREAD

**Issue by uzbekjon** [ionic-team/ionic-native#2428]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

[Call Number](https://ionicframework.com/docs/native/call-number/) plugin's `.isCallSupported()` method throws "_plugin_not_installed_" error. Even though the plugin is installed AND work as expected.

**Expected behavior:**

The promise returned by the method should resolve to true on devises that support the functionality.

**Steps to reproduce:**

Install the plugin as usual:
```
$ ionic cordova plugin add call-number
$ npm install --save @ionic-native/call-number
```
Add the module to providers list:

```typescript
import { CallNumber } from '@ionic-native/call-number';

...

@NgModule({
  ...

  providers: [
    ...
    CallNumber
    ...
  ]
  ...
})
export class AppModule { }
```

**Related code:**

```typescript
import { Component } from '@angular/core';
import { CallNumber } from "@ionic-native/call-number";

@Component({
  selector: 'page-home',
  template: `
    {{isSupported | json}}
    <button ion-button (click)="callNumber()">CallNumber</button>
  `
})
export class HomePage {
  isSupported = false;

  constructor(public phone: CallNumber) {
    this.phone.isCallSupported()
      .then(support => this.isSupported = support)
      .catch(err => this.isSupported = err);
  }

  callNumber(){
    this.phone.callNumber("123456789", true)
      .then(res => this.result = res)
      .catch(err => this.result = err);
  }
}
```

**Other information:**

**Ionic info:**

```
cli packages: (/Users/uzbekjon/.nvm/versions/node/v8.9.4/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.7.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/uzbekjon/Library/Android/sdk

Misc:

    backend : pro
```

**Comment by anjildhamala** [comment]
The plugin does not even have the function isCallSupported() and @ionic-native plugin code doesn't seem to be doing anything by itself. I wonder why the function is even there.

**Comment by ng22792** [comment]
I would like to reopen this issue as the exact behaviour is still occurring.

**Comment by ManigandanRaamanathan** [comment]
Im having 2 ionic project, It works fine on one. Another it's not working at all. No respond at all when executing the function

**Comment by ManigandanRaamanathan** [comment]
@ng22792  my solution for your problem is that try remove your ionic platform based on ( https://ionicframework.com/docs/cli/cordova/platform/ ) and then add the platform back. This will download all the missed out plugin in platform.
