### ISSUE TITLE
Needs updating for rxjs v6

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#2439]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

We are going to be moving to Angular 6 and rxjs 6 for ionic-angular v4. Currently, because of breaking changes in rxjs, the current release of ionic-native will cause the ng cli to break with the following errors:

```
ng] ERROR in node_modules/@ionic-native/core/decorators.d.ts(1,10): error TS2305: Module '"C:/Users/jgw96/Projects/ionic-conference-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
[ng] node_modules/@ionic-native/core/plugin.d.ts(2,10): error TS2305: Module '"C:/Users/jgw96/Projects/ionic-conference-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
[ng] node_modules/@ionic-native/in-app-browser/index.d.ts(2,10): error TS2305: Module '"C:/Users/jgw96/Projects/ionic-conference-app/node_modules/rxjs/Observable"' has no exported member 'Observable'. 
```

**Steps to reproduce:**

- grab the `core-update` branch of the conf app https://github.com/ionic-team/ionic-conference-app/tree/core-update
- remove rxjs-compat from the package.json
- run npm install
- run `ionic serve` with the latest rc of the ionic cli

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by wKoza** [comment]
Hi @jgw96,
What is your plan of migration concerning RxjS with ionic-native ? 
Are you project to upgrade RxJS to 5.5 or 6 quickly ?

I have many reticence with the side-effect import like:
```javascript
import 'rxjs/add/observable/of'
```

I can change this if you want. We can upgdrade to RxJS 5.5, in a first time and use pipeable operators and imports without side-effect.

```javascript
import {of} from 'rxjs/observable/of';
```

**Comment by adamduren** [comment]
@danielsogl When will this be released?

**Comment by slimlime** [comment]
Adding my two cents. My ionic angular electron project when updating dependencies

```bash
[10:39:56]  typescript: ...project/node_modules/@ionic-native/core/decorators.d.ts, line: 1
            Module '"A:/project/node_modules/rxjs/Observable"' has no exported member
            'Observable'.

       L1:  import { Observable } from 'rxjs/Observable';
       L2:  export interface PluginConfig {

[10:39:56]  typescript: ...project/node_modules/@ionic-native/core/plugin.d.ts, line: 1
            Module '"A:/project/node_modules/rxjs/Observable"' has no exported member
            'Observable'.

       L1:  import { Observable } from 'rxjs/Observable';
       L2:  import { CordovaOptions } from './decorators';

[10:39:56]  typescript: ...project/node_modules/ionic-angular/umd/components/input/input.d.ts, line: 3
            Module '"A:/project/node_modules/rxjs/Subject"' has no exported member
            'Subject'.

       L2:  import { NgControl } from '@angular/forms';
       L3:  import { Subject } from 'rxjs/Subject';
       L4:  import 'rxjs/add/operator/takeUntil';

[10:39:56]  typescript: ...project/node_modules/ionic-angular/umd/components/tabs/tabs.d.ts, line: 2
            Module '"A:/project/node_modules/rxjs/Subject"' has no exported member
            'Subject'.

       L1:  import { AfterViewInit, ElementRef, EventEmitter, Renderer, ViewContainerRef } from '@angular/core';
       L2:  import { Subject } from 'rxjs/Subject';
       L3:  import 'rxjs/add/operator/takeUntil';

[10:39:56]  typescript: A:/project/node_modules/rxjs/Observable.d.ts, line: 1
            Cannot find module 'rxjs-compat/Observable'.

       L1:  export * from 'rxjs-compat/Observable';

[10:39:56]  typescript: A:/project/node_modules/rxjs/Subject.d.ts, line: 1
            Cannot find module 'rxjs-compat/Subject'.

       L1:  export * from 'rxjs-compat/Subject';
```

I want to fix this properly but I've been breaking a lot of existing projects lately messing around while learning these building technologies...so... `yarn add rxjs-compat` 😸 

Would this fix 'properly' if I installed the latest @ionic/angular (_disambiguation_ not ionic-angular?) or do I need to run yarn add for all latest versions of @ionic packages?
