### ISSUE TITLE
Could not getting latest ts file for local notifications

### ISSUE THREAD

**Issue by mowaiskalam** [ionic-team/ionic-native#2442]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using local-notifications, I am not getting the described parameter in the documentation. According to the documentation 'schedule()' should have 'trigger' property, but I don't have this, I have only 'at' param which is not working for me on Android. I have double check my local-notifications version is 4.6.0. I think this is because of the typings issue. The plugin is latest but I am unable to update 'ionic-native/local-notification' typings.

**Expected behavior:**
local-notifications typing should have trigger property.

**Steps to reproduce:**
I have just simply installed the plugin

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by alecrem** [comment]
I think I have the same problem as you do, so I opened [a separate issue](https://github.com/ionic-team/ionic-native/issues/2443) to add as much relevant information as I could.

I hope we can get this fixed! I'd love to help if I knew where to start.

**Comment by alecrem** [comment]
Thanks for replying on the other issue.

You should close your issue if it is resolved.

**Comment by marioshtika** [comment]
The developer has updated his plugin but the wrapper for the local notification is not updated.
When trigger: ```{ every: { month: 10, day: 27, hour: 9, minute: 0 } }```, type of ```every``` only expects ```ELocalNotificationTriggerUnit``` which is an enum for string, not an object.
Please update the wrapper.
