### ISSUE TITLE
geolocation.getCurrentPosition doesn't work as expected in Android

### ISSUE THREAD

**Issue by chintankshah** [ionic-team/ionic-native#2444]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request 

**Current behavior:**

geolocation.getCurrentPosition works only if I enable device location before loading the page/component which uses it. Now when the location is found to be disabled and if the user is asked to enabled it and retry, it still doesn't work. But the same works if I move out of the page and reload it and try.

Any help is much appreciated.

**Expected behavior:**

If the location is enabled, it should give location and fall into success callback.

**Steps to reproduce:**

1. Disable location in Android.
2. Load the page/component that loads geoLocation from Constructor.
3. Try to call geolocation.getCurrentPosition (on button click). It will throw error (expected here).
4. Now enable location in Android manually. 
5. Retry calling geolocation.getCurrentPosition (on button click).

**Comment by faisalSiddiqui03** [comment]
Is this for chrome android browser or Cordova android build?
