### ISSUE TITLE
Error while running build with Local-Notification plugin

### ISSUE THREAD

**Issue by mpadmaraj** [ionic-team/ionic-native#2455]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When I do a build with Local Notification, I get this error:
```
[23:00:05]  typescript: node_modules/@ionic-native/local-notifications/index.d.ts, line: 4 
            In ambient enum declarations member initializer must be constant expression. 

       L3:  export declare enum ELocalNotificationTriggerUnit {
       L4:      SECOND = "second",
       L5:      MINUTE = "minute",
```

**Expected behavior:**
Build should be successful

**Steps to reproduce:**
Install Local-Notification plugin.

**Ionic info:** 
```
Cordova CLI: 7.1.0 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X Yosemite
Node Version: v7.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by mpadmaraj** [comment]
I upgraded typescript and the error was resolved. I now have to fix errors in other libraries due to upgrade :(

**Comment by bennyzimmer** [comment]
Same problem here, updating TypeScript don't worked for me

**Comment by dopry** [comment]
```npm install typescript@latest --save-dev```
resolved the issue for me. I wish there were a dependency constraint so I wouldn't have to deal with errors like this.

**Comment by ShirjeelKhan** [comment]
Issue not solve with 
npm install typescript@latest --save-dev

any another solution?

**Comment by CliffyMk** [comment]
refer this
https://github.com/katzer/cordova-plugin-local-notifications/issues/1576
