### ISSUE TITLE
ng-walkthrough kind off intro screen would be great!

### ISSUE THREAD

**Issue by mpadmaraj** [ionic-team/ionic-native#2457]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

Currently Ionic is missing a good intro screen plugin. We do have slide based one but that doesn't look very good on apps. https://github.com/Zefling/ng-walkthrough has a package for angular 5. Was wondering if that could be included natively into Ionic framework.

**Comment by danielsogl** [comment]
You can create your own intro screen with slides. A plugin is not required.
