### ISSUE TITLE
Quality Assurance

### ISSUE THREAD

**Issue by dopry** [ionic-team/ionic-native#2461]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
None of the @ionic-native plugins have any integration tests or qa applied that I can see. Frequently plugins break, I'm getting reports from two of my other project teams that they're also having problems with @ionic-native plugins. 

**Expected behavior:**
I expect plugins not to break builds or cause issues when added to a project. I expect them to work as documented. I expect proactive testing against current and future android builds to ensure reliability of products built on ionic and @ionic-native. 

**Steps to reproduce:**
try using ibeacon on an android 8+ device.
try installing the latest release of local notifications on any device. 

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by danielsogl** [comment]
Our role is not to maintain the plugins by ourself but with the help of the community. Im doing this for low without self-interest. Fell free to open a PR for breaking wrappers.
