### ISSUE TITLE
Missing Parameters in NetworkInterface

### ISSUE THREAD

**Issue by munonex** [ionic-team/ionic-native#2472]
https://github.com/ionic-team/ionic-native/blob/234b6ffd4420299f4e68e2f27d4598649177ef72/src/%40ionic-native/plugins/network-interface/index.ts#L45

Should this line be
`getWiFiIPAddress(success, error): Promise<string> {`?

When I copy the example usage:
`this.networkInterface.getWiFiIPAddress(function (ip) { alert(ip); });`

The current version is getting me error:
> [ts] Expected 0 arguments, but got 1.
(method) NetworkInterface.getWiFiIPAddress(): Promise<string>
Gets the WiFi IP address
@param success — Callback used when successful
@param error — Callback used when failure

**Comment by lalit1002mukati** [comment]
please, tell me how to resolve this issue ,

**Comment by lordjabez** [comment]
As it currently stands, the documentation is wrong. Use a promise, like so:

```
  this.networkInterface.getWiFiIPAddress()
    .then(address => console.info(`IP: ${address.ip}, Subnet: ${address.subnet}`))
    .catch(error => console.error(`Unable to get IP: ${error}`));
```

**Comment by lordjabez** [comment]
There's another issue where the returned Promise is an object, not a string (at least that's true on Android). I'm going to make a PR to address that momentarily.

**Comment by lordjabez** [comment]
Here we go: https://github.com/ionic-team/ionic-native/pull/2587
