### ISSUE TITLE
Geolocation.getPosition() Not working

### ISSUE THREAD

**Issue by anuvak26** [ionic-team/ionic-native#2477]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Getting the an empty JSON {}. 
**Expected behavior:**
If there is an error it should return the message and error code but returing an empty JSON {}

IONIC INFO: 
cli packages: (/home/webdior/.nvm/versions/node/v9.10.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.10.1
    npm  : 5.6.0 
    OS   : Linux 4.13

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

Any help will be appreciated

**Comment by arihantdaga** [comment]
In ionic 4 beta 19. using @ionic-native/geolocation@beta. 
```
const pos = await this.geolocation.getCurrentPosition();
        console.log("Got Position"); // This is never being called. 
```
