### ISSUE TITLE
application does not have sufficient geolocation permissions in ionic 3

### ISSUE THREAD

**Issue by rangholiyanikunj** [ionic-team/ionic-native#2484]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
geolocation plugin not working with some android version 8.0 up devices.

**Expected behavior:**
on page load get current location and display with marker on map.

**Steps to reproduce:**
Follow the steps outlined in https://ionicframework.com/docs/native/geolocation/

**Related code:**
i have to try find out error solution in last 6 days. The following code was used when trouble shooting the install. 

TRY TO CODE 1 : 
getUserPosition(){
  this.options = {
  enableHighAccuracy : false,
  timeout: 30000,
  maximumAge: 15000
  };
  this.geolocation.getCurrentPosition(this.options).then((pos : Geoposition) => {
      this.currentPos = pos;     
      this.addMap(pos.coords.latitude,pos.coords.longitude);
  },(err : PositionError)=>{
    alert("error : " + err.message);
  })
}

TRY TO CODE 2 : 

getUserPosition(){
 navigator.geolocation.getCurrentPosition((pos) => {
        console.log(pos);
        this.addMap(pos.coords.latitude,pos.coords.longitude);
    },
    (error) => console.log(new Date(), error),
    {enableHighAccuracy: false, timeout: 10000, maximumAge: 3000}
);  

TRY TO CODE 3 : 

     navigator.geolocation.getCurrentPosition(
      (position) => {
        this.addMap(position.coords.latitude,position.coords.longitude);
      },
      (error) => alert(error.message)
  )

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

cordova-plugin-geolocation 4.0.1 "Geolocation"

cli packages: (C:\Users\abc\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : Windows 10
```
insert the output from ionic info here
```

**Comment by njejina** [comment]
I have the same problem and I can confirm it too.

**Comment by rangholiyanikunj** [comment]
@njejina I have to find out Second problem solution in ionic 3 with typescript  Angular Google Maps .. It is Working me my project in Android version 7 .

https://angular-maps.com/guides/getting-started/


Thank fully,
Rangholiya nikunj

**Comment by mfouadegy** [comment]
same problem with me it work as expected on ios but not working on android :(

**Comment by rangholiyanikunj** [comment]
@Mohamed I have to find out Second problem solution in ionic 3 with typescript Angular Google Maps .. It is Working me my project in Android version 7 .

https://angular-maps.com/guides/getting-started/

Thank fully,
Rangholiya nikunj

**Comment by jass2125** [comment]
you need to set permission for access native resources, see https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions

**Comment by kapilSoni101** [comment]
@jass2125  sir i have tried but if we add some code in the .xml file but after save change are not save why?

**Comment by kapilSoni101** [comment]
@jass2125:- sir are fixed above issue I have already set permission for native resources it's not working in Android 9 devices plz tell me how to fix?

**Comment by luciano1997** [comment]
tengo el mismo problema y no e logrado solucionarlo

**Comment by prince21590** [comment]
In your ionic project Open config.xml

Add below code at last before `</widget>`
```
<plugin name="cordova-plugin-geolocation" spec="4.0.1">`
       <variable name="GEOLOCATION_USAGE_DESCRIPTION" value="App uses geolocation to determine where you are." />
</plugin>

<platform name="android">
       <uses-permission name="android.permission.ACCESS_COARSE_LOCATION" />
       <uses-permission name="android.permission.ACCESS_FINE_LOCATION" />
       <uses-permission name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
</platform>
```
Using the above change, your app automatically calls a permission dialog when your app uses location details for the first time after a fresh install.

**Comment by amr251ua** [comment]
> @kapilSoni101
> 
> In your ionic project Open config.xml
> 
> Add below code at last before `</widget>`
> 
> ```
> <plugin name="cordova-plugin-geolocation" spec="4.0.1">`
>        <variable name="GEOLOCATION_USAGE_DESCRIPTION" value="App uses geolocation to determine where you are." />
> </plugin>
> 
> <platform name="android">
>        <uses-permission name="android.permission.ACCESS_COARSE_LOCATION" />
>        <uses-permission name="android.permission.ACCESS_FINE_LOCATION" />
>        <uses-permission name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
> </platform>
> ```
> 
> Using the above change, your app automatically calls a permission dialog when your app uses location details for the first time after a fresh install.

You are a life savior, thank you
