### ISSUE TITLE
@ionic-native/health' query method is returning an array always

### ISSUE THREAD

**Issue by ErnstRoca** [ionic-team/ionic-native#2499]
**I'm submitting a ...**
[X] bug report

**Current behavior:**
```(method) Health.query(queryOptions: HealthQueryOptions): Promise<HealthData>``` is returning HealthData, but it's actually returning an array. And i can't do a 'forEach', because does not exist on type 'HealthData'.

**Expected behavior:**
a method returning ```HealthData[]``` or ```HealthData``` when necessary

**Steps to reproduce:**

```
this.health.query({
    startDate: new Date(new Date().getTime() - 365 * 24 * 60 * 60 * 1000),
    endDate: new Date(),
    dataType: 'height'
}).then(res => {
    console.log(res);
}).catch(e => console.log(e));
```

**Other information:**

related issue: [Health: [ts] Property 'forEach' does not exist on type 'HealthData'](1200)

**Ionic info:**

```
cli packages: (C:\Users\xxx\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.1
    npm               : 5.8.0
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\Users\xxx\AppData\Local\Android\sdk

Misc:

    backend : pro
```

**Comment by ahrsavin** [comment]
You can [cast the response to <any>](https://acdcjunior.github.io/typescript-cast-object-to-other-type-or-instanceof.html) as a hack in order to access the Array methods for now

**Comment by gotters** [comment]
I can't even get the health plugin to compile in Android. Did you do anything special to get it to work?
I keep getting the errors below - any advice?

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:574: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ));
                                             ^
  symbol:   variable FITNESS_BLOOD_GLUCOSE_READ
  location: class Scopes
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:576: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ_WRITE));
                                             ^
  symbol:   variable FITNESS_BLOOD_GLUCOSE_READ_WRITE
  location: class Scopes
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:579: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ));
                                             ^
  symbol:   variable FITNESS_BLOOD_PRESSURE_READ
  location: class Scopes
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:581: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ_WRITE));
                                             ^
  symbol:   variable FITNESS_BLOOD_PRESSURE_READ_WRITE
  location: class Scopes
Note: C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
