### ISSUE TITLE
[Feature request] Facebook getDeferredApplink support

### ISSUE THREAD

**Issue by aydemirburak** [ionic-team/ionic-native#2510]
**I'm submitting a ...**  
[ x ] feature request

**Current behavior:**
It seems that cordova-plugin-facebook4 has getDeferredApplink support. However, ionic-native does not have it. 

**Expected behavior:**
Add getDeferredApplink support for the Facebook plugin in ionic-native too

**Other information:**
https://github.com/jeduan/cordova-plugin-facebook4/pull/155

**Comment by DaniShalash** [comment]
Having the same problem here, waiting to be implemented.
