### ISSUE TITLE
MS-ADAL: No Refresh Token there!

### ISSUE THREAD

**Issue by Ahmadre** [ionic-team/ionic-native#2523]
**I'm submitting a ...**
[x] feature request

**Current behavior:**
Successfull Response from our Azure AD, but got only AccessToken, etc. but NO RefreshToken! How can I refresh my actual AccessToken now?

**Expected behavior:**
To get a normal RefreshToken to my AccessToken! Besides an Authorization-Code would be fine, to do it by myself!

**Steps to reproduce:**
It's clearly a feature needed here, no reproduce needed...

**Related code:**

```js
this.authContext.acquireTokenAsync('https://graph.microsoft.com', config.azure_client_id_nativ, "http://localhost:8080", "",encodeURI('code'))
                .then((authResponse: AuthenticationResult) => {
                  myloading.dismiss();
                  console.log('Authentication successfull', authResponse);
                  console.log('Authentication successfull', authResponse.createAuthorizationHeader());
                  console.log('Authentication successfull', authResponse.isMultipleResourceRefreshToken);  <--- WHAT DOES THIS VARIABLE MEANS?!
                })
                .catch((e: any) => {
                  let alert = this.alertCtrl.create({
                    title: "Authentication failed",
                    subTitle: JSON.stringify(e),
                    buttons: ["OK"]
                  });
                  alert.present();
                  myloading.dismiss();
                  console.log('Authentication failed', e);
                });
```

**Ionic info:**

```bash
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v9.3.0
    npm        : 5.7.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by danielsogl** [comment]
Please pay attention to your pronunciation.

This is not related to our native wrapper. Please open a new issue here: https://github.com/AzureAD/azure-

**Comment by Ahmadre** [comment]
@danielsogl here you go. corrected my pronunciation. Thanks I will open an issue there

**Comment by Ahmadre** [comment]
@danielsogl by the way: I think I am right here with my Issue, because I already implemented the ADAL Library in my PWA (like you recommended the adal source) and I am getting a successfull Refresh Token. Just in the Ionic-Plugin it is missing.

**Comment by Ahmadre** [comment]
okay got it! Thanks Daniel

**Comment by Ahmadre** [comment]
Figured out, that Cordova is not exposing the refresh token to security reasons. Maybe I will find another way to get my employee's stay logged in on their iOS and Android devices...
