### ISSUE TITLE
iOS Publishing

### ISSUE THREAD

**Issue by datastone** [ionic-team/ionic-native#2527]
Apple replied as this when my build sent 

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by danielsogl** [comment]
You have to set the NSPhotoLibraryUsageDescription key by yourself as Apple mentioned.

Read more about it here: https://medium.com/collaborne-engineering/cordova-ios-10-nscamerausagedescription-missing-fbcbe5e41565
