### ISSUE TITLE
Firebase Messaging: 404 Not Found

### ISSUE THREAD

**Issue by Genarito** [ionic-team/ionic-native#2532]
**I'm submitting a ...**
[ ] bug report
[x ] feature request

**Current behavior:**
When I tried to install @ ionic-native/firebase-messaging, it's not available

**Expected behavior:**
Install @ionic-native/firebase-messaging normally

**Steps to reproduce:**
npm install --save @ ionic-native/firebase-messaging

**Comment by windwp** [comment]
i have same issue 
'@ionic-native/firebase-messaging' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by adamduren** [comment]
The reason for this is the last release of `ionic-native` was on April 9th. This plugin was added to the repo early June. They'll have to release another version in order for it to be published to NPM. In the meantime you can compile the plugin yourself.

Here's a general howto to help get you on the right track:

```
# Clone ionic-native and install deps
cd $YOUR_WORKSPACE
git clone git@github.com:ionic-team/ionic-native.git
cd ionic-native
npm install

# build the plugin (you can name multiple plugins if needed)
npm run build firebase-messaging
cd dist/@ionic-native/firebase-messaging

# Install option 1 using npm link (will not add to package.json)
npm link
cd $YOUR_IONIC_PROJECT
npm link @ionic-native/firebase-messaging

# Install option 2 using npm install (will add to package.json)
npm install $PATH_TO_IONIC_NATIVE/dist/@ionic-native/firebase-messaging 
```

**Comment by Genarito** [comment]
Thank you so much!
