### ISSUE TITLE
@ionic-native/crop - Plugin not installed

### ISSUE THREAD

**Issue by AdamKernig** [ionic-team/ionic-native#2535]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When trying to use the software issues plugin not installed
**Expected behavior:**

```
following the guidelines in the docs```

**Other information:**
Error info:

Error: Uncaught (in promise): plugin_not_installed
    at c (http://192.168.0.18:8100/build/polyfills.js:3:19752)
    at c (http://192.168.0.18:8100/build/polyfills.js:3:19461)
    at http://192.168.0.18:8100/build/polyfills.js:3:20233
    at t.invokeTask (http://192.168.0.18:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://192.168.0.18:8100/build/vendor.js:5125:33)
    at t.invokeTask (http://192.168.0.18:8100/build/polyfills.js:3:15581)
    at r.runTask (http://192.168.0.18:8100/build/polyfills.js:3:10834)
    at o (http://192.168.0.18:8100/build/polyfills.js:3:7894)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.9
Angular Core: 5.2.10
Angular Compiler CLI: 5.2.10
Node: 9.4.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (C:\Users\Kerni\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.4.0
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\Kerni\AppData\Local\Android\Sdk

Misc:

    backend : pro
```
Some more info

```
 "dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/compiler-cli": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@ionic-native/camera": "4.5.3",
    "@ionic-native/core": "^4.7.0",
    "@ionic-native/crop": "^4.7.0",
    "@ionic-native/in-app-browser": "^4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/storage": "^2.1.3",
    "aws-amplify": "^0.2.15",
    "aws-amplify-angular": "^0.1.4",
    "cordova-plugin-crop": "~0.4.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic": "^4.1.7",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
```
Package.json

```
   <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-ionic" spec="^4.1.7">
        <variable name="APP_ID" value="5dc3d3f2" />
        <variable name="CHANNEL_NAME" value="Master" />
        <variable name="UPDATE_METHOD" value="auto" />
        <variable name="WARN_DEBUG" value="true" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="MAX_STORE" value="2" />
    </plugin>
```

Config.xml

`<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="1.1.19" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="2.0.5" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-ionic" spec="^4.1.7">
        <variable name="APP_ID" value="5dc3d3f2" />
        <variable name="CHANNEL_NAME" value="Master" />
        <variable name="UPDATE_METHOD" value="auto" />
        <variable name="WARN_DEBUG" value="true" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="MAX_STORE" value="2" />
    </plugin>`

**Comment by AkiraEndoGroup** [comment]
same here.

**Comment by AdamKernig** [comment]
Just to add this is still not working, I have dove into the Core.js of the file trying to error out the plugin, and it doesn't seem to reference correctly.

**Comment by bdruhan** [comment]
same here.

**Comment by yordlegunner** [comment]
are you using Ionic DevApp or running on device with "ionic cordova run..."
i had this error and it was because i was using a plugin that was not compatible with the devapp, the it worked fine with a builded apk

**Comment by AdamKernig** [comment]
Im using the dev app which this module is supposed to cater for. I know
this works if you emulate the device or do a native download and try it but
the point is i cant through dev app.

**Comment by yordlegunner** [comment]
the @ionic-native/crop plugin is not on the list that the devapp support

**Comment by AdamKernig** [comment]
Can you please link to the list

**Comment by yordlegunner** [comment]
@AdamKernig https://ionicframework.com/docs/pro/devapp/#native-cordova-plugin-support

**Comment by danielsogl** [comment]
I’m closing this issue. The sac app supports following  plugins: https://ionicframework.com/docs/pro/devapp/

**Comment by AdamKernig** [comment]
Thanks for that perfect. I have made my own crop tool in the meantime but i
have to say this is in a poor place for the docs. My suggestion would be
have tge components labelled on the docs saying if its compatible or not.

**Comment by danielsogl** [comment]
I will keep that in mind. Thanks for your feedback.
