### ISSUE TITLE
📲 [NFC] Uncaught (in promise): plugin_not_installed

### ISSUE THREAD

**Issue by dwiyatci** [ionic-team/ionic-native#2538]
**I'm submitting a ...**
[x] bug report

**Current behavior:**

Following the instructions in [Ionic Native - NFC docs](https://ionicframework.com/docs/native/nfc) throws a delicate error after developing a simple example NFC app.

![screenshot_20180607-000514](https://user-images.githubusercontent.com/4405796/41067882-761dc6d8-69e7-11e8-9c20-92bd6ea26db6.png)

**Expected behavior:**

Following the instructions in [Ionic Native - NFC docs](https://ionicframework.com/docs/native/nfc) should work for developing a simple example NFC app.

**Steps to reproduce:**

- `ionic start ionic-nfc-example blank` (with Cordova integration and without the free Ionic Pro SDK).
- `ionic cordova plugin add phonegap-nfc`.
- `npm install --save @ionic-native/nfc`.
- [Add the NFC plugin to my app's module](https://github.com/dwiyatci/ionic-nfc-example/blob/master/src/app/app.module.ts).
- [Adapt the source code of the "home" page](https://github.com/dwiyatci/ionic-nfc-example/blob/master/src/pages/home/home.ts) based on the [usage snippet](https://ionicframework.com/docs/native/nfc/#usage).
- `ionic serve -c`.
- Test the app on my Android device using Ionic DevApp.

**Related code:**

```ts
ionViewDidEnter() {
  console.log('ionViewDidEnter');
  this.startNFC();
}

startNFC() {
  this.platform.ready().then(() => {
    console.log('nfc installed:', NFC.installed()); // false :(

    this.nfc.addNdefListener(() => {
      console.log('successfully attached ndef listener');
    }, (err) => {
      console.log('error attaching ndef listener', err);
    }).subscribe((event) => {
      console.log('received ndef message. the tag contains: ', event.tag);
      console.log('decoded tag id', this.nfc.bytesToHexString(event.tag.id));

      let message = this.ndef.textRecord('Hello world', 'en', '1');
      this.nfc.share([message]).then(this.onSuccess).catch(this.onError);
    });
  });
}
```

**Other information:**

Please find the complete repo here: https://github.com/dwiyatci/ionic-nfc-example.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/gdwiy/.nvm/versions/node/v8.9.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.0
    npm  : 5.7.1 
    OS   : Linux 4.4

Environment Variables:

    ANDROID_HOME : ~/android_sdk

Misc:

    backend : pro
```

**Comment by don** [comment]
@dwiyatci I ran your project with `ionic cordova run android --device` and it scanned a NFC tag ok. I used chrome://inspect to see the output.)

![ionic-nfc](https://user-images.githubusercontent.com/3133/41071007-ceb13556-69c3-11e8-81a2-6445205dffa7.jpg)

I haven't used Ionic DevApp. Make sure the app has the phonegap-nfc plugin installed. It also could be a timing / initialization issue when you're using the DevApp.

**Comment by dwiyatci** [comment]
Thank you so much, @don ! After the whole day doing the "chores" work, I finally managed to make it _partially_ work. (but I'm so happy already :grin: )
- fix ["no permissions (user in plugdev group; are your udev rules wrong?)"](https://developer.android.com/studio/run/device) issue on my Ubuntu GNU/Linux with this [solution](http://www.janosgyerik.com/adding-udev-rules-for-usb-debugging-android-devices).
- change WebView implementation to `Chrome Stable` (via Developer options).
- `yarn global upgrade cordova --latest`
- `sdkmanager --update`
- `rimraf node_modules platforms plugins`
- `yarn install`
- `ionic cordova platform run android --device`
- `chrome://inspect/#devices`

![screenshot from 2018-06-08 15-05-14](https://user-images.githubusercontent.com/4405796/41161214-6575f12e-6b32-11e8-9c92-36847aa8eb44.png)

I'm really wondering now why I cannot make the "receive ndef message" work (I tested with two different smartphones with two different credit cards that have NFC tag). Do you have any other clues?

**Comment by don** [comment]
> two different credit cards 

The credit cards are probably not NDEF tags. They are some other NFC tag. Use an app like [NFC TagInfo by NXP](https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en_US) to verify your phone can read the tag.

In your code, replace addNdefListener with [addTagDiscoveredListener](https://ionicframework.com/docs/native/nfc/#addTagDiscoveredListener).

**Comment by dwiyatci** [comment]
> In your code, replace addNdefListener with addTagDiscoveredListener.

That's it. This made my day. A happy Friday ending. Thank you so much once again @don. Bless! 🙏

**Comment by mas57es** [comment]
Sorry, I´m going through highs and lows, centaurs, cyclops, hydras and now i can hear de unicorns approaching.  Can you help me? I can´t find wher is my error!!

![captura de pantalla 2019-02-22 a las 17 45 46](https://user-images.githubusercontent.com/36925456/53257357-33b05a80-36ca-11e9-87c4-df3906817681.png)

**Comment by kensodemann** [comment]
Locking this since it is a closed and resolved issue.

@mas57es - for your issue, that is more of a support request than anything else, which belongs either in our forum or in StackOverflow, etc. and not in the issues list.

That said, based solely on the error you are getting, it looks like perhaps you are not following proper version discipline. Please check that the versions of your `@ionic-native/*` items are consistent, so if you are using `@ioninc-native/core` version 4.20.0 you are also using 4.20.0 for you other `@ionic-native` stuff and not a mix if v4.x and v5.x
