### ISSUE TITLE
Expected 2 arguments but got 3 - SQLite Porter

### ISSUE THREAD

**Issue by Raja77777** [ionic-team/ionic-native#2540]
SQLite Porter arguments issue.

this.sqlitePorter.importJsonToDb(this.database, json,successfn)

Hi i am stucked in this and i want to know how to pass the 3rd parameter to importjsonTodb function.
Whenever i include the 3rd opts param it says expected 2 but u given 3 in cordova ionic.
Anyone can help please ??

**Comment by Raja77777** [comment]
SQLite Porter arguments issue.

this.sqlitePorter.importJsonToDb(this.database, json,successfn)

Ionic native does not support the 3rd param but in the porter plugin documentation they have mentioned it.

**Comment by dpa99c** [comment]
Since you are using the [Ionic Native Typescript wrapper](https://ionicframework.com/docs/native/sqlite-porter/) for the plugin, you should be using the returned promise for the success/error callbacks:

    this.sqlitePorter.importJsonToDb(this.database, json)
      .then(() => console.log('Imported'))
      .catch(e => console.error(e));
