### ISSUE TITLE
Expected 2 arguments but got 3 - SQLite Porter

### ISSUE THREAD

**Issue by Raja77777** [ionic-team/ionic-native#2556]
SQLite Porter arguments issue. this.sqlitePorter.importJsonToDb(this.database, json,successfn) Hi i am stucked in this and i want to know how to pass the 3rd parameter to importjsonTodb function. Whenever i include the 3rd opts param it says expected 2 but u given 3 in cordova ionic. Anyone can help please ??

**Comment by dpa99c** [comment]
Duplicate of #2540
