### ISSUE TITLE
Cannot create plugin

### ISSUE THREAD

**Issue by jonmcclung** [ionic-team/ionic-native#2568]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am unable to create a new plugin

**Expected behavior:**
`src/@ionic-native/plugins/fibonacci/` should be created, containing a single file, `index.ts`.

**Steps to reproduce:**
```
git clone https://github.com/ionic-team/ionic-native
cd ionic-native
npm i
gulp plugin:create -n fibonacci
```
**Related code:**

**Other information:**
```
$ gulp plugin:create -n fibonacci
gulp plugin:create -n fibonacci[7997]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x3006bd8841bd
Abort trap: 6
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v10.4.0
    npm  : 6.1.0
    OS   : macOS Sierra

Misc:

    backend : pro
```

**Comment by tiangolo** [comment]
I'm seeing the same error trying to modify a plug-in.

The error is due to an issue related to one of Gulp dependencies' version not being handled well in Node v10.

It is documented here: https://github.com/nodejs/node/issues/20325, https://github.com/gulpjs/gulp/issues/2162, https://github.com/nodejs/node/issues/19786, https://github.com/gulpjs/gulp/issues/2162

To fix is is required to update the dependencies:

```bash
rm -rf ./node_modules
rm package-lock.json
npm install
```

**Comment by danielsogl** [comment]
Ionic Native v4 supports nodes 8 not 10. V5 is fine with Node 10
