### ISSUE TITLE
BLE.autoconnect

### ISSUE THREAD

**Issue by don** [ionic-team/ionic-native#2573]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
BLE.autoConnect returns an Observable which only works on time. The for Cordova, connect/success and disconnect/failure functions are called multiple times. With an Observable the disconnect function can only be called 1x.

https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/ble/index.ts#L306-L313

**Expected behavior:**
BLE.autoconnect needs to return callbacks. I think the right way to do this is to wrap as a sync function and use the callbacks directly?

**Other information:**
Do any other plugins have callbacks that are called many times? It'd be nice if the behavior here matched other Ionic plugins.

I'll send a pull request to fix this once I figure out the right way to do this.

**Comment by don** [comment]
My [current fix](https://github.com/don/ionic-native/commit/7f339b64a70c94b44fa260821edf9af1756eafab) for this uses  `@Cordova({ sync: true })` which provides access to the callbacks from Ionic.  It works but the user needs to bind the callbacks to this, which isn't ideal.

    this.ble.autoConnect(MAC_ADDRESS, this.onConnected.bind(this), this.onDisconnected.bind(this));

@danielsogl @ihadeed @mhartington is there any way to have the Cordova wrapper bind callbacks for the user?

**Comment by DanishaRegil** [comment]
Is this fix in production, if not wen can we expect
