### ISSUE TITLE
ionic2 diagnostic plugin not installed even after installed

### ISSUE THREAD

**Issue by sureshgowd1321** [ionic-team/ionic-native#2577]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Hi everyone !

I am currently working on an ionic 2 app and i need to get my user allow us using his device's GPS.

Thus, i tried to install Diagnotic plugin ... and encountered some issues.

console.warn: Native: tried calling Diagnostic.getPermissionAuthorizationStatus, but the Diagnostic plugin 
            is not installed. 
[01:27:36]  console.warn: Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic' 

**Expected behavior:**
camera should ask user to request access for Camera

**Steps to reproduce:**

**Related code:**

```
ionic plugin add cordova.plugins.diagnostic
npm install --save @ionic-native/diagnostic
```

**Comment by jonathan-jd4software** [comment]
@sureshgowd1321 I am experiencing the same issue

**Comment by danielsogl** [comment]
Have you tried this on a native device or in your browser, because not all plugins support the browser platform.

**Comment by jonathan-jd4software** [comment]
@danielsogl I am testing it in Ionic DevApp on a MotoG5 phone

**Comment by danielsogl** [comment]
Check out the supported plugins here: https://ionicframework.com/docs/pro/devapp/

The Diagnostic plugin is not supported.

**Comment by jonathan-jd4software** [comment]
@danielsogl thank you for the guidance
