### ISSUE TITLE
v5 beta 13 - At least one plugin still has beta 12 code

### ISSUE THREAD

**Issue by geo242** [ionic-team/ionic-native#2583]
**I'm submitting a bug**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
npm package for v5 beta 13 does not match tagged version. It seems to match beta 12

**Expected behavior:**
npm package should match tagged version

**Steps to reproduce:**
"npm i @ionic-native/star-prnt@5.0.0-beta.13" then compare ngx/index.d.ts to the tagged version of the same file

**Comment by danielsogl** [comment]
Please update to beta 14
