### ISSUE TITLE
problem with the firebase in ionic 3

### ISSUE THREAD

**Issue by ali125** [ionic-team/ionic-native#2600]
I have problem with the firebase in ionic 3
first I create a new project and when I add firebase plugin , I cannot build app

same as this steps:
1- ionic start myApp blank
2- ionic cordova plugin add cordova-plugin-firebase
3- npm install --save @ionic-native/firebase
4- ionic cordova build --release --prod android

What should l do????

-- my command after step 4

:app:compileReleaseJavaWithJavac
<path>\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:129: error: constructor Builder in class Builder cannot be applied to given types;
            NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId);
                                                             ^
  required: Context
  found: FirebasePluginMessagingService,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 36s
27 actionable tasks: 27 executed
(node:24524) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\Mortazavi\Desktop\Projects\Test\ionic\myApp4\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:129: error: constructor Builder in class Builder cannot be applied to given types;
            NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId);
                                                             ^
  required: Context
  found: FirebasePluginMessagingService,String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 36s
    at ChildProcess.whenDone (<path>\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:24524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by IvanLencina** [comment]
Same here

**Comment by danielsogl** [comment]
This has nothing to do with the ionic native wrapper. Please open an issue at the plugin source repository.
