### ISSUE TITLE
@ionic-native/diagnostic getMicrophoneAuthorizationStatus returns status as string on IOS and as object { RECORD_AUDIO: string } on Android

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-native#2617]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

https://ionicframework.com/docs/native/diagnostic/#getMicrophoneAuthorizationStatus method invoked under iOS returns status as a string and when invoked under Android returns an object with property RECORD_AUDIO
@ionic-native/diagnostic version is 4.10.1

**Expected behavior:**

It must behave and return string under both iOS and Android

**Steps to reproduce:**

Inovke https://ionicframework.com/docs/native/diagnostic/#getMicrophoneAuthorizationStatus under iOS and Android and expect the returned value.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
cli packages: (/Users/alexryltsov/.nvm/versions/node/v6.9.2/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 6.5.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v6.9.2
    npm               : 3.10.9
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /Users/alexryltsov/Library/Android/sdk/

Misc:

    backend : pro

**Comment by ryaa** [comment]
diagnostic.requestRuntimePermission(this.diagnostic.permission.WRITE_EXTERNAL_STORAGE) also returns object on Android instead of a string.

**Comment by dpa99c** [comment]
This was raised against the plugin as https://github.com/dpa99c/cordova-diagnostic-plugin/issues/324 and fixed in plugin v4.0.10
