### ISSUE TITLE
ionic-native issue

### ISSUE THREAD

**Issue by ssudhakar14** [ionic-team/ionic-native#2625]
ionic 4 application:-

I use ionic-native/camera in my application but got this issue:-

TypeError: Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["Cordova"]) is not a function. (In 'Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["Cordova"])

**Comment by ivas123** [comment]
Make sure you are installing the beta version of ionic-native/camera as that will contain angular compatibility `npm install --save @ionic-native/camera@beta`. Also, make sure to add the plugin into your app.module.ts. I believe this is an issue with the docs not specifying what version to get.

```
import { Camera } from '@ionic-native/camera/ngx'; 

providers: [  Camera ]

```

**Comment by abdoullaye** [comment]
tank your
