### ISSUE TITLE
Ionic Native Doc does not mention the plugin version we should get for Ionic V4

### ISSUE THREAD

**Issue by ivas123** [ionic-team/ionic-native#2627]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When doing `npm install --save @ionic-native/plugin` we are getting the incorrect version of a plugin. This will not work with Ionic V4 as it needs angular compatibility and does not have the ngx folder.

**Expected behavior:**
The docs should tell us to get `npm install --save @ionic-native/plugin@beta` as this will have the ngx folder and therefore be compatible with Ionic V4. As such we are able to reference it inside app.module.ts without getting any errors. 

**Note**: This is a temporary issue as I know it will be fixed after ionic v4 comes out of beta.

```
import { Plugin } from '@ionic-native/plugin/ngx';

providers: [ Plugin ]
```

**Comment by danielsogl** [comment]
I added the @beta tag to the docs. @perrygovier will fix the usage sections.
