### ISSUE TITLE
Camera Plugin: Photo Library Usage Description is not requested on iOS

### ISSUE THREAD

**Issue by Mike1707** [ionic-team/ionic-native#2634]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Unfortunately, the dialog for the Photolibrary Usage Permission is **not showing**. The **permission will be granted immediately**. In the info.plist file is a description stated (see screenshot below). This behavior can be seen in all of my ionic apps and some apps from the Appstore which are implemented with ionic. The permission for the Camera is working fine.

Also, there is no entry in the iOS settings for the App to prohibit the access:

![img_1109](https://user-images.githubusercontent.com/10029709/43993981-a582899a-9d95-11e8-84bc-2661eabd5205.png)

Missing: 

<img width="743" alt="bildschirmfoto 2018-08-11 um 18 27 41" src="https://user-images.githubusercontent.com/10029709/43993868-47830816-9d94-11e8-9fad-70597dc8281f.png">

**Expected behavior:**

Ask for Photolibrary permissions and show the option in the iOS settings to prohibit the access.

**Steps to reproduce:**

Just use the plugin with `sourceType: this.camera.PictureSourceType.PHOTOLIBRARY` and set a `Privacy - Photo Library Usage Description` in your *.plist file.

Also tested with internal/external Testflight testers.

**Related code:**

Implementation of the camera plugin usage:

```
const options: CameraOptions = {
      quality: 80,
      destinationType: this.camera.DestinationType.FILE_URI,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      encodingType: this.camera.EncodingType.JPEG,
      saveToPhotoAlbum: false,
      correctOrientation: true,
      targetWidth: 500,
      targetHeight: 500,
      mediaType: this.camera.MediaType.PICTURE
};

try {
      let imageData = await this.camera.getPicture(options);
} catch (err) {
      console.error(err);
}

```

**Other information:**

info.plist screenshot:

<img width="824" alt="bildschirmfoto 2018-08-11 um 18 29 13" src="https://user-images.githubusercontent.com/10029709/43993933-feebd7e4-9d94-11e8-86e5-160266cda699.png">

Versions: 

`"@ionic-native/camera": "4.11.0"`
`<plugin name="cordova-plugin-camera" spec="^4.0.3">...</plugin>`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.0.6 (/Users/mike/.nvm/versions/node/v10.7.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 2.0.0
   NodeJS            : v10.7.0 (/Users/mike/.nvm/versions/node/v10.7.0/bin/node)
   npm               : 6.3.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/mike/Library/Android/sdk
```

**Comment by Mike1707** [comment]
I still have this issue. Fortunately, apple has not noticed this yet. Hopefully, one of the ionic developers will comment this soon.

**Comment by MrDrProfX** [comment]
Same issue, but apple DID notice :(

**Comment by MrDrProfX** [comment]
I ended up switching to this library for getting library photos: https://ionicframework.com/docs/native/image-picker/

**Comment by Boby** [comment]
I am reopening this issue as none has shown answers to be solved?

**Comment by Mike1707** [comment]
Well, I don‘t know, I gave up using Ionic and implemented native apps.

**Comment by Boby** [comment]
yeah this have been going on where none was fixed for the ios case..

**Comment by dcxn** [comment]
Greetings and thank you for the nice description of the issue Mike1707. I have the same issue and had my company app rejected by Apple. I have all the privacy texts correctly set up in the plist. I am able to replicate this bug on a clean page on an ionic app, with only a single button calling the `camera.getPicture()` method:

1. when I call it with `sourceType: PictureSourceType.PHOTOLIBRARY`, the app **will NOT** prompt the NSPhotoLibraryUsageDescription text popup and ask for permission, it just opens the camera roll automatically as if permission was granted by default (and thus why Apple rejected my app)
2. when I use `sourceType: PictureSourceType.CAMERA`, the app will correctly ask for permission and show the popup and NSCameraUsageDescription text I specified

@jcesarmobile any ideas why sourceType set to library does not show the popup as it should?
