### ISSUE TITLE
ionic-native/code-push has wrong dependencies listed in package.json, will not ngc compile

### ISSUE THREAD

**Issue by dmitriv2** [ionic-team/ionic-native#2640]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
If you have an ionic version that runs with angular 4, and install the latest @ionic-native/code-push you will get an error during a production build. ngc will give a "Metadata version mismatch for module..." error. 

The npm package metadata file is clearly "version: 4" which points to angular 5.

The package.json for code-push should have the right peer Dependencies

**Expected behavior:**
code-push 4.4.0 and above should tell you that you need a higher version of ionic (^3.9.0 i think?) and angular ^5

Also, please kindly update documentation to say use version 4.3.3 or below for angular 4 compatibility.

**Steps to reproduce:**
start a basic ionic project with ionic 3.8.0, install @ionic-native/code-push latest, if you're using the code-push code run 'ionic cordova build browser --prod' you should see the error. 

Also, just get ionic-native/code-push from npm and look at index.metadata.json, you will see "version":4 which means it will only work with angular 5

**Related code:**

```
[{"__symbolic":"module","version":4,
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.0.6
   Ionic Framework    : ionic-angular 3.8.0
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.2.3, browser 4.1.0

System:

   NodeJS : v6.10.2 (C:\Program Files\nodejs\node.exe)
   npm    : 3.10.10
   OS     : Windows 7

Environment:

   ANDROID_HOME : not set
```

**Comment by danielsogl** [comment]
You habe to Uwe ng v5 becaise ionic 3 dopendes on Angular 5.
