### ISSUE TITLE
plugin background-fetch

### ISSUE THREAD

**Issue by jseter** [ionic-team/ionic-native#2656]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
configure method returns a promise and has no mechanism for passing a callback.  The current implementation will only complete the promise the first time the callback fires and will silently ignore future callbacks.

**Expected behavior:**
```
@param {Function} callbackFn This callback will fire each time an iOS background-fetch event occurs (typically every 15 min).
@param {Function} errorCallback The failureFn will be called if the device doesn't support background-fetch.
```
Per the original code, and the plugin documentation, the callback is fired multiple times.
It needs to either be a sync void returning function that accepts a callback and error callback or wrapped with a cold observable.

**Steps to reproduce:**

configure a simple background fetch application that appropriately calls configure once, while operating in the background continuously for multiple 15-minute intervals.

**Related code:**

**Comment by chrisjdev** [comment]
I think this can be fixed by changing 
```javascript
BackgroundFetch.prototype.configure = function (config) { return cordova(this, "configure", { "callbackOrder": "reverse" }, arguments); };
```
to
```javascript
BackgroundFetch.prototype.configure = function (config) { return cordova(this, "configure", { "callbackOrder": "reverse", "observable": true }, arguments); };
```
And then updating the documentation to reflect the change that it's now an Observable.

**Comment by thibaud-sanchez** [comment]
This plugin is unusable and is now compatible with Android but marked as compatible only with iOS.
How can we contribute to make it compatible ?
