### ISSUE TITLE
Add GoogleMaps to the v4 api list page

### ISSUE THREAD

**Issue by wf9a5m75** [ionic-team/ionic-native#2658]
Please add  @ionic-native/google-maps to https://beta.ionicframework.com/docs/native page.

@ionic-native/google-maps v5.0.0-beta works on ionic v4

**Comment by wf9a5m75** [comment]
@mlynch ping

**Comment by wf9a5m75** [comment]
`the maintainer of that plugin decided` is me.

The reason of this is the ionic team does not maintenance the wrapper plugin well.
If I sent a new pull request, you left almost 2 months. That's why I got angry, then divided to different repo.
If you guarantee to manage well, I don't need to manage the wrapper plugin.

I don't ask any difficult thing. I just ask `please add a link to the google maps repo`, like this page.
https://ionicframework.com/docs/native/

Is this super difficult?

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native/blob/fe5b7ce0afce7aabf7b539890f6699ce8b89a4c6/scripts/docs/processors/jekyll.js#L13-L17

**Comment by wf9a5m75** [comment]
@perrygovier Any comments?

**Comment by wf9a5m75** [comment]
Run away?

**Comment by wf9a5m75** [comment]
Ok, if Ionic team does not help me, I won't help you. Starting from now until you work, I will decline any issues for the ionic-native/google-maps.

**Comment by wf9a5m75** [comment]
Thank you for your replying, I understand that.
I didn't know the `ionic-docs` repo. That's why I ignored first two days.

> I was hoping I could write a script to inspect it and automatically generate a docs page like the others, but a link would work for now.

Creating a doc page is difficult from different repo, and I think the general doc pages are less information.
There are already doc pages, and I will put latest information to here.
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/README.md

Could you add a link to this page when you are available?  I just want to ask you only this one.
Thanks.

**Comment by perrygovier** [comment]
Hey @wf9a5m75, adding this should be very quick and easy, but the larger build script needs some updates to get it to take effect on the website. I can't do it today, but it should be soon.

**Comment by wf9a5m75** [comment]
Okay, effecting a link in next time update is fine. Thanks for your help.

**Comment by wf9a5m75** [comment]
Great! Thank you!

**Comment by wf9a5m75** [comment]
@perrygovier Could you add a link to Google Maps repo URL in the new list? https://ionicframework.com/docs/native

**Comment by perrygovier** [comment]
Ah, the docs were refactored and the person who took it over didn't know about this special case. I've brought him up to speed.

**Comment by wf9a5m75** [comment]
Then when will you (he) add Google Maps link to the list page? I waited 4 days, but no updated.
