### ISSUE TITLE
possible to add this plugin ? audio file to base64

### ISSUE THREAD

**Issue by arsewizz** [ionic-team/ionic-native#2670]
in many case we need to upload audio file to a server, but before to do this we need to convert it.
[the cordova audio convert](https://github.com/jimmylagp/Base64-Encode-Decode-Audio)

**Comment by danielsogl** [comment]
Feel free to create a PR. Actually I don't have enough time to add new plugins by my self.

**Comment by danielsogl** [comment]
Read the Developer Guide: https://github.com/ionic-team/ionic-native/blob/master/DEVELOPER.md

**Comment by arsewizz** [comment]
the documentation is not clear, after reading I do not find myself. I find this article but nothing passes [Writing a Ionic Native wrapper for  the existing/created Cordova plugin](https://silviu-s.com/how-to-create-cordova-plugin-with-ionic-framework-native-support/)

**Comment by danielsogl** [comment]
The documentation is clear. Follow other plugin wrappers as examples. Your linked articles are about creating a native plugin with Cordova but you have to write an ionic wrapper, not the plugin itself.
