### ISSUE TITLE
Ionic-v4 and Native BLE: write doesn't work

### ISSUE THREAD

**Issue by smartifier-salomaa** [ionic-team/ionic-native#2673]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
BLE plugin write function expects ArrayBuffer and following the example on the docs, doesn't work anymore in Ionic v4. Code that used to output ArrayBuffer (array.buffer) now outputs ArrayBuffer | SharedArrayBuffer. 

Type 'ArrayBuffer | SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
  Type 'SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
    Types of property '[Symbol.toStringTag]' are incompatible.
      Type '"SharedArrayBuffer"' is not assignable to type '"ArrayBuffer"'.

I tried changing the type definitions to ArrayBuffer | SharedArrayBuffer, but BLE.write function doesn't work. The promise is never resolved.

```
To Native Cordova ->  BLE write BLE1198508039 ["options": [CE249DA5-9692-528C-54A5-2ED088FB9D0B, 00abba00-536d-6172-7469-666965720000, 00abba02-536d-6172-7469-666965720000, {
}]]
getData
Looking for 00abba02-536D-6172-7469-666965720000 with properties 8
```
**Expected behavior:**
Code would compile and BLE.write function works as expected.

**Steps to reproduce:**

**Related code:**

```
  // ASCII only
  function stringToBytes(string) {
     var array = new Uint8Array(string.length);
     for (var i = 0, l = string.length; i < l; i++) {
         array[i] = string.charCodeAt(i);
      }
      return array.buffer;
  }
```

**Other information:**
Ionic Native BLE:
[https://beta.ionicframework.com/docs/native/ble](https://beta.ionicframework.com/docs/native/ble)

Cordova plugin: cordova-plugin-ble-central
[https://github.com/don/cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central)

In package.json:
```
"@ionic-native/core": "5.0.0-beta.15"
"@ionic-native/ble": "^5.0.0-beta.15"
"cordova-plugin-ble-central": "^1.2.2"
"typescript": "^2.9.2"
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.5

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.7
   @capacitor/core           : 1.0.0-beta.7

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Comment by juanct** [comment]
I am working with Native Ble in Ionic-v4 and I just cast the buffer argument to type ArrayBuffer and know write function is working correctly:

`array.buffer as ArrayBuffer`

**Comment by smartifier-salomaa** [comment]
Can you check the BLE plugin name and version you are using? I'm using
`"cordova-plugin-ble-central": "^1.2.2"`

Also, can you paste here the code, where you convert your write value to ArrayBuffer? 

I tried the following code without success:

```
private numberToBytes(number: number): ArrayBuffer {
  let array = new Uint8Array(1);
  array[0] = number;
  return array.buffer as ArrayBuffer;
}
```

When I was running my code on Android, I noticed that my write generates an **Error 13** when run on Android (for some reason iOS doesn't return error promise).
**Error 13 is GATT_INVALID_ATTRIBUTE_LENGTH**

That would indicate something goes wrong when converting the write value to ArrayBuffer. 

Actual write code that I'm using is:

```
private write(deviceId: string, serviceUUID: string, characteristicUUID: string, value: ArrayBuffer): Promise<any> {
  return this.ble.write(deviceId, serviceUUID.toLowerCase(), characteristicUUID.toLowerCase(), value);
}
```

**Comment by juanct** [comment]
I am using:

```
@ionic/angular": "^4.0.0-beta.7
@ionic-native/ble": "^5.0.0-beta.17
@ionic-native/core": "^5.0.0-beta.17
cordova-plugin-ble-central": "^1.2.2
typescript": "~2.9.2
```

I test your functions and I don't get any error on android, my code is the following:

```
public Playbletest(): void{
this.write(this.peripheral.id,"1900","2b03",this.numberToBytes(97)).then(
()=>{
console.log("write correct");
},
()=>{
console.log("error writing");
}
);
}

private numberToBytes(number: number): ArrayBuffer {
  let array = new Uint8Array(1);
  array[0] = number;
  return array.buffer as ArrayBuffer;
}

private write(deviceId: string, serviceUUID: string, characteristicUUID: string, value: ArrayBuffer): Promise<any> {
  return this.ble.write(deviceId, serviceUUID.toLowerCase(), characteristicUUID.toLowerCase(), value);
}
```

I am testing in motorola g5 plus device for android and using a nrf51822 dev board to make the connection.

My code for the connection:

```
public CancelScan(): void{ 
  if(this.timeoutvar !== null){
  clearTimeout(this.timeoutvar);
  }
  this.setStatus('Timeout error');
  this.ble.stopScan().then(()=>{},()=>{});
}

public StartScan(): void{  
  if(this.timeoutvar !== null){
  clearTimeout(this.timeoutvar);
  }
  if(this.bleenabled){
  this.ble.stopScan().then(()=>{ 
    this.ngZone.run(() => {
    console.log('Scanning for Bluetooth LE Devices');
    this.devices = null;  // clear list
    this.services = []; // clear list
    this.ble.startScan([]).subscribe(
    device => this.onDeviceDiscovered(device),
    error => this.scanError(error)
    );
  });
  },
  ()=>{ //error al desconectar
    console.log('Error stopping scan');
  });

  this.timeoutvar = setTimeout(()=>{
  this.CancelScan();
  },5000);

}

}

public scanError(error): void{
  console.log('Error ' + error);
}

public onDeviceDiscovered(device): void {
    this.ngZone.run(() => {
       if(device.name == "Testdevice"){
       if(device.rssi>-50){
         if(this.timeoutvar !== null){
         clearTimeout(this.timeoutvar);
         }
//console.log(JSON.stringify(device));
         this.devices = device;
         this.StartConnect(device);
       }
       }
     });
}

public StartConnect(device:any):void{
  this.ble.stopScan().then(()=>{ 
    this.ble.connect(device.id).subscribe(
      peripheral => this.onConnected(peripheral),
      peripheral => this.onDeviceDisconnected(peripheral)
    );
  },
  ()=>{ 
    console.log('Error stopping scan');
  });
}

onConnected(peripheral) {

this.ngZone.run(() => {
this.setStatus('connection ready');
this.peripheral = peripheral;
for(let service of peripheral.characteristics){
  this.services.push(service);
}
});

//console.log(peripheral);

this.ble.startNotification(peripheral.id, "1900","2b04").subscribe(
buffer => {
  var data = new Uint8Array(buffer);
  if(data[0]==98){
    console.log("received");
  }
}
);
console.log("device ready");

}

  onDeviceDisconnected(peripheral) {
    console.log('disconnected');
  }

```

**Comment by smartifier-salomaa** [comment]
I think the root cause is Capacitor. When I moved my project back to Cordova project, also BLE write started to work again. I guess you have been also using Cordova, not Capacitor?

**Comment by juanct** [comment]
Yes, I use Cordova

**Comment by 2016508006** [comment]
> Yes, I use Cordova

sir ,  can you please tell me how to send data to noridc nrf51 board .. i have to send 2 data at a same time .. and it was =>>> ble.write(relay number , how long the relay has to run in seconds ) ... ==>>>> example: ble.write(4,5);    4 is relay number and 5 means 5 seconds it has to run .... i'm using latest ionic version and angular and cordova. 

thanks in advance❤️

**Comment by technowriter** [comment]
Hello,
I know its late to reply to this tread, but after struggling a lot to get BLE work in IONIC4, i have updated my work on my blog, so that it will be useful for some one. https://bugsncodes.blogspot.com/2020/01/ionic-4-bluetooth-low-energy-example.html
