### ISSUE TITLE
v5-beta.15 network plugin runs into error using last beta version

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-native#2674]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
We are using the ionic-native/network plugin in ionic4 using native@5.0.0-beta.15 in this case if we do a simple 
```
 this.network
                .onchange()
                    .subscribe(
                        (event) => {
                        }
                    );
```
we run into the followed error:
```
core.js:1673 ERROR RangeError: Maximum call stack size exceeded
    at setupSubscription (fromEvent.js:27)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
    at setupSubscription (fromEvent.js:46)
```
downgrading @beta.14 anything is working again.

The problem does **not** exists on `ionic3` using latest `native@4.12.0`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:
   ionic (Ionic CLI)          : 4.1.1 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.6
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 4 other plugins)

System:
   Android SDK Tools : 26.1.1 (/home/abc/android/sdk)
   NodeJS            : v8.11.1 (/usr/bin/node)
   npm               : 6.4.0
   OS                : Linux 4.15
```

**Comment by crebuh** [comment]
I can confirm this, downgrading to beta.14 and everything works again.

    Ionic:

        ionic (Ionic CLI)          : 4.0.1 (/usr/lib/node_modules/ionic)
        Ionic Framework            : @ionic/angular 4.0.0-beta.7
        @angular-devkit/core       : 0.7.5
        @angular-devkit/schematics : 0.7.5
        @angular/cli               : 6.1.0
        @ionic/ng-toolkit          : 1.0.7
        @ionic/schematics-angular  : 1.0.3

    Cordova:

        cordova (Cordova CLI) : 8.0.0
        Cordova Platforms     : android 7.0.0, ios 4.5.5

    System:

        Android SDK Tools : 25.2.5
        NodeJS            : v9.11.2 (/usr/bin/node)
        npm               : 5.6.0
        OS                : Linux 4.4

**Comment by rabs19912** [comment]
hi! im facing the same issue, and im glad to find the answer here,
but i dont have idea of how donwgrade ionic,
whitch is the best way to donwgrade native to beta.14?
thanks!

**Comment by rabs19912** [comment]
it works! thanks so much!

**Comment by Entrecampos** [comment]
What version is it working?

**Comment by kapilraghuwanshi** [comment]
how about today? Which versions and how it is working?

Coz I am still getting this error.
