### ISSUE TITLE
Using in React project

### ISSUE THREAD

**Issue by amerzad** [ionic-team/ionic-native#2687]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When ever I use any Ionic-Native plugin in Capacitor, it requires @angular/core at least, and I believe it is mostly just for @injectable decorator.

**Expected behavior:**
There should be some way to ask for this decorator only in @angular context.
I think it is a great idea to have a fork of Ionic-Native to be compatible with Capacitor, or is there any other way?

**Comment by victororlyk** [comment]
yes would be really nice to have support for React as they have made it possible to work with React half of the plugins are incomepetible with React or really hard to set up!
