### ISSUE TITLE
Error: Metadata version mismatch for module ...  found version 4, expected 3 anyone has some error when run  ionic cordova build android --prod --release

### ISSUE THREAD

**Issue by jackbbhua** [ionic-team/ionic-native#2692]
Error: Metadata version mismatch for module /Applications/MAMP/htdocs/tiaotiao/node_modules/@ionic-native/core/decorators.d.ts, found version 4, expected 3

"homepage": "",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "^4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/tsc-wrapped": "^4.4.6",
    "@ionic-native/core": "^4.11.0",
    "@ionic-native/device": "^4.10.0",
    "@ionic-native/file": "^4.7.0",
    "@ionic-native/file-transfer": "^4.7.0",
    "@ionic-native/geolocation": "^4.7.0",
    "@ionic-native/hot-code-push": "^4.11.0",
    "@ionic-native/http": "^4.11.0",
    "@ionic-native/image-picker": "^4.5.2",
    "@ionic-native/keyboard": "^4.5.2",
    "@ionic-native/media": "^4.11.0",
    "@ionic-native/native-audio": "^4.11.0",
    "@ionic-native/splash-screen": "4.3.0",
    "@ionic-native/status-bar": "4.3.0",
    "@ionic-native/streaming-media": "^4.11.0",
    "@ionic-native/video-player": "^4.11.0",
    "@ionic/storage": "2.0.1",
    "@jiguang-ionic/jpush": "^1.0.2",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^3.0.1",
    "@types/bluebird": "^3.5.23",
    "@types/bluebird-global": "^3.5.6",
    "@types/lodash": "^4.14.91",
    "@types/node": "^10.5.7",
    "@types/pixi.js": "^4.7.5",
    "angular2-swing": "0.14.0",
    "aplayer": "^1.10.1",
    "com.moust.cordova.videoplayer": "https://github.com/moust/cordova-plugin-videoplayer.git",
    "com.synconset.imagepicker": "^2.1.10",
    "cordova-android": "6.4.0",
    "cordova-browser": "~5.0.3",
    "cordova-ios": "4.5.5",
    "cordova-plugin-advanced-http": "^1.11.1",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-jcore": "^1.2.3",
    "cordova-plugin-media": "^5.0.2",
    "cordova-plugin-nativeaudio": "^3.0.9",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
    "cordova-plugin-streaming-media": "^2.1.3",
    "cordova-plugin-telerik-imagepicker": "^2.1.8",
    "cordova-plugin-video-player": "git+https://github.com/moust/cordova-plugin-videoplayer.git",
    "cordova-plugin-wechat": "^2.3.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.7.1",
    "ionic-audio": "^3.2.2",
    "ionic-img-viewer": "^2.9.0",
    "ionic-native": "^2.9.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-jpush": "^0.1.1",
    "ionicons": "3.0.0",
    "jpush-phonegap-plugin": "^3.4.3",
    "lodash": "^4.17.4",
    "ng-elastic": "^1.0.0-beta.5",
    "ng-lottie": "^0.3.1",
    "ng-socket-io": "^0.2.4",
    "node-vibrant": "^3.0.0",
    "pixi.js": "^4.8.1",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "rythm.js": "^2.2.3",
    "socket.io": "^2.1.1",
    "svgaplayerweb": "^2.1.0",
    "sw-toolbox": "3.6.0",
    "videogular2": "^6.3.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.1.11",
    "@types/core-js": "^2.5.0",
    "typescript": "^2.9.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "ionic-plugin-keyboard": {},
      "com.synconset.imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "your usage message"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-nativeaudio": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file": {},
      "cordova-plugin-advanced-http": {},
      "jpush-phonegap-plugin": {
        "APP_KEY": "715c9f23d5f1d415a942e9da"
      },
      "cordova-plugin-wechat": {
        "WECHATAPPID": "wxe803ca0dcb1d20cd"
      },
      "com.moust.cordova.videoplayer": {},
      "cordova-plugin-streaming-media": {},
      "cordova-plugin-media": {
        "KEEP_AVAUDIOSESSION_ALWAYS_ACTIVE": "NO"
      }
    },
    "platforms": [
      "browser",
      "ios",
      "android"
    ]

**Comment by danielsogl** [comment]
You have to upgrade to angular 5
