### ISSUE TITLE
Ionic network downlinkMax method always returns null

### ISSUE THREAD

**Issue by jayzyaj** [ionic-team/ionic-native#2693]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I always get null when I call the downlinkMax property of ionic/network

**Expected behavior:**
Expected to get the network downlinkMax of the device to test network speed.

**Steps to reproduce:**
1. Call the downlinkMax method and it always returns null.

**Related code:**

```
async initializeApp() {
   await this.platform.ready()
  console.log(this.network.downlinkMax) // returns null
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.0.0-rc.13 (/home/clifford/.npm-global/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v6.12.2 (/usr/local/bin/node)
   npm               : 4.6.1
   OS                : Linux 4.13

Environment:

   ANDROID_HOME : /home/clifford/Android/Sdk
```

**Comment by kensodemann** [comment]
Looking at the underlying plugin (https://github.com/apache/cordova-plugin-network-information), there is no `downlinkMax` property to expose. I don't see anything on the plugin that would provide similar information. It probably ought to be removed here.

**Comment by HashNotAdam** [comment]
Agreed; I'm here for the same reason. After receiving this error I dug into cordova-plugin-network-information and couldn't find any references to downlinkMax
