### ISSUE TITLE
bug(camera-v5): Using the Camera Provider Injectable fails 

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-native#2706]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When importing camera:
```ts
import { Camera } from '@ionic-native/camera';
```
And providing it to an angular module, I get the following error:
> Uncaught TypeError: Object(...) is not a function
    at Object../node_modules/@ionic-native/camera/index.js (index.js:257)

**Expected behavior:**
No error

**Steps to reproduce:**
Use ionic 4, and ionic-native 5 beta 17.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\amitm\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v10.1.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.3.0
   OS     : Windows 10
```

**Comment by ihadeed** [comment]
@AmitMY you need to import it from `/ngx` like this:
```ts
import { Camera } from '@ionic-native/camera/ngx';
```

**Comment by AmitMY** [comment]
Thanks.
Apparently, all my plugins were v5, except for the camera
