### ISSUE TITLE
admob pro plugin not working

### ISSUE THREAD

**Issue by MoAsmar** [ionic-team/ionic-native#2710]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am trying to run ads using [AdMob Pro](https://ionicframework.com/docs/native/admob-pro/) native plugin but it is not working when I remove isTesting or set it to false, 
I also tried the admob free which is not working and not maintained anymore.

**Expected behavior:**
showing ads for prod, isTesting is working fine

**Steps to reproduce:**
```
$ ionic start testadmobpro blank
$ cd testadmobpro 
$ ionic cordova plugin add cordova-plugin-admobpro
$ npm install --save @ionic-native/admob-pro
$ cordova platform add android
$ cordova run android
```

**home.ts**
```
import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { AdMobPro } from '@ionic-native/admob-pro';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private admob: AdMobPro, private platform: Platform) {
    this.platform.ready().then(()=>{
      console.log('platform ready');
      this.admob.createBanner({adId: 'MY_AD_ID', autoShow: true});
    })
  }

  ionViewDidLoad(){
    console.log('ionViewDidLoad');
    this.admob.createBanner({adId: 'MY_AD_ID', autoShow: true});
  }
}

```

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)  : 4.0.6 (C:\Users\Me\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 25.2.3
   NodeJS            : v9.4.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\Me\AppData\Local\Android\Sdk



```

**Comment by dalejomen** [comment]
good morning,
I have problems with the plugin cordova-plugin-admobpro when I compile my project and generate the apk for android generates it well. but when I install the apk in my cellphone to application does not load the program is closed.

This was working fine until last week as this plugin used it in several apps.

**Comment by chintaner** [comment]
SAME issue after CLI update , application does not start in mobile.

**Comment by webgeekga** [comment]
I am not able to install the ionic-native/admob-free plugin.

While running this command `npm install --save @ionic-native/admob-free` it gives me this output 

> Unrecognized token in source text.
At line:1 char:20
 npm install --save  <<<< @ionic-native/admob-free
 CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
  FullyQualifiedErrorId : UnrecognizedToken

**Comment by webgeekga** [comment]
> I am not able to install the ionic-native/admob-free plugin.
> 
> While running this command `npm install --save @ionic-native/admob-free` it gives me this output
> 
> > Unrecognized token in source text.
> > At line:1 char:20
> > npm install --save  <<<< @ionic-native/admob-free
> > CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
> > FullyQualifiedErrorId : UnrecognizedToken

It's working with "".
i.e npm install --save "@ionic-native/admob-free"
