### ISSUE TITLE
bug(v5-google-maps): requires rxjs v5

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-native#2714]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
```ts
import {
  Circle,
  GoogleMap,
  GoogleMapOptions,
  GoogleMaps,
  GoogleMapsEvent,
  HtmlInfoWindow
} from '@ionic-native/google-maps/ngx';
```

errors:

> ERROR in node_modules/@ionic-native/google-maps/ngx/index.d.ts(2,10): error TS2305: Module '"node_modules/rxjs/Observable"' has no exported member 'Observable'.
> node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Expected behavior:**
No error

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\amitm\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic 5.1.5, (and 7 other plugins)

System:

   NodeJS : v10.1.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.3.0
   OS     : Windows 10
```

Plugins:
```
    "@ionic-native/camera": "5.0.0-beta.17",
    "@ionic-native/core": "5.0.0-beta.17",
    "@ionic-native/date-picker": "5.0.0-beta.17",
    "@ionic-native/facebook": "5.0.0-beta.17",
    "@ionic-native/geolocation": "5.0.0-beta.17",
    "@ionic-native/globalization": "5.0.0-beta.17",
    "@ionic-native/google-analytics": "^5.0.0-beta.17",
    "@ionic-native/google-maps": "5.0.0-beta.17",
    "@ionic-native/native-geocoder": "5.0.0-beta.17",
    "@ionic-native/splash-screen": "5.0.0-beta.17",
    "@ionic-native/status-bar": "5.0.0-beta.17",
```

**Comment by AmitMY** [comment]
(Obviously, installing `rxjs-compat` solves it but it shouldn't be required imo)

**Comment by wf9a5m75** [comment]
`@ionic-native/google-maps : v5.0.0-beta.21`

**Comment by AmitMY** [comment]
Thanks. Didn't see that release in GitHub. I can't update at the moment, so I'll take your word for it.
