### ISSUE TITLE
@ionic-native/printer Error

### ISSUE THREAD

**Issue by heedoo** [ionic-team/ionic-native#2718]
I am using
Ionic 4 
Capacitor
and installed cordova printer plugin. ("@ionic-native/printer": "^4.12.2")

**Current behavior:**
I import plugin from module.ts and added "Printer" in provider but when I run on device, app returns error.
'''
Ex)
//sample.module.ts
import { Printer, PrintOptions } from '@ionic-native/printer';
providers: [Printer]

'''

[Error] ERROR – Error: Uncaught (in promise): TypeError: Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["CordovaCheck"]) is not a function. (In 'Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["CordovaCheck"])()', 'Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["CordovaCheck"])' is an instance of Object)
./node_modules/@ionic-native/printer/index.js@http://localhost:3992/host-checkin-checkin-module.js:107:76
__webpack_require__@http://localhost:3992/runtime.js:82:34
./src/app/host/checkin/checkin.page.ts@http://localhost:3992/host-checkin-checkin-module.js:243:98
__webpack_require__@http://localhost:3992/runtime.js:82:34
./src/app/host/checkin/checkin.module.ts@http://localhost:3992/host-checkin-checkin-module.js:157:90
__webpack_require__@http://localhost:3992/runtime.js:82:34
http://localhost:3992/main.js:339:35
onInvoke@http://localhost:3992/vendor.js:36908:39
run@http://localhost:3992/polyfills.js:2460:49
http://localhost:3992/polyfills.js:3194:37
onInvokeTask@http://localhost:3992/vendor.js:36899:43
runTask@http://localhost:3992/polyfills.js:2510:57
drainMicroTaskQueue@http://localhost:3992/polyfills.js:2917:42
promiseReactionJob@[native code] — zone.js:814
Error: Uncaught (in promise): TypeError: Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["CordovaCheck"]) is not a function. (In 'Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["CordovaCheck"])()', 'Object(_ionic_native_core__WEBPACK_IMPORTED_MODULE_1__["CordovaCheck"])' is an instance of Object)
./node_modules/@ionic-native/printer/index.js@http://localhost:3992/host-checkin-checkin-module.js:107:76
__webpack_require__@http://localhost:3992/runtime.js:82:34
./src/app/host/checkin/checkin.page.ts@http://localhost:3992/host-checkin-checkin-module.js:243:98
__webpack_require__@http://localhost:3992/runtime.js:82:34
./src/app/host/checkin/checkin.module.ts@http://localhost:3992/host-checkin-checkin-module.js:157:90
__webpack_require__@http://localhost:3992/runtime.js:82:34
http://localhost:3992/main.js:339:35
onInvoke@http://localhost:3992/vendor.js:36908:39
run@http://localhost:3992/polyfills.js:2460:49
http://localhost:3992/polyfills.js:3194:37
onInvokeTask@http://localhost:3992/vendor.js:36899:43
runTask@http://localhost:3992/polyfills.js:2510:57
drainMicroTaskQueue@http://localhost:3992/polyfills.js:2917:42
promiseReactionJob@[native code] — zone.js:814
	capacitorConsole (user-script:2:68)
	defaultErrorLogger (vendor.js:34757)
	handleError (vendor.js:34803)
	next (vendor.js:37403:140)
	(anonymous function) (vendor.js:36639)
	__tryOrUnsub (vendor.js:95124)
	next (vendor.js:95062)
	_next (vendor.js:95006)
	next (vendor.js:94983)
	next (vendor.js:94749)
	emit (vendor.js:36623)
	run (polyfills.js:2460)
	onHandleError (vendor.js:36930)
	runGuarded (polyfills.js:2476)
	_loop_1 (polyfills.js:2999)
	microtaskDrainDone (polyfills.js:3008)
	drainMicroTaskQueue (polyfills.js:2924)
	promiseReactionJob

**Steps to reproduce:**
1. ionic cordova plugin add cordova-plugin-printer
2. npm install --save @ionic-native/printer
3. npx cap sync
4. npx cap copy ios
5. npm run build
6. npx cap open ios

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/moonhe/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.3 (/Users/moonhe/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.6.0
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b


```

**Comment by danielsogl** [comment]
You have to install the Plugin Beta Version.
