### ISSUE TITLE
ionic 4 native printer beta returns error

### ISSUE THREAD

**Issue by heedoo** [ionic-team/ionic-native#2719]
**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
After calling "check" function, it returns below error.
I take a look module index.js file under ngx folder and "getPromise" is not declared.

**Error message:**
[Error] ERROR – Error: Uncaught (in promise): ReferenceError: Can't find variable: getPromise
http://localhost:3992/host-checkin-checkin-module.js:50:34
isAvailable@http://localhost:3992/host-checkin-checkin-module.js:43:26
http://localhost:3992/host-checkin-checkin-module.js:549:38
onInvoke@http://localhost:3992/vendor.js:36908:39
run@http://localhost:3992/polyfills.js:2460:49
http://localhost:3992/polyfills.js:3194:37
onInvokeTask@http://localhost:3992/vendor.js:36899:43
runTask@http://localhost:3992/polyfills.js:2510:57
drainMicroTaskQueue@http://localhost:3992/polyfills.js:2917:42
invokeTask@http://localhost:3992/polyfills.js:2822:40
invokeTask@http://localhost:3992/polyfills.js:3862:20
globalZoneAwareCallback@http://localhost:3992/polyfills.js:3888:27 — zone.js:814
Error: Uncaught (in promise): ReferenceError: Can't find variable: getPromise
http://localhost:3992/host-checkin-checkin-module.js:50:34
isAvailable@http://localhost:3992/host-checkin-checkin-module.js:43:26
http://localhost:3992/host-checkin-checkin-module.js:549:38
onInvoke@http://localhost:3992/vendor.js:36908:39
run@http://localhost:3992/polyfills.js:2460:49
http://localhost:3992/polyfills.js:3194:37
onInvokeTask@http://localhost:3992/vendor.js:36899:43
runTask@http://localhost:3992/polyfills.js:2510:57
drainMicroTaskQueue@http://localhost:3992/polyfills.js:2917:42
invokeTask@http://localhost:3992/polyfills.js:2822:40
invokeTask@http://localhost:3992/polyfills.js:3862:20
globalZoneAwareCallback@http://localhost:3992/polyfills.js:3888:27 — zone.js:814resolvePromise — zone.js:814(anonymous function) — zone.js:877onInvokeTask — core.js:3815runTask — zone.js:188drainMicroTaskQueue — zone.js:595invokeTask — zone.js:500invokeTask — zone.js:1540globalZoneAwareCallback — zone.js:1566
	capacitorConsole (user-script:2:68)
	defaultErrorLogger (vendor.js:34757)
	handleError (vendor.js:34803)
	next (vendor.js:37403:140)
	(anonymous function) (vendor.js:36639)
	__tryOrUnsub (vendor.js:95124)
	next (vendor.js:95062)
	_next (vendor.js:95006)
	next (vendor.js:94983)
	next (vendor.js:94749)
	emit (vendor.js:36623)
	run (polyfills.js:2460)
	onHandleError (vendor.js:36930)
	runGuarded (polyfills.js:2476)
	_loop_1 (polyfills.js:2999)
	microtaskDrainDone (polyfills.js:3008)
	drainMicroTaskQueue (polyfills.js:2924)
	invokeTask (polyfills.js:2822)
	invokeTask (polyfills.js:3862)
	globalZoneAwareCallback (polyfills.js:3888)

**Steps to reproduce:**
this.printer.isAvailable().then((res)=>{
        console.log("success", res);
      }, (err)=>{
        console.log("error:", err);
      });

**Ionic info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/moonhe/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.3 (/Users/moonhe/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.6.0
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b


```

**Comment by danielsogl** [comment]
Fixed
