### ISSUE TITLE
Update RXJS to v6 so ionic native can be used with angular 6

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/ionic-native#2725]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Update rxJS to version 6 so this plugin doesn't throw these warnings in the console when used with angular 6 (which depends on rxJS 6):
```
npm WARN @ionic-native/aes-256@4.12.2 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/app-version@4.12.2 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/camera@4.12.2 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/core@4.12.2 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/deeplinks@4.14.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
```

**Expected behavior:**

No warnings

**Steps to reproduce:**

- Update to angular 6
- Run `npm i`

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/Users/borntsch/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.4 (/Users/borntsch/.nvm/versions/node/v8.11.4/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Comment by BorntraegerMarc** [comment]
Thanks for your answer @wf9a5m75 
But I can't update to an unstable beta version of ionic-native as our app is used in production. So I created this issue with the hopes that v6 of rxjs could be installed with a new version 4 of ionic-native.

Since angular 6 is stable and we would like to use it in production.

**Comment by wf9a5m75** [comment]
I feel `ionic 4` is almost stable, `@capacitor` is kind of unstable.

Well, it's depends on your opinion, you can choose it.
But I think ionic team won't work for your request.

**Comment by danielsogl** [comment]
The v5 Beta is already stable. We just call it beta because of the ionic v4 beta.
if you still want to use native v4 you have to use the `rxjs-compat ` package for backward compatibility.

**Comment by barocsi** [comment]
I have installed ionic 4 using cli. That installed angular 7 and rxjs 6 for me. Then installed ionic native plugins per documentation. Then how come that all native plugins throw error at compile time? I just do not understand the logic behind it.
