### ISSUE TITLE
[v5] AdMobFree: Duplicate class AdMobFree 

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic-native#2729]
@danielsogl On your last merge from master to v5, in AdMobFree are now two AdMobFree  classes

 ->  https://github.com/ionic-team/ionic-native/blob/v5/src/%40ionic-native/plugins/admob-free/index.ts

See issue: https://github.com/ionic-team/ionic/issues/15687

**Comment by danielsogl** [comment]
Thanks for the hint.
