### ISSUE TITLE
@ionic-native/ms-adal crashes with "--type=angular"

### ISSUE THREAD

**Issue by RobusXLR** [ionic-team/ionic-native#2732]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
index.js:113 Uncaught TypeError: Object(...) is not a function
    at index.js:113
    at Object../node_modules/@ionic-native/ms-adal/index.js (index.js:123)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)

index.js:113:
MSAdal = MSAdal_1 = __decorate([
        Plugin({
            pluginName: 'MSADAL',
            plugin: 'cordova-plugin-ms-adal',
            pluginRef: 'Microsoft.ADAL',
            repo: 'https://github.com/AzureAD/azure-activedirectory-library-for-cordova',
            platforms: ['Android', 'iOS', 'Windows']
        })
    ], MSAdal);

**Expected behavior:**
To see default start page.

**Steps to reproduce:**
1. ionic start myproj --type=angular
2. ionic cordova plugin add cordova-plugin-ms-adal
3. npm install --save @ionic-native/ms-adal
4. Add MSAdal to app.module.ts and to providers

**Related code:**
import { MSAdal } from '@ionic-native/ms-adal';

@NgModule({
    declarations: [AppComponent],
    entryComponents: [],
    imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule, MSAdal],
    providers: [
        MSAdal,
        StatusBar,
        SplashScreen,
        { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
    ],
    bootstrap: [AppComponent]
})

**Other information:**
NOTE '@ionic-native/ms-adal/ngx' does not exist

**Ionic info:**:
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\Robert.gill\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\Robert.gill\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.1.0
   OS                : Windows 10

**Comment by danielsogl** [comment]
You have to install the beta version of this plugin wrapper:

`npm install --save @ionic-native/ms-adal@beta`
