### ISSUE TITLE
5.0.0-beta.14 - Uncaught TypeError: Object.setPrototypeOf called on null or undefined brokes android <=7.0

### ISSUE THREAD

**Issue by glebmachine** [ionic-team/ionic-native#2737]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
`@ionic-native/push` plugin brokes Android <= 7.0
![](http://joxi.ru/YmE0RpOU0v5gjr.jpg)

**Expected behavior:**
Application starts and not broken

**Steps to reproduce:**
1. Add `@ionic-native/push`
2. Run on android <= 7.0
3. Boom, js is broken

**Related code:**
none

**Other information:**
Cause of this:
![](http://joxi.ru/MAj9YeNi4wpVN2.jpg)
 
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
Ionic:

   ionic (Ionic CLI)          : 4.0.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.1, ios 4.5.4

System:

   NodeJS : v10.9.0 (D:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set
```

**Comment by danielsogl** [comment]
Have you installed the beta version of the push plugin wrapper?

**Comment by glebmachine** [comment]
@danielsogl, yes: `5.0.0-beta.14`
I'm using ionic 4

**Comment by glebmachine** [comment]
Yeah, it's my bad, everything ok now, it works down to 5.0

**Comment by danielsogl** [comment]
Thanks for the update.
