### ISSUE TITLE
admob-free plugin duplicate identifier since beta.18

### ISSUE THREAD

**Issue by TheDuc** [ionic-team/ionic-native#2738]
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Code will not compile due to Duplicate identifier 'AdMobFree'

**Expected behavior:**
To not have duplicate exports

**Related code:**
https://github.com/ionic-team/ionic-native/blob/7aa5e00453663632c94d8febcb6f1f88922c3bfd/src/%40ionic-native/plugins/admob-free/index.ts#L118
https://github.com/ionic-team/ionic-native/blob/7aa5e00453663632c94d8febcb6f1f88922c3bfd/src/%40ionic-native/plugins/admob-free/index.ts#L372

**Comment by TheDuc** [comment]
I see that it is already fixed in the v5 branch

**Comment by danielsogl** [comment]
Yes I fixed is yesterday. I will release beta 21 today.
