### ISSUE TITLE
keychain-touch-id save function missing parameter

### ISSUE THREAD

**Issue by abdalla-magdi** [ionic-team/ionic-native#2749]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
when calling "**save**" function from **keychain-touch-id** plugin, error callback is always fired even the plugin succeeded

**Expected behavior:**
Success callback should be called when the plugin save action succeed

**Steps to reproduce:**
Call save function from the plugin and error callback will be fired

**Related code:**

https://github.com/ionic-team/ionic-native/blob/fcd6d26727a5a3d45ca90a75d8c5b58bad0c1204/src/%40ionic-native/plugins/keychain-touch-id/index.ts#L53

**Other information:**
I found that the issue is that in the definition typing file "**save**" function has a missing parameter as follow:
 **save(key: string, password: string): Promise<any> { return; }**
it should be:
  **save(key: string, password: string, userAuthenticationRequired: boolean): Promise<any> { return; }**
https://github.com/ionic-team/ionic-native/blob/fcd6d26727a5a3d45ca90a75d8c5b58bad0c1204/src/%40ionic-native/plugins/keychain-touch-id/index.ts#L53

This parameter has been added in the plugin repository:
https://github.com/sjhoeksma/cordova-plugin-keychain-touch-id/commit/2fc7ecd7394814d2d2aa1e1276c5f2fd67e20f62#diff-ea46243878390ffe97bb68800127d8d7

**Comment by mkw2000** [comment]
This was fixed [here](https://github.com/ionic-team/ionic-native/pull/3324)
