### ISSUE TITLE
NFC ReaderMode

### ISSUE THREAD

**Issue by stephendwolff** [ionic-team/ionic-native#2756]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The Phonegap-NFC plugin has a 'readermode': https://github.com/chariotsolutions/phonegap-nfc#nfcreadermode, which is not exposed by the ionic-native wrapper.

**Expected behavior:**
I would expect this function to be added to the ionic-native nfc plugin, with a warning if not available on the platform (i think it is android only)

**Steps to reproduce:**
Create a project, and add the nfc plugin, and try and use the readerMode. The project will not compile.

**Related code:**
Example code from the PhoneGap NFC Plugin page
```
nfc.readerMode(
    nfc.FLAG_READER_NFC_A | nfc.FLAG_READER_NO_PLATFORM_SOUNDS, 
    nfcTag => console.log(JSON.stringify(nfcTag)),
    error => console.log('NFC reader mode failed', error)
);```

**Other information:**
I have a native android app which reads the NFC card tag with no problems, on the device i'm testing, but using the ionic-native nfc plugin, i get the 'tag type not supported' - as seen in this issue:
 - https://github.com/chariotsolutions/phonegap-nfc/issues/316

The above issue mentions another related issue - which has the readerMode:
 - https://github.com/chariotsolutions/phonegap-nfc/issues/198


**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 8 other plugins)

System:

   NodeJS : v10.5.0 (/usr/local/Cellar/node/10.5.0_1/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Comment by rodrigograca31** [comment]
Agreed! Why isnt `readerMode` available?

It's the basic way to read a tag on Android.

My current solution is to use the plugin directly:

```typescript
nfc: any = (<any>window).nfc;
```

**Comment by robingenz** [comment]
Any updates?

**Comment by adnathanail** [comment]
Any updates?

**Comment by don** [comment]
#3381 add a typescript wrapper for [nfc.readerMode](https://github.com/chariotsolutions/phonegap-nfc#nfcreadermode)
