### ISSUE TITLE
BROKEN ionic-native/contacts plugin, save() ignores arrays like emails, phoneNumbers etc

### ISSUE THREAD

**Issue by Bramzor** [ionic-team/ionic-native#2760]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Save functionality of ionic-native contacts plugin does not want to save any array parameter like phoneNumbers, emails, urls etc. Created a test app repo which shows exactly what fails: https://github.com/Bramzor/ionic-native-contacts-tests

For example:

Print before save():
... "urls":[{"type":"SomeValue","value":"http://www.example.com"}] ...
After contact.save() -> returned by ionic-native contacts:
... "urls":null ...

Any idea why my input is ignored?

**Expected behavior:**

... "urls":[{"type":"SomeValue","value":"http://www.example.com"}] ...

**Steps to reproduce:**

Find any contact using ionic-native contacts
Try to update/add a url
Trigger save and view response (which is the updated contact data but without the url update)

**Related code:**

```
contact.urls.push(new ContactField("SomeValue", "http://www.example.com"))
console.log(contact)
let result = await contact.save()
console.log(result)
```

**Other information:**

Tested with @ionic-native/contacts version 4.7.0 and with the latest version 4.15.0

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (cvcionic/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.11.2
    npm        : 6.1.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by Bramzor** [comment]
I created a test app that shows exactly what fails with the current version of ionic-native/contacts : https://github.com/Bramzor/ionic-native-contacts-tests

**Comment by BatteryAcid** [comment]
So right now to get around this, in the case of a Contact update, I'm manually setting the rawId to id before the save, and this appears to be working.  

- Any ideas on what rawId should actually be or how it should be set? 

At the moment only testing on Android.
Thanks

> ionic (Ionic CLI)           : 4.12.0 
> Ionic Framework         : @ionic/angular 4.0.0-rc.1
> @angular/cli                  : 7.1.4
> @ionic/angular-toolkit        : 1.2.2
>
> cordova (Cordova CLI) : 7.1.0
> Cordova Platforms     : android 6.3.0

**Comment by Bramzor** [comment]
> So right now to get around this, in the case of a Contact update, I'm manually setting the rawId to id before the save, and this appears to be working.
> 
> * Any ideas on what rawId should actually be or how it should be set?
> 
> At the moment only testing on Android.
> Thanks
> 
> > ionic (Ionic CLI)           : 4.12.0
> > Ionic Framework         : @ionic/angular 4.0.0-rc.1
> > @angular/cli                  : 7.1.4
> > @ionic/angular-toolkit        : 1.2.2
> > cordova (Cordova CLI) : 7.1.0
> > Cordova Platforms     : android 6.3.0

By doing this you can update the arrays too? Can you confirm this? Because for me this never worked.

**Comment by BatteryAcid** [comment]
> By doing this you can update the arrays too? Can you confirm this? Because for me this never worked.

Yes, saving arrays like phoneNumber works now.  I've only tested with the simulator.

The changes alone in the pull request above are not enough, you have to set the Contact's `_objectInstance.rawId` field to something before save - will investigate further what the expected values are for rawId.

My current workaround is just to set the rawId to the id:  
`contactToUpdate._objectInstance.rawId = contactToUpdate.id;`

**Comment by Bramzor** [comment]
@BatteryAcid I assume that by setting rawId to something different, you are actually not saving (updating) a contact anymore but just saving it as a new contact. I know for example that when saving a new contact, the arrays are working perfectly but when updating, it wasn't overwriting the array. Problem occurred when I tried to overwrite existing information in the array. (validated on iOS) So it might work on Android but not on iOS.

**Comment by BatteryAcid** [comment]
@Bramzor I'm now seeing the following:

- a clean save on phone numbers works.
- adding an additional number works
- clearing out all numbers works (empty phone number array)
- removing (overwriting) doesn't work, you can't replace the the phone numbers with a different array of phone numbers and expect it to actually remove the one not included in the new list.   **I believe this is what you are also seeing.**  

> ex:
> - existing: ['555-555-5555'] 
> - replace phone numbers array with ['111-222-3333'] will retain the existing _555_ number after a save to end up with: ['555-555-5555', '111-222-3333']
>
> <sup>(removed object formatting for brevity)</sup>

This is not the expected behavior I had in mind.  My work around is to clear out the entire array first, save, then update with whatever I want, then save again.  It's clumsy but it works.

I haven't started my iOS testing yet.

**Comment by Bramzor** [comment]
@BatteryAcid What does not work on iOS is both adding and clearing. Well, it does work if I add a breakpoint somewhere so I assume it is some kind of race condition in the native code. Never checked Android and if I check iOS native source code what you mention is the correct behavior. Removing is the only code missing on the native part.

So workaround that I currently use is .clone() to clone the object and I just remove the old one while saving the cloned contact as a new contact.
