### ISSUE TITLE
Keyboard method disableScroll gone

### ISSUE THREAD

**Issue by heidji** [ionic-team/ionic-native#2762]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

related issue [#42](https://github.com/ionic-team/cordova-plugin-ionic-keyboard/issues/42)

The method has been removed after associating the ionic-native/keyboard plugin with the new cordova-plugin-ionic-keyboard plugin. this method was for many the only reliable method to stop scrolling in iOS. no workarounds are known to me.

**Comment by tmk1991** [comment]
This is preventing upgrading the wrapper for native to anything over 4.13.0 ... @mlynch
