### ISSUE TITLE
youtube-video-player callback promise

### ISSUE THREAD

**Issue by markdegrootnl** [ionic-team/ionic-native#2765]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

openVideo() returns a void. 

**Expected behavior:**

openVideo() should return a promise which resolves the callback function.
The plugin accepts a callback function which is called when the video is done playing: https://github.com/ihadeed/CordovaYoutubeVideoPlayer 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by JensUweB** [comment]
* push *
This plugin is basically unusable for us in our use case without this.
