### ISSUE TITLE
SQLite - TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by eloufirhatim** [ionic-team/ionic-native#2770]
Hello,

I am using ionic v4 with SQLite, and I just created a service containing the database CRUD functionnality, but when I launch the application on an Android emulator I got this error
![image](https://user-images.githubusercontent.com/6197875/46735534-5ba89f80-cc8e-11e8-9097-534bcb5007f2.png)
I am using the version **4.15.0** of the SQLite plugin
![image](https://user-images.githubusercontent.com/6197875/46735560-6e22d900-cc8e-11e8-92d6-a08b4be86974.png)
The service containing the CRUD methods is like below:
![image](https://user-images.githubusercontent.com/6197875/46736339-b17e4700-cc90-11e8-8016-7d5e7dfafa75.png)

Can you help please.
Thank you in advance,
Hatim

**Comment by danielsogl** [comment]
You have to use the beta branch like the pre installed plugin wrappers.

**Comment by eloufirhatim** [comment]
I think it's my bad, sorry.
In the Ionic Native docs they say

> To use a plugin, import and add the plugin injectable to a @NgModule. For Angular, the import path should end with /ngx.

So I changed `import { SQLite } from '@ionic-native/sqlite' into` `import { SQLite } from '@ionic-native/sqlite/ngx'` in both **app.module.ts** and the service file and it's builded successfully.

Thanks and sorry again

**Comment by danielsogl** [comment]
No problem :)
