### ISSUE TITLE
@ionic-native/local-notifications getAllScheduled and getAllTriggered not working

### ISSUE THREAD

**Issue by marcovtwout** [ionic-team/ionic-native#2778]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report

**Current behavior:**
When calling `localNotifications.getAllScheduled()` or `localNotifications.getAllTriggered()`, the following error shows up in console:

```
Ionic Native: tried calling LocalNotifications.getAllScheduled, but the LocalNotifications plugin is not installed.
Install the LocalNotifications plugin: 'ionic cordova plugin add cordova-plugin-local-notification'```
```

This looks like an issue with the Ionic plugin, since the plugin is installed correctly and other methods work as expected.

**Expected behavior:**
Function should return Promise<Array<ILocalNotification>> as documented.

**Other information:**
Support for these functions was recently added by @danielsogl, but perhapt not fully tested: https://github.com/ionic-team/ionic-native/commit/10d222dceaed6bf372bec4ebaba0080946048294#diff-b485ec70d7e39ac4e9507e7f1db111a2R730

The old cordova-plugin-local-notifications 0.8 itself had a function `getAllTriggered()`, which is replaced by `getTriggered()` in 0.9 (https://github.com/katzer/cordova-plugin-local-notifications#methods).

**Comment by danielsogl** [comment]
Loks like they remove this two functions.

**Comment by marcovtwout** [comment]
Yes, getAllTriggered() was basically an alias for getTriggered().

**Comment by marcovtwout** [comment]
@danielcregg Tested and works as expected. Thanks for fixing and releasing so quickly.

**Comment by SVANNER** [comment]
I get the same issue with the following version of IONIC

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/mnt/ssd/Android/Sdk)
   NodeJS            : v10.15.3 (/usr/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.4

local-notifications plugin version is 0.9.0-beta.2

Thanks for your help !
