### ISSUE TITLE
[Diagnostic] Proposition regarding change handlers to return an Observable instead of having a synced callback

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic-native#2786]
**I'm submitting a ...**
- Feature request / improvement proposition

# Feature request

**Current behavior:**

Currently the ionic native wrapper let us pass a function to be called back for any change handlers.

**Expected behavior:**

For convenient reasons I think it would be better to have these handlers return an observable instead.

**Steps to reproduce:**

Current usage makes impossible to **directly** add `registerBluetoothStateChangeHandler` to an rx stream.

```ts
this.BTStateChangeHandler = new Subject()

this.diagnosticPlugin.registerBluetoothStateChangeHandler(BTState => {
  this.BTStateChangeHandler.next(BTState)
})
...
```

Cordova implementation is simple ([source](https://github.com/ionic-team/ionic-native/blob/v5/src/%40ionic-native/plugins/diagnostic/index.ts#L461)):

```ts
  /**
   * Registers a function to be called when a change in Bluetooth state occurs.
   * @param {Function} handler
   */
  @Cordova({ platforms: ['Android', 'iOS'], sync: true })
registerBluetoothStateChangeHandler(handler: Function): void {}
```
would become
```ts
  /**
   * Registers a function to be called when a change in Bluetooth state occurs.
   * @returns {Observable<any>}
   */
  @Cordova({ "callbackOrder": "reverse", "observable": true, "platforms": ["Android", "iOS"] })
registerBluetoothStateChangeHandler(): Observable<any>;
```
I listed these methods:
 * registerBluetoothStateChangeHandler
 * registerLocationStateChangeHandler
 * registerPermissionRequestCompleteHandler
 * registerNFCStateChangeHandler

These handlers are exactly what Observables are meant for, a stream where it can be nexted a new value anytime.

Let me know what you think about this idea and if there is some things that has to be taken into consideration such as managing the breaking change, or maybe adding other methods aswell for instance. 

I can also prepare the pull request if needed.

**Comment by enzonotario** [comment]
Hi! I also want this. Have you found a solution for this?
