### ISSUE TITLE
Network Plugin "'Plugin' references 'Plugin'"

### ISSUE THREAD

**Issue by dahlb** [ionic-team/ionic-native#2788]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
production compile results in this error in ionic project optimize build
ERROR in ../@ionic-native/network/index.ts(67,2): Error during template compile of 'Network'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'Plugin'
    'Plugin' references 'Plugin'
      'Plugin' is not initialized at ../@ionic-native/core/decorators/interfaces.ts(100,22).

**Expected behavior:**

expected app to compile

**Steps to reproduce:**

using versions from ionic info simple add Network provider to app module to cause this error

**Related code:**

```
import { Network } from '@ionic-native/network';
providers: [
  Network
]
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/Users/brendandahl/.nvm/versions/node/v8.11.2/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.8.4
   @angular-devkit/schematics : 0.8.4
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.1.0
   @ionic/schematics-angular  : 1.0.6

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.8
   @capacitor/core           : 1.0.0-beta.8

System:

   NodeJS : v8.11.2 (/Users/brendandahl/.nvm/versions/node/v8.11.2/bin/node)
   npm    : 5.1.0
   OS     : macOS
```

**Comment by mmubasher** [comment]
have you tried using `5.0.0-beta.21`? import it as mentioned below
```
import { Network } from '@ionic-native/network/ngx';
```
I tested it on following environment and build is successful
```
Ionic:

   ionic (Ionic CLI)             : 4.3.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.7.2
   @angular-devkit/schematics    : 0.7.2
   @angular/cli                  : 6.1.1
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.13.0
   npm               : 6.4.1
   OS                : Windows 10

```
