### ISSUE TITLE
Ionic 4 FingerprintAIO - 

### ISSUE THREAD

**Issue by emilgiev** [ionic-team/ionic-native#2791]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

***Current Version:**
4.1.2
/////////
*** just updated version to 4.2.1*** 

Problem still appears.

**Current behavior:**

I'm trying to implement FIngerprintAIO in my current ionic4 application, this might have already been asked on previous topics, or solved but i seem not to be able to find it.

insert any relevant code here
```
import { FingerprintAIO, FingerprintOptions } from '@ionic-native/fingerprint-aio';
import { Platform } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

  fingerprintOptions: FingerprintOptions

  constructor(private fingerprint: FingerprintAIO, private platform: Platform) {

    this.fingerprint.show({
      clientId: 'fingerprint-demo',
      clientSecret: 'password',
      disableBackup: true,
    })
  }

insert the output from ionic info here
```

Uncaught TypeError: Object(...) is not a function
    at index.js:92
    at Object../node_modules/@ionic-native/fingerprint-aio/index.js (index.js:141)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)

**Comment by emilbayes** [comment]
This should do:

```
import { FingerprintAIO, FingerprintOptions } from '@ionic-native/fingerprint-aio/ngx'
```

**Comment by CleberOtaviano** [comment]
@emilbayes, Not working for me why "@ionic-native/fingerprint-aio/ngx" not a package from npm for install on project.

**Comment by indraraj26** [comment]
which version of  finterPrint-aio are you using ?
