### ISSUE TITLE
Ionic 4 barcode scanner - Cannot initialize a parameter of type 'AVCaptureVideoOrientation' with an rvalue of type 'UIInterfaceOrientation'

### ISSUE THREAD

**Issue by heedoo** [ionic-team/ionic-native#2798]
**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When I run on barcode scanner on iOS device, I get below error on CDVBarcodeScanner.mm file line 779.([previewLayer.connection setVideoOrientation:[[UIApplication sharedApplication] statusBarOrientation]];)

Cannot initialize a parameter of type 'AVCaptureVideoOrientation' with an rvalue of type 'UIInterfaceOrientation'

**Expected behavior:**
It should not crash and open a camera

**Steps to reproduce:**
1. Install phonegap-plugin-barcodescanner plugin
2. install @ionic-native/barcode-scanner": "^5.0.0-beta.21
3. import { BarcodeScanner } from '@ionic-native/barcode-scanner/ngx';
4. Add BarcodeScanner in constructor (private barcodeScanner: BarcodeScanner)
5. Run (npx cap sync -> npx cap copy -> npx cap open ios -> run in Xcode)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Ionic:

   ionic (Ionic CLI)             : 4.2.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/xxx/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.3 (/Users/xxx/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.6.0
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b
```
insert the output from ionic info here
```

**Comment by eddskt** [comment]
Nobody???

**Comment by eddskt** [comment]
Hi @heedoo after after much research I found a solution to my case:
Try Change:

`self.processor.previewLayer.connection.videoOrientation = [[UIApplication sharedApplication] statusBarOrientation];`
 **BY:**
    `self.processor.previewLayer.connection.videoOrientation = (AVCaptureVideoOrientation)[[UIApplication sharedApplication] statusBarOrientation];`

INFO: https://gitlab.codecentric.de/open-source/phonegap-plugin-barcodescanner/commit/e23d82ddd042ec969611f020e1420628ead9b63b

**Comment by lassesteffen** [comment]
The barcodescanner plugin version 8.0.1 fixed this error for me.
