### ISSUE TITLE
onDisconnect onConnect not working

### ISSUE THREAD

**Issue by utopiafx** [ionic-team/ionic-native#2821]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

(see also temporary fix/workaround down below)

**Current behavior:**
onDisconnect onConnect not firing
and expect also to identify the networkinfo
this.network.type

**Expected behavior:**
onDisconnect onConnect to be firing.
this.network.type also writes unknown
**Steps to reproduce:**

Create a new ionic blank project
and follow exactly installation from the ionic documentation

$ ionic cordova plugin add cordova-plugin-network-information
$ npm install --save @ionic-native/network

**Related code:**

```
The code example from ionic documentation 
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Package.json
"@ionic-native/network": "^4.12.2", 
"cordova-plugin-network-information": "^2.0.1",

@ionic/app-scripts : 3.2.0
Cordova Platforms  : android 7.0.0 ios 4.5.5
Ionic Framework    : ionic-angular 3.9.2

System:

ios-deploy : 1.9.2
ios-sim    : 6.1.2
Node       : v9.3.0
npm        : 5.5.1
OS         : macOS High Sierra
Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

ANDROID_HOME : ~/Library/Android/sdk

Misc:

backend : pro

```
insert the output from ionic info here
```

TEMPORARY WORKAROUND/FIX
$ npm uninstall --save @ionic-native/network
$ npm i --save @ionic-native/network@4.10.0

But still the this.network.type is showing unknown on 4.10.0

LOCATED ISSUE:
It seems to be locate in the module packets between > 4.10.0 and above

**Comment by erichstark** [comment]
I didnt have problem on 4.10 and 4.18 works also. The only one problem was that these events didnt fire on start, so I am not sure if it is a bug or feature.

**Comment by picolo74** [comment]
I m facing the same problem, downgrading to 4.10.0 solve the problem : Events are fired.


Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/home/aurel/.nvm/versions/node/v8.11.2/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/aurel/Android/Sdk)
   NodeJS            : v8.11.2 (/home/aurel/.nvm/versions/node/v8.11.2/bin/node)
   npm               : 6.1.0
   OS                : Linux 3.16

**Comment by erichstark** [comment]
I have created implementation where I checking if there is some type of network and then we can assume Online status

`platform.ready().then(() => {
      this.watchNetworkEvents(); // onConnect, onDisconnect
      let status = this.network.type !== 'none' ? 'Online' :'Offline';
      // send status
    });`
