### ISSUE TITLE
Ionic 4 image picker not resolving/rejecting

### ISSUE THREAD

**Issue by voltairebiton** [ionic-team/ionic-native#2822]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
After selecting images, there are no response being returned

**Expected behavior:**
Should return a response of the images i selected

**Steps to reproduce:**
1. Create new ionic 4 app
2. Install image picker as instructed here https://beta.ionicframework.com/docs/native/image-picker
3. Create a simple button and run this.imagePicker.getPictures and log the response

**Related code:**
```
this.imagePicker.getPictures(options).then((results) => {
  console.log(results);
}, (err) => { console.log(err) });
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:
   ionic (Ionic CLI)             : 4.3.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (5 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 7
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub. I will check it on tomorrow
