### ISSUE TITLE
how to use ionic v4 with mauron85 Background geolocation v3.0.0-alpha.50

### ISSUE THREAD

**Issue by coyu1314** [ionic-team/ionic-native#2842]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

After extensive research on why I am getting crash issue every time when backgroundlocation.start() is called on my android oreo 8.1. I finally found that pluging v2.x.x doesn't work with android oreo (8.1). So I tried to use the latest version of mauron85 background location v3.0.0-alpha.50. but then I am getting new issue when running the android app. It complains that this plugin is not found and needed to install this plugin every time when I call backgroundlocation.start(). I am not sure what went wrong here. It looks like that the ionic v4 beta will default to background location v2.3.6 . so my question is how can I use mauron85 background location v3.0.0-alpha.50 on ionic v4 beta. Please help. I got stuck on this issue for almost 2 weeks now and still no solution. thanks

**Expected behavior:**

bg location start normallly

**Steps to reproduce:**

1. create a new ionic v4 app. 
2. $ ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.50
3. $ npm install --save @ionic-native/background-geolocation@beta
4. run the app on a device using debug
5. call this.backgroundGeolocation.start(); on app
6. then in the android studio log will see the error saying the plugin not found. please install plugin cordova-plugin-mauron85-background-geolocation. 

**Related code:**

`Native: tried calling BackgroundGeolocation.start, but the BackgroundGeolocation plugin is not installed.`

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**Comment by lautaro08** [comment]
Hi, i am having the same problem with the version 2.3.6 of the BackgroundGeolocation plugin. 
It would be very helpful if someone could contribute to this issue.

**Comment by coyu1314** [comment]
> Hi, i am having the same problem with the version 2.3.6 of the BackgroundGeolocation plugin.
> It would be very helpful if someone could contribute to this issue.

don't use the latest version of the android. use android 7.0.0 and the issue will be gone(at least for now). try it see if it works for u. 
> ionic cordova platform add android@7.0.0

**Comment by Alain1405** [comment]
I'm having the same issue using alpha version of the plugin and release `4.20.0` of `@ionic-native/background-geolocation`. The issue appears to be related with this change `https://github.com/ionic-team/ionic-native/commit/1ba6f97#diff-e63998df11af847c2d73beb4b393dc9dL305`.

**Comment by jafelixdimaticasoftware** [comment]
Is there any solution implemented?

Thank!

**Comment by SaltyPotato** [comment]
I'm also having this issue

**Comment by TobiasFP** [comment]
I have the same issue

**Comment by VIKozlov** [comment]
Just use android@7.0.0. It works even in ionic 4 and --type=angular. I used @latest for installing cordova plugins and @ionic/native

**Comment by vilasrm** [comment]
> Just use android@7.0.0. It works even in ionic 4 and --type=angular. I used @latest for installing cordova plugins and @ionic/native

Please share detail steps to run Background Geolocation using Ionic 4.

following are ionic info

Ionic:
   ionic (Ionic CLI)             : 4.12.0 (C:\Users\VilasM\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.2.3

Cordova:
   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
 
System:
   NodeJS : v11.3.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Comment by VIKozlov** [comment]
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   NodeJS : v11.4.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

And I used --type=angular for the command "Ionic start"

**Comment by kanhaiya3020** [comment]
> Hi, i am having the same problem with the version 2.3.6 of the BackgroundGeolocation plugin.
> It would be very helpful if someone could contribute to this issue.

use this error will remove cordova plugin add cordova-plugin-mauron85-background-geolocation@2
$ npm install --save @ionic-native/background-geolocation@3

**Comment by kanhaiya3020** [comment]
> > Hi, i am having the same problem with the version 2.3.6 of the BackgroundGeolocation plugin.
> > It would be very helpful if someone could contribute to this issue.
> 
> use this error will remove cordova plugin add cordova-plugin-mauron85-background-geolocation@2
> $ npm install --save @ionic-native/background-geolocation@3



> > Hi, i am having the same problem with the version 2.3.6 of the BackgroundGeolocation plugin.
> > It would be very helpful if someone could contribute to this issue.
> 
> use this error will remove
$ cordova plugin add cordova-plugin-mauron85-background-geolocation@2
> $ npm install --save @ionic-native/background-geolocation@3
