### ISSUE TITLE
Android 7.1.2 sourceType use PHOTOLIBRARY Error:Unable to create bitmap!

### ISSUE THREAD

**Issue by zhumengjia** [ionic-team/ionic-native#2845]
I use plug-ins to upload pictures. 
select pictures from albums and convert them into base64 format. Error: unable to generate bitmaps!At the same time, I found that other Android phones with versions less than 8.0.0 have similar problems. It's no problem to take pictures with a camera. If you choose pictures from an album, you will report this error.
The plugin version I currently use is @ionic-native/camera^4.18.0&cordova-plugin-camera@^4.0.3.

**Comment by jmdmao** [comment]
same for me
