### ISSUE TITLE
Looks like local-notification cordova plugin no longer works on Android > v7 (and is possibly not supported)

### ISSUE THREAD

**Issue by chadanuk** [ionic-team/ionic-native#2849]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
@ionic-native/local-notifications ^4.18.0
katzer/cordova-local-notification 0.9.0-beta2
Cordova-Android v7.1.1
Android > v7

**Expected behavior:**
Schedule a notification to occur in the future.

**Steps to reproduce:**
Launch an ionic v3 app. In an Android emulator > android v7 

**Related code:**

Run the following and a notification will appear
```js
cordova.plugins.notification.local.schedule({
    title: 'My notification',
    text: 'Some text...',
    launch: true,
    priority: 2,
});
```
Run the following and a notification will *not* appear in 25 seconds
```js
cordova.plugins.notification.local.schedule({
    title: 'My notification',
    text: 'Some text...',
    launch: true,
    priority: 2,
    trigger: {in: 25, unit: 'second'}
});
```

**Other information:**
See https://github.com/katzer/cordova-plugin-local-notifications/issues/1732 for further information.
also, https://github.com/katzer/cordova-plugin-local-notifications/issues/1728

I have tested the fork suggested (https://github.com/Steffaan/cordova-plugin-local-notifications) and it fixes the problem but  we don't want to run this in production as it is not currently recommended by ionic.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.2.0 (/Users/danchadwick/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/danchadwick/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.3 (/Users/danchadwick/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.6.0
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by Entrecampos** [comment]
Hi @chadanuk

I am also using ionic 4 and after upgrade is working now :-)

[https://stackoverflow.com/questions/51918585/ionic3-the-end-of-local-notifications/56021324#56021324](url)
