### ISSUE TITLE
app-center-shared implementation

### ISSUE THREAD

**Issue by robertoandrade** [ionic-team/ionic-native#2850]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Seems like there's support for both `app-center-analytics`, `app-center-crashes` and `app-center-push` but the common/shared module between them isn't exposed as an ionic-native module: https://github.com/Microsoft/appcenter-sdk-cordova/tree/master/cordova-plugin-appcenter-shared

**Expected behavior:**
I wonder if there's an easy way to import this into an ionic app without official support or only waiting for the implementation by the team could get it exposed?

**Steps to reproduce:**
Trying to leverage some of the `AppCenter.installationId` and `AppCenter.customProperties` APIs.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by johnborges** [comment]
Looks like  [cordova-plugin-appcenter-shared](https://github.com/Microsoft/appcenter-sdk-cordova/tree/master/cordova-plugin-appcenter-shared) only exposes `AppCenter.getInstallId` and `AppCenter.setUserId`. I'll open a PR to get this added.
