### ISSUE TITLE
browser-tab Error: Unable to run. Uses-sdk:minSdkVersion 16 cannot be smaller than version 18

### ISSUE THREAD

**Issue by Lucaarioo** [ionic-team/ionic-native#2851]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
The bug is in @ionic-native/browser-tab
minSdkVersion is for 16 in the library
Not able to run on my device or emulator
**Unable to run. Uses-sdk:minSdkVersion 16 cannot be smaller than version 19**
In my config minSdk version is 19

**Expected behavior:**
After changing in my config file and even after clean build it was not working.
I changed the **def minSdkVersion** in the library package from 16 to 19, then it worked perfectly fine.

**Steps to reproduce:**
Install browser-tab keep minimum sdk version above 19. 
Try to build,
Error: Unable to run. Uses-sdk:minSdkVersion 16 cannot be smaller than version 18 ...

**Other information:**
I'm using Ionic 4

**Comment by malinges** [comment]
Same issue here with ionic 3.9 😞

**Comment by Lucaarioo** [comment]
@malinges I found a way out for this error. Just go to the npm module and just modify the version there to your requirement. That way worked fine for me

**Comment by Lucaarioo** [comment]
@malinges I found a way out for this error. Just go to the npm module and just modify the version there to your requirement. That way worked fine for me

**Comment by malinges** [comment]
Thanks, that's more or less what I did too.
But I had to automate this "patch" as my app is built on a CI environment.
Here's how I did it in case you're interested:

- create a script (for example `tools/patch-browsertab-plugin.js`) that looks for any files matching `platforms/android/cordova-plugin-browsertab/*-BrowserTab.gradle` (my app uses different app IDs on different environments, so in my case the filename _will_ change) and patches them by replacing `def minSdkVersion = 16` with `def minSdkVersion = 19`:
```javascript
const fs = require('fs');
const path = require('path');

const FOLDER = path.join(__dirname, '../platforms/android/cordova-plugin-browsertab');
const FILE_SUFFIX = '-BrowserTab.gradle';

fs.readdirSync(FOLDER)
.filter(filename => filename.endsWith(FILE_SUFFIX))
.forEach(filename => {
  const file = path.join(FOLDER, filename);
  const contents = fs.readFileSync(file).toString('utf-8')
    .replace('def minSdkVersion = 16', 'def minSdkVersion = 19');
  fs.writeFileSync(file, contents, {encoding: 'utf-8'});
});
```
- add this script to package.json's scripts:
```javascript
  "scripts": {
    // ... other scripts here ...
    "patch-browsertab-plugin": "node ./tools/patch-browsertab-plugin.ts"
  },
```
- automatically call this script before building using ionic hooks: add 2 scripts, called `ionic:build:before` and `ionic:serve:before`, in package.json and make them call `npm run patch-browsertab-plugin`:
```javascript
  "scripts": {
    // ... other scripts here ...
    "ionic:build:before": "npm run patch-browsertab-plugin",
    "ionic:serve:before": "npm run patch-browsertab-plugin",
    "patch-browsertab-plugin": "node ./tools/patch-browsertab-plugin.ts"
  },
```

And voilà, my app builds properly without having to think about it, and I can even switch environments whenever I need/want.

**Comment by dudanogueira** [comment]
@malinges  thank you. I was able to build it using ionic's appflow with this workaround
