### ISSUE TITLE
Video Player documentation seems to be outdated

### ISSUE THREAD

**Issue by raghav-axero** [ionic-team/ionic-native#2852]
It seems the current documentation present at https://ionicframework.com/docs/native/video-player/ is outdated.
The command "ionic cordova plugin add https://github.com/moust/cordova-plugin-videoplayer.git" no longer works and gives the following error:

> Failed to restore plugin "com.moust.cordova.videoplayer" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin com.moust.cordova.videoplayer@https://github.com/moust/cordova-plugin-videoplayer via registry.  
> Probably this is either a connection problem, or plugin spec is incorrect.  
> Check your connection and plugin name/version/URL.  
> Failed to get absolute path to installed module

The command which works instead is this:

"cordova plugin add cordova-plugin-video-player"

**Comment by kiprotichHarun** [comment]
i got an error when i used this command
