### ISSUE TITLE
@ionic-native/wechat : TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by yaseiakira** [ionic-team/ionic-native#2854]
**Current behavior:**
When I called sendPaymentRequest in the wechat plug-in, the console reported an error: Cannot read property'then'of undefined

**Expected behavior:**
The code can call wechat App and use its payment function

**Steps to reproduce:**
The code can call wechat App and use its payment function

**Related code:**

this.wechat.sendPaymentRequest({
            "prepayid": "res.Data.prepayId",
            "partnerid": "res.Data.machId",
            "timestamp": "res.Data.timeStam",
            "noncestr": "res.Data.nonceStr",
            "package": "Sign=WXPay",
            "sign": "res.Data.paySign"
        }).then(() => {
            this.alertService.showSimpleAlert("支付成功!", "JSON.stringify(wxPayResp)");
            //this.goPaySuccess();
        }).catch(() => {
            this.alertService.showSimpleAlert("支付失败!", "JSON.stringify(wxPayError)");
        });

This is the development environment information:
`Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Program Files\nodejs\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (E:\AndroidSDK)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.7.1
   OS                : Windows 10`

**Comment by qichangjun** [comment]
here is the same error

**Comment by dc165015** [comment]
I got the same error. If just only use the window.Wechat without @ionic-native wrap, it works. It seems the plugin didn't get wrapped correctly by the @Plugin() decorator.

**Comment by artdong** [comment]
@yaseiakira this.wechat.sendPaymentRequest({
"prepayid": "res.Data.prepayId",
"partnerid": "res.Data.machId",
"timestamp": "res.Data.timeStam",
"noncestr": "res.Data.nonceStr",
"package": "Sign=WXPay",
"sign": "res.Data.paySign"
})
