### ISSUE TITLE
@ionic-native/camera error "Requested device not found" in browser

### ISSUE THREAD

**Issue by iliyaZelenko** [ionic-team/ionic-native#2855]
**I'm submitting a bug report.**

**Current behavior:**
![image](https://user-images.githubusercontent.com/13103045/50419768-2d713f80-083b-11e9-95a0-9cfcc018acad.png)

**Expected behavior:**

To work in the browser.

**Steps to reproduce:**

1. Install plugin https://beta.ionicframework.com/docs/native/camera
2. Use my code
3. Run `ionic serve --cordova --platform browser` to check result in browser

**Related code:**

```js
try {
  const imageData = await this.camera.getPicture(options);

  console.log(imageData);
} catch (e) {
  console.dir(e);
}
```

**Other information:**

This code works in my virtual device. Also in browser i use Geolocation plugin and it's works here.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v10.11.0 (D:\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by TheSabre** [comment]
What you need to know:-

"ionic-serve" -  runs your code as a website
"ionic run"  - runs your code as an app for a particular platform, using the cordova plugins for that platform.

Try running: ionic cordova run _<your_platform>_

ionic-camera is supported by the following platforms:

- iOS
- Android
- Windows
- Browser

**Comment by iliyaZelenko** [comment]
```
ionic serve --cordova --platform browser
```
I took this command from [here](https://github.com/ionic-team/ionic-cli/issues/3043#issuecomment-408998076).

The reason I tried to use this command: I need a livereload (`--livereload` in `ionic cordova run browser` does not work, https://github.com/ionic-team/ionic-cli/issues/2312).



I also tried running `ionic cordova run browser` and got the same error:

![image](https://user-images.githubusercontent.com/13103045/50728430-45499d00-1132-11e9-8dd2-2a008b6496a8.png)

I use Geolocation plugin and it's works here, as with `ionic serve --cordova --platform browser`.

**Comment by danielsogl** [comment]
The Camera plugin is not supported in the browser.

**Comment by iliyaZelenko** [comment]
@danielsogl See the link that I wrote: https://beta.ionicframework.com/docs/native/camera/#supported-platforms

- Android
- Browser
- iOS
- Windows

**Comment by qdeme** [comment]
I have exactly the same problem.
I get the same error message on Windows in Chrome, when I run "ionic cordova run browser".
![image](https://user-images.githubusercontent.com/38522047/53644671-6f51a400-3c37-11e9-99cf-92afe946994e.png)
Is it a bug?
Thanks in advance for your help

**Comment by mirkonasato** [comment]
Had the same error, but on a workstation that has no camera so the error actually makes perfect sense: you cannot possibly use the camera on a device without camera!

Trying on a laptop _with_ a camera I get the [Cannot read property 'enumerateDevices' of undefined](https://github.com/ionic-team/capacitor/issues/1577) error instead.
