### ISSUE TITLE
@ionic-native/google-maps - Custom marker icons not show on PROD realeses

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic-native#2859]
I'm submitting a ... 
`  question`

OS: (check one with "x")
`  iOS`

cordova information: (run $> cordova plugin list)

```
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-advanced-http 2.0.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.5 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-proguard 1.0.0 "Cordova plugin ProGuard"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.3 "SocialSharing"
cordova-sqlite-storage 2.5.2 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
```

Ionic information: (run $> Ionic info)

```
Ionic:

   ionic (Ionic CLI)  : 4.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v9.9.0 (/usr/local/bin/node)
   npm               : 5.7.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

If you use @ionic-native/google-maps, please tell the package.json (only @ionic-native/core and @ionic-native/google-maps are fine mostly)

```
@ionic-native/core : 4.18.0
@ionic-native/google-maps : 4.15.1
Tested on iOS 12.1
```

Current behavior:
When I deploy map to mobile device with --prod flag, custom icons for markers not show(show default icon):

```
{
title: 'title',
snippet: 'snippet,
lat: lat,
lng: lng,
icon: {url: 'assets/icon/good.png', size: {width: 16, height: 16}},
data: data
}
```

If I add to the image url the 'www' (url: 'www/assets/icon/good.png'.......) it works. Without 'www' only works with --livereload flag

Ionic HTTP server rejects access for some reason.

https://user-images.githubusercontent.com/167831/50331253-ec7fd080-04b2-11e9-8cf1-3661c2f2920d.png

Expected behavior:
Custom marker icons should show on all deploy modes

In my opinion the problem is related with the last ionic webkview version with iOS

LINK to source code

`https://github.com/Hanzofm/ionic-googlemaps-quickdemo`

**Comment by chonz0** [comment]
Hi there! I was facing the same issue, and indeed it is related to webkview.
You need to add this to your `config.xml`:
```
    <platform name="ios">
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        ...
```
