### ISSUE TITLE
ionic-native/file-chooser doesn't have filter parameter

### ISSUE THREAD

**Issue by JaviRpo** [ionic-team/ionic-native#2860]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Promise of `open()` doesn't have an optional filter like the cordova plugin has.

**Expected behavior:**

Add the optional parameter.

**Related code:**
- [ionic-native documentation](https://ionicframework.com/docs/native/file-chooser/#open)
- [codova plugin documentation](https://github.com/ihadeed/cordova-filechooser#filter-optional)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.6.0 (C:\Users\javier.restrepo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 8 other plugins)
System:

   Android SDK Tools : 26.1.1 (C:\Users\javier.restrepo\AppData\Local\Android\sdk)
   NodeJS            : v10.7.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.1.0
   OS                : Windows 10
```

**Comment by 08Thug** [comment]
let filter={ "mime": "application/pdf" }  // text/plain, image/png, image/jpeg, audio/wav etc
 this.fileChooser.open(filter) ... //Rest of the code

Try the above code for filters ,but for me audio filter is not working

**Comment by agrajj** [comment]
I see this has been patched in https://github.com/ionic-team/ionic-native/blob/v5.12.0/src/@ionic-native/plugins/file-chooser/index.ts 

My app still using "@ionic-native/file-chooser": "^4.20.0", and am unable to upgrade to v5 at this moment.

Is there any workaround for the same?
