### ISSUE TITLE
Request Permission Method Not Found in SMS Plugin

### ISSUE THREAD

**Issue by sathishkrishnan20** [ionic-team/ionic-native#2866]
Could not Sent the SMS because the permission denied by the device. And Could not ask the Permission also, Could you add the RequestPermission Method for SMS. or is there any other option i can go ahead?

**Comment by jsfmrydvd** [comment]
Also having the same problem.

**Comment by jsfmrydvd** [comment]
Also having the same problem.

**Comment by sathishkrishnan20** [comment]
Hi @jsfmrydvd  I have tried using android permissions plugin. that is also not even asking the permission for SMS, am pasting the code which i am using, please advise me if any error here. 

`
this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(
        result => { 
            if(!result.hasPermission) {
              console.log(result)
              sendWithUserIntervention = true;
              this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS);
        }
}); `

**Comment by jsfmrydvd** [comment]
@sathishkrishnan20 it seems that ionic native sms doesn't really work on mine so instead I used https://github.com/hazems/cordova-sms-plugin/  

```
sendTxt() {
      var messageInfo = {
        	phoneNumber: "xxxxxxxxxx",
        	textMessage: "This is a test message"
        };
        this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => {
            sms.sendMessage(messageInfo, function(message) {
                alert(message);
            }, function(error) {
                alert(error);
            });
        }).catch((err) => {
            alert(JSON.stringify(err));
        });

  };
```
Btw you need to declare the custom plugin by (declare var sms: any;)

**Comment by sathishkrishnan20** [comment]
Could not help me out, Looks like the problem with mobile or Permissions, Because it is prompting for 
 to grant permission Camera Location, Storage and some others. but Its not prompting for READ_SMS, WRITE_SMS, READ_CONTACTS, WRITE_CONTACTS. 

may be some others, i checked those

**Comment by jsfmrydvd** [comment]
@sathishkrishnan20 just use this code to grant permissions 

```
this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => {
//this is to send SMS
}).catch((err) {
 alert(JSON.stringify(err));
});
```
You can find all permissions here [](https://developer.android.com/reference/android/Manifest.permission)

**Comment by sathishkrishnan20** [comment]
Thank you for your Response. the problem is, the dialogue box is not prompting for SEND_SMS permission to grant. but its prompting for CAMERA permission. 

and also its not catching the Error, instead its going to Success callback, with the message of  `{ hasPermission : false }`

**Comment by akashpjames** [comment]
`import { Component } from '@angular/core';
import { SMS } from '@ionic-native/sms/ngx';
import { AndroidPermissions } from '@ionic-native/android-permissions/ngx';

@Component({
    selector: 'app-sms',
    templateUrl: 'sms.page.html',
    styleUrls: ['sms.page.scss']
})
export class smsPage {
    
    constructor(public androidPermissions: AndroidPermissions, private sms: SMS) {}
    
    sendSMS() {
        this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => {
            this.sms.send('00000000', 'Hello world!');
        }).catch((err) => {
            alert(JSON.stringify(err));
        });
    }
}`
@jsfmrydvd  I tried this, but still it is not prompting for permission. Can anyone help me with this?

**Comment by jsfmrydvd** [comment]
Good day sir! @akashpjames, the sms native plugin didn't also work for me. So instead, I used this one [](https://www.npmjs.com/package/hazems-cordova-plugin-sms). Still you will need to add the android permissions. This is the current working code that I am using ` sendTxt() {
    var messageInfo = {
          phoneNumber: "09123456789", //add your number here
          textMessage: "This is a test message"
      };
      this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => {
          sms.sendMessage(messageInfo, function(message) {
              //
          }, function(error) {
              //
          });
      }).catch((err) => {
          alert(JSON.stringify(err));
      });
  };` Also, you need to add this one before the @component `declare var sms: any;
` Hope it helps!

**Comment by akashpjames** [comment]
@jsfmrydvd  Thanks man. Even though I tried these yesterday, it was not working for me. I found what my issue was, I had cordova-sms-plugin installed inside my plugins folder. Because of that, even though I had installed the plugin by adding this in package.json ("com.jsmobile.plugins.sms": "https://github.com/hazems/cordova-sms-plugin.git"), it was taking the old plugin. I uninstalled it and now it works seamlessly. Thanks.

**Comment by jsfmrydvd** [comment]
@akashpjames Glad it worked for you! Cheers

**Comment by LUNBOX** [comment]
@jsfmrydvd @akashpjames I uninstalled the ionic sms plugin and installed the other plugin and says plugin_not_availabale as the error

**Comment by LUNBOX** [comment]
Do I need put plugin in providers and if so what name of it in providers

**Comment by jsfmrydvd** [comment]
@LUNBOX Goodevening sir. Try to check if the plugin is already installed. Please run this code in your working directory on CMD `cordova plugins` you should see 

> com.jsmobile.plugins.sms 0.0.2 "sms" 
if the plugin is not there try running this code `com.jsmobile.plugins.sms 0.0.2 "sms" --save` 

>

**Comment by LUNBOX** [comment]
says + hazems-cordova-plugin-sms@0.0.2
updated 1 package and audited 4207 packages in 16.939s when I installed. Not in Cordoba plugin list so when I type com.jsmobile.plugins.sms 0.0.2 "sms" --save says -bash: com.jsmobile.plugins.sms: command not found. Any ideas? Thanks

**Comment by chrisgriffith** [comment]
To install a plug in the command is
 ionic cordova plugin add com.jsmobile.plugins.sms

**Comment by LUNBOX** [comment]
Thanks plugin is not in the plugin list when I type Cordova plugins but code below still causes plugin not installed error

var messageInfo = { phoneNumber: "numbegoesherer", textMessage: "This is a test message" }; 
      this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => { sms.sendMessage(messageInfo,function(message) { }, function(error) {  }); }).catch((err) => { alert(JSON.stringify(err)); }); };

**Comment by LUNBOX** [comment]
One thing I have noticed is 'sms' is declared but never used. in app module. this could be the reason any ideas please @jsfmrydvd 
      L34:  declare var sms: any;

**Comment by akashpjames** [comment]
@LUNBOX If you have uninstalled the ionic sms plugin, then no need of this line:
`import { SMS } from '@ionic-native/sms/ngx';`. Make sure that you have installed only one sms related plugin installed in your project. You can do so by this command `cordova plugins`. This is the [plugin](https://github.com/floatinghotpot/cordova-plugin-sms) I am using in my project. I don't have any other plugins in my plugins directory for SMS other than that.
While using the plugin I have mentioned, no need to add them in the providers list. Just have this at the top of your .ts file.
`declare var SMS: any;`
Then you can use the plugin in your .ts file like this:
`
        const options = {box: 'inbox', indexFrom: 0, maxCount: 10};
        this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.READ_SMS).then(
            success => {
                if (!success.hasPermission) {
                    this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.READ_SMS).
                    then((success) => {
                            this.ReadSMSList(options);
                        },
                        (err) => {
                            console.error(err);
                        });
                }
            },
            err => {
                this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.READ_SMS).
                then((success) => {
                        this.ReadSMSList(options);
                    },
                    (err) => {
                        console.error(err);
                    });
            });
        
        ReadSMSList(options){
            if (SMS) {
                SMS.listSMS(options, (ListSms) => {
                    console.log(ListSms);
                    },
                    error => {
                        alert(JSON.stringify(error));
                    });
            }
        }`

**Comment by LUNBOX** [comment]
I installed that plugin and it still saying plugin_not_installed as error message.
`var messageInfo = { phoneNumber: "numbegoesherer", textMessage: "This is a test message" };
this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => { SMS.sendMessage(messageInfo,function(message) { }, function(error) { }); }).catch((err) => { alert(JSON.stringify(err)); }); };`

any ideas why it saying this when cordovan plugins it says cordova-plugin-sms 1.0.5 "SMS"

**Comment by akashpjames** [comment]
@LUNBOX  I don't why you are getting this error message. Either you haven't installed properly or some residual code is messing up with your project. I created a demo app. You can see it [here](https://github.com/akashpjames/smsApp). This is one is working fine and sending the messages.

**Comment by LUNBOX** [comment]
Hi,

I tried ionic serve but not working it says Not performing Ionic build for
project type: angular. I then just used your ts file etc and looked at ur
sms plugins I have same one installed and still says plugin not installed
as error. You sure you can use sms if it not in providers as it not picking
up the plugin.

**Comment by akashpjames** [comment]
cd to the cloned directory.
1. npm install
2. ionic cordova run android

The plugin will not work with ionic serve as android permissions won't be available in your browser. You have to debug in an android phone with the second command I have typed in. The issue you got with ionic build for project type:angular might be because you haven't done npm install. I haven't added any other code in providers. I have tested the code I have put in that repo I have mentioned and it is working fine.

**Comment by LUNBOX** [comment]
Thanks for help, i did npm install when i run it on phone app emukates to
phone but says application error then err connection refused. I am using
ionic 3 could this be the issue

**Comment by akashpjames** [comment]
It could be the issue. The demo app I have created uses Ionic 4.

**Comment by LUNBOX** [comment]
Is there any way u could make it ionic 3 totally undedstand if u cant

**Comment by akashpjames** [comment]
Never worked on Ionic 3 before. I'll try tomorrow. Sorry, can't do it now. Have to sleep.

**Comment by LUNBOX** [comment]
No worries your great help

**Comment by akashpjames** [comment]
I will not be trying out with ionic 3 as I have to change my current ionic setup. But I found one GitHub project which uses the same SMS plugin and Ionic 3. You can refer to this [project](https://github.com/bharathirajatut/ionic3/tree/master/readSMSList) for Ionic 3 solution.

**Comment by LUNBOX** [comment]
I have followed it and found out. it alerts 'error2' and plugin_not_installed. I have no clue why this is. Is sms still supported with android as searched someplace you have fill in a form. I just do not know why it not working at all. I only get it working by opening the application of external sms but do not want this. Does intent have to be used.

`import { Component } from '@angular/core';
import { NavController,Platform, IonicPage } from 'ionic-angular';
declare var SMS:any;
import { AndroidPermissions } from '@ionic-native/android-permissions';

@IonicPage()
@Component({
  selector: 'page-testsms',
  templateUrl: 'testsms.html',
})

export class TestsmsPage {

    constructor( public androidPermissions: AndroidPermissions ) {}

    checkPermissionAndSend() {
 
        this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(
            success => {
                if (!success.hasPermission) {
                    this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).
                    then((success) => {
                            alert('hi')
                            this.sendMessage();
                        },
                        (err) => {
                            alert("error1")
                            alert(err);
                        });
                }
            },
            err => {
                this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).
                then((success) => {
                        alert('success')
                        this.sendMessage();
                    },
                    (err) => {
                        alert('error2')
                        alert(err);
                    });
            });
    }

    sendMessage(){
        if(SMS) {
            SMS.sendSMS("0871357817", "Test Message", () => {
                alert('Message sent successfully');
            }, (error) => {
                alert(error);
            });
        }
    }
}

<ion-header>
        <ion-navbar color="primary">
          <ion-title>
            SMS Application
          </ion-title>
        </ion-navbar>
      </ion-header>
      
      <ion-content padding>
        <ion-card>
          <ion-item>
            <button  ion-button color='light'(click)="checkPermissionAndSend()"> send message</button>
          </ion-item>
        </ion-card>
      </ion-content>

**Comment by LUNBOX** [comment]
Below my ts file and it is alerting error2 and saying plugin_not_installed. Very strange as list plugins says

> cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 0.6.0 "Permissions"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-device-motion 2.0.1 "Device Motion"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googleplus 7.0.0 "Google SignIn"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.0 "NativeStorage"
cordova-plugin-sms 1.0.5 "SMS"

Any ideas what is going on. Is sms not sending as android changed it sms at the start of the year. Does intent have be used. if sending a SMS is a core feature of your application, you need to fill the form. In this case, the developer can use options = { android: { intent: '' } }; I am just lost on why it saying plugin_not_installed.
```
``
import { Component } from '@angular/core';
import { NavController,Platform, IonicPage } from 'ionic-angular';
declare var SMS:any;
import { AndroidPermissions } from '@ionic-native/android-permissions';

@IonicPage()
@Component({
  selector: 'page-testsms',
  templateUrl: 'testsms.html',
})

export class TestsmsPage {
```

    constructor( public androidPermissions: AndroidPermissions ) {}

    checkPermissionAndSend() {
        alert('hisss');
        this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(
            success => {
                if (!success.hasPermission) {
                    this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).
                    then((success) => {
                            alert('hi')
                            this.sendMessage();
                        },
                        (err) => {
                            alert("error1")
                            alert(err);
                        });
                }
            },
            err => {
                this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).
                then((success) => {
                        alert('success')
                        this.sendMessage();
                    },
                    (err) => {
                        alert('error2')
                        alert(err);
                    });
            });
    }

    sendMessage(){
        if(SMS) {
            SMS.sendSMS("0871357817", "Test Message", () => {
                alert('Message sent successfully');
            }, (error) => {
                alert(error);
            });
        }
    }
`}`

**Comment by LUNBOX** [comment]
Update so `sendMessage(){
    if(SMS) {
        SMS.sendSMS("0871357817", "Test Message", () => {
            alert('Message sent successfully');
        }, (error) => {
            alert(error);
        });
    }
}

works it sends the text but that only if turn on sms permissions in app settings. does anyone know why it not prompting user to accept permissions when`call checkPermissionAndSend() function

**Comment by FallenKnight85** [comment]
Hi hope this helps.
On latest Android Versions 
Please ensure that you placed this line an all AndroidManifest.xml and plugin.xml

<uses-permission android:name="android.permission.SEND_SMS" />

Then check on app permissions of your android device if SMS is already listed.

**Comment by JeeDay** [comment]
Hi Guys,

I have a very simple solution for a part of you, but it depends on your use case,

1 - Do you want to send SMS in background ( as Android allows ) ? => I have no solution for you sorry

2 - Do you want to send SMS via native Intent ? ( The native SMS screen will opened with a prefilled message and recipients )

I was blocked for a while trying to use this plugin, and I was having the same issues that you met

above.. But I forgot there was another plugin dealing with text messages.

https://ionicframework.com/docs/native/social-sharing

With this plugin you can share a message via SMS, WhatsApp, Facebook, to recipients,

but you can just use it for SMS.

Simple example :

`// Message
const message = 'Hi, I can send message easily';
// Example with one phone number
const recipient = '0600112233'; => It can take one phone number or multiple separated by comma
this.sharer.shareViaSMS(message, recipient).then();`

**Comment by n1705771** [comment]
@jsfmrydvd I installed the custom sms plug in. Can you please tell me how to import the sms from the installed plug in? 
is it as below ?
`import { SMS } from '@ionic-native/sms'`;

I import it as above, but ionic cannot find the sendMessage function from sms.
`this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(() => {
      this.sms.sendMessage(messageInfo, function(message) {
        alert(message);
      }, function(error) {
        alert(error);
      });
    }).catch((err) => {
      alert(JSON.stringify(err));
    });`

**Comment by akashpjames** [comment]
Check this : https://github.com/akashpjames/smsApp/blob/master/src/app/tab1/tab1.page.ts

**Comment by n1705771** [comment]
@akashpjames Thanks! It is very helpful!

**Comment by mughalgee** [comment]
@akashpjames I did the same as your github project
sendMessage(){
            if(SMS) {
                SMS.sendSMS("00923404033847", "Test Message", () => {
                    alert('Message sent successfully');
                }, (error) => {
                  alert(error);
                });
            }else{
              alert('SMS not configured');
            }
        }
it did nothing.

**Comment by nikhil-kumar-behera-oranetech** [comment]
used https://github.com/akashpjames/smsApp/blob/master/src/app/tab1/tab1.page.ts as reference and getting error
declare var SMS: any;
getting ReferenceError: SMS is not defined

**Comment by NishilE** [comment]
> Hi @jsfmrydvd I have tried using android permissions plugin. that is also not even asking the permission for SMS, am pasting the code which i am using, please advise me if any error here.
> 
> `this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.SEND_SMS).then( result => { if(!result.hasPermission) { this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS); } else { this.sms.send(mobileNo, message); } });`

Did you found a solution to this?
