### ISSUE TITLE
Duplicate entry in ionic-native docs

### ISSUE THREAD

**Issue by appfeel** [ionic-team/ionic-native#2870]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Duplicate entry in https://ionicframework.com/docs/native for Admob left menu, both redirecting to https://ionicframework.com/docs/native/admob-pro

**Expected behavior:**
Only one entry, pointing to https://github.com/ionic-team/ionic-native/tree/master/src/%40ionic-native/plugins/admob

**Steps to reproduce:**
Open https://ionicframework.com/docs in browser
Click Admob left side menu (first entry)
Click Admob left side menu (second entry)

**Related code:**
N/A

**Other information:**
<img width="975" alt="captura de pantalla 2019-01-08 a les 9 44 31" src="https://user-images.githubusercontent.com/8643279/50819401-3dece400-132a-11e9-955f-382b57900fea.png">

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
N/A

**Comment by appfeel** [comment]
I've seen this other issue: https://github.com/ionic-team/ionic-native/issues/659 and it seems that Old folders don't get deleted automatically by the doc generator. @ihadeed Is there something I could do to help this to be fixed? I've been looking at the script `update_docs.sh` but don't really understand how ionic-site works...

**Comment by danielsogl** [comment]
ping @mlynch
