### ISSUE TITLE
NFC native plugin misses the phonegap «Tag Technology Functions»

### ISSUE THREAD

**Issue by nlko** [ionic-team/ionic-native#2873]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
No support of the «Tag Technology Functions» of the phonegap plugin

**Expected behavior:**
Support of the following API:
- connect;
- transceive;
- close API.

**Steps to reproduce:**
Trying to call these apis on 4.19.0 will fail if used through the dependecy injection.

But these API work if I call them through the global phonegap object (called nfc).

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by don** [comment]
#3381 adds the wrappers for [connect](https://github.com/chariotsolutions/phonegap-nfc#nfcconnect), [transceive](https://github.com/chariotsolutions/phonegap-nfc#nfctransceive), and [close](https://github.com/chariotsolutions/phonegap-nfc#nfcclose)
