### ISSUE TITLE
Ibeacon plugin not working with ionic v4

### ISSUE THREAD

**Issue by thrinasco** [ionic-team/ionic-native#2896]
when iam using Ibeacon with ionic 4 Beta i am getting the following Error.

locationManager is undefined.

![image 1](https://user-images.githubusercontent.com/12268500/51661330-8ff26280-1fd6-11e9-8cbd-f68c7e95da15.png)

**Comment by mhartington** [comment]
Hi there! This appears to be an issue, but there's no information on how to recreate or how to debug this. Could you please provide some more information or a demo in the form of a github repo? Thanks!

**Comment by MiguelSyll** [comment]
I have the same Problem. The plugin does not work. I am using Android and Ionic V4.

this.delegate = this.ibeacon.Delegate();

This line triggers the Error.

Miguel

**Comment by mhartington** [comment]
Closing as dup of #2631
