### ISSUE TITLE
local-notifications doesn't have a proper exported module.

### ISSUE THREAD

**Issue by JoCarrasco** [ionic-team/ionic-native#2897]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
LocalNotificationOriginal is not assignable to type provider error.

**Expected behavior:**
Should be able to import the module and used it without any compilation error.

**Steps to reproduce:**

Install ionic-native/local-notifications as the documentation shows it, and import it into the app.module.ts
**Related code:**
```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { IonicStorageModule } from '@ionic/storage';
import { Keyboard } from '@ionic-native/keyboard';
import { LocalNotifications } from '@ionic-native/local-notifications';
import { Geolocation } from '@ionic-native/geolocation';

import { MyApp } from './app.component';
import { ApiProvider } from '../providers/api';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { MapProvider } from '../providers/map';
import { ComponentsModule } from '../components/components.module';
import { ModalRegisteredPageModule } from '../pages/modal-registered/modal-registered.module';
import { LeafletProvider } from '../providers/leaflet';
import { CompileProvider } from '../providers/compile';
import { MarkerPlaceComponent } from '../components/marker-place/marker-place';
import { MarkerSelfComponent } from '../components/marker-self/marker-self';
import { MarkerUserComponent } from '../components/marker-user/marker-user';
import { NotificationProvider } from '../providers/notification';
import { ModalComponent } from '../components/modal/modal';

var _log = window.console.log;
window.console.log = (message?: any, ...optionalParams: any[]) => { return _log(JSON.stringify(message), JSON.stringify(optionalParams || [])) }

@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    ModalRegisteredPageModule,
    IonicModule.forRoot(MyApp, {
      scrollPadding: false,
      scrollAssist: false,
      autoFocusAssist: false,
      swipeBackEnabled: true
    }),
    HttpClientModule,
    ComponentsModule,
    IonicStorageModule.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    MarkerSelfComponent,
    MarkerUserComponent,
    MarkerPlaceComponent,
    ModalComponent
  ],
  providers: [
    Keyboard,
    StatusBar,
    HttpClient,
    Geolocation,
    SplashScreen,
    LocalNotifications,
    { provide: ErrorHandler, useClass: IonicErrorHandler },
    ApiProvider,
    MapProvider,
    CompileProvider,
    LeafletProvider,
    NotificationProvider
  ]
})
export class AppModule { }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by JoCarrasco** [comment]
![36359a6f-1bfc-479e-95d5-77fb80fbfcbf](https://user-images.githubusercontent.com/34868263/51720775-5bf25e00-2025-11e9-9bfb-8d46f1670f21.jpg)

**Comment by siddharth-vaghasia** [comment]
+1 have you found any fix for this ?
Also when we import it in directly page...it give below error
"ERROR in src/app/home/home.page.ts(18,95): error TS2304: Cannot find name 'LocalNotifications'"

**Comment by JoCarrasco** [comment]
> +1 have you found any fix for this ?
> Also when we import it in directly page...it give below error
> "ERROR in src/app/home/home.page.ts(18,95): error TS2304: Cannot find name 'LocalNotifications'"

Sure. I found it,It looks like there's a outdated ionic 3 core trying to get into a ionic 4 package.

Just install the 4.7.0 version of local-notifications

**Comment by Entrecampos** [comment]
Hi @siddharth-vaghasia 

I am also using ionic 4 and after upgrade is working now :-)

[https://stackoverflow.com/questions/51918585/ionic3-the-end-of-local-notifications/56021324#56021324](url)
