### ISSUE TITLE
upgrading from 4.20 to 5.0.0

### ISSUE THREAD

**Issue by blondie63** [ionic-team/ionic-native#2898]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --consolelogs --nobrowser
[app-scripts] [11:03:09]  ionic-app-scripts 3.2.2
[app-scripts] [11:03:09]  watch started ...
[app-scripts] [11:03:09]  build dev started ...
[app-scripts] [11:03:09]  clean started ...
[app-scripts] [11:03:09]  clean finished in 5 ms
[app-scripts] [11:03:09]  copy started ...
[app-scripts] [11:03:09]  deeplinks started ...
[app-scripts] [11:03:09]  deeplinks finished in 92 ms
[app-scripts] [11:03:09]  transpile started ...
[app-scripts] [11:03:13]  typescript: src/app/app.component.ts, line: 26
[app-scripts]             Cannot find name 'SplashScreen'.
[app-scripts]       L25:  public splashScreen: SplashScreen,
[app-scripts]       L26:  public translate: TranslateService,
[app-scripts]       L27:  public store: Store,
[app-scripts] [11:03:13]  typescript: src/app/app.module.ts, line: 95
[app-scripts]             Argument of type '{ declarations: (typeof TabsPage | typeof LoginPage | typeof TermsOfServicePage | typeof
[app-scripts]             OtpVerif...' is not assignable to parameter of type 'NgModule'. Types of property 'providers' are
[app-scripts]             incompatible. Type '(typeof IonicErrorHandler | typeof Store | typeof LoggerService | DeviceOriginal |
[app-scripts]             typeof ApiServ...' is not assignable to type 'Provider[]'. Type 'typeof IonicErrorHandler | typeof Store |
[app-scripts]             typeof LoggerService | DeviceOriginal | typeof ApiServi...' is not assignable to type 'Provider'. Type
[app-scripts]             'DeviceOriginal' is not assignable to type 'Provider'. Type 'DeviceOriginal' is not assignable to type
[app-scripts]             'ClassProvider'. Property 'provide' is missing in type 'DeviceOriginal'.
[app-scripts] [11:03:13]  typescript: src/pages/home/home.ts, line: 40
[app-scripts] [11:03:13]  typescript: src/pages/signup/signup.ts, line: 80
[app-scripts] [11:03:13]  typescript: src/providers/api.service.ts, line: 15
[app-scripts] [11:03:13]  typescript: src/providers/geolocation.service.ts, line: 24
[app-scripts]       L95:  @NgModule({
[app-scripts]       L96:    declarations: [
[app-scripts]             Cannot find name 'Network'.
[app-scripts]       L39:  public datetimePipe: DatetimePipe,
[app-scripts]       L40:  public network: Network,
[app-scripts]       L41:  public alertCtrl: AlertController,
[app-scripts]             Cannot find name 'Sim'.
[app-scripts]       L79:      public formBuilder: FormBuilder,
[app-scripts]       L80:      private sim: Sim
[app-scripts]             Cannot find name 'Device'.
[app-scripts]       L14:  public store: Store,
[app-scripts]       L15:  public device: Device) {
[app-scripts]       L16:  this.state = store.getState();
[app-scripts]             Argument of type '{ timeout: number; enableHighAccuracy: boolean; }' is not assignable to parameter of type
[app-scripts]             'PositionCallback'. Type '{ timeout: number; enableHighAccuracy: boolean; }' provides no match for the
[app-scripts]             signature '(position: Position): void'.
[app-scripts]       L23:  return new Promise((resolve, reject) => {
[app-scripts]       L24:    this.geolocation.getCurrentPosition(this.GEOLOCATION_SETTINGS).then((user_position) => {
[app-scripts]       L25:      console.log("getGeolocation - SUCCESS", user_position);
[app-scripts] [11:03:13]  copy finished in 4.43 s

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.1, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 3.1.0, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/mauro/Library/Android/sdk/)
   ios-deploy        : 2.0.0
   ios-sim           : 5.0.13
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```
Are there other dependencies ?
Type ver ?

**Comment by JustasKuizinas** [comment]
Have this problem to

**Comment by blondie63** [comment]
I solved it changing import to: 
// Ionic Native Plugins
import { StatusBar } from '@ionic-native/status-bar/ngx';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { IonicStorageModule } from '@ionic/storage/';
import { Network } from '@ionic-native/network/ngx';
import { Device } from '@ionic-native/device/ngx';

**Comment by mhartington** [comment]
V5 is part of the ionic 4 release process. As it is a major release, there are breaking changes.
Please see the docs for ionic native

https://ionicframework.com/docs/native/
