### ISSUE TITLE
Release/Tag 5.0.0

### ISSUE THREAD

**Issue by JulianVonDenBuschSiemens** [ionic-team/ionic-native#2900]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
You already published your plugins in version 5.0.0 on npm repositories.
On wich commit/tag were they build?
Have you planned to add a release/tag for version 5.0.0?

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
V5 is tagged on npm as `latest`

**Comment by JulianVonDenBuschSiemens** [comment]
You´re right. But I don´t see a correlation to a specific github commit.
I want to know from which commit the npm version 5.0.0 was build.
