### ISSUE TITLE
Cant get reader mode in ionic native nfc working

### ISSUE THREAD

**Issue by Vartex05** [ionic-team/ionic-native#2907]
Hi, iam trying to use Reader mode to read NFC in my app, but it doesnt seems to work. I use it like this : 

```
  readCardId(){
    return new Promise<string>((resolve)=>{
      let alert=this.alertCtrl.create({title:'Přiložte kartu:',enableBackdropDismiss: false,
        buttons: [{
          text: 'Zrušit',
          role:'cancel',
          handler: data => {
            resolve(null);
          }}]
      });
      alert.present();
      this.nfc.readerMode(this.nfc.FLAG_READER.NFC_A,(tag)=>{
        console.log("tag:"+tag);
        resolve(null);
      },
      error=>{
        console.log("errTag"+error);
        resolve(null);
      });
    })
}
```

But when i read a tag, it doesnt log anything, not even any error. Has anyone some working example?

**Comment by mhartington** [comment]
Hi there! It appears this isn't really an issue, and more of a question, so Im going to close this. Please check out the [forum](https://forum.ionicframework.com) as this is a better place for questions. Thanks!
