### ISSUE TITLE
I have been importing both google plus and facebook with /ngx but still facing the same issue.

### ISSUE THREAD

**Issue by NimaiUser** [ionic-team/ionic-native#2908]
I have been importing both google plus and facebook with /ngx but still facing the same issue. 
![google fb error](https://user-images.githubusercontent.com/20452525/52053016-2f3acb00-257e-11e9-872a-fe8533a71c98.png)
I am using ::::
--------------
Ionic CLI :  4.3.0
cordova  : 8.1.2 
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0

_Originally posted by @NimaiUser in https://github.com/ionic-team/ionic-native/issues/2621#issuecomment-459319141_

**Comment by mhartington** [comment]
Hi there! This appears to be an issue, but there's no information on how to recreate or how to debug this. Could you please provide some more information or a demo in the form of a github repo? Thanks!

**Comment by NimaiUser** [comment]
Thank you for your response.

I just created a sample ionic project and  added cordova-plugin-facebook4 with my project appId and app name. And imported  facebook/ngx with Facebook in providers and in login screen. On login button i am using following method:
 
 async doFbLogin(){
    const loading = await this.loading.create({
      spinner: 'crescent',
      content: 'Please Wait....'
    });
    
    // var permission = new Array<string>();

    //the permissions your facebook app needs from the user
    const permissions = ["public_profile", "email"];

    this.fb.login(permissions).then(response =>{
      this.presentLoading(loading);
      let userId = response.authResponse.userID;

      console.log("Fb data"+response)
      //Getting name and gender properties
      this.fb.api("/me?fields=name,email", permissions)
      .then(user =>{
        console.log("fb details","->"+user)
        loading.dismiss();
      })
    }, error =>{
      console.log(error);
      loading.dismiss();
    });
  }

  async presentLoading(loading) {
    return await loading.present();
  }

which is reflecting an error in mobile while tesing.

**Comment by NimaiUser** [comment]
Thank you.

My Ionic CLI  is 4.3.0

So i am using it with /ngx.
Presently i am following this tutorial https://ionicthemes.com/tutorials/about/ionic-facebook-login
with out using native-storage plugin. On mobile it is not performing anything while inspecting it in web browser it displayed the above errors(that i mentioned in my first post).
