### ISSUE TITLE
Function Missing in OneSignal plugin

### ISSUE THREAD

**Issue by onlyanup** [ionic-team/ionic-native#2909]
**I'm submitting a ...** 
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Getting error Property 'setExternalUserId' does not exist on type 'OneSignal' while using the function described in the Cordova SDK Document.

**Expected behavior:**
The function should exist.

**Steps to reproduce:**
Create an Ionic 4 starter project and install OneSignal plugin
Initialize the plugin and try to register user id

**Related code:**
```
export class AppComponent {
constructor(oneSignal: OneSignal) {
   oneSignal.setExternalUserId(userId);
}

```

**Other information:**
OneSignal-Cordova-SDK has added 2 new functions in release 2.4.6:
```
setExternalUserId(string)
removeExternalUserId
```
These functions implementations are missing from the latest version of "@ionic-native/onesignal": "^5.0.0" package

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Ionic:

   ionic (Ionic CLI)             : 4.10.0 (C:\Users\Anup\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 9 other plugins)

System:

   NodeJS : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by zamtime** [comment]
Did you find a solution for this? I need these methods as well...

**Comment by onlyanup** [comment]
No, I have not found it yet. But looks like the developers are not even looking at it. Will find a workaround and let you know soon.

**Comment by danielsogl** [comment]
We have not enough time to maintain the hundreds plugins inside the ionic-native repo. This repos need the help of the community. Fell free to open an PR adding the missing functions

**Comment by onlyanup** [comment]
Since the feature is released [here](https://github.com/ionic-team/ionic-native/releases/tag/v5.7.0), I'm closing this issue.

**Comment by nacho004** [comment]
@onlyanup can you please add the methods to version 4 of @ionic-native/onesignal ?

**Comment by onlyanup** [comment]
This issue is already closed. You can create a new issue if you have any.
@nacho004
