### ISSUE TITLE
Device Accounts plugin not working with ionic 4. Returns error saying plugin_not_installed.

### ISSUE THREAD

**Issue by manishmlv50** [ionic-team/ionic-native#2911]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mhartington** [comment]
Hi there! It appears that you've opened an issue, but have not provided the necessary information we require in order to debug. Im going to close this issue because of that. Please open a **new** issue and completely fill out the issue template. Thanks!
