### ISSUE TITLE
InApp Browser TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by pptyasar** [ionic-team/ionic-native#2918]
**I'm submitting a**
[X] bug report

**Current behavior:**
Could not call insertCSS(), or executeScript() functions with this.iab.create(..)  object

**Related code:**

```
const browser = this.iab.create('https://www.elgiultra.com');
browser.insertCSS({ code: ".navbar-header{color: red;}" });
```

**Error information:**
When debugging  with android studio error thrown as "**TypeError: Object(...) is not a function**"

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/opt/Android/Sdk)
   NodeJS            : v8.11.3 (/usr/bin/node)
   npm               : 3.10.10
   OS                : Linux 4.15

```

**Comment by InvinNO1** [comment]
I have encountered this problem when I use ionic 3 and @ ionic-native / in-app-browser 5.x.x.
Please use @ ionic-native / in-app-browser 4.20.0 to solve the problem
