### ISSUE TITLE
in-app-purchase-2 does not support store.manageSubscriptions()

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic-native#2921]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
No support for store.manageSubscriptions() as described on https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md

**Expected behavior:**
To be supported.

**Steps to reproduce:**
No way to call the function.

**Other information:**
ionic-native version 4.20.0 (but 5.0.0 doesn't have it either)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI) : 4.8.0

System:

   NodeJS : v6.11.5
   npm    : 3.10.10
   OS     : macOS Mojave
```

**Comment by selected-pixel-jameson** [comment]
Obviously it would be nice if this would work, but I think it goes without saying that most things don't work as expected when it comes to Ionic Native. That being said you can just use this link to work around this. https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/manageSubscriptions

**Comment by danielsogl** [comment]
Feel free to open a PR to add this feature :)
That's the sense of Open Source.
