### ISSUE TITLE
How to add my own custom plugin with ionic v4 app?

### ISSUE THREAD

**Issue by DRPC1996** [ionic-team/ionic-native#2927]
I haven't any idea to do it

**Comment by ihadeed** [comment]
@DRPC1996 two options:

1. fork the repo, add a plugin, and compile it from there
2. write plugin wrappers similar to the compiled Ionic Native code; example:
```ts
import { cordova, IonicNativePlugin } from '@ionic-native/core';

export class MyPlugin extends IonicNativePlugin {
  // @Plugin args go here as properties
  pluginName = 'MyPlugin';

  someMethod(arg1, arg2) {
    // @Cordova decorator args go to this cordova method (3rd arg)
    return cordova(this, 'someMethod', {}, [arg1, arg2]);
  }
}
```

**Comment by stefantrost** [comment]
Are there any notes on how to migrate ionic-native plugins? I couldn't find any, neither in the Ionic migration guide, nor the complete list of breaking changes, nor in the changelog of ionic-native....

**Comment by ihadeed** [comment]
@stefanhuber how did you create your old Ionic Native plugins? 

If you created them inside your Ionic app, you will have to follow the example above for migration (importing functions, removing decorators).

If it was part of an Ionic Native repo fork, you can just update your fork to the current master branch, place your files in the plugins directory, and recompile.

**Comment by stefantrost** [comment]
@ihadeed I didn't create them, but I  guess they were created as part of the Ionic app. The steps you prescribed seemed to have worked. Thank you!
It would be really helpful if this information would be part of the migration guide of Ionic.

**Comment by bryyyanribo** [comment]
@ihadeed Is there a guide for this one? I tried to follow this [docs](https://github.com/ionic-team/ionic-native/blob/master/DEVELOPER.md) and I can't seem to fix the issue.
