### ISSUE TITLE
cordova-plugin-advanced-http not working

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/ionic-native#2934]
**I'm submitting a **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
By just installing cordova-plugin-advanced-http like instructed [here](https://ionicframework.com/docs/native/http#installation), building my project and running it in iOS through XCode i'm getting the following lines in the console:
```
[log] - deviceready has not fired after 5 seconds.
[log] - Channel not fired: onCordovaReady
```

**Expected behavior:**
To not see 2 lines printed above and be able to use HTTP lib

**Steps to reproduce:**

**Related code:**

**Other information:**
I'm currently running Ionic4 with Vuejs and Capacitor

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI) : 4.10.3 (/usr/local/lib/node_modules/ionic)

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (3 plugins total)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

We have instructions for [Angular](https://ionicframework.com/docs/native#angular) or [vanilla javascript](https://ionicframework.com/docs/native#vanilla-javascript)

The instructions you link are for Angular, so in vue might be a bit different, try the vanilla ones.

**Comment by NunoSav** [comment]
@jcesarmobile i made this sample project, tested it out on iPhone 5s with iOS12 and still getting those lines output'd to the XCode console

repo: https://github.com/NunoSav/ionic-capacitor-vue-native-http

**Comment by jcesarmobile** [comment]
It's a Capacitor issue, I've been able to reproduce. Let's continue there
https://github.com/ionic-team/capacitor/issues/1247

**Comment by danielsogl** [comment]
Thanks for the update
