### ISSUE TITLE
Blank screen after removing the plugins from app.module.ts

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic-native#2943]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

I updated to Ionic native 5.2.0 and removed the plugins from `app.module.ts` as described [here](https://github.com/ionic-team/ionic-native/blob/master/CHANGELOG.md#520-2019-02-20).

After this my Ionic 4 app shows the SplashScreen but doesn't show anything else, so the app shows a blank white screen constantly.

When I re-add the plugins to `app.module.ts` everything works as before.

**Expected behavior:**

The app is working after removing the plugins from `app.module.ts`

**Steps to reproduce:**

1. update to Ionic native 5.2.0
2. remove all plugins from `app.module.ts`
3. app doesn't work anymore without throwing errors

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.13.3
   @angular-devkit/schematics    : 7.3.3
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 11 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.8.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

```

**Comment by remisture** [comment]
Same issue for me. `ionic s --prod` gives me `NullInjectorError: No provider for t!`.

**Comment by chrisgriffith** [comment]
Did you remove the references from the app.component.ts file? The starter templates have both the Splash Screen and Status Bar plugs called there.

**Comment by cvaliere** [comment]
yup, docs say that, starting from v5.2.0, importing plugins in app.module is not required anymore, but it seems untrue

it's supposed to be this commit (https://github.com/ionic-team/ionic-native/commit/8b53c04dc5d8e3bb8f527499e3e0a4661c097072), but it doesn't seem to work

@danielsogl what do you say?

**Comment by carstenbaumhoegger** [comment]
@chrisgriffith No, I didn't remove the references from `app.component.ts`.
I've just removed the imports from `app.module.ts` as @cvaliere says and this didn't work although the docs say so.

**Comment by danielsogl** [comment]
I reverted my changes for now.
