### ISSUE TITLE
[iOS] Location accuracy will always return true  

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-native#2945]
Desc:
IOS
I have disabled location service for all app. for the first time it will open setting & cancel,
Setting will navigate to location service. And when you hit the cancel and re-open the app you will always get true even if the location service is disabled.

I am using Android permission that works fine in android it checks everytime i open the page/ or navigate somewhere else and return back to that page it checks everytime. [IonViewWillEnter]

There is no proper way to detect i am not even able to detect as if the location service of mobile is off then isLocationEnabled will return N/a, isLocationAvailable will also return N/a or force user in ios to enable location service or location permission for app.

case1:
Suppose i enabled the location service and enable the location permission for my app. then after sometime i disabled the location permission for my app then isLocationEnabled is returning true,
and isLocationAvailable returns the N/a [Diagnostic]
case2:
suppose i enabled the location service and not allowed the location permission for my app. then islocationEnabled is returning true and isLocationAvaiable return the N/a [Diagnostic]
If IslocationEnabled return the true then how can i navigate the user to setting

REPO: https://github.com/indraraj26/location-permission-ios

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Location accuracy will always return true even if you cancel 

**Expected behavior:**
Location accuracy should popup everytime if location service is disabled

**Steps to reproduce:**

**Related code:**

```
html
 <button ion-button color="danger" (click)="enableLocation()"> Location </button>
ts
 this.diagnostic.getLocationAuthorizationStatus().then((yes) => {
    if(yes == 'denied') {
      console.log("get getLocationAuthorizationStatus", yes);
      this.locationAccuracy.canRequest().then((canRequest: boolean) => {

        if(canRequest) {
        // the accuracy option will be ignored by iOS
        this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
        (v) => {alert('Request successful')
          this.locationAccs = v; 
        },
        error => alert('Error requesting location permissions'+JSON.stringify(error))
        );
        }
        else {
          this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
            (v) => {alert('Request successful')
              this.locationAccs = v; 
            },
            error => alert('Error requesting location permissions'+JSON.stringify(error))
            );
        }
        
        });
        }
  }).catch(err => console.log(err))
}
```

````
all this will return N/a except Authorization stauts which is denied
checkLocationSetting() {
    this.diagnostic.isLocationAuthorized().then((yes) => {
      console.log("location authorized",yes)
      this.isLocactionAuthorizedd = yes;
    }).catch(err => console.log(err));
    this.diagnostic.isLocationAvailable().then((yes) => {
      console.log("location available", yes);
      this.isLocationAviabledd = yes;
    }).catch(err => console.log(err))
    this.diagnostic.getLocationAuthorizationStatus().then((yes) => {
      console.log("get getLocationAuthorizationStatus", yes);
      this.getLocationAuthorizationStatussed = yes;
    }).catch(err => console.log(err))
    this.diagnostic.isLocationEnabled().then((yes) => {
      console.log("is location enabled", yes);
      this.islocationEnableddd = yes;
    }).catch(err => console.log(err));
  }
````

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v9.10.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by dpa99c** [comment]
This is a documented caveat of using the location accuracy plugin on iOS - see [iOS "Cancel" button caveat](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#ios-cancel-button-caveat): 

> iOS assumes that if the user pressed "Cancel", they don't want your app to use their location, so iOS prevents you from asking them again to switch on Location Services.

If Location Services is switched off, then [isLocationEnabled()](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationenabled) will return false. Therefore if the user pressed Cancel, there's no way you can tell that; you can only tell that Location Services is still off.

Note that in my experience, this is an extremely uncommon real-world situation: most iOS users don't even know where to find Location Services, let alone making the decision to turn it off. Those that do are probably informed enough to know of the consequences without your app trying to detect it and tell them.

**Comment by indraraj26** [comment]
when i disabled the location service then isLocationEnabled() returns nthing.  How can i check my app location permission is set to never or while using the app or always

**Comment by dpa99c** [comment]
Using [cordova-diagnostic-plugin-example](https://github.com/dpa99c/cordova-diagnostic-plugin-example):

Location Services ON:
<img width="300" src="https://user-images.githubusercontent.com/2345062/53739030-b08cc280-3e88-11e9-82d0-c1091b0c58fe.png" />
![screenshot 2019-03-04 at 14 15 26](https://user-images.githubusercontent.com/2345062/53739034-b08cc280-3e88-11e9-9028-9da476bcd88b.png)

Location Services: OFF:
<img width="300" src="https://user-images.githubusercontent.com/2345062/53739032-b08cc280-3e88-11e9-9522-cd9f8432d3d1.png" />
![screenshot 2019-03-04 at 14 18 22](https://user-images.githubusercontent.com/2345062/53739029-aff42c00-3e88-11e9-9c09-a44a0ced8852.png)

**Comment by indraraj26** [comment]
Dear @dpa99c, 

Thank you for helping me. Now isLocationEnabled() return false/true based on location service.

This is what i have done even for the first time i don't see app location permission request in iOS.

This is all in ionViewWillEnter which will execute everytime when user will open page i have condition where i will always have to submit lat and lng.

Before this i am checking platform is ready or not;
````
if (this.platform.is('ios')) {
                this.diagnostic.isLocationEnabled().then((yes) => {
                  console.log(yes);
                  if (!yes) {
                    console.log("make it location service is disabled please check setting")
                     this.checkLocation = true; //dom data will hide
                     this.iosLocation = true; //dom for instruction to user that location service is disabled.
                  }else {
                    console.log("i am in else condition")
                   this.diagnostic.getLocationAuthorizationStatus().then((status) => {
                     console.log("getLocation Authorization status", status) // if location service on i will come here and check not_determined or denied then make a request 
                           if((status == 'denied') || (status == 'not_determined')) {
                             console.log("lets make a request", status)
                            this.locationAccuracy.canRequest().then((canRequest: boolean) => {
                              if(canRequest) {
                                this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
                                  () => console.log('Request successful'),
                                  error => console.log('Error requesting location permissions', error)
                                );
                              }
                              this.navigateToSetting = true; // this will turn on one button dom that will navigate to user to location permission 
                              this.checkLocation = true;  // dom data will hide
                              console.log("button will see in dom")
                            });
                           } else {
                             this.checkLocation = false; 
                             this.iosLocation = false;
                             this.navigateToSetting = false;
                             console.log("everything is good. you are good to go")
                           }
                   }).catch(
                     err => {
                       console.log("get Location authrozation status", err)
                     }
                   )

                  }
                }).catch((error) => console.log("is location enabled diagnostic", error));
              }
````

Thank you.

**Comment by indraraj26** [comment]
Dear @dpa99c , 

I can confirm without ionic-webview it is not making any request for location permission in IOS.

Here is the repo: https://github.com/indraraj26/location-permission-ios

Note: i am getting cors issue if i am using ionic-webview in ios but it is fine in android.

Thank you

**Comment by dpa99c** [comment]
> I can confirm without ionic-webview it is not making any request for location permission in IOS.

Your code above is wrong: you are calling `getLocationAuthorizationStatus()` and if the resulting status is `denied` or `not_detemined`, you are calling `locationAccuracy.canRequest()` and `locationAccuracy.request()` and expecting this to request "location permission", but this is not the purpose of the location accuracy plugin.

The location accuracy plugin on iOS requests the system dialog which provides the Settings button in order to manually re-enable Location Services - it **does not** request "location permission" (authorization) - this should be done using [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization) from `cordova-diagnostic-plugin`.  

Please see [this screen capture](http://ge.tt/5VXNvru2) which demonstrates the plugin working fine on iOS 12 using [the example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example). As can be seen in the video clip, the system dialog is correctly shown and this works even if the app has not yet requested/been granted location authorization.

**Comment by indraraj26** [comment]
Dear dpa99c, 

That means first i have to call requestLocationAuthorization then i should make a request for location accuracy popup.

Okay let me change the code Thank you for helping me i know it is very fraustrating for you that you have to explain each and everything.

Thank you once again.

**Comment by dpa99c** [comment]
@indraraj26 

> That means first i have to call requestLocationAuthorization then i should make a request for location accuracy popup.

If Location Services is OFF then you can't tell if your app has location authorization or not, so the best flow is:

- check if Location Services is ON or OFF using `diagnostic.isLocationEnabled()`
- if OFF, use the location accuracy plugin (`locationAccuracy.canRequest()` => `locationAccuracy.request()`) to request the system dialog which allows users to manually turn it ON via Settings 
- since the user pressing the "Settings" button in the dialog switches to the Settings app, your app is put into the background, so on your app resuming from background (`resume` event), you should re-check if Location Services  is ON or OFF using `diagnostic.isLocationEnabled()`.
- once you know Location Services is ON, you can then check if your app has location authorization (permission) using `diagnostic.isLocationAuthorized()`.
- if it's not authorized, request it with `diagnostic.requestLocationAuthorization()`.


> Thank you for helping me i know it is very fraustrating for you that you have to explain each and everything.

It's OK, this is a complicated mechanism to implement and lots of devs find it tricky to understand. Sorry if I sounded rude.

**Comment by indraraj26** [comment]
Dear @dpa99,

Thank you, this algorithm works perfectly in iOS. I have been struggling from two days to make it work for iOS. I really appreciate your help.
