### ISSUE TITLE
Plugin_not_installed

### ISSUE THREAD

**Issue by sostoli** [ionic-team/ionic-native#2948]
Hello team,
I noticed that everytime i resolved a promise, in the catch i get a "plugin_not_installed" as error. I remove and add platform again but still there. I am running out of idea.

Here is my ionic info

Ionic:

   ionic (Ionic CLI)  : 4.9.0 (/usr/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/xxx/Android/Sdk)
   NodeJS            : v10.15.1 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

**Comment by ShafiqShams** [comment]
same issue please help ionic team :'(

**Comment by robmoore-i** [comment]
I'm trying to use a custom plugin and getting this as well.

3 weeks old and no response. Ionic team, have you considered ditching your marketing team and actually shipping quality software?

**Comment by tuxicoman** [comment]
I have encountered a similar issue while using @ionic-native/firebase-crashlytics.

In my case, the method `initialize()` wasn't matching the cordova lib's function `initialise()` (s vs z) resulting in a negative answer of the checkAvailability() function from @ionic-native/core.

Since the test of plugin and method availability is done together, the plugin returned a misleading warning "Plugin not installed..." 

```
function checkAvailability(plugin, methodName, pluginName) {

    [...]

    if (!pluginInstance || (!!methodName && typeof pluginInstance[methodName] === 'undefined')) {
        if (typeof window === 'undefined' || !window.cordova) {
            cordovaWarn(pluginName, methodName);
            return ERR_CORDOVA_NOT_AVAILABLE;
        }
        pluginWarn(pluginName, pluginPackage, methodName);
        return ERR_PLUGIN_NOT_INSTALLED;
    }
    return true;
}
```

**Comment by ArnoldMessifet** [comment]
To make it work, I had to remove "isCallSupported" call... This needs a fix.
```
// const isCallSupported = await this.callNumber.isCallSupported();
// if (isCallSupported) {
    return await this.callNumber.callNumber(phoneNumber, true);
// }
```
