### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined in Email Composer

### ISSUE THREAD

**Issue by mehtaparam** [ionic-team/ionic-native#2957]
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of undefined
**Current behavior:**
vendor.js:2134 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at get (vendor.js:62312)
    at getPlugin (vendor.js:62344)
    at checkAvailability (vendor.js:75732)
    at vendor.js:105120
    at EmailComposer.isAvailable (vendor.js:105144)
    at ImportExportPage.<anonymous> (18.js:139)
    at step (18.js:91)
    at Object.next (18.js:72)
    at 18.js:66
    at new t (polyfills.js:3)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at webpackJsonp.775.__awaiter (18.js:62)
    at ImportExportPage.webpackJsonp.775.ImportExportPage.sendEmail (18.js:136)
    at ImportExportPage.<anonymous> (18.js:223)
    at step (18.js:91)
    at Object.next (18.js:72)
    at 18.js:66
    at new t (polyfills.js:3)
    at webpackJsonp.775.__awaiter (18.js:62)

**Expected behavior:**
I should be able to use compose mail feature

**Steps to reproduce:**
Added plugin from IONIC native. Follower their steps to code.

**Related code:**
async sendEmail(attachment:string){
    this.emailComposer.isAvailable().then((available: boolean) =>{
      if(available) {
        //Now we know we can send
        let email = {
          to: 'mehtaparam008@gmail.com',
          cc: 'param@codingmantra.in',
          attachments: [
          ],
          subject: 'Order Export',
          body: 'Hi There, <br>Please find attached attachment for order export',
          isHtml: true
        } 
        // Send a text message using default options
        this.emailComposer.open(email);
      }
     });
  }

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Ionic:

   ionic (Ionic CLI)  : 4.11.0 (C:\Users\Param\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (E:\Android_SDK)
   NodeJS            : v8.11.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by jickay** [comment]
Having the same issue. What is it trying to split exactly? And what delimiter?

**Comment by FranciscoValerio** [comment]
I have the same problem. Any solution?

**Comment by mehtaparam** [comment]
I have used SocialSharing plugin

import { SocialSharing } from '@ionic-native/social-sharing/ngx';

async sendEmail() {
    // Share via email
    // tslint:disable-next-line:max-line-length
    this.socialSharing.shareViaEmail('Your Text', Title', ['test@test.com'], null, null, [
      'your_attachment_file_if_you_want',
    ]).then(() => {
      // Success!
    }).catch(() => {
      // Error!
    });
  }

**Comment by javapach** [comment]
> I have the same problem. Any solution?

if you are using ionic 3 and the _@ionic-native/email-composer_ plugin, you must use the plugin version 4.xx ^,  version 5 only works with ionic 4
