### ISSUE TITLE
In App Purchase 2 Doesn't Support autoFinishTransactions

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/ionic-native#2960]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When working with the cordova-plugin-pruchase in development you can build up a large queue of unfinished transactions. This makes it difficult to debug. In order to clear up that queue the plugin provides a property ```autoFinishTransactions``` which can be set to ```true```. This property is not in the Ionic wrapper for the plugin. 

**Expected behavior:**
I expect to be able to set ```autoFinishTransactions`` to ```true``` and have it function accordingly to the documentation located here at (https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#random-tips)

**Steps to reproduce:**
Try to reference ```store.autoFinishTransactions``` within your code. 

```

**Comment by xUnholy** [comment]
I think this is intentional because he cautions the use of this usage in production as it would be problematic. I think adding this to the wrapper may not be the intention the plugin maintainer had in mind.

Alternatively, have you tried raising this issue on his repository?
