### ISSUE TITLE
GooglePlus plugin not working in Ionic 4

### ISSUE THREAD

**Issue by JerryBels** [ionic-team/ionic-native#2966]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
GooglePlus plugn stopped working

**Expected behavior:**
Working plugin

**Related code:**

```
    doGoogleLogin() {
      console.log(111);
      return new Promise<any>((resolve, reject) => {
        if (this.platform.is('cordova')) {
          console.log(222);
          this.googlePlus.login({
            'scopes': '',
            'webClientId': environment.google_web_client_id,
            'offline': true
          }).then((response) => {
            console.log(333, response);
            const googleCredential = firebase.auth.GoogleAuthProvider.credential(response.idToken);
            firebase.auth().signInWithCredential(googleCredential)
              .then((user) => {
                console.log(444, user);
                resolve({
                  id: user.uid,
                  originUserId: response.userId,
                  email: response.email,
                  first_name: response.givenName,
                  last_name: response.familyName,
                  image: response.imageUrl
                });
              });
          }, (err) => {
            console.log(err);
            reject(err);
          });
        }
      });
    }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\JB\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 17 other plugins)

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7

```

Relevant package.json part: 

```
...
    "@ionic-native/google-plus": "^5.2.0",
...
    "cordova-plugin-googleplus": "^7.0.0",
    "cordova-support-google-services": "1.2.1",
...
      "cordova-plugin-googleplus": {
        "REVERSED_CLIENT_ID": "com.googleusercontent.apps.myid",
        "WEB_APPLICATION_CLIENT_ID": "myid.apps.googleusercontent.com",
        "PLAY_SERVICES_VERSION": "11.8.0"
      },
...
```

So it stopped working not long ago, I'm not sure when. What I do know is, when I migrated to Ionic 4 it worked, and now it doesn't. But the thing is, it gives no error at all ! Simply prints in console:

```
111
222
```

And then simply nothing. No `333` nor errors.

**Comment by dotNetkow** [comment]
It's worth noting that Google Plus is about to be shut down ([on April 2nd, 2019](https://support.google.com/plus/answer/9217723?hl=en&authuser=0)), so realistically you need to move on to a new login solution.

Unfortunately, I don't know a lot about Google Plus authentication, but a quick search brought me [here](https://developers.google.com/+/mobile/android/api-deprecation). It says to use [Google Sign-In for Android](https://developers.google.com/identity/sign-in/android/). Hope that helps.

**Comment by JerryBels** [comment]
@dotNetkow thanks for this but as @EddyVerbruggen said multiple times, the related plugin has been migrated to Google sign-in long ago :)

**Comment by dotNetkow** [comment]
aw @JerryBels apologies! Was just trying to be helpful. Carry on! :)

**Comment by JerryBels** [comment]
Found it. I had implemented this fix : https://github.com/arnesson/cordova-plugin-firebase/issues/742#issuecomment-398794131 and so Google Login plugin was simply not compiling correctly - thus the weirdness of what happened. Removed it, removed the plugin from the project, changed code a bit, rebuilt - working like a charm.

**Comment by JerryBels** [comment]
Can be usefull if you're stuck with this : https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/487

**Comment by TonGarcia** [comment]
Hi guys, I'm using the oficial ionic native Google plus plugin. As said, it no longer exists.... While signing using the plugin on iOS it works correctly, but in Google Android it is not working, it doesn't retrieve anything (then nor catch in promise).

**Comment by JerryBels** [comment]
You're mistaken. The plugin does exists and it works well. It's still called Google Plus, yet it has migrated to Google Login ages ago. So you should really try and follow the advices in this thread - https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/487 it helped me a lot getting it working.

**Comment by TonGarcia** [comment]
Thank you @JerryBels , I'll try it out. My app was working weeks before, now broken. It is working as it might be on iOS, but not on Android.
