### ISSUE TITLE
Is it actually the case that to use your own plugin for ionic-native you have to submit a PR to this repo?

### ISSUE THREAD

**Issue by robmoore-i** [ionic-team/ionic-native#2971]
Or is there a way that I can add a plugin locally? Can there be some documentation for how to do this as well?

I hope my feedback is okay for you and that you act on it quickly. Your users are talking about you!

Rob

**Comment by vegaro** [comment]
There's some documentation about how to add a plugin to Ionic Native here https://github.com/ionic-team/ionic-native#plugin-missing

Also, this shouldn't be an issue. You can ask this type of questions in Ionic Worldwide's Slack https://ionicworldwide.herokuapp.com/.
