### ISSUE TITLE
@ionic-native/keyboard

### ISSUE THREAD

**Issue by empty-god** [ionic-team/ionic-native#2972]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Android Build: Using the Ionic Keyboard package and plugin, subscribing to OnKeyboardWillShow or OnKeyboard will not subscribe and will return "TypeError: Invalid Event Target". I tried several life-cycle methods. None actually subscribed correctly.

**Expected behavior:**
You should be able to subscribe and run code on Keyboard toggle.

**Steps to reproduce:**
1. Add Keyboard packages to project as in docs.
2. Pull in keyboard using DI.
3. In ngAfterViewInit add the below code:
```
this.platform.ready().then(() => {
      this.keyboard.onKeyboardShow().subscribe(() => {
        console.log('show');
      });
      this.keyboard.onKeyboardHide().subscribe(() => {
        console.log('hide');
      });
});
```
4. Build and run and you will receive two "TypeError: Invalid Event Target" messages. App will still function.

**Related code:**
What I used as a workaround:

 ```
 private keyboardShowSub: Subscription;

    this.keyboardShowSub = fromEvent(window, 'keyboardWillShow').subscribe(() => {
      this.hideFooter = true;
    });
    this.keyboardHideSub = fromEvent(window, 'keyboardWillHide').subscribe(() => {
      this.hideFooter = false;
    });
```

This shows that the actual event is firing, but there is an issue in the Observable wrapper.

**Other information:**
https://github.com/ionic-team/ionic-native/issues/2306

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Ionic:

   ionic (Ionic CLI)          : 4.0.3 (C:\Users\aaleksandrov\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.1.2
   @angular-devkit/core       : 7.1.4
   @angular-devkit/schematics : 7.1.4
   @angular/cli               : 7.2.1
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.0.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\aaleksandrov\AppData\Local\Android\Sdk

**Comment by ambrzz** [comment]
same here!

**Comment by Ans0n-Ti0** [comment]
Hi @empty-god,

It happens for battery status native API too.
I used your workaround and it works nicely for now.

Thanks

**Comment by georgechr** [comment]
It's because the internals of ionic-native have changed and if a target is not defined then the boolean 'true' is used instead of the window global

**Comment by waileong** [comment]
Any estimated timeline from Ionic Team?

**Comment by netsesame2** [comment]
Find the same issue.

**Comment by Dinath** [comment]
As @netsesame2 says, we must now use the `window` code as shown in the documentation.

https://github.com/ionic-team/cordova-plugin-ionic-keyboard

I think on that both `onKeyboardShow()` and `onKeyboardHide()` will soon be removed from `Keyboard` package.

**Comment by dansiemens** [comment]
@Dinath not likely. This is a bug with the Observables provided by the npm package, not an intentional deprecation of features.

**Comment by bharanitt** [comment]
> It happens for battery status native API too.

yes in ionic v4 also same problem for Battery status plugin! if you find any solution please let me know

**Comment by RafaelKr** [comment]
The mentioned workaround in the first post should also work for the Battery status plugin:

```
fromEvent(window, 'batterystatus').subscribe((status) => {
  console.log(status)
});
```

**Comment by Domvel** [comment]
The `BatteryStatus` service brought me here. What is exactly the problem? It's a simple rxjs subscription. Ok, I don't yet understand the Ionic native source code. [See code here](https://github.com/ionic-team/ionic-native/blob/v5.13.0/src/@ionic-native/plugins/battery-status/index.ts#L60) I think the useless `return` is for linter reason `no-empty`. 
I think it's a generally problem for every native plugin for Ionic.

**Comment by Domvel** [comment]
The `BatteryStatus` service brought me here. What is exactly the problem? It's a simple rxjs subscription. Ok, I don't yet understand the Ionic native source code. [See code here](https://github.com/ionic-team/ionic-native/blob/v5.13.0/src/@ionic-native/plugins/battery-status/index.ts#L60) I think the useless `return` is for linter reason `no-empty`. 
I think it's a generally problem for every native plugin for Ionic and needs a high priority to fix this in my opinion.

Update: The workaround `fromEvent` is no solution for me. Because of type issues of the rxjs Event. I have to use `BatteryStatusEvent` but this is not available. ... In vs-code is it available. But on build the compiler says: "Property 'level' does not exist on type `Event`"

Update: Ok someone wrote something about the reason (georgechr): 
> It's because the internals of ionic-native have changed and if a target is not defined then the boolean 'true' is used instead of the window global

But what exactly does that mean? What do we have to do?

@kensodemann

**Comment by Domvel** [comment]
Ok there is no target element set on the cordova decorator of some plugins like `BatteryStatus`. [Example see here](https://github.com/ionic-team/ionic-native/blob/v5.13.0/src/@ionic-native/plugins/battery-status/index.ts#L56-L59).

But the [cordova decorator](https://github.com/ionic-team/ionic-native/blob/v5.13.0/src/%40ionic-native/core/decorators/cordova.ts) which pass the argument through the [wrap method](https://github.com/ionic-team/ionic-native/blob/v5.13.0/src/%40ionic-native/core/decorators/common.ts#L379-L394) and then the [wrapEventObservable method](https://github.com/ionic-team/ionic-native/blob/v5.13.0/src/%40ionic-native/core/decorators/common.ts#L151-L154) uses a default value.

```ts
function wrapEventObservable(event: string, element: any): Observable<any> {
  element = (typeof window !== 'undefined' && element) ? get(window, element) : element || typeof window !== 'undefined' || {};
  return fromEvent(element, event);
}
```

It should be the window. Or did I miss something?

**Comment by Domvel** [comment]
@danielsogl I fixed it. Please, could you merge it and release it as soon as possible? 🙂
