### ISSUE TITLE
@ionic-native/android-permissions typing is sloppy

### ISSUE THREAD

**Issue by jpike88** [ionic-team/ionic-native#2981]
**I'm submitting a ...**  (check one with "x")
[x] bug report
**Current behavior:**

This is a bit of the code from the plugin's type definitions:

```
/**
     * Request permissions
     * @param {string[]} permissions An array with permissions
     * @return {Promise<any>} Returns a promise
     */
    requestPermissions(permissions: string[]): Promise<any>;
    /**
     * This function still works now, will not support in the future.
     * @param {string} permission The name of the permission
     * @return {Promise<any>} Returns a promise
     */
    hasPermission(permission: string): Promise<any>;
```

Promise<any>??? No mention of callbacks? Makes this library a pain to use without wondering if you did it right.

**Comment by jcesarmobile** [comment]
the point of ionic native is to use cordova plugins with promises instead of using callbacks
