### ISSUE TITLE
typo in @ionic-native/nfc

### ISSUE THREAD

**Issue by ab-kily** [ionic-team/ionic-native#2985]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The problem in @ionic-native/nfc plugin. There is a method called __makeReadyOnly()__, but it seem there is a typo. 

**Expected behavior:**
That method should be called __makeReadOnly()__, as in its _phonegap-nfc_ parent. 

**Steps to reproduce:**

**Related code:**
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/nfc/index.ts
```javascript
  /**
   * Makes a NFC tag read only. **Warning** this is permanent.
   * @returns {Promise<any>}
   */
  @Cordova()
  makeReadyOnly(): Promise<any> {
    return;
  }
``` 

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**Comment by rodrigograca31** [comment]
@ab-kily is right. should be `makeReadOnly`

Original function: https://github.com/chariotsolutions/phonegap-nfc#nfcmakereadonly
