### ISSUE TITLE
Initialize() method not working in @ionic-native/firebase-crashlytics

### ISSUE THREAD

**Issue by tuxicoman** [ionic-team/ionic-native#2990]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

firebaseCrashlytics.initialize() doesn't return the crashlytics instance.
1. it has void type
2. function names are not aligned; initiali**z**e vs initiali**s**e

> Native: tried calling FirebaseCrashlytics.initialize, but the FirebaseCrashlytics plugin is not installed
> Install the FirebaseCrashlytics plugin: 'ionic cordova plugin add cordova-plugin-firebase-crashlytics'

**Expected behavior:**
It should return the crashlytics instance.

**Steps to reproduce:**

Install firebase-crashlytics and call as per describe in the [ionicframework doc](https://ionicframework.com/docs/native/firebase-crashlytics) 

```
import { FirebaseCrashlytics } from '@ionic-native/firebase-crashlytics/ngx';


constructor(private firebaseCrashlytics: FirebaseCrashlytics) { }

...


const crashlytics = this.firebaseCrashlytics.initialize();
crashlytics.logException('my caught exception');
```

**Related code:**
https://github.com/ionic-team/ionic-native/blob/4859387925b1dfeb416b80856fbfb991b6884348/src/%40ionic-native/plugins/firebase-crashlytics/index.ts#L43
https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/blob/0a3a15b34d612bece06863d2e8a0dee3e1495ab0/www/crashlytics.js#L43
```
module.exports = {
  initialise: function() {
    return new Crashlytics();
  }
};
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic 5.2.1, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/romain/Android/Sdk)
   NodeJS            : v8.11.4 (/usr/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.15
```

**Comment by davidquon** [comment]
Is there any work around for this until it gets fixed?

**Comment by pastcompute** [comment]
I hacked it using this instead:
```
import { cordova } from '@ionic-native/core';

// ...

constructor(private firebaseCrashlytics: FirebaseCrashlytics, platform: Platform,

// ...

// inside platform.ready()
const crashlytics = cordova(this.firebaseCrashlytics, "initialise", { "sync": true }, undefined);
```

**Comment by MarkAMcCorkle** [comment]
@pastcompute On which version of ionic? I still get the following error using your code. 

```
[Warning] Native: tried calling FirebaseCrashlytics.initialize, but the FirebaseCrashlytics plugin is not installed. (cordova.js, line 1509)
[Warning] Install the FirebaseCrashlytics plugin: 'ionic cordova plugin add cordova-plugin-firebase-crashlytics' (cordova.js, line 1509)
```

**Comment by DiegoGarciaMartin** [comment]
I have the same error with this plugin.

@pastcompute It didn't work your solution.

**Comment by pastcompute** [comment]
@MarkAMcCorkle 

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 10 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 7.0.0
   NodeJS     : v10.14.2 (/usr/local/bin/node)
   npm        : 6.9.0
```

**Comment by davidquon** [comment]
Updating to https://github.com/ionic-team/ionic-native/releases/tag/v5.6.0 worked for me.  Thanks @danielsogl!  👍

**Comment by MarkAMcCorkle** [comment]
I see the plugin installs but does it actually work for you? I still get the following error when the iOS app is actually ran. What other steps did you take? I installed everything in [this readme](https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics). 

`Install the FirebaseCrashlytics plugin: 'ionic cordova plugin add cordova-plugin-firebase-crashlytics'`

**Comment by davidquon** [comment]
@MarkAMcCorkle The FirebaseCrashlytics plugin does work for me but I've only tested on Android.  According to the README iOS is untested.
https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics#supported-platforms

In case it helps here is what I'm using for Firebase Analytics and Firebase Crashlytics on Android.
```
    "cordova-plugin-firebase-analytics": "1.1.1",
    "cordova-plugin-firebase-crashlytics": "0.1.0"

      "cordova-plugin-firebase-crashlytics": {
        "ANDROID_FIREBASE_CORE_VERSION": "16.0.8"
      },
      "cordova-plugin-firebase-analytics": {
        "FIREBASE_CORE_VERSION": "16.0.+"
      }
```

Also here is my `ionic info`:
```
$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/DQ/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/DQ/Library/Android/sdk)
   NodeJS            : v10.15.0 (/Users/DQ/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b
```

You might want to try removing the iOS platform and re-adding it as I've had issues like that in the past with Android as well.  If you find any tips to make it work on iOS please post them for myself and others to use if needed to get this working on iOS.  Good luck!

**Comment by maykon-oliveira** [comment]
I am facing same problem.
I am getting:

```
Native: tried calling FirebaseCrashlytics.log, but the FirebaseCrashlytics plugin is not installed.
Install the FirebaseCrashlytics plugin: 'ionic cordova plugin add cordova-plugin-firebase-crashlytics'
```

But it's installed
