### ISSUE TITLE
Include WifiWizard2

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic-native#2994]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently there is no decent wifi plugin available

**Expected behavior:**
Include WifiWizard2 for wifi connection handling
https://github.com/tripflex/WifiWizard2

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by datazen** [comment]
yes would like to see this also

**Comment by jospete** [comment]
@digaus I added support for it [here](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/wifi-wizard-2/index.ts);
It does not appear to be in the ionic native website yet though.

**Comment by digaus** [comment]
> @digaus I added support for it [here](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/wifi-wizard-2/index.ts);
> It does not appear to be in the ionic native website yet though.

Nice thanks for the work!  I myself am not depending on this anymore since I moved to capacitor and created my own Wifi Plugin :)
