### ISSUE TITLE
Cannot use @Cordova or @Plugin decorator on own package

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic-native#3001]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to create a cordova plugin wrapper own my own package (an ionic project) for `cordova-plugin-certificates`, but when trying to run, it fails when I add the @Cordova decorator to method or @Plugin decorator to class.

**Expected behavior:**
It should just work, it's an simple plugin, there's nothing to be wrong here IMO.

**Steps to reproduce:**

**Related code:**

```
import { Injectable } from '@angular/core';
import { Cordova, IonicNativePlugin, Plugin } from '@ionic-native/core';

@Plugin({
  pluginName: 'Certificates',
  plugin: 'cordova-plugin-certificates',
  pluginRef: 'cordova.plugins.certificates',
  repo: 'https://github.com/hypery2k/cordova-certificate-plugin',
  platforms: ['Android']
})
@Injectable()
export class Certificates extends IonicNativePlugin {

  @Cordova()
  trustUnsecureCerts(trust: boolean): Promise<void> {
    return;
  }

}
```

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/esoares/android-sdk/)
   NodeJS            : v10.15.3 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

```

**Comment by maxtacco** [comment]
Possibly duplicate of https://github.com/ionic-team/ionic-native/issues/2829
