### ISSUE TITLE
How to add my plugin template to ionic-native?

### ISSUE THREAD

**Issue by pranav9k** [ionic-team/ionic-native#3022]
Hi,

I have created a cordova plugin for capturing biometric information. I don't have to publish the plugin to npm. I am adding the plugin from my source folder itself.

My concern is how to add the template to ionic-native (It's of no use for the other people)?

**Comment by danielsogl** [comment]
Just follow this guide: https://github.com/ionic-team/ionic-native/blob/master/DEVELOPER.md
