### ISSUE TITLE
wrapEventObservable (rc/@ionic-native/core/decorators/common.ts) is returning the wrong value for element

### ISSUE THREAD

**Issue by 188599** [ionic-team/ionic-native#3031]
**I'm submitting a ...** 
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

When the element parameter is undefined, it returns true or an empty object.

**Expected behavior:**

When the element parameter is undefined, it should return window or an empty object.

**Steps to reproduce:**

Had a problem when subscribing to the onChange method of the ScreenOrientation plugin. It gave me this error.

![image](https://user-images.githubusercontent.com/49286231/58204456-b4272d00-7cb2-11e9-8a93-356d404c8ee3.png)

**Related code:**

After some digging, I found where the problem came from.

https://github.com/ionic-team/ionic-native/commit/e1a25af0b5b3166517fec993dceea075ff26627b#diff-dd9bcc452b9bbbad227208ec1235d90d

Made a little example with both methods on stackblitz, showing how they behave differently.

https://stackblitz.com/edit/typescript-md3cpw?file=index.ts

**Other information:**

I believe changing this line: 

`
  element = (typeof window !== 'undefined' && element) ? get(window, element) : element || typeof window !== 'undefined' || {};
`
To this: 

`
  element = (typeof window !== 'undefined' && element) ? get(window, element) : element || typeof window !== 'undefined' ? window : {};
`

Would fix it.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Usuario\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Usuario\AppData\Local\Android\sdk)
   NodeJS            : v11.1.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.7.0
   OS                : Windows 10
```

**Comment by Thomas-Vandenhede** [comment]
Also having this issue.

I suggest not reassigning the `element` parameter, as doing so is considered bad practice and it's always preferable to keep functions pure if possible. Also let's remove nested ternary operators for the sake of readability (https://eslint.org/docs/rules/no-nested-ternary).

Not sure why we would want to pass a literal object `{}` to `fromEvent` either as doing so would result in an error being thrown as seen here https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/fromEvent.ts#L208.

Also, why do we need to check for the type of `window`? Isn't this code supposed to be executed in a browser? Somebody correct me if I'm wrong.

Finally, `get(window, element)` is executed irrespectively of the type of `element`, which contradicts the signature of the `get` function considering `element` is of type `any`:
```typescript
function get(element: Element | Window, path: string)
```
I suggest adding a type check for the `element` parameter.

Here's my proposed fix:
```typescript
function wrapEventObservable(event: string, element: any): Observable<any> {
  var target;

  if (typeof window !== 'undefined') {
    switch (typeof element) {
      case 'string':
        target = get(window, element);
        break;
      case 'undefined':
        target = window;
        break;
      default:
        target = element;
    }
  } else {
    target = {};
  }

  return fromEvent(target, event);
}
```

**Comment by jcesarmobile** [comment]
This was fixed in latest release
