### ISSUE TITLE
create my own custom plugin wrapper with ionic v4

### ISSUE THREAD

**Issue by plat10510** [ionic-team/ionic-native#3034]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ x ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
sorry, i cant login forum, tell me 'There is a problem with your account. Please contact the site's administrator.'

I created a push [cordova plugin](https://github.com/plat10510/cordova-plugin-umengpush.git) and a ionic v3 ionic-native plugin, it works well. but when I use the plugin on ionic v4, error 'Uncaught TypeError: Object(...) is not a function', by looking up issues and forums, I learned that I should write like this:
```
@Injectable()
export class Upush extends IonicNativePlugin {
  static pluginName = 'upush';
  static plugin = 'cordova-plugin-umengpush';
  static pluginRef = 'cordova.plugins.UMengPush';
  static repo = 'https://github.com/plat10510/cordova-plugin-umengpush.git';
  static install = 'cordova plugin add cordova-plugin-umengpush';
  static platforms = ['Android', 'iOS'];
  
  coolMethod(alias, alias_type) :Promise<any> {
    return cordova(this, 'coolMethod', { "successIndex": 2, "errorIndex": 3 }, [alias, alias_type]);
  }

}
```
when I try to 'npm run build upush', get error:
```
Error: ENOENT: no such file or directory, open '/Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/dist/@ionic-native/plugins/.DS_Store/index.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/scripts/tasks/build-esm.ts:21:27
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/scripts/tasks/build-esm.ts:16:9)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@5.6.0 build:esm: `ts-node -P scripts/tsconfig.json scripts/tasks/build-esm`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-native@5.6.0 build:esm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yl/.npm/_logs/2019-05-24T03_05_43_528Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@5.6.0 build: `npm run build:core && npm run build:esm && npm run build:ngx && npm run build:es5 "upush"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-native@5.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yl/.npm/_logs/2019-05-24T03_05_43_550Z-debug.log
```

debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   'upush' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ionic-native@5.6.0~prebuild: ionic-native@5.6.0
6 verbose lifecycle ionic-native@5.6.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle ionic-native@5.6.0~prebuild: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/node_modules/.bin:/Users/yl/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/yl/maven/bin:/usr/local/mysql/bin:/Users/yl/android_sdk/tools:/Users/yl/android_sdk/platform-tools
8 verbose lifecycle ionic-native@5.6.0~prebuild: CWD: /Users/yl/Documents/ionic3/plugin/ionic4/ionic-native
9 silly lifecycle ionic-native@5.6.0~prebuild: Args: [ '-c', 'rimraf -rf dist' ]
10 silly lifecycle ionic-native@5.6.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle ionic-native@5.6.0~build: ionic-native@5.6.0
12 verbose lifecycle ionic-native@5.6.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle ionic-native@5.6.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/yl/Documents/ionic3/plugin/ionic4/ionic-native/node_modules/.bin:/Users/yl/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/yl/maven/bin:/usr/local/mysql/bin:/Users/yl/android_sdk/tools:/Users/yl/android_sdk/platform-tools
14 verbose lifecycle ionic-native@5.6.0~build: CWD: /Users/yl/Documents/ionic3/plugin/ionic4/ionic-native
15 silly lifecycle ionic-native@5.6.0~build: Args: [ '-c',
15 silly lifecycle   'npm run build:core && npm run build:esm && npm run build:ngx && npm run build:es5 "upush"' ]
16 silly lifecycle ionic-native@5.6.0~build: Returned: code: 1  signal: null
17 info lifecycle ionic-native@5.6.0~build: Failed to exec build script
18 verbose stack Error: ionic-native@5.6.0 build: `npm run build:core && npm run build:esm && npm run build:ngx && npm run build:es5 "upush"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at EventEmitter.emit (events.js:214:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:925:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose pkgid ionic-native@5.6.0
20 verbose cwd /Users/yl/Documents/ionic3/plugin/ionic4/ionic-native
21 verbose Darwin 18.6.0
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "upush"
23 verbose node v8.11.4
24 verbose npm  v5.6.0
25 error code ELIFECYCLE
26 error errno 1
27 error ionic-native@5.6.0 build: `npm run build:core && npm run build:esm && npm run build:ngx && npm run build:es5 "upush"`
27 error Exit status 1
28 error Failed at the ionic-native@5.6.0 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

```

and what I ultimately want to do is I want to implement a plugin like ionic-native/sms, with an ngx floder that works in ionic v4,like
```
import { Upush } from 'upush/ngx';
```

thx so mush!!

**Ionic info:

```
Ionic CLI 4.5.0,
node -v    v8.11.4
npm -v     5.6.0
```

**Comment by plat10510** [comment]
help!!

**Comment by srinidhirao** [comment]
When you pull the code in Mac, it creates a .DS_Store file. You need to delete this file at all the places  it is present in your project and delete it. Since this is a hidden file, you may have to turn on the setting to view hidden files.
https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

**Comment by plat10510** [comment]
> 在Mac中提取代码时，会创建.DS_Store文件。您需要在项目中存在的所有位置删除此文件并将其删除。由于这是一个隐藏文件，您可能必须打开设置才能查看隐藏文件。
> https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

ok,thx bro

**Comment by saushahi** [comment]
plat10510 you got your plugin working .
i am also getting issue to create wrapper for  ionic 4 ios. can you share the sample.

**Comment by plat10510** [comment]
> plat10510 you got your plugin working .
> i am also getting issue to create wrapper for ionic 4 ios. can you share the sample.

I still don't know how to solve it.
XDDDD

**Comment by mohdairin** [comment]
HI,

im facing the same issue also when i want to call the plugin in v4, while in v3 working fine

Error: Uncaught (in promise): TypeError: Object(...) is not a function

**Comment by plat10510** [comment]
> HI,
> 
> im facing the same issue also when i want to call the plugin in v4, while in v3 working fine
> 
> Error: Uncaught (in promise): TypeError: Object(...) is not a function

I still don't know how to solve this problem, so I've been using cordova to call it

**Comment by mohdairin** [comment]
> > HI,
> > im facing the same issue also when i want to call the plugin in v4, while in v3 working fine
> > Error: Uncaught (in promise): TypeError: Object(...) is not a function
> 
> I still don't know how to solve this problem, so I've been using cordova to call it

Hi, how you call using cordova, could you please explain more on this,
Thank you

**Comment by plat10510** [comment]
https://stackoverflow.com/questions/52093202/how-to-use-non-native-cordova-plugins-in-ionic-4

https://forum.ionicframework.com/t/how-to-use-cordova-custom-plugin-in-ionic/123858

**Comment by plat10510** [comment]
> > > HI,
> > > im facing the same issue also when i want to call the plugin in v4, while in v3 working fine
> > > Error: Uncaught (in promise): TypeError: Object(...) is not a function
> > 
> > 
> > I still don't know how to solve this problem, so I've been using cordova to call it
> 
> Hi, how you call using cordova, could you please explain more on this,
> Thank you

https://stackoverflow.com/questions/52093202/how-to-use-non-native-cordova-plugins-in-ionic-4

https://forum.ionicframework.com/t/how-to-use-cordova-custom-plugin-in-ionic/123858

**Comment by saushahi** [comment]
I am calling it by creating variable same as android and it’s working fine.

Sent from my iPhone

On 29-Jul-2019, at 7:52 AM, mohdairin <notifications@github.com<mailto:notifications@github.com>> wrote:


HI,
im facing the same issue also when i want to call the plugin in v4, while in v3 working fine
Error: Uncaught (in promise): TypeError: Object(...) is not a function

I still don't know how to solve this problem, so I've been using cordova to call it

Hi, how you call using cordova, could you please explain more on this,
Thank you

**Comment by saushahi** [comment]
Please add your plungin inside your Npm module using command Npm install your plugin name then declare the variable of your plugin clobber target  as any and call the js function of plugin inside your code .
I tried and it’s working for me.

Sent from my iPhone

On 29-Jul-2019, at 8:14 AM, luoyuanli <notifications@github.com<mailto:notifications@github.com>> wrote:


HI,
im facing the same issue also when i want to call the plugin in v4, while in v3 working fine
Error: Uncaught (in promise): TypeError: Object(...) is not a function

I still don't know how to solve this problem, so I've been using cordova to call it

Hi, how you call using cordova, could you please explain more on this,
Thank you

https://stackoverflow.com/questions/52093202/how-to-use-non-native-cordova-plugins-in-ionic-4

https://forum.ionicframework.com/t/how-to-use-cordova-custom-plugin-in-ionic/123858

**Comment by mohdairin** [comment]
Hi im using this guy method and its working,

https://dev.to/hitman666/how-to-create-an-android-cordova-plugin-for-showing-toast-popups--9fb

just change declare var to declare let on the ts class

**Comment by mohdairin** [comment]
> > HI,
> > im facing the same issue also when i want to call the plugin in v4, while in v3 working fine
> > Error: Uncaught (in promise): TypeError: Object(...) is not a function
> 
> I still don't know how to solve this problem, so I've been using cordova to call it

Hi im using this guy method and its working,

https://dev.to/hitman666/how-to-create-an-android-cordova-plugin-for-showing-toast-popups--9fb

just change declare var to declare let on the ts class
