### ISSUE TITLE
cordova-plugin-firebase is not maintened anymore, use cordova-plugin-firebase-lib instead

### ISSUE THREAD

**Issue by hugoblanc** [ionic-team/ionic-native#3038]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[*] feature request

**Current behavior:**
https://github.com/arnesson/cordova-plugin-firebase has not been updated for 6 months.
Firebase sdk recently been updated and that breaks the plugin. 
[1057](https://github.com/arnesson/cordova-plugin-firebase/issues/1057)
https://github.com/wizpanda/cordova-plugin-firebase-lib which is a fork of the original plugin seems to be a good alternative. 

**Expected behavior:**
Ionic native should provide working and up to date plugins. 

**Steps to reproduce:**
start a new ionic project
install cordova-plugin-firebase
add platform android
run android
build failed

**Other information:**
All version of ionic are impacted as this issue doesn't depends of ionic/ionic-native
I could create a PR to reference cordova-plugin-firebase-lib instead of cordova-plugin-firebase but I don't know if you're ready to that change. 

Also, it could be great that ionic native v4 get the update too, but I don't know what is your process about that

**Comment by patryk-fuhrman** [comment]
There is also fork from cordova-plugin-firebase which is maintained and might have greater API than cordova-plugin-firebase-lib [cordova-plugin-firebasex](https://github.com/dpa99c/cordova-plugin-firebasex)

**Comment by hugoblanc** [comment]
> There is also fork from cordova-plugin-firebase which is maintained and might have greater API than cordova-plugin-firebase-lib [cordova-plugin-firebasex](https://github.com/dpa99c/cordova-plugin-firebasex)

Sure, [dpa99c](https://github.com/dpa99c) was quite active on the original plugin.
I posted propositions on both repository, let's wait for authors' responses . 

[Dpa99 feature request](https://github.com/dpa99c/cordova-plugin-firebasex/issues/47)
[Wizpanda feature request](https://github.com/wizpanda/cordova-plugin-firebase-lib/issues/45)

**Comment by patryk-fuhrman** [comment]
I think this should be a feature request to ionic native team not @dpa99c. To use this in ionic we basically need Ionic-native/Firebase proxy file for the new version or make the old one point to firebasex plugin.

**Comment by ippeiukai** [comment]
It seems the discussion to coordinate the efforts is progressing nicely in https://github.com/dpa99c/cordova-plugin-firebasex/issues/47#issuecomment-513644354. As a user of `@ionic-native/firebase`, I appreciate all your efforts to continue its good. I'm looking forward to upgrading our dependencies.

However, I understand `cordova-plugin-firebasex` has a lot of breaking changes by now. `cordova-plugin-firebase` still works okay as long as an old version of Firebase SDK is specified to Gradle build, and some of our projects would continue to use it for some time unless the migration is trivial.

So, may I suggest following for Ionic Native?
- deprecate the wrapper for `cordova-plugin-firebase` (`@ionic-native/firebase`) and leave it as is for a while
- make new ionic native wrapper for `cordova-plugin-firebasex` (or whatever successor) and recommend it to the users of `@ionic-native/firebase`

That is, of course, unless the updated `@ionic-native/firebase` with successor plugin can be made reasonably backward compatible. 
It would avoid confusions and ease our migration process very much.

Thanks!

**Comment by hugoblanc** [comment]
I'm gonna work on this part [wrapper](https://github.com/dpa99c/cordova-plugin-firebasex/issues/47#issuecomment-513781226)
