### ISSUE TITLE
@ionic/react alternative of this.platform.ready() from '@ionic/angular'

### ISSUE THREAD

**Issue by sergey-king** [ionic-team/ionic-native#3042]
In `import { Platform } from '@ionic/angular';` we have 
`this.platform.ready().then(() => { _call some native plugin here_ });` to make sure app is fully ready before calling any native service. 

Related: https://forum.ionicframework.com/t/ionic-4-native-tried-accessing-the-sqlite-plugin-but-its-not-installed/159400

What is the alternative for @ionic/react?
P.S.: Importing it from the `ionic-angular` is not an option

Error:
`⚡️  [warn] - Native: tried accessing the SQLite plugin but it's not installed.`
`⚡️  [warn] - Install the SQLite plugin: 'ionic cordova plugin add cordova-sqlite-storage'`

**Comment by danielsogl** [comment]
For now you should be able to use the Cordova `deviceReady` event described here: https://cordova.apache.org/docs/en/9.x/cordova/events/events.html#page-toc-source

You should also create a new issue here about that react/vue specific problem: https://github.com/ionic-team/ionic
