### ISSUE TITLE
Diagnotics: method missing requestRemoteNotificationsAuthorization

### ISSUE THREAD

**Issue by ciekawy** [ionic-team/ionic-native#3050]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

`requestRemoteNotificationsAuthorization` method is missing

**Expected behavior:**

`requestRemoteNotificationsAuthorization` method available for the diagnostics module

**Comment by cyptus** [comment]
the method does not work for me, the promise is loading for ever when beeing awaited.
