### ISSUE TITLE
Support for GET Request with responseType 'blob'

### ISSUE THREAD

**Issue by NisStrom** [ionic-team/ionic-native#3067]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

Wtih version 2.1.0 cordova-plugin-advanced-http added the functionality to send web request with response type 'blob' or 'arraybuffer'. This would be nice to have in @ionic-native/http in order not to need downloadFile.

**Comment by nejcsilc** [comment]
+1
