### ISSUE TITLE
"plugin not installed" error in SSL pinning using ionic-native http

### ISSUE THREAD

**Issue by jintzz** [ionic-team/ionic-native#3072]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I am using the plugin [ ionic-native http](https://ionicframework.com/docs/native/http) in my current project for enabling SSL pinning. I followed the steps mentioned in the [link ](https://ionicframework.com/docs/native/http) but after taking the build, getting an error 'Plugin not installed'. But the plugin is installed and is listed in config.xml file. and package.json.

The certificate is placed inside www/certificates folder and its in DER format (.cer)

**Other information:**
https://github.com/silkimen/cordova-plugin-advanced-http/issues/8

**Comment by memphis23** [comment]
It worked for me but after updating Ionic CLI it does not.
I get the following errors:
Native: tried calling HTTP.setSSLCertMode, but the HTTP plugin is not installed.
Install the HTTP  plugin: 'ionic cordova plugin add cordova-plugin-advanced-http' 
Pinning not enabled: plugin_not_installed
However this is not true, plugin is installed.

**Comment by funkyvisions** [comment]
I'm getting the same thing.  It makes me scared to use these wrapper if there isn't gonna be support.  I was able to get cordova-plugin-advanced-http to work with the ionic-native wrapper, but I thought we weren't supposed to use that anymore.  Ugh.  And the Capacitor community http plugin is a mess.  I'm stuck.
