### ISSUE TITLE
@ionic-native/file-opener can not open file with ios 13

### ISSUE THREAD

**Issue by corbin88** [ionic-team/ionic-native#3073]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm using @ionic-native/file-opener and @ionic-native/file. When I open a PDF all that appears is the title of the PDF and not the document itself.

xcode console error:

>[default] QLUbiquitousItemFetcher: <QLUbiquitousItemFetcher: 0x600000ddaf80> could not create sandbox wrapper. Error: Error Domain=NSPOSIXErrorDomain Code=22 "couldn't issue sandbox extension com.apple.quicklook.readonly for '/Users/corbin/Library/Developer/CoreSimulator/Devices/25CCF08E-B841-4D53-BAB9-661C52DC27FA/data/Containers/Data/Application/ACDAB821-3A64-41BB-ACA6-CF25B79D7D06/Library/NoCloud/1561409109067.pdf': Invalid argument" UserInfo={NSDescription=couldn't issue sandbox extension com.apple.quicklook.readonly for '/Users/corbin/Library/Developer/CoreSimulator/Devices/25CCF08E-B841-4D53-BAB9-661C52DC27FA/data/Containers/Data/Application/ACDAB821-3A64-41BB-ACA6-CF25B79D7D06/Library/NoCloud/1561409109067.pdf': Invalid argument} #PreviewItem

<img width="337" alt="Screen Shot 2019-06-23 at 10 36 10 PM" src="https://user-images.githubusercontent.com/24969455/60141681-5f307800-9784-11e9-9760-f80ad02eaef9.png">

**Expected behavior:**

The PDF open in the file opener. It seems to be working with ios 12.2 for someone trying to help me with the problem, but not ios 13.

[Image of working](https://ionicacademy.com/community/uploads/monthly_2019_06/1329041593_Screenshot2019-06-25at15_11_44.thumb.png.64023dfa6138c2ff9a2d1e94e88ae3aa.png)

**Steps to reproduce:**

[I created an ionic project to reproduce the problem. Here is the repo.](https://github.com/corbin88/ionic-file-opener-problem)

**Related code:**

```
openLocalPdf() {
let filePath = this.file.applicationDirectory + 'www/assets';
 
let fakeName = Date.now();
this.file.copyFile(filePath, 'JournalPDF.pdf', this.file.dataDirectory, `${fakeName}.pdf`).then(result => {
this.fileOpener.open(result.nativeURL, 'application/pdf')
.then(() => console.log('File is opened'))
.catch(e => console.log('Error opening file', e));
});
}
```

**Other information:**

Xcode 11 beta
IOS Version 11.0 (SimulatorApp-895.5.1 SimulatorKit-553.11 CoreSimulator-643.8.4)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Android SDK Tools : 26.1.1 (/Users/myname/Library/Android/sdk)
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave

   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 4.12.0 → 5.1.0    │
   │     Run npm i -g ionic to update     │
   │                                      │
   ╰──────────────────────────────────────╯
```

**Comment by luzianscherrer** [comment]
I got the same problem in my app.

**Comment by danielsogl** [comment]
Please open an issue here: https://github.com/pwlin/cordova-plugin-file-opener2

**Comment by rondog** [comment]
this seems to only affect the simulator. It works if you do it on a device. It must have broke between file-opener2  2.x and 3.x because it was working fine before I updated
