### ISSUE TITLE
createBanner() crashes the app immediately on Android 9

### ISSUE THREAD

**Issue by jneumann83** [ionic-team/ionic-native#3076]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
createBanner() crashes the app immediately on Android 9
Plugin Version admob-pro 5.8.0

**Expected behavior:**
don`t crash the app

**Steps to reproduce:**

**Related code:**
```
let opt = {
                        adSize: this.bannerSize,
                        position: this.admobPro.AD_POSITION.BOTTOM_CENTER,
                        bgColor: '#333333',
                        isTesting: false,
                        autoShow: false,
                        license: xxxxxxxxxxx)
};                  
this.admobPro.setOptions(opt);

this.admobPro.createBanner({
            adId: xxxxxxxxxxx
}).then(()=> {
            this.admobPro.showBanner(this.admobPro.AD_POSITION.BOTTOM_CENTER);
}).catch( e => {

});
```
Ionic:

   Ionic CLI                     : 5.0.2
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 6.4.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 24 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.3

System:

   Android SDK Tools : 26.1.1 (C:\Users\JN\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.8.0
   OS                : Windows 10

Plugin List:

cordova-android-play-services-gradle-release 1.1.4 "cordova-android-play-services-gradle-release"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-admobpro 2.37.2 "AdMob Plugin Pro"
cordova-plugin-android-idfa 1.0.4 "Advertising ID (IDFA) Plugin using Google Play Services for Android"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-native-keyboard 2.0.3 "Native Keyboard"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.5 "SocialSharing"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

**Comment by piyushysoft** [comment]
Just leaving this here in case it helps, I was getting the "Dependency failing" errors due to different play services versions with cordova 9. In my case it was from phonegap-plugin-push as well as this admob plugin.

Adding the PLAY_SERVICES_VERSION to config.xml as described in the docs did nothing. What worked for me:

cordova plugin rm cordova-plugin-admob-free --variable ADMOB_APP_ID="XXXXXXX"
cordova plugin add cordova-admob-sdk --variable PLAY_SERVICES_VERSION="15.0.1"
cordova plugin add cordova-plugin-admob-free --variable ADMOB_APP_ID="XXXXXXX"
This added this line to my package.json under cordova plugins:

"cordova-admob-sdk": { "PLAY_SERVICES_VERSION": "15.0.1" }

That fixed android builds for me.
