### ISSUE TITLE
Option "storeToFile: boolean" is not available in CameraPreview plugin

### ISSUE THREAD

**Issue by t4lpi** [ionic-team/ionic-native#3077]
**I'm submitting a ...**
[x] bug report

**Current behavior:**
"storeToFile: boolean" doesn't exists in CameraPreviewOptions interface so I can only get base64 data back as the result of TakePicture() method.

**Expected behavior:**
I want to set "storeToFile: true" so I'm able to get back image path instead of base64 data when I'm taking a picture.

**Related code:**
camera.component.ts
...
startCamera() {

        const cameraPreviewOpts: CameraPreviewOptions = {
            x: 0,
            y: 0,
            width: this.platform.width(),
            height: this.platform.height(),
            camera: 'front',
            tapPhoto: false,
            previewDrag: false,
            toBack: true,
            alpha: 1,
            storeToFile: true // ERROR
        };
        this.cameraPreview
            .startCamera(cameraPreviewOpts)
            .then(res => console.log(res), err => console.log(err));
    }
...
**ERROR:**
![github](https://user-images.githubusercontent.com/45562599/60337709-1a832780-99a4-11e9-9d30-c0181964bdbe.png)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Talpi\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, browser 6.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\android-sdk-windows)
   NodeJS            : v11.10.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by cassini-usman** [comment]
@Talpi208 did you find any workaround for it ?

**Comment by Talpi208** [comment]
> @Talpi208 did you find any workaround for it ?

I converted base64 into Blob, created a file with a generated random name at specific filePath then write the Blob into the file which equaled the picture. 

I dont think its the best solution but i haven't find anything better like to get back file URI and handle the given path. :(

**Comment by HighSoftWare96** [comment]
I noticed that however the `storeToFile` actually works and the `takePicture` returns the path of the cached image..

**Comment by elepetit** [comment]
Hi, just modify the file index.d.ts in node module @ionic-native/camera-prview/ngx and add storeToFile to the interface CameraPreviewOptions
