### ISSUE TITLE
cordova-firebase-lib and @ionic-native/firebase

### ISSUE THREAD

**Issue by pcova2099** [ionic-team/ionic-native#3078]
Hi, I installed the wiz-panda's version of cordova-plugin-firebase-lib and compile fine but the problem is when I use Firebase in the app it gives me this error `ERROR plugin_not_installed`. I think the problem is becose this pluging api is diferent than old version. For example:

my app is trying to call "Firebase.getToken" but in the new version the call is "FirebasePlugin.getToken"

I don't know if that it's the reason  but the point is, @ionic-native/firebase doesn't works with the new version of plugin.

anyone have an idea?

this is my ionic's info. 

```
Ionic:

   ionic (Ionic CLI)  : 4.4.0 (C:\Users\pcova\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v8.11.1 (C:\Program Files (x86)\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

I'm using `"@ionic-native/firebase": "^4.20.0"` and `cordova-plugin-firebase-lib@4.1.0`

![error](https://user-images.githubusercontent.com/49649243/60361920-e9135780-99b5-11e9-9366-d1d15fefd767.png)

PD: I tried to use cordova-plugin-firebase but has the same problem and sorry for my english

Link to: ["cordova-plugin-firebase-lib"](https://www.npmjs.com/package/cordova-plugin-firebase-lib#supported-cordova-platforms-1)

**Comment by JoseGeorges8** [comment]
having the same issue

**Comment by elaval** [comment]
Also having the same issue.  Does anybody have cordova-plugin-firebase-lib working with @ionic-native/firebase?

**Comment by danielsogl** [comment]
Because it is a native plugin you have to run your app on a real device. Browser is not supported
