### ISSUE TITLE
Ionic native printer not work

### ISSUE THREAD

**Issue by shahabzebare** [ionic-team/ionic-native#3093]
https://stackoverflow.com/questions/56904318/i-have-problem-with-ionic-native-plugin-for-printing-ionic-4

**Comment by aosifre** [comment]
Same problem

**Comment by aosifre** [comment]
No patches or solutions?

**Comment by aosifre** [comment]
I solved the problem with a [fork ](https://github.com/isiigoteam/cordova-plugin-printer)but I can't print a PDF with it could you fix the problem on ionic-native/print?

**Comment by domschmidt** [comment]
Problem relates to the recent update in 0.8.0 of the interface. method "check" is no longer available and renamed to canPrintItem.
0.7.3 seems to work fine.

**Comment by agent-simon-s** [comment]
I'm encountering the same issue. Anyone find a fix yet?
Its not just the method name "canPrintItem"
I'm getting no positive test for the printer itself. Tried 0.8.0 and 0.7.3

Error:

> [Error] ERROR – Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.printer')
ionic://localhost/main-es2015.js:1853:17
onInvoke@ionic://localhost/vendor-es2015.js:71868:39
run@ionic://localhost/polyfills-es2015.js:3130:49
ionic://localhost/polyfills-es2015.js:3861:39
onInvokeTask@ionic://localhost/vendor-es2015.js:71849:43
runTask@ionic://localhost/polyfills-es2015.js:3174:57
drainMicroTaskQueue@ionic://localhost/polyfills-es2015.js:3565:42
promiseReactionJob@[native code]
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.printer')
ionic://localhost/main-es2015.js:1853:17
onInvoke@ionic://localhost/vendor-es2015.js:71868:39
run@ionic://localhost/polyfills-es2015.js:3130:49
ionic://localhost/polyfills-es2015.js:3861:39
onInvokeTask@ionic://localhost/vendor-es2015.js:71849:43
runTask@ionic://localhost/polyfills-es2015.js:3174:57
drainMicroTaskQueue@ionic://localhost/polyfills-es2015.js:3565:42
promiseReactionJob@[native code]resolvePromise — zone-evergreen.js:797(anonymous function) — zone-evergreen.js:862onInvokeTask — core.js:34182runTask — zone-evergreen.js:168drainMicroTaskQueue — zone-evergreen.js:559promiseReactionJob
    defaultErrorLogger (vendor-es2015.js:46777)
    handleError (vendor-es2015.js:46829)
    next (vendor-es2015.js:72582)
    (anonymous function) (vendor-es2015.js:68718)
    __tryOrUnsub (vendor-es2015.js:115058)
    next (vendor-es2015.js:114997)
    _next (vendor-es2015.js:114947)
    next (vendor-es2015.js:114924)
    next (vendor-es2015.js:114710)
    emit (vendor-es2015.js:68680)
    run (polyfills-es2015.js:3130)
    onHandleError (vendor-es2015.js:71904)
    runGuarded (polyfills-es2015.js:3143)
    (anonymous function) (polyfills-es2015.js:3669)
    drainMicroTaskQueue (polyfills-es2015.js:3572)
    promiseReactionJob

System:

> Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.8.1
   native-run                             : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.9.0 (/usr/local/bin/node)
   npm        : 6.2.0
   OS         : macOS Mojave
   Xcode      : Xcode 11.3.1 Build version 11C504
