### ISSUE TITLE
Support to send formdata through ionic 

### ISSUE THREAD

**Issue by ankithanrsc** [ionic-team/ionic-native#3099]
I am trying to send formdata through my ionic 3 application.
But ionic does not support formdata body, neither cordova-plugin-advanced-http does.
I am able to send json body in requests successfully using native http.
But for sending formdata, I have tried multiple options like angular HttpClient, xmlhttprequest, fetch...,etc , which led me to cors issue.
With angular httpclient, I have tried the following:
I have tried to use ionic service proxy by setting up proxy in ionic.config.json, but that led me to internal server error 500 : "getaddrinfo ENOTFOUND"
I edited my proxyUrl to remove "https://" and use only "myurl.com", and that gave me "ECONNREFUSED tcpconnectwrap.afterconnect"
I found cordova-http plugin which was forked and updated to build cordova-plugin-advanced-http. I see that cordova-http supports formdata but it has been dropped in cordova-advanced-http and thus in ionic.
I am behind company proxy  and have been on this for 3 weeks.
I even posted [this](https://forum.ionicframework.com/t/ionic-native-http-post-formdata/167754) question on the forum but got no support there... Hoping I could find some solution with the ionic team.

**Comment by mkw2000** [comment]
Try the file transfer plugin

**Comment by kedarSRKS** [comment]
Hi, I'm facing same issue since 1 week, please could you help me to solve this issue...

**Comment by ankithanrsc** [comment]
I couldnot send formdata object using ionic _http_. I also tried angular _httpclient_ but had a CORS issue. I had to contact the server side guys to change for alternatives like json.

**Comment by kedarSRKS** [comment]
Okay, Thank you for the response. Will try angular httpClient

**Comment by kedarSRKS** [comment]
Thanks for suggestion @ankithanrsc , today solve that issue by converting image to base64 and send using JSON Method.
