### ISSUE TITLE
Input Local notifications without response

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic-native#3102]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

It's not possible to retrieve data from scheduled input notification.

**Expected behavior:**

I need to get input data somehow. [Here is how plugin implements](https://github.com/katzer/cordova-plugin-local-notifications#input) this (I couldn't find any much informations about how to get input data).

I'm not sure but implementation probably is missing second [parameter](https://github.com/katzer/cordova-plugin-local-notifications#custom) **eopts**:
```
cordova.plugins.notification.local.on('yes', function (notification, eopts) { ... });
```

I've even found another guy with the same problem: https://www.reddit.com/r/angular/comments/be4513/local_notification_with_reply_action/el31vbs/

**Steps to reproduce:**

Create new message
```ts
this.localNotifications.schedule({
      id: 1,
      title: 'Title',
      text: 'Message',
      actions: [
        {
          id: 'reply',
          title: 'Reply',
          type: ILocalNotificationActionType.INPUT,
        },
      ],
    });
```

Listen for reply action

```ts
this.localNotifications.on('reply').subscribe(notification => {
      console.log(notification);
    });
```

**Related code:**

This is how response looks like. Nothing about response:
`
{"smallIcon":"res://notification_icon","title":"Title","defaults":0,"vibrate":false,"foreground":false,"showWhen":true,"progressBar":{"enabled":false,"value":0},"lockscreen":true,"launch":true,"autoClear":true,"priority":0,"meta":{"version":"0.9-beta.2","plugin":"cordova-plugin-local-notification"},"id":1,"number":0,"wakeup":true,"attachments":[],"silent":false,"groupSummary":false,"text":"Message","actions":[{"id":"reply","title":"help","type":"input"}],"trigger":{"type":"calendar"},"sound":"default","led":true}
`

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/rafalschmidt/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by maheshbelavadi** [comment]
I have the same issue. Any plan to fix this soon?
