### ISSUE TITLE
ionic native/stripe (package com.stripe.android.util does not exist)

### ISSUE THREAD

**Issue by dhanasekar13** [ionic-team/ionic-native#3111]
I'm submitting a Bug report On @ionic-native/strip@ 4.20.0
**Bug Report**
1 -> 
\src\platforms\android\app\src\main\java\com\zyramedia\cordova\stripe\CordovaStripe.java:142: error: cannot find symbol
2->
\src\platforms\android\app\src\main\java\com\zyramedia\cordova\stripe\CordovaStripe.java:17: error: package com.stripe.android.util does not exist
import com.stripe.android.util.CardUtils;

**Current behavior**
  if (CardUtils.isValidCardNumber(cardNumber)) {
        ^
  symbol:   variable CardUtils
  location: class CordovaStripe
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

**Expected behavior:**
Build successfull

**Related code:**

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details

**Comment by benjibobs** [comment]
I am facing this issue too. Did you ever find a workaround, bypass or fix?

**Comment by sushilwis** [comment]
facing the same issue. can anyone tell me, what's happening ?
