### ISSUE TITLE
Diagnostic and Open-Native-Settings does not work with Ionic4

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [ionic-team/ionic-native#3116]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Import Diagnostic in Ionic4 according to documentation import https://ionicframework.com/docs/native/diagnostic

Unresolved import, no module found for import { Diagnostic } from '@ionic-native/diagnostic/ngx';

**Expected behavior:**
Import should not throw an error

**Steps to reproduce:**
Using an Ionic4, Angular 7 basic setup and try to import import { Diagnostic } from '@ionic-native/diagnostic/ngx';

Same applies to import { OpenNativeSettings } from '@ionic-native/open-native-settings/ngx';

There is not ngx folder in the node_modules library and importing without /ngx does not work, because then he complains on compiling the project

**Comment by ndrake** [comment]
For native-diagnostic, I think you need to import **Diagnostic**, not **Device**.

**Comment by mariomurrent-softwaresolutions** [comment]
Sorry, this was a typo. Actually I am importing diagnostics

**Comment by mluis** [comment]
I'm getting: ` 'Diagnostic' refers to a value, but is being used as a type here.` when I use it in the constructor like the documentation states:

```
import { Diagnostic } from '@ionic-native/diagnostic';

constructor(private diagnostic: Diagnostic) { }
```

**Comment by mluis** [comment]
It turns out I had to include it like `import { Diagnostic } from '@ionic-native/diagnostic/ngx';`
