### ISSUE TITLE
Secure storage plugin no longer maintained

### ISSUE THREAD

**Issue by l3ender** [ionic-team/ionic-native#3125]
**I'm submitting a ...**
[ ] bug report
[x] feature request

**Current behavior:**
Ionic currently references <https://github.com/Crypho/cordova-plugin-secure-storage> which has been archived by the repository owner and will no longer be maintained.

**Expected behavior:**
Ionic should use a different and supported plugin for the feature. This seems like a pretty critical part of an app so something native to Ionic would make sense.

**Comment by distante** [comment]
Do you know a Cordova plugin that does something similar?

**Comment by l3ender** [comment]
It seems like someone else has taken up and maintaining a fork: https://github.com/mibrito707/cordova-plugin-secure-storage-echo

See also https://github.com/ionic-team/ionic-native/issues/3157.
