### ISSUE TITLE
Function Missing in OneSignal (4.20.0) plugin

### ISSUE THREAD

**Issue by nacho004** [ionic-team/ionic-native#3132]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Getting error Property 'setExternalUserId' does not exist on type 'OneSignal' while using the function described in the Cordova SDK Document.

**Expected behavior:**
 The function should exist.
 Same as #2909 

**Steps to reproduce:**
Create an Ionic 3 starter project and install OneSignal plugin
Initialize the plugin and try to register user id

**Related code:**

```
export class AppComponent {
constructor(oneSignal: OneSignal) {
   oneSignal.setExternalUserId(userId);
}
```

**Other information:**
OneSignal-Cordova-SDK has added 2 new functions in release 2.4.6:

```
setExternalUserId(string)
removeExternalUserId
```

These functions implementations are missing from the latest version of @ionic-native/onesignal@4 package

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0-dev, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/nacho/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by gabeta** [comment]
Have you get one solution ? Have same problem

**Comment by gabeta** [comment]
This seems to be a workaround.
window['plugins'].OneSignal.setExternalUserId(this.user.email);
