### ISSUE TITLE
help publish ionic native plugin wrapper 

### ISSUE THREAD

**Issue by mostafa-mansour1** [ionic-team/ionic-native#3154]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request 

**Current behavior:**
I already create a plugin to preview file in cordova projects https://github.com/mostafa-mansour1/previewAnyFile
and i created the ionic plugin wrapper for it but i don't know the best way to publish it into ionic repo

**Comment by TekinGomes37** [comment]
Me too
