### ISSUE TITLE
[@ionic-native/http] setSSLCertMode is actually deprecated. Instead setServerTrustMode should be used.

### ISSUE THREAD

**Issue by HighSoftWare96** [ionic-team/ionic-native#3167]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

The method `setSSLCertMode` is now deprecated in cordova as the documentation explains [here](https://github.com/silkimen/cordova-plugin-advanced-http#setsslcertmode-deprecated).

**Expected behavior:**

The method `setServerTrustMode` should be actually typed and used. [Doc](https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode)

**Other information:**

Related issue: #2649 #2912 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 16 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.10.3
   OS     : macOS Mojave
   Xcode  : Xcode 10.3 Build version 10G8

```

**Comment by FrancescoPaiola** [comment]
I have the same problem. please update!
