### ISSUE TITLE
Typescript Error Cannot find name 'unknown'.

### ISSUE THREAD

**Issue by kodeine** [ionic-team/ionic-native#3174]
**I'm submitting a ...**  (check one with "x")
[x] bug report

![image](https://user-images.githubusercontent.com/8620059/65393724-8cc09980-dd52-11e9-92e3-921069a84fcc.png)

```
$ ionic serve
> ionic-app-scripts serve --address localhost --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
[app-scripts] [16:17:45]  ionic-app-scripts 3.2.4 
[app-scripts] [16:17:45]  watch started ... 
[app-scripts] [16:17:46]  build dev started ... 
[app-scripts] [16:17:46]  clean started ... 
[app-scripts] [16:17:46]  clean finished in 101 ms 
[app-scripts] [16:17:46]  copy started ... 
[app-scripts] [16:17:47]  copy finished in 889 ms 
[app-scripts] [16:17:47]  deeplinks started ... 
[app-scripts] [16:17:50]  deeplinks finished in 2.83 s 
[app-scripts] [16:17:50]  transpile started ... 
[app-scripts] [16:18:06]  typescript: node_modules/@ionic-native/core/decorators/common.d.ts, line: 10 
[app-scripts]             Cannot find name 'unknown'. 
[app-scripts]        L9:  export declare function wrapPromise(pluginObj: any, methodName: string, args: any[], opts?: CordovaOptions): Promise<unknown>;
[app-scripts]       L11:   * Checks if plugin/cordova is available


```

```
Ionic Framework: ^3.9.2
Ionic App Scripts: 3.2.4
Angular Core: ^5.2.11
Angular Compiler CLI: ^5.2.11
Node: 11.5.0
OS Platform: macOS High Sierra
```

**Comment by dominikse** [comment]
I could fix this issue in first place by replacing "Promise<unknown>" by "Promise<any>" in "core/decorators/common.d.ts" file.
I'm pretty sure it is not a proper solution but the error vanished. Still not sure if there will be any side effects...

**Comment by mariusbackes** [comment]
Which TypeScript version do you use?
In my project I used version 2.6.2 and had the same issue. After upgrading to the latest version (3.6.3) it is working fine.

**Comment by dominikse** [comment]
In my case upgrading typescript from 2.9.2 to 3.6.4 leads to the following error during ionic serve :-/ 

`[ng] ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.10.0 but 3.6.4 was found instead.`
`[ng] ℹ ｢wdm｣: Failed to compile.`

**Comment by emanuellandell** [comment]
> I could fix this issue in first place by replacing `Promise<unknown>` with `Promise<any>` in "core/decorators/common.d.ts" file.
> I'm pretty sure it is not a proper solution but the error vanished. Still not sure if there will be any side effects...

the only solution I found that worked. Thanks!

**Comment by ericgopak** [comment]
> I could fix this issue in first place by replacing `Promise<unknown>` with `Promise<any>` in "core/decorators/common.d.ts" file.
> I'm pretty sure it is not a proper solution but the error vanished. Still not sure if there will be any side effects...

Happens to me as well, using typescript 2.6.2 due to angular-cli limitations. The temporary fix by dominikse worked for me

**Comment by david-schopf** [comment]
Try to add this to a Typescript declaration file of your project:

`declare type unknown = any;`

**Comment by terryjiang2020** [comment]
I wonder why we don't officially update "Promise<unknown>" to "Promise<any>" here since it has been an existing issue for a long time.
