### ISSUE TITLE
how to update ionic plugin docs

### ISSUE THREAD

**Issue by mostafa-mansour1** [ionic-team/ionic-native#3175]
Dears, 

my new plugin [PreviewAnyFile](https://github.com/ionic-team/ionic-native/tree/master/src/%40ionic-native/plugins/preview-any-file) just merged into the master branch  of ionic-native, 

how to show it in the ionic native document page 

here 

https://ionicframework.com/docs/native/overview

**Comment by 5im0n** [comment]
To add your plugin to the documentation, you should update the file **[native.json](https://github.com/ionic-team/ionic-docs/blob/master/scripts/data/native.json)** in the [Ionic-docs](https://github.com/ionic-team/ionic-docs) repository.
