### ISSUE TITLE
ionic 3 support

### ISSUE THREAD

**Issue by BugsBunnyBR** [ionic-team/ionic-native#3179]
So... the current version of ionic-native dont' support ionic v3 anymore, right?
I mean... It looks like there is a need to use angular 7 since 5.0.0-beta22, is it right?
I was looking forward to use the firebasex plugin without having to update all code base.

**Comment by danielsogl** [comment]
The code is compiled with the latest Angular release but you can upgrade to Ionic-Native V4 without problems.

**Comment by BugsBunnyBR** [comment]
Ionic native v4 does not contain Firebase X

**Comment by danielsogl** [comment]
This has nothing to do with backwards compatibility and is also wrong as you can see here: https://www.npmjs.com/package/@ionic-native/firebase-x

**Comment by BugsBunnyBR** [comment]
@danielsogl firebase-x depends of ionic-native code that is meant to work with angular7, even older versions of firebase-x would not work with ionic 3. So no, I am not wrong here.
