### ISSUE TITLE
Youtube Video Player on IOS 13 Issue > Fixed

### ISSUE THREAD

**Issue by abomadi** [ionic-team/ionic-native#3198]
for all people who have issue with you-tube-video-player plugin I have forked and updated a plugin to work with the new IOS update.

```
ionic cordova plugin rm cordova-plugin-youtube-video-player
ionic cordova plugin add https://github.com/abomadi/CordovaYoutubeVideoPlayer
```

**Comment by marshall86** [comment]
the issue is still open. The App crashes as soon as you try to launch the player

**Comment by abomadi** [comment]
I am already using the plugin, make sure u have implemented it correctly, and if any logs are there post it here

**Comment by coddark** [comment]
unable to install plugin.

**Environment Details:**

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

**global packages:**

    cordova (Cordova CLI) : 8.0.0 

**local packages:**

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

**System:**

    ios-deploy : 2.0.0 
    ios-sim    : 8.0.2 
    Node       : v7.9.0
    npm        : 4.2.0 
    OS         : macOS
    Xcode      : Xcode 11.0 Build version 11A420a




**Error   :**
          >ionic cordova plugin add https://github.com/abomadi/CordovaYoutubeVideoPlayer
          >UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to 
            fetch plugin https://github.com/abomadi/CordovaYoutubeVideoPlayer via registry.
          >Check your connection and plugin name/version/URL.
          >Failed to get absolute path to installed module (node:16794) DeprecationWarning: 
             Unhandled promise rejections are deprecated. In the future, promise rejections that are not 
             handled will terminate the Node.js process with a non-zero exit code.

**Comment by abomadi** [comment]
@coddark it looks a node issue, can u update to 
   NodeJS            : v12.10.0
   npm               : 6.9.0

**Comment by vrdriver** [comment]
Hey mate, I didn't have success with yours, but I tried this one for iOS 13 and it worked.

ionic cordova plugin add https://github.com/christopherafbjur/CordovaYoutubeVideoPlayer
