### ISSUE TITLE
Typing @ionic-native/purchases for cordova-plugin-purchases needs updating

### ISSUE THREAD

**Issue by wilkovanhoek** [ionic-team/ionic-native#3215]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
According to the typing of the package `@ionic-native/purchases` an array of oldSku strings can be given when calling the plugin's method `makePurchase(productIdentifier: string, oldSkus?: string[], type?: ProductType): Observable<RCMakePurchaseResponse>`. Within the plugin this has been changed from an array `string[]` to a single value `string`. This results in compilation errors.

**Expected behavior:**
The definition should accept a `string` instead of an array of strings `string[]`

**Steps to reproduce:**
Use the plugin and provide an array of strings as `oldSkus` parameter, when calling `makePurchase`.

**Related code:**

https://github.com/RevenueCat/cordova-plugin-purchases/blob/0.3.2/src/plugin/plugin.ts

**Other information:**
`ERROR in src/app/shop/revenueCatShop.service.ts(102,41): error TS2345: Argument of type 'string' is not assignable to parameter of type 'string[]'.`

**Comment by vegaro** [comment]
Just opened https://github.com/ionic-team/ionic-native/pull/3301 which should fix this

**Comment by vegaro** [comment]
The PR just got merged @wilkovanhoek . This can be closed now
