### ISSUE TITLE
Android Q print error TypeError: Printer.getPlugin(...).check is not a function

### ISSUE THREAD

**Issue by ravatsinh** [ionic-team/ionic-native#3242]
when calling 
```
 this.printer.isAvailable().then((success)=>{
      this.printService=true;
    }).catch((error)=>{
      console.log('print error',error)
    });
```
`print error TypeError: Printer.getPlugin(...).check is not a function `

**Comment by domschmidt** [comment]
Duplicate of 3225?
https://github.com/ionic-team/ionic-native/pull/3225

**Comment by indraraj26** [comment]
Hi, 
It is working fine in Android but Getting same error in iOS.

"@ionic-native/core": "^5.19.1",
"@ionic-native/printer": "^5.19.1",
