### ISSUE TITLE
error TS2322: Type 'AdMobOriginal' is not assignable to type 'Provider'.

### ISSUE THREAD

**Issue by ramoas86** [ionic-team/ionic-native#3243]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

I installed the plugin following the ionic guide (https://ionicframework.com/docs/native/admob-plus). After adding "Admob" to @NgModule providers, the error happens.

Message:
[ng]        ERROR in src/app/app.module.ts(21,5): error TS2322: Type 'AdMobOriginal' is not assignable to type 'Provider'.
[ng]       Type 'AdMobOriginal' is missing the following properties from type 'TypeProvider': apply, call, bind, prototype, and 5 more.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

_app.module.ts_

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

import { AdMob } from "@ionic-native/admob-plus";

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [
    StatusBar,
    SplashScreen,
    AdMob,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

_package.json_

{
  "name": "TesteAppVazio",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/android": "^1.3.0",
    "@capacitor/core": "1.3.0",
    "@ionic-native/admob-free": "^5.17.1",
    "@ionic-native/admob-plus": "^5.17.1",
    "@ionic-native/core": "^5.17.1",
    "@ionic-native/splash-screen": "^5.17.1",
    "@ionic-native/status-bar": "^5.17.1",
    "@ionic/angular": "^4.11.5",
    "cordova-admob-plus": "^0.32.0",
    "cordova-android": "^8.1.0",
    "cordova-plugin-admob-free": "^0.27.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.5.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@capacitor/cli": "1.3.0",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-admob-plus": {}
    }
  }
}

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by maihannijat** [comment]
Try to import it from the following:

`import { AdMob } from "@ionic-native/admob-plus/ngx";`

**Comment by mwmw7** [comment]
@maihannijat  thank you
