### ISSUE TITLE
InAppBrowser without angular - Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic-native#3257]
Hi. I am trying to use inAppBrowser without Angular like this:

```
import { InAppBrowser } from '@ionic-native/in-app-browser';

export const openBrowser = function(url: string) {
  let instance = InAppBrowser.create(url, '_blank', {
    hideurlbar: 'yes',
    fullscreen: 'yes',
    hardwareback: 'no',
    hidenavigationbuttons: 'yes',
    location: 'no',
  });

  instance.on('loadstop').subscribe(function() {
    instance
      .executeScript({
        code: "function getToken(){return localStorage.getItem('authToken');}getToken();",
      })
      .then(function(params) {
        console.log('params:', params);
        // let token = params[0];
        instance.close();
      });
  });
```
But then, I face an error saying `Uncaught TypeError: Cannot read property 'subscribe' of undefined`

Any idea how to fix this issue? Thanks.

**Comment by mhartington** [comment]
Do you have rxjs installed?

**Comment by donfour** [comment]
Bump, having the same issue.

Yes, I do have rxjs installed.

**Comment by donfour** [comment]
Might be related to #2899

**Comment by mateoc10** [comment]
I'm having the same issue. Did you find a solution?

**Comment by donfour** [comment]
@mateoc10 unfortunately no... please let me know when you do...

**Comment by mateoc10** [comment]
@donfour I made it work by adding "_blank" and location: "yes". But it doesn't work on chrome while developing. On iOS and Android it works fine.
`const browser = InAppBrowser.create(loginUrl, '_blank', { location: "yes" })
  browser.on("loadstart").subscribe(info => {
       console.log("INFO", info)
})
`

**Comment by nitisha123** [comment]
I am trying the same, but still getting error
