### ISSUE TITLE
HTTP JSON serializer behaving differently depending on the platform

### ISSUE THREAD

**Issue by krimsz** [ionic-team/ionic-native#3281]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic native http client JSON serializer behaves differently in iOS than in Android.
`httpClient.setDataSerializer('json');` Will create a different payload depending on the platform (the order of the fields in the  serialized JSON changes). 

For iOS it seems that the order is alphabetically inverse (Z to A for the field keys, both in root and in nested level)
For Android the order of the fields in the object is preserved

**Expected behavior:**
The serialization is the same regardless of the platform.

**Steps to reproduce:**

- Create a component with a httpService
- Set serializer to json
- Make a post request
- The content can be verified in the server side, if printing the body as it comes the serialization will be seen as different

**Related code:**

```
import {HTTP} from '@ionic-native/http/ngx';

export class SomeService {
  constructor(private httpClient: HTTP) {}

  async postRequest(url: string, postBody: object): Promise<object> {
    this.httpClient.setDataSerializer('json');
    try {
      return await this.httpClient.post(url, postBody, null);
    } catch (e) {
      throw new MyCustomError(e);
    }
  }

}
```

**Other information:**
In order to work around the issue, we set the serializer to `utf8`, stringify the payload and add a `{'Content-Type': 'application/json'}` header.
```
    this.httpClient.setDataSerializer('utf8');
    await this.httpClient.post(url, JSON.stringify(postBody), {'Content-Type': 'application/json'});

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.6.0 (/usr/local/Cellar/node/12.6.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 11.3 Build version 11C29

```

**Comment by NunoSav** [comment]
I'm also experiencing issues related to this, in my case iOS serialization returns a payload with the following format `{ key = value; key2 = value2; }`.
