### ISSUE TITLE
@ionic-native/firebase-authentication doesn't export getCurrentUser()

### ISSUE THREAD

**Issue by a-ferrari** [ionic-team/ionic-native#3282]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
@ionic-native/firebase-authentication doesn't export getCurrentUser() 

**Expected behavior:**
why doesn't  @ionic-native/firebase-authentication export getCurrentUser() of cordova-plugin-firebase-authentication? Is there a reason or different way to check if a user is already logged?

**Comment by wizvaibhav** [comment]
@a-ferrari Having the same issue. Need the user instance but the @ionic-native/firebase-authentication doesnt export getCurrentUser().

Did you find any other way. I am using Ionic and dont want to use angular fire auth since it doesnt send otp for verification without captcha.

**Comment by a-ferrari** [comment]
> @a-ferrari Having the same issue. Need the user instance but the @ionic-native/firebase-authentication doesnt export getCurrentUser().
> 
> Did you find any other way. I am using Ionic and dont want to use angular fire auth since it doesnt send otp for verification without captcha.

Hi,
I use cordova so I can use jwt token 
 i.e
declare var cordova: any
....
cordova.plugins.firebase.auth.getCurrentUser().then((userInfo) => {
      if (typeof (userInfo) != "undefined") {
        // user information or null if not logged in
        console.log('getCurrentUser user info:' + JSON.stringify(userInfo));
        this.user = userInfo;
      }
    }).catch((error) => {
      console.log(error)
      alert('error:' + error)
    });

**Comment by cleverappdesign** [comment]
Having the same issue as well, all the other functions work except getCurrentUser(), will this be updated? Thanks!
