### ISSUE TITLE
ionic ios app crashing when open pdf by using ionic document viewer

### ISSUE THREAD

**Issue by gaus694** [ionic-team/ionic-native#3283]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by gaus694** [comment]
here is the xcode throw error when pdf opening.

Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3901.4.2/UIApplication.m:5330
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'

**Comment by jayordway** [comment]
I have this issue too, when building with XCode 11.x and iOS 13.x, works fine on Android.

**Comment by fiedl** [comment]
I don't have experience with this api. But maybe something to track down the issue:

I've just browsed through the code of the document viewer and found something in `SDVReaderViewController.m`:

```cpp
// SDVReaderViewController.m

    UIView *statusBar = [[[UIApplication sharedApplication] valueForKey:@"statusBarWindow"] valueForKey:@"statusBar"];
    
    if ([statusBar respondsToSelector:@selector(setBackgroundColor:)]) {
        previousColor = statusBar.backgroundColor;
        statusBar.backgroundColor = [UIColor blackColor];//set whatever color you like

    }
```

And a little down:

```cpp
    UIView *statusBar = [[[UIApplication sharedApplication] valueForKey:@"statusBarWindow"] valueForKey:@"statusBar"];
    
    if ([statusBar respondsToSelector:@selector(setBackgroundColor:)]) {
        
        statusBar.backgroundColor = previousColor;//set whatever color you like
    }
```

When commenting out these lines, the app does no longer crash.
