### ISSUE TITLE
File read promise returns nothing

### ISSUE THREAD

**Issue by ir2pid** [ionic-team/ionic-native#3289]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
In ionic 3, in android API 28, file readAsDataURL, readAsBinaryString or readAsArrayBuffer all return a promise which is never resolved. No logs in console either. Works in emulator and iOS devices.

**Expected behavior:**
The promise should return the data of the file being read

**Steps to reproduce:**
needs File Chooser and File plugins,

open a file selector and try to read the chosen file;
app hangs in line `file.readAsBinaryString`

```

```

**Related code:**
```

  test() {
    this.fileChooser
      .open()
      .then(file => {
        debugger;
        this.filePath
          .resolveNativePath(file)
          .then(resolvedFilePath => {
            debugger;
            let path = resolvedFilePath.substring(0, resolvedFilePath.lastIndexOf('/'));
            let file = resolvedFilePath.substring(resolvedFilePath.lastIndexOf('/') + 1, resolvedFilePath.length);
            this.readCsvData(path, file);
          })
          .catch(err => {
            alert(JSON.stringify(err));
          });
      })
      .catch(err => {
        alert(JSON.stringify(err));
      });
  }
  private readCsvData(path, filename) {
    this.file
      .readAsBinaryString(path, filename)
      .then(content => {
        debugger;
        console.log('File-Content: ' + JSON.stringify(content));
      })
      .catch(err => {
        console.log(err);
        alert(JSON.stringify(err));
      });
  }

```
```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Ionic:

   Ionic CLI          : 5.4.6 (/Users/xx/.nvm/versions/node/v10.14.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 31 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.3.0 

System:

   Android SDK Tools : 26.1.1 (/Users/xx/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.14.0 (/Users/xx/.nvm/versions/node/v10.14.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504

```
insert the output from ionic info here
```

**Comment by bradmasitek** [comment]
Hi did you ever get this working?  I am having the same issue with no response or error.

**Comment by elvisgraho** [comment]
Same issue.

**Comment by n0hkie** [comment]
Hi any update or solution on the issue? I'm also having this issue on android 10 but not on android 7.1
