### ISSUE TITLE
bluetooth-le plugin with react

### ISSUE THREAD

**Issue by qwenzo** [ionic-team/ionic-native#3292]
when i compile an ionic app with react i get this error with the bleutoothle plugin
```
./node_modules/@ionic-native/bluetooth-le/index.js
[react-scripts] Module not found: Can't resolve '@angular/core' in 'C:\projects\test-ble-react\myApp\node_modules\@ionic-native\bluetooth-le'
```
i am using "@ionic/react": "^4.11.8", "react": "^16.12.0" and "cordova-plugin-bluetoothle": "^4.5.6".
i used the library @ionic-native/bluetooth-le to import the plugin

**Comment by Arxi** [comment]
I do believe you have to also install the npm package "@ionic-native/core" 

how do you use or import the plugin?

**Comment by Theofilos-Chamalis** [comment]
I face the same issue too, and I have installed @ionic-native/core as well. 

The import I use is based on the provided documentation, i.e.
`import { BluetoothLE } from '@ionic-native/bluetooth-le/ngx';`

**Comment by jrobeson** [comment]
the provided documentation is for angular, so just remove the `ngx`

**Comment by iddan** [comment]
Documentation should mention that the BluetoothLE interface is a singleton when not in ngx

**Comment by jrobeson** [comment]
it really just needs an entire section for react usage, but that's a docs bug, not one that should be filed here.  IMO this bug should be closed and reopened at the docs repo.
