### ISSUE TITLE
Can't get the coordinates from Openlayer Polygon Drawing.

### ISSUE THREAD

**Issue by FQuouhadiho** [ionic-team/ionic-native#3296]
I'm building an app using Ionic 4 included Openlayers.
After drawing the polygon, i can see the coordinates on the console.log but I don't have a solution to get these coordinates. Any solution will be helpful

here is what I tried

    ngOnInit(){   
        const scope = this;
       this.addInteractions(GeometryType.POLYGON);
       this.source.on('addfeature', function(coord){
        var feature = coord.feature;
       var coords = feature.getGeometry().getType;
      }

        ----

     addInteractions(geoTy) {
      this.map.getInteractions().clear;

      this.draw = new Draw({
      source: this.source,
      type: geoTy
    });
    
    this.map.addInteraction(this.draw);
    this.snap = new Snap({source: this.source});
    this.map.addInteraction(this.snap);

    console.log(this.map.getInteractions().get);
     }

I haven't added things that are less important for this.
Ionic:

   Ionic CLI                     : 5.4.14 (C:\Users\FQDev\AppData\Roaming\npm\node_modules\ionic)    
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 
7 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\FQDev\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (D:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by danielsogl** [comment]
This issue has nothing to do with this repo. Please us the ionic forum to find help
