### ISSUE TITLE
firebase-authentication - phone authentication

### ISSUE THREAD

**Issue by jeanres** [ionic-team/ionic-native#3297]
Hi, 

I am currently implementing phone number authentication with the https://www.npmjs.com/package/@ionic-native/firebase-authentication package, receiving the text message is not a problem but the verification of the message with the verificationId is

```
 phoneLogin(phoneNumber: string): Promise<any> {
    return this.firebaseAuthentication.verifyPhoneNumber(phoneNumber, 60);
  }

  verifyOneTimePin(verificationId: string, otp: number): Promise<any> {
    return this.firebaseAuthentication.signInWithVerificationId(verificationId, otp)
  }
```

```
  send() {
    this.authService.phoneLogin(this.phoneNumber).then((verificationId) => {
      this.verificationId = verificationId
      // this.otpVisible = true
    }).catch((exception) => {
      swal({
        title: 'Login Failed',
        text: exception,
        type: 'error',
        cancelButtonText: 'Ok',
        confirmButtonClass: 'gradientOrange',
        buttonsStyling: true,
        heightAuto: false
      });
    })
  }

  verify() {
    this.authService.verifyOneTimePin(this.verificationId, this.otp).then((result) => {
      console.log(result)
    })
  }
```

The verification method always returns null.

**Comment by dupiesdupreez** [comment]
I've also had this issue before. Subscribing.

**Comment by jeanres** [comment]
@dupiesdupreez the initial verifyPhoneNumber returns the verificationId correctly though, but when passing it to the signInWithVerificationId returns null. 

Pretty silly, the docs do not explain much either...

**Comment by dupiesdupreez** [comment]
What do the docs say your response must look like? Do they even mention that?

**Comment by NikolaPeevski** [comment]
@jeanres Have you tried this workaround https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/20#issuecomment-390292383 ?
