### ISSUE TITLE
@ionic-native/facebook is dependent on Angular

### ISSUE THREAD

**Issue by Justas-S** [ionic-team/ionic-native#3300]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
@ionic-native/facebook plugin lists `angular` as a peer dependency, making it unusable with all other frameworks(or no framework).

**Expected behavior:**
Plugin to be independent of framework, just like the rest of Ionic 4.

**Steps to reproduce:**
Importing any class from the library is enough for it to crash.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

Ionic:

   Ionic CLI       : 5.4.13 (/.npm/lib/node_modules/ionic)
   Ionic Framework : @ionic/vue 0.0.9

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.18.1 (/usr/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.15


```

**Comment by pitis** [comment]
Yup....same problem. Seems nobody cares about this. Really makes me switch to React Native

**Comment by jonapgar** [comment]
Same with @ionic-native/nfc

**Comment by jonapgar** [comment]
Note that I just pulled master from this repo and rebuilt and the @ionic-native/nfc package seems to be working. Hopefully they are pushing new versions to npm soon.

**Comment by pitis** [comment]
Nah, I already got even more problems with Ionic. This is my last project with it, too many bugs

**Comment by danielsogl** [comment]
If you check the package.json inside the downloaded native wrapper plugin you will see that angular is not required dependency.

```json
  "peerDependencies": {
    "rxjs": "^5.5.0 || ^6.5.0",
    "@ionic-native/core": "^5.1.0"
  },
```

You can use the native wrappers even with plain javascript as described in the readme.
