### ISSUE TITLE
BAD PULL feat(firebase-x): add missing methods, parameter (#3273)

### ISSUE THREAD

**Issue by forestgun** [ionic-team/ionic-native#3304]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

 BAD Pull request [#3273](https://github.com/ionic-team/ionic-native/pull/3273), Error 

In the modifications made to the pull request, a parameter was added to setCrashlyticsCollectionEnabled() that it should never have. Now to compile, you must use setCrashlyticsCollectionEnabled('boolean') when the cordova plugin only waits for setCrashlyticsCollectionEnabled() without parameters. Now or I have error in compilation or in execution. but it does not work.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by incal** [comment]
Hi, I confirm the problem, can't use the method:
 `self.firebaseX.setCrashlyticsCollectionEnabled(true);`
> Error in Success callbackId: FirebasePlugin1151226500 : TypeError: callback.success.apply is 
> [app-scripts]             not a function

**Comment by TdoubleG** [comment]
I can confirm this bug! setCrashlyticsCollectionEnabled() shouldn't accept a parameter. See the documentation of the cordova plugin!

https://github.com/dpa99c/cordova-plugin-firebasex#setcrashlyticscollectionenabled

**Comment by almothafar** [comment]
With version 9.0.0 now it got 3 parameters
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/CHANGELOG.md#version-900
