### ISSUE TITLE
NavigationBar: callback.success.apply is not a function

### ISSUE THREAD

**Issue by vandres** [ionic-team/ionic-native#3305]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

Whenever a function of the plugin is called through Ionic Native, there is an error `callback.success.apply is not a function`

**Expected behavior:**

No errors

**Steps to reproduce:**

Just use the following code. It seems no callback function is provided or the call to the native plugin is wrong. Using the plugin directly works fine

```   
this.navigationBar.setUp(true);
```

**Related code:**
this works:

```
(window as any).navigationbar.setUp(true);
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI          : 5.4.15 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run (update available: 0.3.0)  : 0.2.9

System:

   ios-deploy : 1.10.0
   NodeJS     : v10.18.1 (/usr/local/bin/node)
   npm        : 6.13.7
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504

```

**Comment by rathodkaran07** [comment]
Any update on this?

**Comment by julianCast** [comment]
Same here!

**Comment by mvaljento** [comment]
Is there any update on this? I just ran into this error when attempting to auto-hide the navigation bar.

**Comment by morozenkomv** [comment]
The same issue.
