### ISSUE TITLE
Ionic Native plugin texts not displaying System language

### ISSUE THREAD

**Issue by niravparsana94** [ionic-team/ionic-native#3306]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Ionic Native plugin texts not displaying System language

**Expected behavior:**
Ionic Native plugin texts should display System language

**Reference post:**
[Ionic Native plugin texts not displaying System language](https://forum.ionicframework.com/t/ionic-native-plugin-texts-not-displaying-system-language/182150)

**Comment by jcesarmobile** [comment]
The plugins' UI doesn't depend on ionic-native, but on the plugin itself.

Anyway, in this case it doesn't even depends on the plugin, iOS projects only include English language, if you want to include more, use edit-config tag like this:

```
<edit-config target="CFBundleLocalizations" file="*-Info.plist" mode="overwrite">
  <array>
    <string>en</string>
    <string>es</string>
  </array>
</edit-config>
```
