### ISSUE TITLE
Upgrade from 5.20.0 to latest version 5.21.0 breaking the build

### ISSUE THREAD

**Issue by developerjohan01** [ionic-team/ionic-native#3311]
**I'm submitting a ...**  (check one with "x")
[x] bug report

Want to test the new version of Ionic (version 5) and the recommendation is to upgrade Ionic and dependencies to the latest released version first. Note the the build breaks before upgrading the Ionic library, using Ionic 4 or 5 gives the same result.

When using version `5.21.0` the `/ngx` **folders are missing** for  `@ionic-native/firebase-x/` and `@ionic-native/app-availability`

**Current behavior:**
ionic serve /  build is breaking

**Expected behavior:**
build should work 

**Steps to reproduce:**
Upgrade dependencies from version `5.20.0` to `5.21.0`. 

**Related code:**
This is working 
```
...
        "@ionic-native/app-availability": "^5.20.0",
...
        "@ionic-native/firebase-x": "^5.20.0",
```
this is not working 
```
...
        "@ionic-native/app-availability": "^5.21.0",
... 
        "@ionic-native/firebase-x": "^5.21.0",
```

**Other information:**
```

ERROR in app/app.module.ts:12:27 - error TS2307: Cannot find module '@ionic-native/firebase-x/ngx'.

12 import { FirebaseX } from '@ionic-native/firebase-x/ngx';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/app.module.ts:35:33 - error TS2307: Cannot find module '@ionic-native/app-availability/ngx'.

35 import { AppAvailability } from '@ionic-native/app-availability/ngx';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
% ionic info 

Ionic:

   Ionic CLI                     : 6.0.1 (/Users/x/.nvm/versions/node/v10.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-rc.3
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/Users/x/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.15.0 (/Users/x/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.3 Build version 11C29
```

**Comment by danielsogl** [comment]
Looks like the publishing script had some issues. I will create a new release later this day

**Comment by paulstelzer** [comment]
The same for admob-free. Here is no ngx folder, too (also in 5.21.2)

**Comment by danielsogl** [comment]
Every time I create a new release I receive an "duplicated version" errors from the npm registry... I'm not sure what's the issue. @ihadeed can you take a look?

**Comment by paulstelzer** [comment]
@danielsogl All in all 5.21.2 isn't working for me even if a ngx folder exists. After updating (for example InAppPurchase2) I only get an InjectionError. So at the moment I stay at 5.20.0. I am using Angular 9 and ivy.

**Comment by danielsogl** [comment]
I reverted local to 5.20 and the issue still exists. I don't understand whats happening under the hood...
@ihadeed @mhartington can you take a look?

**Comment by mhartington** [comment]
Hello all. I am looking into this issue. I've started a blank project and have installed status-bar and splashscreen at v5.21.2. 

At the moment, I am not able to replicate the issue with 5.21.2. If someone has a project that I could inspect, that would be great.

**Comment by BenjaminPiette** [comment]
Looks like this issue happens for newly created apps, as the ngx folder will not be created. If if was there before, seems like no problem.

We're also running into this error today in Travis without changing a thing, a travis is getting the latest ionic npm release.

**Comment by mhartington** [comment]
@BenjaminPiette Ok, I am seeing this for newly created projects. From the looks of it, I'm thinking it might be a deployment issue on CI side. I'm looking into it.

**Comment by pchasco** [comment]
'@ionic-native/splash-screen/ngx' is missing also.

**Comment by mhartington** [comment]
Hey folks, I've released v5.21.4. This should address both the missing `ngx` directory and "duplicated version" errors on publishing.

Please test this out and verify that all is well.

**Comment by mhartington** [comment]
I have tested out myself, and all is well 🎉

**Comment by danielsogl** [comment]
Thank you mike

**Comment by paulstelzer** [comment]
Can confirm, everything is working again - thanks
