### ISSUE TITLE
@ionic-native/firebase-x setAutoInitEnabled() is missing

### ISSUE THREAD

**Issue by tomavanc** [ionic-team/ionic-native#3312]
**I'm submitting a ...**
[x] bug report
[x] feature request
[ ] support request

**Current behavior:**

As stated in [@dpa99c cordova-plugin-firebasex #unregister](https://github.com/dpa99c/cordova-plugin-firebasex#unregister): To prevent a new token being generated, by sure to disable autoinit using setAutoInitEnabled() before calling unregister(). But setAutoInitEnabled() is not present in @ionic-native/firebase-x.
> Unregisters from Firebase by deleting the current device token. Use this to stop receiving push notifications associated with the current token. e.g. call this when you logout user from your app. By default, a new token will be generated as soon as the old one is removed. **To prevent a new token being generated, by sure to disable autoinit using setAutoInitEnabled() before calling unregister().**

**Expected behavior:**

To access the function setAutoInitEnabled() to unregister a device.

**Steps to reproduce:**

1. Install and import @ionic-native/firebase-x
2. Import FirebaseX in app.module.ts and on a page
3. Try to access setAutoInitEnabled()
4. Error `Property 'setAutoInitEnabled' does not exist on type 'FirebaseX'.`

**Related code:**

Taken from [https://github.com/dpa99c/cordova-plugin-firebasex#setautoinitenabled](https://github.com/dpa99c/cordova-plugin-firebasex#setautoinitenabled)
```typescript
window.FirebasePlugin.setAutoInitEnabled(false, function(){
    console.log("Auto init has been disabled ");
    window.FirebasePlugin.unregister();
});
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run (update available: 0.3.0)  : 0.2.9

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.14.1 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Mojave
   Xcode      : Xcode 11.3 Build version 11C29
```

**Comment by jspiral** [comment]
Hi, is there any update on this issue ?

Still have the same problem ( "@ionic-native/firebase-x": "^5.26.0")
