### ISSUE TITLE
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit

### ISSUE THREAD

**Issue by rafaelximenes** [ionic-team/ionic-native#3313]
**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
After build my ionic 4 project and than try installing in my iphone on ios 13.3.1 happens the error below:

dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit  Referenced from: /private/var/containers/Bundle/Application/850E5805-1742-44F8-9339-7EB2ABA87C43/Adoo.app/Adoo  Reason: no suitable image found.  Did find:	/private/var/containers/Bundle/Application/850E5805-1742-44F8-9339-7EB2ABA87C43/Adoo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit: code signature invalid for '/private/var/containers/Bundle/Application/850E5805-1742-44F8-9339-7EB2ABA87C43/Adoo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit'
	/private/var/containers/Bundle/Application/850E5805-1742-44F8-9339-7EB2ABA87C43/Adoo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit: stat() failed with errno=25Message from debugger: failed to send the k packet

**Expected behavior:**
Running app in my iphone

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
ionic v4
```
insert the output from ionic info here
```

**Comment by MadyAkira** [comment]
According to this post [on stackoverflow](https://stackoverflow.com/questions/46704524/dyld-library-not-loaded-reason-no-suitable-image-found) this is an issue with iOS 13.3.1. It should be solve on the next update.

**Comment by jcesarmobile** [comment]
yeah, it's not related to ionic-native, closing.
