### ISSUE TITLE
Ionic native Screenshot  plugin giving error on android (Java exception was raised during method invocation

### ISSUE THREAD

**Issue by sridharan31** [ionic-team/ionic-native#3326]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
While trying to make an ionic native Screenshot  call from android or ios, I am getting the following error
Error: Java exception was raised during method invocation

**Expected behavior:**
I should be able to make successful native Screenshot  on android and IOS

**Steps to reproduce:**

import { SocialSharing } from '@ionic-native/social-sharing/ngx';
import { Screenshot } from '@ionic-native/screenshot/ngx';

**Related code:**

this.screenshot.URI(80)
    .then((res) => {
      this.socialSharing.shareViaFacebook(null, res.URI, null)
       .then(() => {},
         () => { 
           alert('SocialSharing failed');
         });
       },
      () => {
      alert('Screenshot failed');
      });

insert any relevant code here
```

**Other information:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\mohamedbahars\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.2
   @angular-devkit/schematics    : 9.0.2
   @angular/cli                  : 9.0.2
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (F:\android-sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.7
   OS                : Windows 10

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by HamzaKhalidMirza** [comment]
Did you find an answer? I'm having the same issue on SocialSharing. When I remove cordova-plugin-ionic-webview, it is working but due to removing webview plugin, some others issues arise i.e some images are not working...
