### ISSUE TITLE
How to get InAppBrowser to display behind statusbar?

### ISSUE THREAD

**Issue by benvallack** [ionic-team/ionic-native#3332]
How can we get the InAppBrowser view to show behind the statusbar? I think the statusBar.overlaysWebView option in Ionic 3 is no longer available in the capacitor version of the plugin so how can we get the InAppBrowser view to show behind the status bar?

Thanks!

**Comment by jcesarmobile** [comment]
ionic-native is just a wrapper around cordova plugins, so read the actual plugin docs to see if it's possible, but I don't think it is.
