### ISSUE TITLE
in-app-purchase-2 missing typings?

### ISSUE THREAD

**Issue by HarelM** [ionic-team/ionic-native#3340]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
The in-app-purchase-2 wrapper and typings do not match the docs

**Expected behavior:**
The typings should match the docs

**Steps to reproduce:**
Try to use `store.applicationUsername = ...`.
See here, seems like this is fairly new (after version 9.0)
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeapplicationusername

**Comment by rastafan** [comment]
I believe the applicationusername missing type has been resolved in this commit: #3320 

But it still lacks the "group" type in the Product class i believe.

**Comment by HarelM** [comment]
Thanks for the info, at the time when I opened this issue the PR probably wasn't merged. I saw that a new version was released a week ago, I'll try it out and close this issue of this was resolved...

**Comment by HarelM** [comment]
The following version was released, I'm guessing that `deferred` is now missing in the types here...
https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v10.1.0
I'm not using it, but it's probably worth correcting.
I've updated to latest ionic native version and I now see the applicationUsername, thanks @nvahalik
