### ISSUE TITLE
ERROR: Manifest merger failed for cordova-plugin-firebase-config

### ISSUE THREAD

**Issue by frankcs** [ionic-team/ionic-native#3341]
**I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
Following the install guide in https://ionicframework.com/docs/native/firebase-config
Getting this error when building for android
```
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-43:19 to override.

```
**Expected behavior:**
Application to build correctly

**Steps to reproduce:**
- Execute
```
npm install cordova-plugin-firebase-config
npm install @ionic-native/firebase-config
ionic cap sync
ionic cap open android
```
- Build from Android Studio

**Comment by wf9a5m75** [comment]
Please ask the other side.

**Comment by jcesarmobile** [comment]
closing since it's not a problem on ionic-native

**Comment by rodrigosoareschaves** [comment]
Following the suggestion, this worked for me on config.xml inside <platform name="android"></platform>:

`<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest">
            <manifest xmlns:tools="http://schemas.android.com/tools" />
        </edit-config>
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application tools:replace="android:appComponentFactory" android:appComponentFactory="android.support.v4.app.CoreComponentFactory" /> 
</edit-config>`

After run cordova build android, another error happened saying that "tools:replace is out of bounds" or something like this...
So, I just removed the code from config.xml and it worked well.

**Comment by rodrigosoareschaves** [comment]
But technically, the https://github.com/dpa99c/cordova-plugin-androidx would fix this issue (here, even with this plugin the erro was happening, that's why I used the edit-config).
