### ISSUE TITLE
cordova-plugin-fcm-with-dependecy-updated fails for IOS

### ISSUE THREAD

**Issue by tdakanalis** [ionic-team/ionic-native#3350]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When I run the command 

> ionic cordova build ios --prod

 i get back the following error: 

> FCMPlugin.m:7:9: fatal error: 'Firebase.h' file not found
> #import "Firebase.h"

**Expected behavior:**
The xcode project should be created.

**Steps to reproduce:**
Run the command 

> ionic cordova build ios --prod

**Other information:**
For FCM intagration i use ionic-native/fcm and the cordova-plugin-fcm-with-dependecy-updated plugin (4.4.0).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.3
   @angular-devkit/build-angular : 0.900.3
   @angular-devkit/schematics    : 9.0.3
   @angular/cli                  : 9.0.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.1.0, browser 6.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 11 other plugins)

System:

   NodeJS : v12.13.0 (/home/tdakanalis/.nodenv/versions/12.13.0/bin/node)
   npm    : 6.12.0
   OS     : Linux 4.19
```

**Comment by danielsogl** [comment]
Not related to the ionic wrapper itself. Please open an issue at used plugin repository
