### ISSUE TITLE
Generate custom cordova plugin, but unavailable in ionic 3

### ISSUE THREAD

**Issue by yangguansen** [ionic-team/ionic-native#3352]
**I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

- Download the repo and operate follow the DEVELOPER.md.
- Generate my custom plugin at /dist/@ionic-native/plugins/PLUGIN-NAME.
- Copy the folder to my ionic v3 project  node_modules/@ionic-native/

**Expected behavior:**

- the plugin is available on my phone

**Other information:**

I guess the problem is ionic-native version doesn't compatible with Ionic v3.

**Ionic info:**

```
Ionic:

   Ionic CLI          : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 23 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   Android SDK Tools : 26.1.1 (/Users/tax/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v12.14.1 (/usr/local/bin/node)
   npm               : 6.13.4
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by jcesarmobile** [comment]
it is compatible, you just need to update typescript to 3 and use the ngx import
