### ISSUE TITLE
@ionic-native/document-viewer - broken

### ISSUE THREAD

**Issue by nhhockeyplayer** [ionic-team/ionic-native#3375]
upgraded from version 5.20.0 to 5.23.0
and its broken
cannot open pdf's
breaking changes
been squashed by gradle wrapper studio cordova and ionic plugins build issues 
sorry for lack of detail

I rolled back and moving on

**Comment by djflip2016** [comment]
what was your solution for fixing this?

**Comment by nhhockeyplayer** [comment]
I rolled back
