### ISSUE TITLE
Bundle file is missing in GitHub Releases

### ISSUE THREAD

**Issue by srinidhirao** [ionic-team/ionic-native#3396]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
As per the documentation of ionic native, steps for integrating ionic native in a Vanilla JS app are as follows:
```
Download the latest bundle from the Github releases page.
Include it in index.html before your app's code.
Access any plugin using the global IonicNative variable.
```
Each release in the GitHub releases page (https://github.com/ionic-team/ionic-native/releases) contains a zip file of the source code but not any bundle file. Am I missing something?

**Expected behavior:**
GitHub releases page listing the bundle file which can be included in a JS project.

**Comment by jcesarmobile** [comment]
where are those instructions? 
here it doesn't mention anything about it 
https://ionicframework.com/docs/native/community#vanilla-javascript

**Comment by srinidhirao** [comment]
Its in the readme file of ionic native GitHub:

https://github.com/ionic-team/ionic-native

![Screenshot 2020-05-12 at 7 15 32 PM](https://user-images.githubusercontent.com/9901457/81699450-fda0f700-9484-11ea-815b-1a182f735f5b.png)

**Comment by jcesarmobile** [comment]
I've gone until version 3 and it has never included the distribution code, so not sure why it was documented like that, should be changed
