### ISSUE TITLE
Some cordova plugin not works in browser. What should I do to use these plugins functionality in browser too?

### ISSUE THREAD

**Issue by manojbharti** [ionic-team/ionic-native#3407]
I am using ionic-5, some pluings like cordova plguin facebook4, google etc. are not working in browser for me. Please suggest me what should i do. I want to use their functionality for browser too.

**Comment by jcesarmobile** [comment]
you can mock plugins that don't have web implementation
https://github.com/ionic-team/ionic-native/blob/master/README.md#mocking-and-browser-development-ionicangular-apps-only

or if you want real functionality, first it might not be possible, and if it's possible you can send a pull request to those plugins implementing it
