### ISSUE TITLE
How to integrate two or more google-services.json file in one project using ionic v3

### ISSUE THREAD

**Issue by Bhagirath123** [ionic-team/ionic-native#3409]
i am making one project in ionic v3 i need to integrate one or more fcm project for push notification

Description

project name is example package id is com.example.in

then i am create two fcm project using two different user account using same package id and same project name now i need to integrate that two fcm project in my app how can i implement that can any one help

**Comment by jcesarmobile** [comment]
you can use cordova hooks https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/
