### ISSUE TITLE
Is Ionic 3 compatible with ionic native v5 ?

### ISSUE THREAD

**Issue by ulver2812** [ionic-team/ionic-native#3414]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Using Ionic native v5 with Ionic 3 causes build issue (typescript errors, etc.). It works correctly with ionic native 4.20.0.

**Expected behavior:**
Use Ionic 3 with ionic native 5

**Comment by ulver2812** [comment]
After some research, trial and errors tests, etc. I find out that Ionic 3 is not compatible with Ionic native 5. Ionic 3 works till Ionic native 4.

**Comment by jcesarmobile** [comment]
I just created an Ionic 3 app and updated ionic-native/core to latest 5 and it works

All I had to do was updating typescript to 3 and changing the plugin imports to use the ngx version
