### ISSUE TITLE
InAppBrowser is not asignable to type 'Provider'

### ISSUE THREAD

**Issue by Sunny41** [ionic-team/ionic-native#3415]
**I'm submitting a ...**  (check one with "x")
[ x] bug report

I upgraded to Ionic 5 and used the InAppBrowser. That because iOS isn't accepting the UIWebView of the ThemeableBrowser, but that's another topic that grinds my gears.

Nevertheless, I tried to integrate InAppBrowser instead, like the docs said. 
Installing wasn't that big of a deal but using it in the app.modul.ts. 
I imported the plugin with 
```import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';```

and 

```import { InAppBrowser } from '@ionic-native/in-app-browser';```

nothing seems to help. 

Version: 
@ionic-native/in-app-browser@5.25.0

Error Code: 
```
Type 'InAppBrowserOriginal' is not assignable to type 'Provider'.
  Type 'InAppBrowserOriginal' is missing the following properties from type 'FactoryProvider': provide, useFactoryts(2322)
```

Ionic Info:

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a
```

**Comment by zero-1** [comment]
in app.module.ts ... try doing 

`import { InAppBrowser } from '@ionic-native/in-app-browser/ngx/index';`

seems like a duplicate of https://github.com/ionic-team/ionic-native/issues/3518
