### ISSUE TITLE
Support for cordova-plugin-purchase@10.1.2

### ISSUE THREAD

**Issue by remisture** [ionic-team/ionic-native#3422]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

Support the latest release:

> Add promise-like return value to store.refresh
> store.refresh() now returns a promise-like object with the following functions:
> 
> .completed(fn) - Calls fn when the queue of previous purchases have been processed. At this point, all previously owned products should be in the approved state.
> .finished(fn) - Calls fn when all purchased in the approved state have been finished or expired.

Ref. https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v10.1.2

**Comment by danielsogl** [comment]
Pull requests are welcome :)
