### ISSUE TITLE
Error: using ionic Command task for version 6.6.0 fails on Azure DevOps pipeline

### ISSUE THREAD

**Issue by maluthbadugecara** [ionic-team/ionic-native#3427]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

I am trying to build my ionic app using MS Azure DevOps pipelines. The task fails when using Ionic version 6.6.0 but works fine when version 5.4.14 is used.

Seems like the task fails when the installation command is issued in the host machine (Mac).

**Current behavior:**
Information:

Extract from build YAML:

#Ionic Commands

– task: IonicCommand@1

inputs:

ionicCommand: ‘build’

ionicVersion: ‘6.6.0’

cordovaVersion: ‘8.1.2’

**Expected behavior:**
Ionic installation should work and build should go ahead without an issue

**Steps to reproduce:**
Create an Azure DevOps pipeline build and use IonicCommand Task in the YAML.
Use the command Ionic Build with Ionic version 6.6.0 (Anything higher than 5.4.14)
Run the pipeline.
Notice the error.
----------------------------------
/Users/runner/.taco_home/node_modules/cordova/8.1.2/node_modules/cordova Module cache at /Users/runner/.taco_home/node_modules Installing ionic@6.6.0 to /Users/runner/.taco_home/node_modules/ionic/6.6.0. (This may take a few minutes.) Command failed: npm install --force ionic@6.6.0 2>&1

**Other information:**
I think the install command syntax is wrong. It should be :

npm install --force @ionic/cli@6.6.0
and NOT

npm install --force ionic@6.6.0

From What I have seen, Ionic has changed package naming in the latest version:

Link:

https://ionicframework.com/docs/intro/cli.

Appreciate a fix.

However, there is a workaround for this, which is to use the plain old CmdLine task, combined with a custom NPM task. i.e: NPM task to install ionic cli with correct command syntax and CmdLine task to build using the ionic build.

Thanks

**Comment by danielsogl** [comment]
This issue has nothing to do with this repo.
