### ISSUE TITLE
Ionic 6 LaunchNavigator Plugin problem

### ISSUE THREAD

**Issue by mahmoudsaghir** [ionic-team/ionic-native#3436]
I followed the steps for the LaunchNavigator plugin in this link https://ionicframework.com/docs/native/launch-navigator/ step by step.
But i faced this problem at launchNavigator.navigate

TypeError: Object(...) is not a function
at LaunchNavigator.navigate

I am using the following plugin :
"@ionic-native/launch-navigator": "^5.26.0"
And i am using cordova 9.0.0 (cordova-lib@9.0.1).

**Comment by Ng-India99** [comment]
Same issue, did you find the solution ?

**Comment by mahmoudsaghir** [comment]
not yet
