### ISSUE TITLE
Firebase Crashlytics Android build error on Capactior

### ISSUE THREAD

**Issue by lucsbonifacio** [ionic-team/ionic-native#3446]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm currently working with Ionic and Capacitor. When installing the [Firebase Crashlytics](https://ionicframework.com/docs/native/firebase-crashlytics) plugin, I'm unable to build the Android project, with the error:

```
A problem occurred configuring project ':capacitor-cordova-android-plugins'.
> groovy.lang.MissingPropertyException: Could not get unknown property 'assemble' for task ':capacitor-cordova-android-plugins:assembleDebug' of type org.gradle.api.Task.
```

**Expected behavior:**

I expect to be able to build the Android project after installing the Firebase Crashlytics plugin using Ionic 5 with Capacitor.

**Steps to reproduce:**

- Create a project using Ionic 5 and Capacitor;
-  Follow the installation proposed on the [plugin page](https://ionicframework.com/docs/native/firebase-crashlytics);
- Run the Android project on the emulator.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.9.2 (/Users/lucasbonifacio/.nvm/versions/node/v12.0.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic 3.1.3, cordova-plugin-ionic-wkwebview-engine 1.1.4, (and 23 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   ios-sim    : 8.0.2
   NodeJS     : v12.0.0 (/Users/lucasbonifacio/.nvm/versions/node/v12.0.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
```

**Comment by skibaalex** [comment]
You can just remove this block of code and it runs

**Comment by ugald80** [comment]
Sorry @skibaalex, I didn't get it. Which block of code has to be removed?

**Comment by ethanwu155** [comment]
I would like to know as well as I am running into this issue too.
