### ISSUE TITLE
allow to open specific app setting page

### ISSUE THREAD

**Issue by keshavkhatri** [ionic-team/ionic-native#3448]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
plugin does not allow to open settings page of specific app

**Expected behavior:**
i want a feature where i give the package name and it opens settings page of that app where user can see its info and uninstall also

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by rgustavsson** [comment]
@keshavkhatri, there's actually a way of doing this already:

`await this.openNativeSettings.open('application_details')`

**Comment by keshavkhatri** [comment]
@rgustavsson this will open the app settings of the app from which you are calling this function
i have requested for a feature that will let me open settings page of a different app for example i want to open settings page of facebook from my ionic app in that case this one is not useful
