### ISSUE TITLE
Property 'addTrigger' does not exist on type 'OneSignal'.

### ISSUE THREAD

**Issue by rafaneri** [ionic-team/ionic-native#3449]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Property 'addTrigger' does not exist on type 'OneSignal'.

**Expected behavior:**
Can use addTrigger OneSignal function on the OneSignal provider

**Steps to reproduce:**
```
// Call this method
this.oneSignal.addTrigger
```

**Related code:**

```
this.oneSignal.addTrigger
```

**Other information:**
Ionic 5

**Comment by samuelawal** [comment]
I am having the same issue
Please assist
