### ISSUE TITLE
 Private plugins in Ionic

### ISSUE THREAD

**Issue by xdvarpunen** [ionic-team/ionic-native#3462]
-

**Comment by xdvarpunen** [comment]
-

**Comment by xdvarpunen** [comment]
Is it possible to develop cordova plugins with ionic-wrappers that are not part of this repository just like how cordova plugins work?

Reference online: https://forum.ionicframework.com/t/is-it-possible-to-use-a-private-standalone-ionic-native-wrapper/107282

**Comment by xdvarpunen** [comment]
Looks like capacitor has no issues with developing private plugins: https://capacitor.ionicframework.com/docs/plugins/#how-capacitor-plugins-work

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native-google-maps

`@ionic-native/google-maps` plugin is member of `@ionic-native` plugins, but it's not under this repository.
The plugin spin outed, and under my control.

So, yes, you can create own private plugin.
`@ionic-native` plugin is just a wrapper plugin for a cordova plugin.

It means if you create a cordova plugin using `TypeScript`, you don't need to create a wrapper plugin.

**Comment by xdvarpunen** [comment]
@wf9a5m75 Thanks! I got it now. There is 4 different ways of creating plugins that are importable to Ionic:

1. `plugman` generated Cordova plugin with types for TypeScript
2. Ionic-Native public repository based Cordova plugin(1) wrapper
3. Ionic-Native repository fork with single or more Cordova plugin(1) wrapper renamed as own (this makes it unique and private)
4. Capacitor CLI generated plugin

1,2, and 3 are for Cordova based projects and 4 is for Capacitor based project.
