### ISSUE TITLE
iOS splashscreen.hide() not compatible with cordova-ios >= v6

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-native#3472]
**I'm submitting a ...**  (check one with "x")
[X] feature request

**Current behavior:**
With Cordova iOS v6 release, the splashscreen has been move into its [core](https://cordova.apache.org/news/2020/06/13/plugins-release.html).

For that reason, I  suppose, `splashscreen.hide()` has no effect anymore.

**Expected behavior:**
`splashscreen.hide()` compatible with cordova-ios v6

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : 1.0.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v14.4.0 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c

**Comment by dcarvajal7** [comment]
Same issue here. Tested with cordova-ios 6.1.1

**Comment by maximo72** [comment]
Same here, 6.1.1

**Comment by federufino** [comment]
Same...

**Ionic info:**
Ionic:

   Ionic CLI                     : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 11.0.1
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 7 other plugins)

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.1 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 12.2 Build version 12B45b

**Comment by sametacar** [comment]
same here.

**Comment by rbarriuso** [comment]
Is this a problem of Ionic Native or the plugin itself? Perhaps you need to open an issue at https://github.com/apache/cordova-plugin-splashscreen/

**Comment by sametacar** [comment]
it is a plugin bug I believe. After platform ready system looks to SplashScreenDelay value in config for > cordova-ios 6. 
so yes, it means splashScreen.hide() is not working actually. 

for now, I've changed the value of SplashScreenDelay like that, 
<preference name="SplashScreenDelay" value="300" />

it's not a solution, but it saves the day

**Comment by rbarriuso** [comment]
Thanks @sametacar . Actually the behavior of the plugin doesn’t seem so odd. It seems that the splash screen plugin on iOS waits for `SplashScreenDelay` every time `show()` or `hide()` are called. Knowing that, it's easy to decrease the timeout when you want to call `hide()` from your code.
