### ISSUE TITLE
InAppPurchase2 Doesn't Recognize store.refresh().finished()

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/ionic-native#3480]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When using the latest version of the InAppPurchase 2 Plugin the documentation references 
store.refresh().finished() but when using the native Ionic Plugin it says that it doesn't exists. 
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storerefresh

**Expected behavior:**
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storerefresh
I would expect that I could access the store.refresh().finished() method in the Ionic Native Plugin.

**Comment by AbhishekJ01** [comment]
Did you find the solution for this ? I'm still not able to use 'store.refresh().finished()'.

Please help. @j3k0

**Comment by Filipki** [comment]
You can try something like 
`(store.refresh() as any).finished(() => { ... }); `

**Comment by j3k0** [comment]
I pushed a commit with the added typings, you can test by installing the plugin from the git repo
