### ISSUE TITLE
Diagnostics: New location accuracy authorization API

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic-native#3488]
**I'm submitting a ...**
[x] feature request

**Current behavior:**

The cordova-diagnostics Plugin added a Function for the new ios14 location accuracy authorization API: https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/CHANGELOG.md

**Expected behavior:**

Please add all added Functions to the ionic-native Wrapper as soon as possible

**Comment by angelofan** [comment]
I am also waiting for the support of `@ionic-native/diagnostic`!

**Comment by angelofan** [comment]
Is there any progress?

**Comment by angelofan** [comment]
Before @ionic-native/diagnostic is updated, the plugin can be called like this:
```
declare let cordova: any;

cordova.plugins.diagnostic.getLocationAccuracyAuthorization((accuracy)=>{
  console.log(accuracy);
},(err)=>{
  console.log(err);
});
```

**Comment by angelofan** [comment]
Is there waiting for anyone send a pull request, or waiting for ionic team to change?

This code file looks like it was automatically generated by a program.

**Comment by HansKrywaa** [comment]
Closed as my pr is merged
