### ISSUE TITLE
CleverTap methods missing from index.d.ts

### ISSUE THREAD

**Issue by darshanclevertap** [ionic-team/ionic-native#3491]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Current plugin version missing `showInbox()`, `initializeInbox()` methods in the `index.d.ts` file imported by the Ionic App

**Expected behavior:**
The above methods should be present as per the `index.ts` file [given here](https://github.com/ionic-team/ionic-native/blob/master/src/@ionic-native/plugins/clevertap/index.ts)

**Steps to reproduce:**
Add the CleverTap dependency using the documentation [given here](https://ionicframework.com/docs/native/clevertap)

**Other information:**
This is a major feature of CleverTap and our clients using Ionic cannot use this.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI          : 5.4.15 (/Users/darshan/.nvm/versions/node/v12.14.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms: android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/darshan/Library/Android/sdk)
   NodeJS            : v12.14.1 (/Users/darshan/.nvm/versions/node/v12.14.1/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
```

Please let us know if there's something missing from our side to make this work.

**Comment by darshanclevertap** [comment]
Any help here?

**Comment by danielsogl** [comment]
Feel free to create a PR. This repo is driven by the community

**Comment by darshanclevertap** [comment]
@danielsogl If you could kindly expedite the merging of the PR, it would be of great help 🙏
