### ISSUE TITLE
Barcode Scanner Bug

### ISSUE THREAD

**Issue by Stefan-Behrendt** [ionic-team/ionic-native#3493]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
When I try to import and inject the BarcodeScanner in my `barcode.service.ts`, [as explained in the official documentation](https://ionicframework.com/docs/native/barcode-scanner#usage), I get the following error message:

```
'BarcodeScanner' refers to a value, but is being used as a type here. Did you mean 'typeof BarcodeScanner'? ts(2749)
```

It doesn't matter which import I use, whether `'@ionic-native/barcode-scanner'` or `'@ionic-native/barcode-scanner/ngx'`, the error message is identical. Moreover, the file `index.d.ts` located at *node_modules/@ionic-native/barcode-scanner/ngx* is not referenced correctly in Visual Studio Code: If you follow the import declaration, it moves to *node_modules/@ionic-native/barcode-scanner/index.d.ts* instead, which is located one directory above.

When I try to inject `BarcodeScannerOriginal` instead of `BarcodeScanner`, the code looks properly but when executing `ng serve`, it throws the following error messages:

```
ERROR in ./src/app/services/remote/barcode.service.ts 37:136-161
"export 'BarcodeScannerOriginal' (imported as 'i2') was not found in '@ionic-native/barcode-scanner/ngx'

ERROR in ./src/app/services/remote/barcode.service.ts 47:63-88
"export 'BarcodeScannerOriginal' (imported as 'i2') was not found in '@ionic-native/barcode-scanner/ngx'
```
**Expected behavior:**
The Barcode Scanner should be injectable as a provider in my `barcode.service.ts` as described in the official documentation:

```
import { BarcodeScanner } from '@ionic-native/barcode-scanner/ngx';

constructor(private barcodeScanner: BarcodeScanner) { }
```

**Steps to reproduce:**
`ng generate service barcode`

Then, copy the following code into the service:

```
import { BarcodeScanner } from '@ionic-native/barcode-scanner/ngx';

constructor(private barcodeScanner: BarcodeScanner) { }
```

and run `ng serve`.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1000.4
   @angular-devkit/schematics    : 10.0.4
   @angular/cli                  : 10.0.4
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (3 plugins total)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.3.0

System:

   ios-deploy : 1.9.4
   NodeJS     : v12.16.1 (/usr/local/bin/node)
   npm        : 6.14.7
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
```

**Comment by teamstratos** [comment]
Did someone find a solution for this? I am having the same issue when importing the scanner in to core module. It only works when importing into feature modules.

**Comment by SparkFountain** [comment]
Our solution was to add the Barcode Scanner in `app.module.ts` and to import the Scanner itself from the "ngx" subfolder.

```
// app.module.ts

import { BarcodeScanner } from '@ionic-native/barcode-scanner/ngx';
// ...

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    // ...
  ],
  providers: [
    StatusBar,
    SplashScreen,
    BarcodeScanner,  // <-- here we go
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

```
// barcode.service.ts

import { Injectable } from '@angular/core';
import { BarcodeScanner, BarcodeScanResult } from '@ionic-native/barcode-scanner/ngx';  // <-- regard the "ngx"
import { from, Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { BarCodeData } from 'settings/bar-code-data';

@Injectable({
  providedIn: 'root',
})
export class BarcodeService {
  constructor(private barcodeScanner: BarcodeScanner) {}

  getBarcode$(): Observable<BarCodeData[]> {
    return from(this.barcodeScanner.scan()).pipe(
      map((data: BarcodeScanResult) => {
        return JSON.parse(data.text) as BarCodeData[];
      })
    );
  }
}
```

**Please note:** We use Visual Studio Code for development and had an issue when trying to jump into the BarcodeScanner declaration file. For some strange reason, it always referred to the "index.d.ts" file one level above the actual definition scope. However, we could only fix this problem by deleting the entire _node_modules_ folder, as well as the _package-lock.json_ file.
