### ISSUE TITLE
Ionic native - Email Composer plugin not supporting params for request and check permission 

### ISSUE THREAD

**Issue by maniya108** [ionic-team/ionic-native#3499]
**Ionic native Email composer plugin not supporting params for request and check permission **  (v5.27.0)

**Current behavior:**
Ionic native Email composer plugin not supporting parameters for request and check permission method

**Expected behavior:**
It should ask parameter variable for requestPermission() and hasPermission() method

**Steps to reproduce:**
I will try to request and check the permission but it throwing callbackId error.

**Related code:**

Ionic native code
------------------
export declare class EmailComposer extends IonicNativePlugin {

    hasPermission(): Promise<boolean>;
    requestPermission(): Promise<boolean>;
}

In Android Plugin
-----------------
       if("open".equalsIgnoreCase(action)) {
            open(args.getJSONObject(0));
        } else if ("check".equalsIgnoreCase(action)) {
            **check(args.optInt(0, 0));**
        } else if ("request".equalsIgnoreCase(action)) {
            **request(args.optInt(0, 0));**
        }  else {
            return false;
        }

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : macOS Catalina
```

**Comment by maniya108** [comment]
Please fix ASAP

**Comment by Belligerator** [comment]
This is still the issue.
