### ISSUE TITLE
InAppBrowser's executeScript causes an unsafe eval error only in the case of ionic-native.

### ISSUE THREAD

**Issue by nrikiji** [ionic-team/ionic-native#3515]
**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
When executing InAppBrowser's executeScript via ionic-native, the following error occurs.
Calling the plugin directly without using Ionic-native will not cause this error.

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'
```

**Steps to reproduce:**
"@ionic-native/core": "^5.23.0"
"@ionic-native/in-app-browser": "^5.23.0"

**Related code:**

Success
```
const browser = window.open(url, '_blank', options);
browser.addEventListener('loadstop', event => {
  const code = "(function() { " + 
    "alert('test!!');"
  "})();"
  browser.executeScript({ code: code });
});
```

Error
```
const browser = this.iab.create(url, '_blank', options);
browser.on('loadstop').subscribe(event => {
  const code = "(function() { " + 
    "alert('test!!');"
  "})();"
  browser.executeScript({ code: code });
});
```

**Comment by WouterWidgets** [comment]
@nrikiji did you manage to fix this somehow, using the ionic native wrapper?

Cheers, Wouter

**Comment by Xiad32** [comment]
Just wondering if this was resolved elsewhere. Still seeing the same error here.
