### ISSUE TITLE
Type 'InAppBrowserOriginal' is not assignable to type 'Provider' in ionic5 with inappbrowser plugin

### ISSUE THREAD

**Issue by kalandher** [ionic-team/ionic-native#3518]
**I'm submitting a ...**  (check one with "x")
[ ] bug report

Type 'InAppBrowserOriginal' is not assignable to type 'Provider'.
Type 'InAppBrowserOriginal' is missing the following properties from type 'FactoryProvider': provide, useFactoryts(2322)

**Related code:**

Error after upgrading to ionic 5.4.16, cordova 10.0.0.

```
import { InAppBrowser } from ‘@ionic-native/in-app-browser/ngx’;
```
and added

InAppBrowser to providers array in app.module.ts

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
`Ionic:

Ionic CLI : 5.4.16 (C:\Users\ks1162\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 5.3.1
@angular-devkit/build-angular : 0.901.12
@angular-devkit/schematics : 9.1.12
@angular/cli : 9.1.12
@ionic/angular-toolkit : 2.3.1

Cordova:

Cordova CLI : 10.0.0
Cordova Platforms : android 9.0.0
Cordova Plugins : no whitelisted plugins (1 plugins total)

Utility:

cordova-res : not installed
native-run : not installed

System:

NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
npm : 5.6.0
OS : Windows 10`
```

**Comment by zero-1** [comment]
in app.module.ts ... try doing 

`import { InAppBrowser } from '@ionic-native/in-app-browser/ngx/index';`
