### ISSUE TITLE
Error: Invalid provider for the NgModule 'AppModule' - only instances of Provider and Type are allowed, got

### ISSUE THREAD

**Issue by Leo1305Pineda** [ionic-team/ionic-native#3520]
**I'm submitting a ...**  (check one with "x")
[x] bug report

Error to inject provide FileTransfer in app.module.

package.json
```
"dependencies": {
    "@ionic-native/file-transfer": "^5.28.0",
    "cordova-plugin-file-transfer": "^1.7.1",
}
```

app.module.ts
```
import { FileTransfer } from '@ionic-native/file-transfer/ngx';
providers: [
        FileTransfer,
]
```

ionic info

![image](https://user-images.githubusercontent.com/12752959/91709975-85ecfa00-eb51-11ea-804c-03a60080048a.png)

inspect console device

![image](https://user-images.githubusercontent.com/12752959/91709438-c4ce8000-eb50-11ea-8c7c-fc025b5fa32c.png)

**Comment by HMMApps** [comment]
the same issue HERE !! 
is there any solution ??

**Comment by fathanyr** [comment]
Is there any solution? i have the same issue

**Comment by picolo74** [comment]
> Is there any solution? i have the same issue

Check that the import is correct : 

import {BackgroundMode} from '@ionic-native/background-mode/ngx';

add /ngx if needed.

**Comment by jayantpaliwal** [comment]
@picolo74 checked all imports, not worked for me.

**Comment by paulosllvn** [comment]
ANY UPDATE ON THIS?

**Comment by nileshbandekar** [comment]
I have copied and pasted the folder, and it created a new "folder's name - copy" and it just worked.

It was, most likely, a problem with how the libraries got installed I hope that helps

**Comment by Seth-Know** [comment]
In my case I just deleted the node_modules & package-lock.json then ran `npm install` to reinstall everything.
