### ISSUE TITLE
Property 'coords' does not exist on type Geoposition

### ISSUE THREAD

**Issue by ilclaudio** [ionic-team/ionic-native#3525]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
after updating the Geolocation plugin in a Ionic4/Cordova app, I have this error:

[ng]   Property 'coords' does not exist on type 'PositionError'.
[ng] ...: error TS2339: Property 'coords' does not exist on type 'Geoposition | PositionError'.
I have always used the plugin in this way:

this.geolocation.watchPosition(geo_options)
      .subscribe(position => {
          this.currentLatitude = position.coords.latitude;
          this.currentLongitude = position.coords.longitude;
The Cordova plugin and the Ionic module are:

cordova-plugin-geolocation 4.0.2 "Geolocation"
"@ionic-native/geolocation": "^5.28.0",

**Expected behavior:**

No errors

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

I think there is a problem with the version 5.28.0 of the Ionic native module, because with this one the app works well:
npm install @ionic-native/geolocation@5.27.0

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 5.4.10
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 21 other plugins)

Utility:

   cordova-res : 0.11.0 (update available: 0.15.0)
   native-run  : 0.2.2 (update available: 1.0.0)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v12.16.3 
   npm               : 6.14.4
   OS                : Windows 10
```

**Comment by rapropos** [comment]
I think this is working as intended, see #3303. What I would do is test for the presence of either `coords` or `code` to determine whether I have a `Geoposition` or a `PositionError`, as either are potentially coming at you on the same road.

**Comment by StevieApp** [comment]
This solves the whole issue
```
let watch = this.geolocation.watchPosition().subscribe(position => {
      if ((position as Geoposition).coords != undefined) {
        var geoposition = (position as Geoposition);
        console.log('Latitude: ' + geoposition.coords.latitude + ' - Longitude: ' + geoposition.coords.longitude);
      } else { 
        var positionError = (position as PositionError);
        console.log('Error ' + positionError.code + ': ' + positionError.message);
    }
```
