### ISSUE TITLE
In App Purchase 2 doc shows the wrong npm package in installation instructions and does not reflecting the latest changes in the plugin API

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-native#3554]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**

The In App Purchase 2 doc (https://ionicframework.com/docs/native/in-app-purchase-2) shows the wrong npm package.
It shows ***cc.fovea.cordova.purchase*** while it must be ***cordova-plugin-purchase***

@ionic-native/in-app-purchase-2 is also not reflecting the latest changes in the plugin API.

**Expected behavior:**

The doc must show the right package name
For example,
```
npm install cordova-plugin-purchase
```
and @ionic-native/in-app-purchase-2 should reflecting the latest changes in the plugin API.

**Steps to reproduce:**

N/A

**Other information:**

See installation instruction at https://github.com/j3k0/cordova-plugin-purchase

**Comment by rodrigograca31** [comment]
@danielsogl This issue should not have been closed.

This is still an issue, the code was updated but the documentation wasn't.
Namely: 
1. Here: https://ionicframework.com/docs/native/in-app-purchase-2
2. and here: https://ionicframework.com/docs/v3/native/in-app-purchase-2/

Maybe the v3 one can stay? but the other one has to be updated.
