### ISSUE TITLE
cordova-plugin-ble-central no longer working with @ionic/ble 5.28.0 or 5.29.0

### ISSUE THREAD

**Issue by ASHBAW** [ionic-team/ionic-native#3559]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
I write a packet of data to a device using the cordova-plugin-ble-central. I receive a notification back. I read the notification and alway receive two byte of 0x00 back.

**Expected behavior:**
With @ionic/ble version 5.27.0 and earlier I receive the expected data back in the notification.

**Steps to reproduce:**

**Related code:**
// this send a packet of data to the device
```
this.ble.write(this.deviceId,id, characteristics.message, packet);

// get notification and validate data
 this.ble.startNotification(this.deviceId, hickory.id, hickory.characteristics.dataReady)
      .subscribe(rx => this.receive(rx), error => this.rejectTransaction(error));

 receive(rxPacket: ArrayBuffer) {
   log('rx', rxPacket);
   // validate rxPacket here - always receive ArrayBuffer of size 2 - [0x00, 0x00]
 }
```

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.13
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 11 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.2) : 1.1.0

System:

   ios-sim : 8.0.2
   NodeJS  : v12.18.3 (/Users/lester2/.nvm/versions/node/v12.18.3/bin/node)
   npm     : 6.14.8
   OS      : macOS Catalina
   Xcode   : Xcode 12.0.1 Build version 12A7300

**Comment by ASHBAW** [comment]
The **destruct: true** was added into 5.28.0. This breaks notifications. If I set this to false or remove it notifications work.

Can you set this to false or remove it like it was in  5.27.0 in the next release?

```
  @Cordova({
    observable: true,
    destruct: true, <= NOTIFICATIONS NO LONGER WORK WITH THIS, IF SET TO FALSE OR REMOVE THEY WORK
    clearFunction: 'stopNotification',
    clearWithArgs: true,
  })
  startNotification(deviceId: string, serviceUUID: string, characteristicUUID: string): Observable<any> {
    return;
  }
```

**Comment by jrobeson** [comment]
@ASHBAW : if that's the case, can you submit a PR? It's likely to get more notice than an issue.
