### ISSUE TITLE
allow passing params to fingerprint-aio

### ISSUE THREAD

**Issue by khaledosman** [ionic-team/ionic-native#3568]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
fingerprint-aio doesn't support passing params/options for `isAvailable()` call

**Expected behavior:**
the plugin supports params/options like `allowBackup` to check for backup auth methods such as passcode if biometric is not supported https://github.com/niklasmerz/cordova-plugin-fingerprint-aio#optional-parameters

**Comment by lucianojs** [comment]
miss param `confirmationRequired` too for the options in the other methods.

https://github.com/niklasmerz/cordova-plugin-fingerprint-aio#optional-parameters-1
