### ISSUE TITLE
Cordova AppRate config method has been changed

### ISSUE THREAD

**Issue by petrot** [ionic-team/ionic-native#3576]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
With the current version of the ionic plugin, the `this._appRate.preferences = {...}` does not update the preferences.
The cordova plugin has been changed, the current method is `setPreferences()`

**Expected behavior:**
Preferences can be updated.

**Comment by DorianLovera** [comment]
+1 the appRate cordova plugin updated supporting the android in app rating. The Ionic wrapper update is needed for us to use this new feature.

**Comment by ma77hi4s** [comment]
+1

**Comment by jcesarmobile** [comment]
should be fixed by https://github.com/ionic-team/ionic-native/pull/3598
