### ISSUE TITLE
Background-mode does not work with VueJS without angular/core package

### ISSUE THREAD

**Issue by dcyou** [ionic-team/ionic-native#3605]
**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Current behavior:**

I have to install the angular/core package to use the background-mode feature describe here
https://ionicframework.com/docs/native/background-mode

**Expected behavior:**

do not install angular/core for a VueJS project or update the documentation and explain why we need that package

**Steps to reproduce:**

follow the current documentation here with a VueJS project
https://ionicframework.com/docs/native/background-mode

**Related code:**
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/background-mode/index.ts#L1

**Other information:**

```
ERROR  Failed to compile with 1 error                                                                                                                                                                                                     2:09:52 PM

This dependency was not found:

* @angular/core in ./node_modules/@ionic-native/background-mode/ngx/index.js

To install it, you can run: npm install --save @angular/core
```

**Comment by Gaby-alogo** [comment]
Up+1

Same issue here.

**Comment by dcyou** [comment]
FYI including that lib trigger a warning related to:
https://github.com/angular/angular/issues/21560 and break the external hot reload

**Comment by dcyou** [comment]
to unbreak the external hot reload:
I added those two stuff in my Webpack configuration:
https://github.com/angular/angular/issues/21560#issuecomment-433601967
https://github.com/angular/angular/issues/20357#issuecomment-392266272

but still a ugly workaround...
