### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by KrisVanHoye** [ionic-team/ionic-native#3617]
**I'm submitting a issue IONIC REACT**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Install Taptic Engine:
1. npm install @ionic-native/core
2. ionic cordova plugin add cordova-plugin-taptic-engine
3. npm install @ionic-native/taptic-engine

**Expected behavior:**
jest should still work fine after installing plugins for Capacitor

**Steps to reproduce:**
Install the Taptic Engine pluging for Capacitor

Run:
npm test

Output:
C:\WorkSpace\David\node_modules\@ionic-native\taptic-engine\index.js:14
    import { IonicNativePlugin, cordova } from '@ionic-native/core';

SyntaxError: Cannot use import statement outside a module

**Related code:**
import { TapticEngine } from '@ionic-native/taptic-engine'
import PlatformService from './platformService'

export const TapticService = () => {
    const { supportTaptic } = PlatformService()

    const selection = () => {
        if (supportTaptic()) {
            TapticEngine.selection();
        }
    }

    const notifySuccess = () => {
        if (supportTaptic()) {
            TapticEngine.notification({ type: 'success' })
        }
    }

    const notifyWarning = () => {
        if (supportTaptic()) {
            TapticEngine.notification({ type: 'warning' })
        }
    }

    return { selection, notifySuccess, notifyWarning}
}

**Other information:**
On the internet I found some related info with following proposal:
Add extra config to jest.config.json or to package.json:

  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|@ionic-native|@ionic)"
    ]
  },

I  my case it does not help, other Jest related errors comes up.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Ionic:

   Ionic CLI       : 6.12.0 (C:\Users\kvh\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.2
   native-run  : not installed

System:

   NodeJS : v14.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

**Comment by Elardzhi** [comment]
I have the same issue

**Comment by tgeorgiadis** [comment]
Same issue here

**Comment by Muhammad-Bilal-7896** [comment]
Same issue any clue please let me knwo
