### ISSUE TITLE
Hide Safari view controller Hide URL in ionic v4

### ISSUE THREAD

**Issue by Naveendodda** [ionic-team/ionic-native#3634]
How to hide URL BAR IN SAFARI VIEW CONTROLLER plugin by using Ionic

![Simulator Screen Shot - iPhone 11 - 2021-03-05 at 14 04 59](https://user-images.githubusercontent.com/54097808/110310499-a1691e00-8028-11eb-82b2-934509488cb2.png)

**Comment by jcesarmobile** [comment]
You can't, Safari View Controller don't allow to hide the bars.

**Comment by Naveendodda** [comment]
Thank you . we want hide tool bar i.e url and done buttons Only

**Comment by jcesarmobile** [comment]
It’s not possible

**Comment by Naveendodda** [comment]
Each and every plugin we can customize right ?why it 's not possible please explain little bit clear

**Comment by jcesarmobile** [comment]
Because Apple doesn't allow to hide the bars of the Safari View Controller, I don't know why, ask Apple

**Comment by Naveendodda** [comment]
In android how to hide toolbar
