### ISSUE TITLE
Problem with @ionic-native/bluetooth-serial (5.32) and Android 11 when scanning new bluetooth device

### ISSUE THREAD

**Issue by fralicca** [ionic-team/ionic-native#3650]
When I scan new bluetooth devices with **discoverUnpaired** I don't get any results.
This issue does not occur with Android 10 (or earlier) versions.

I thank you in advance.

**Comment by FractalMind** [comment]
Any news on this?

**Comment by michael-batoon-magneds** [comment]
No solution for this?

**Comment by FractalMind** [comment]
> No solution for this?

Check out this post: https://forum.ionicframework.com/t/black-screen-on-android-12/224116
