### ISSUE TITLE
Cordova Plugin Lottie splashscreen Crashed the  ionic app

### ISSUE THREAD

**Issue by Mani-VD** [ionic-team/ionic-native#3679]
**I'm submitting a  bug report
Ionic app build not running in android device as expected. It crashed the default splashscreen which in consequence app crash occurs

**Current behavior:**
Even App's default splashscreen not showing and app kills itself.

**Expected behavior:**
Requires Lottie JSON load to open a graphical spashscreen

**Steps to reproduce:**
Expecting to roll back default splashscreen's behaviour on unlinking lottie splashscreen. Note(Lottie splashscreen also not working)

**Other information:**
ionic-cli version 6.14.
android build tools 25+

**Comment by andalike** [comment]
I was missing the documentation and this was what i added later.(in config.xml file under Android)

 <preference name="AndroidXEnabled" value="true" />
  <preference name="GradlePluginKotlinEnabled" value="true" />
