### ISSUE TITLE
trying to add ibeacon support to ionic vue /capacitor app 

### ISSUE THREAD

**Issue by sdetweil** [ionic-team/ionic-native#3685]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

using doc here
https://ionicframework.com/docs/native/ibeacon

the @ionic-native/ibeacon/ngx/index,js

references @angular (line2) 
```
import { Injectable } from '@angular/core';
```
and later 
```
    IBeacon.decorators = [
        { type: Injectable }
    ];
```
and @ionic-native/core not in dependencies, but used on line 3. 
```
import { IonicNativePlugin, cordova, checkAvailability } from '@ionic-native/core';
```

**Comment by jcesarmobile** [comment]
Sadly the ionic native docs are still very angular centric, there is little information about how to use it with other frameworks. Mostly this https://ionicframework.com/docs/native/community

You can see there that ngx imports are for angular only, so if not using angular don’t include the ngx in the import.
