### ISSUE TITLE
Error 'Plugin-Version' of 'unspecified' for 'com.android.build.gradle.LibraryPlugin@139d3994' is not a valid version number

### ISSUE THREAD

**Issue by mivewi** [ionic-team/ionic-native#3688]
**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
When using gradlew bundleRelease I get the errors:

```
> Configure project :capacitor-cordova-android-plugins
Error 'Plugin-Version' of 'unspecified' for 'com.android.build.gradle.LibraryPlugin@139d3994' is not a valid version number

> Configure project :app
Error 'Plugin-Version' of 'unspecified' for 'com.android.build.gradle.AppPlugin@5347c145' is not a valid version number 
OneSignal Warning: Could not get AGP plugin version
google-services.json not found, google-services plugin not applied. Push Notifications won't work
```

**Expected behavior:**
Build was without errors.

**Steps to reproduce:**
From a fresh new app with no other plugins added:
1. ionic build --prod
2. ionic cordova plugin add onesignal-cordova-plugin
3. npm install onesignal-cordova-plugin
4. npx cap sync
5. npm install onesignal-cordova-plugin
6. npx cap sync
7. cd android && gradlew bundleRelease

**Other information:**
Other people are having the same issue, with no solution yet:
https://stackoverflow.com/questions/67678333/error-plugin-version-of-unspecified-for-com-android-build-gradle-appplugin

**Ionic info:**

 ```
Ionic:
   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.4.0        
   @angular-devkit/build-angular : 12.0.3
   @angular/cli                  : 12.0.3
   @ionic/angular-toolkit        : 2.3.3

Capacitor:
   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.7

Cordova:
   Cordova CLI       : not installed
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:
   cordova-res : 0.15.3
   native-run  : 1.4.0

System:
   Android SDK Tools : 26.1.1 (C:\Users\mivew\AppData\Local\Android\Sdk)
   NodeJS            : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.10
   OS                : Windows 10
```

Onesignal versions:
"@ionic-native/onesignal": "^5.31.1"
"onesignal-cordova-plugin": "^2.11.4"

**Comment by gelinger777** [comment]
@danielsogl  why you are closing issue without even answering to it? Because github-actions closed it due to your inactivity? 
fantastic logic!

**Comment by danielsogl** [comment]
@gelinger777 feel free to create a pull request. This repository is driven by the community. I only manage pull requests.

**Comment by gelinger777** [comment]
@danielsogl I apologize. I thought Ionic is a real company and keeps plugins updated etc.

**Comment by mivewi** [comment]
> @danielsogl I apologize. I thought Ionic is a real company and keeps plugins updated etc.

@gelinger777  I think I also need to apologise for the misleading thread. I just realized I made this thread in the ionic team, not the onesignal, the company which is the ones that is responsible for the plugin.

**Comment by danielsogl** [comment]
@gelinger777 this repo is maintained by ionic (or better me) but we are not developing plugin wrappers because there are hundreds of them. I do this in my free time without getting payed for :) Only enterprise plugins and capacitor core plugins are developed by the ionic-team.

**Comment by gelinger777** [comment]
@danielsogl  thank you for your clearification and  your contributions.

**Comment by AbdullahKhan780** [comment]
I'm also getting the same issue. Please fix this issue!!
