### ISSUE TITLE
Wrong type in plugin purchases

### ISSUE THREAD

**Issue by davidecampello** [ionic-team/ionic-native#3704]
**I'm submitting a ...**
[X] bug report

**Current behavior:**
at row 963 of file https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/purchases/index.ts
there is the availablePackages array defined as array with one element of type PurchasesPackage.

**Expected behavior:**
I think it should be ann array of multiple PurchasesPackage elements like readonly availablePackages: PurchasesPackage[];

**Comment by vegaro** [comment]
I believe this has been addressed in https://github.com/ionic-team/ionic-native/pull/3702/files

**Comment by davidecampello** [comment]
Thank you @vegaro!
