### ISSUE TITLE
TODO: cordova-plugin-ms-adal

### ISSUE THREAD

**Issue by hieuld** [ionic-team/ionic-native#372]
[cordova-plugin-ms-adal](https://github.com/AzureAD/azure-activedirectory-library-for-cordova)

Could you merge this plugin into ionic-native? Thanks

**Comment by jbagaresgaray** [comment]
Any update or progress for this? Coz I would like to try it :)

**Comment by babilog** [comment]
Any updates? Can someone link me to any documentation that I could reference to maybe begin porting the Cordova plugin to Ionic Native?

**Comment by danielsogl** [comment]
Hey @hieuld, I will take a look in too this plugin!

**Comment by sonu-ajay** [comment]
Can anyone share example of implementing cordova-plugin-ms-adal with ionic
