### ISSUE TITLE
ToDo: Digits Plugin

### ISSUE THREAD

**Issue by philipphalder** [ionic-team/ionic-native#402]
Hello,

it would be great if someone is able to build a Plugin for Digits.

https://get.digits.com

Ionic1:
https://github.com/cosmith/cordova-digits
https://github.com/nifino/twitter-digits-plugin

thank you

**Comment by joshbabb** [comment]
https://get.digits.com/blog/digits-is-now-shut-down

> Digits is now shut down
> October 2, 2017

This issue should thus be closed, @ihadeed

**Comment by danielsogl** [comment]
@joshbabb Thanks for the hint!
