### ISSUE TITLE
TODO: Add support for SQLlite 2 plugin

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-native#455]
https://github.com/nolanlawson/cordova-plugin-sqlite-2

**Comment by ihadeed** [comment]
Should we replace the existing SQLite plugin with this?

**Comment by danielsogl** [comment]
@ihadeed I think we can close it because they stopped the development.

**Comment by joshbabb** [comment]
> Latest commit 33afdef  on Jun 20, 2016

Looks dead to me!

**Comment by danielsogl** [comment]
I close this issue because they stoped the development
