### ISSUE TITLE
Add cordova-hot-code-push plugin

### ISSUE THREAD

**Issue by Manduro** [ionic-team/ionic-native#482]
An amazing plugin with similar functionality to Ionic Deploy, except it can be used on your own server.

https://github.com/nordnet/cordova-hot-code-push

**Comment by ihadeed** [comment]
We just merged cordova-code-push-plugin by Microsoft in this PR https://github.com/driftyco/ionic-native/pull/420 

We can add this too eventually.

**Comment by danielsogl** [comment]
@Manduro I will take a look into this!

**Comment by danielsogl** [comment]
@Manduro looks like this plugin is not maintained anymore. There are over 100 open issues.
