### ISSUE TITLE
EstimoteBeacons no longer maintained

### ISSUE THREAD

**Issue by NgYueHong** [ionic-team/ionic-native#558]
This is to report to you that EstimoteBeacons (http://ionicframework.com/docs/v2/native/estimotebeacons/) is now no longer maintained. So, I guess it's best to have it removed and adding others to bring eddystone support to ionic.

**Comment by mlynch** [comment]
Is there a better plugin we can support instead?

**Comment by ihadeed** [comment]
@NgYueHong is suggesting adding support to this plugin here (made by the same developer): https://github.com/evothings/cordova-eddystone

I just read the note that the `estimotebeacons` developer left in the README file. It says to use the `iBeacon` plugin, which we already have a wrapper for in ionic-native. 

I think there is no harm in leaving the Estimote Plugin for now, in case anyone is using it. We can leave the same note in the docs suggesting to use iBeacon plugin instead.

**Comment by richardshergold** [comment]
At the Ionic UK meetup last night we had a talk from Aaron Czichon and he said he was working on adding support to Ionic Native for Estimote Beacons in the "next few weeks"

**Comment by Inoverse** [comment]
Didn't expected that the plugin is no longer maintained. I will have a look at the plugin and the Estimote SDK in the upcoming weeks. I'll try to maintain it and extend it with the new Estimote SDK. If this is successful, I'll also create the Native plugin.
