### ISSUE TITLE
Idea: visual debugging aids

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-native#585]
One thing that might be helpful is a "debug" mode where calls to plugins that aren't installed can trigger alerts, along with ways to mock data or "run" an app and control it (think a side menu with plugins to access to send to the app running inside this app)

**Comment by ihadeed** [comment]
So you're thinking of disabling the current console logs unless debug mode
is enabled?

We could call a function before bootstrapping the app. Just like how we
call enableProdMode() in angular 2. Maybe we can even intercept the
enableProdMode() call somehow to save some time for Ionic 2 users.

As for the side menu idea, are you thinking to inject a side menu in any
app? Or to create a demo application that tests all plugins with ability to
provide params (similar to the new features in Ionic Creator)?
