### ISSUE TITLE
Please add cordova-plugin-zeroconf as a plugin

### ISSUE THREAD

**Issue by NeoLSN** [ionic-team/ionic-native#636]
Please consider to add this https://github.com/becvert/cordova-plugin-zeroconf plugin in ionic-native.

**Comment by ghenry22** [comment]
This would be an interesting one to allow ionic apps to find other instances of the app or other services on the network

**Comment by danielsogl** [comment]
@NeoLSN you can close this issue.

**Comment by danielsogl** [comment]
@ihadeed can you close it?
