### ISSUE TITLE
Can't get position for Polygon click event

### ISSUE THREAD

**Issue by emilio-simoes** [ionic-team/ionic-native#650]
In cordova-plugin-googlemaps the click event has two parameters, the first one is the clicked polygon and the second one is the clicked position:

```
polygon.on(plugin.google.maps.event.OVERLAY_CLICK, function(overlay, latLng) {
  // Handle event
});
```

But ionic-native uses an Observable that only passes through the polygon object leaving the position inaccessible.

The clicked position should be accessible in the event.

**Comment by ihadeed** [comment]
I'll look into a solution for this. Possibly converting the args to an object so it becomes function({overlay; latlng;}){} instead of what you have there.

In the meanwhile, here's a work around:
```
let myMap = new GoogleMap(....);

myMap._objectInstance.on(GoogleMapsEvent.OVERLAY_CLICK, (overlay, latLng) => {
   // do something with the data here
});
```

**Comment by emilio-simoes** [comment]
I'll be looking forward for the solution, thanks.

In the meanwhile I've found that same fix after a while but with a small difference. Since the 'objectInstance' is private an to avoid typescript compilation errors I'm registering the event like this:

```
myMap['_objectInstance'].on(GoogleMapsEvent.OVERLAY_CLICK, (overlay, latLng) => {
   // do something with the data here
});
```

It works the same way and I don't get that nasty error when running the app.

**Comment by ihadeed** [comment]
Ok so I looked into this. Observables can only pass one argument in their callback.

So I thought about a work around but I'm still not 100% sure if it's a good one. 

The observable will check the number of arguments the callback function has, if it's more than 1, it will return an array of arguments rather than just the first one.
```
// if you're expecting something like (eventInfo: any) => {}
GoogleMap.on('MAP_READY').subscribe(data => {
  // data will be a single value
});

// if you're expecting something like (overlay, latlng) => {}
GoogleMap.on('OVERLAY_CLICK').subscribe(data => {
  // data will be an array with 2 values in it
  //  [overlay, latLng]
});

```

**Comment by emilio-simoes** [comment]
Personally I think it's an acceptable solution. May become a it confusing but at least the position is accessible and I believe that to be more important.

If I may just do another suggestion, I think you should consider doing the same for the 'one' event handler also since the events can be subscribed both on the 'on' and 'one', thus making the plugin behavior consistent.
