### ISSUE TITLE
Cannot change StatusBar color when using Crosswalk in Ionic 2 RC (Appears blue with white text)

### ISSUE THREAD

**Issue by escobar5** [ionic-team/ionic-native#689]
There seems to be a problem when using Crosswalk on Ionic2 RC. It doesn't seem to be possible to change the StatusBar color, it always appears blue with white text.

https://forum.ionicframework.com/t/ionic-rc0-plugin-statusbar-not-working-in-android-with-crosswalk/66449/3

**Comment by ihadeed** [comment]
This would be an issue with the plugin or with crosswalk.

**Comment by Tobiaswk** [comment]
I would like to have this issue reopened. It seems that there is a shortcoming with the Platform class.

My evidence;
```
platform.ready().then(() => {
      setTimeout(() => {
        StatusBar.backgroundColorByHexString('#7c7472'); // set status bar to white
      },1000);
    });
```
It seems like Platform.ready method signals "ready" too early. When introducing a timeout like in the above code the statusbar is filled with the correct color.

**Comment by ihadeed** [comment]
@Tobiaswk what version of Ionic are you using?

**Comment by Tobiaswk** [comment]
@ihadeed I'm on RC3.

**Comment by escobar5** [comment]
Can confirm that, that is the workaround people is using for the moment: https://forum.ionicframework.com/t/ionic2-rc0-and-ionic2-rc1-plugin-statusbar-not-working-in-android-with-crosswalk/66449/18

The problem is that when viewed in task manager it's still blue.

Also, people are reporting this only happens with ionic

**Comment by mlynch** [comment]
Thanks for the info everyone. It seems suspect this would only be related to ionic. As a test, can you try going outside of Ionic and doing something like:

```javascript
document.addEventListener("deviceready", function() {
  window.StatusBar.backgroundColorByHexString('#7c7472');
}, false)
```

**Comment by markharding** [comment]
Resolved this by changing `<meta name="theme-color" content="#4e8ef7">` in index.html

**Comment by Artfloriani** [comment]
@markharding This resolved the issue for me, cheers.

It seems that Statusbar is setting the app color on deviceready, then this tag on index.html is overriding it.

**Comment by tompradana** [comment]
This code worked for me:

```
constructor(public platform: Platform) {
        if ( this.platform.is('android') ) {
            this.platform.ready().then(() => {
                // Okay, so the platform is ready and our plugins are available.
                // Here you can do any higher level native things you might need.
                Splashscreen.hide();
                StatusBar.overlaysWebView(false);
                StatusBar.backgroundColorByHexString('#00FFFF');
            });
        }
    }
```
