### ISSUE TITLE
TODO: QRScanner

### ISSUE THREAD

**Issue by ihadeed** [ionic-team/ionic-native#715]
https://github.com/bitpay/cordova-plugin-qrscanner

**Comment by John-Luke** [comment]
It's really necessary? In [ZBar docs](https://github.com/tjwoon/csZBar/blob/master/README.md) say that ZBar plugin can read QR

**Comment by ihadeed** [comment]
This plugin is more configurable and it works differently, some people might prefer it over ZBar. Also has browser platform support.

**Comment by melkir** [comment]
The embeddable view with the webview component is very interesting

**Comment by renshuki** [comment]
+1 for the embed QR scanner.

**Comment by Gillardo** [comment]
I agree, please add

**Comment by danielsogl** [comment]
@ihadeed on my list

**Comment by Lyfei** [comment]
> 

not found

**Comment by Lyfei** [comment]
> @ihadeed on my list

Not found

**Comment by ryaa** [comment]
This [PR](https://github.com/danielsogl/awesome-cordova-plugins/pull/4492) should add support for the qr-scanner cordova plugin
