### ISSUE TITLE
TODO: Mapbox - Native maps 

### ISSUE THREAD

**Issue by ihadeed** [ionic-team/ionic-native#716]
https://github.com/Telerik-Verified-Plugins/Mapbox

**Comment by appwrx** [comment]
+1

**Comment by kemalcany** [comment]
👍

**Comment by dragonfire1119** [comment]
I see this is back in 2016. Do we have a ETA on when this might be done? Thanks...

**Comment by danielsogl** [comment]
Cane be closed since the plugin already supports typescript
