### ISSUE TITLE
TODO: Update google maps plugin

### ISSUE THREAD

**Issue by mhartington** [ionic-team/ionic-native#751]
The maintainers of the google maps plugin have reached out and mention that they've revamped the plugins API

https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Migrate-from-v1-to-v2

https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps/www

We should update the plugin to match the new API and make a note of the required version

**Comment by ihadeed** [comment]
I think we should wait till they release v2 stable then we can update our wrapper.

**Comment by jstoup111** [comment]
Is there a way I can patch this in the meantime until they've released you've updated the wrapper?

Specifically, I'm not able to actually call any touch or click events on the map. I'm not sure if this is a bug in v2, or in ionic.

**Comment by dyew** [comment]
Yes, there are a few methods deprecated and some methods renamed in V2 of the plugin. Details here: [Migrate from v1 to v2](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Migrate-from-v1-to-v2)

I need help with injecting several GoogleMaps Native components into Ionic V1. There is no problem injecting $cordovaGoogleMap into Ionic V1, but there are a few classes, const and interfaces in the plugin that also need to be imported but are not handled by the initAngular1() function in native:

Example:
- export const GoogleMapsEvent
- export class GoogleMapsMarker
- export class GoogleMapsCircle
- export class Geocoder

How can I import these into ionic V1?

**Comment by RafaelKr** [comment]
Hi, I would like to do this update to v2, as I need it soon.

1. For which branch should I add this? master or v3?
2. Should I create new definitions named "googlemap-v2" or should I extend the existing one with the new/renamed functions?

**Comment by ihadeed** [comment]
@RafaelKr 

You should build it based on the `v3-injectable` branch since that will be the next release. If you build it based on `v3` or `master` we can port it later on to `v3-injectable`.

You should modify the existing definitions to match the updated API. There is no need to create a new one. 

Please note that we're still not going to merge it until Google Maps plugin v2 is stable (they announced that it will be released very soon).

**Comment by jorgutpar** [comment]
@ihadeed 
Hello, do you have any news on this? I'm still waiting for them to make the version 2 stable

**Comment by ihadeed** [comment]
Closed by #1759
