### ISSUE TITLE
[Feature request]: Ensure observables trigger change detection

### ISSUE THREAD

**Issue by amuramoto** [ionic-team/ionic-native#823]
It appears that when Ionic Native observables return, they do not always kick off change detection. This means the user has to call something like `ChangeDetectorRef.detectChanges()` manually.

Should all observables automatically call change detection when they emit?

**Comment by Bouzmine** [comment]
+1

**Comment by ihadeed** [comment]
A work around I came across is setting the change detection strategy to `ChangeDetectionStrategy.OnPush`.

**Comment by tkem** [comment]
@ihadeed: It's a viable workaround when using the Observable directly as a component input, though http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html#observables suggests that `markForCheck()` may still be needed. Using an `async` pipe *may* work around even this. too, but I haven't tested that yet.

Still, AFAICS `ionic-native` claims to ensure change detection is triggered "automatically" for Observables right on its front page: https://github.com/driftyco/ionic-native#promises-and-observables; to me, that suggests a behavior similar to DOM events, or Promises as provided by the zone.js wrappers.

**Comment by tkem** [comment]
Any news on this? I still see ionic-native making claims about "easy to use plugins with Angular change detection" on its front page...

**Comment by ihadeed** [comment]
This issue can be fixed by upgrading your app to use Angular 4 instead of Angular 2.

At the moment, the official Ionic 2 app base still uses Angular 2. My guess is that they will upgrade it to Angular 4 once Ionic 3 is ready for production.

I'm using `ionic-angular@2.3.0` with Angular 4 in this demo app here and it works well: https://github.com/ihadeed/ionic-native-playground

**Comment by tkem** [comment]
Great news, @ihadeed, thank you!

**Comment by tubaman** [comment]
I'm on the latest ionic(3.3.0) with the angular(4.1.2) that it depends on and I still have the same issue.

**Comment by ihadeed** [comment]
@tubaman could you share a code that we can use to reproduce the issue?

**Comment by BaHXeLiSiHg** [comment]
Faced same problem, will try to share...

In "App" module a have my custom module - "Basic":
`
@NgModule({
    imports: [
        BrowserModule,
        IonicModule.forRoot(CyclingRoutesApp),
        BasicModule
    ],
    declarations: [
       <<any name app>>
    ],
    bootstrap: [
        IonicApp
    ],
    entryComponents: [
        <<any name app>>
    ],
    providers: [
        StatusBar,
        SplashScreen,
        { provide: ErrorHandler, useClass: IonicErrorHandler }
    ]
})
export class AppModule {}
`
"Basic" module contains 2 components and service:
`
@NgModule({
    imports: [
        IonicModule
    ],
    declarations: [
        BasicComponent,
        TrackingComponent
    ],
    entryComponents: [
        TrackingComponent
    ],
    providers: [
        BasicService
    ],
    exports: [
        BasicComponent
    ]
})
export class BasicModule {}
`

"Basic" service provides simple event emitter:
`
@Injectable()
export class BasicService {
    public menuStateEmitter = new EventEmitter<boolean>();

    constructor() {}
}
`

Template of "Basic" component has menu:
`
<ion-menu type="push" [content]="basicNavigation" (ionOpen)="menuOpened()"></ion-menu>
`

When menu is opened - fires function "menuOpened()", it triggers emitter, that was created in service like this - "this._basicService.menuStateEmitter.next(true);" ("Basic" service imported in "Basic" component "import { BasicService } from './basic.service';").

In mine second component ("Tracking", also it has simple template) i have listener (Subscription type):
`
this._menuStateListener = this._basicService.menuStateEmitter.subscribe((isActive: boolean) => {
    this.isMenuActive = isActive;
});
`

It listening emitter and change boolean variable, it is shown in DOM:
`
active - {{ isMenuActive }}
`

Every time on event emitt - "this.isMenuActive" changing it's value (watching in debugger), but DOM value never changes, untill calling "ChangeDetectorRef.detectChanges();";

**Comment by BaHXeLiSiHg** [comment]
Well, just builded application and noticed that DOM refreshes as expected, even without `ChangeDetectorRef.detectChanges();`. So, issue appear only in browser `ionic serve`. Hope that will help to figure out why it's happening.
