### ISSUE TITLE
Ionic V1 Google Maps Events Problem

### ISSUE THREAD

**Issue by allurco** [ionic-team/ionic-native#915]
Hi, the documentation just covers Ionic 2, but I am trying to use this on a V1 project:

```
map = new $cordovaGoogleMap(mapCanvas);
map.one($cordovaGoogleMapsEvent.MAP_READY).then(function(r) {
       console.log('Map is ready!');
 });
```

But it throws:
`Unknown provider: $cordovaGoogleMapsEventProvider <- $cordovaGoogleMapsEvent. `

What is wrong with it?

**Comment by ihadeed** [comment]
Closing this issue since Ionic Native v5 includes all bug fixes/features and it supports Ionic 2.x apps.
