### ISSUE TITLE
RC4 - [BUG] - Plugin Network not installed

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-native#951]
_From @FanYeeChok on January 9, 2017 3:57_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Steps to reproduce:**

1.  Install plugin
`ionic plugin add cordova-plugin-network-information`
2. Write following code
```
import { Network } from 'ionic-native';

 if (Network.connection === 'wifi') {
      console.log('we got a wifi connection, woohoo!');
}
```

3. Error
`[Warning] Native: tried calling Network.connection, but the Network plugin is not installed. (ionic.native.min.js, line 4) [Warning] Install the e plugin: 'ionic plugin add cordova-plugin-network-information' (ionic.native.min.js, line 4)`

Note: Tried `Network.type` also display same error.

**Other information:**
Plugin using
https://ionicframework.com/docs/v2/native/network/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

_Copied from original issue: driftyco/ionic#9918_

**Comment by jgw96** [comment]
_From @jsayol on January 9, 2017 11:20_

Hi @FanYeeChok! It might be better if you open this issue on the ionic-native repo instead: https://github.com/driftyco/ionic-native

**Comment by jgw96** [comment]
_From @AndreasGassmann on January 9, 2017 11:56_

The plugin works fine for me with Ionic RC4.

Can you try updating to the latest Ionic Native version? Maybe also update your ionic CLI.

FYI: 3 weeks ago the API of the Network Plugin changed. It is now `Network.type` instead of `Network.connection`. https://github.com/driftyco/ionic-native/commit/ec5e27be4b1455ad5b0ee4ea2da5592e63be3dea .

**Comment by mhartington** [comment]
Was this running on a device or via ionic-serve?

**Comment by ihadeed** [comment]
Since ionic-native  v2.2.12 it's `Network.type` instead of `Network.connection`. See change log here: https://github.com/driftyco/ionic-native/releases/tag/v2.2.12

**Comment by jsayol** [comment]
Just FYI, @FanYeeChok did already mention they tried that:
> Note: Tried Network.type also display same error.

**Comment by FanYeeChok** [comment]
This happened because we are upgraded from RC2 -> RC4.

Here my other developer machine info and scenario:
1. Update to latest ionic-native but still getting the same issue.
2. `ionic start` a brand new v2 project but still getting the same issue.


latest ionic info: 
```
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.3.1
Xcode version: Not installed
```

package.json file:
```
{
 "name": "ionic-hello-world",
 "author": "Ionic Framework",
 "homepage": "http://ionicframework.com/",
 "private": true,
 "scripts": {
   "clean": "ionic-app-scripts clean",
   "build": "ionic-app-scripts build",
   "ionic:build": "ionic-app-scripts build",
   "ionic:serve": "ionic-app-scripts serve"
 },
 "dependencies": {
   "@angular/common": "2.2.1",
   "@angular/compiler": "2.2.1",
   "@angular/compiler-cli": "2.2.1",
   "@angular/core": "2.2.1",
   "@angular/forms": "2.2.1",
   "@angular/http": "2.2.1",
   "@angular/platform-browser": "2.2.1",
   "@angular/platform-browser-dynamic": "2.2.1",
   "@angular/platform-server": "2.2.1",
   "@ionic/storage": "1.1.7",
   "ionic-angular": "2.0.0-rc.4",
   "ionic-native": "2.2.14",
   "ionicons": "3.0.0",
   "rxjs": "5.0.0-beta.12",
   "zone.js": "0.6.26"
 },
 "devDependencies": {
   "@ionic/app-scripts": "0.0.47",
   "typescript": "2.0.9"
 },
 "cordovaPlugins": [
   "cordoba-plugin-console",
   "cordova-plugin-statusbar",
   "cordova-plugin-whitelist",
   "cordova-plugin-splashscreen",
   "cordoba-plugin-device",
   "ionic-plugin-keyboard"
 ],
 "cordovaPlatforms": [],
 "description": "test: An Ionic project"
}
```


Code below is used:
```
if (Network.type == "wifi") {

console.log("123");

}
```
On browser:
```
[Warning] Native: tried calling Network.type, but the Network plugin is not installed.
[Warning] Install the Network plugin: 'ionic plugin add cordova-plugin-network-information'
```
On device (Android):
`the console is not being called.`

Are there any possible problems that can cause the installed plugin not being detected?

**Comment by NoNameProvided** [comment]
Dont you have to wrap it into a `platform.ready()` call? RC4 became faster, maybe it's reach that code part faster than before, and plugins are not loaded yet. 

 Or do all ionic-native call wait until `platform.ready()` is fired @ihadeed?

**Comment by ihadeed** [comment]
@NoNameProvided yes, you do need to wait for `platform.ready()` before doing anything.

**Comment by leongzw** [comment]
I'm facing the same problem as well. Everything is working fine during RC2 development. However, only the cordova-plugin-network-information hit this issue after upgraded to RC4. I have also tried to ionic start a new v2 project and only added this plugin, but it's still not being detected.

@NoNameProvided I'm not using it when initiating the applications, but I do check the network condition after the application is fully ready such as when navigating to another page.

I do appreciate for any suggested possible solutions, I would try them all since I have really no idea how to get rid of this issue.

**Comment by NoNameProvided** [comment]
> @NoNameProvided yes, you do need to wait for platform.ready() before doing anything.

Could be a good improvement. ;) I have been toying with the idea of making a PR for this and a few other stuff. Maybe will do when I have some more time.

**Comment by larssn** [comment]
Using `ionic-native@latest (seems to be 2.5.1)` and `ionic-angular 1.0.1` I have the same problem.

The plugin seems to be installed, because I can subscribe to onConnect etc, but the warning still appears.

However the `type` property on `Network` is null, including inside a `platform.ready()`.
Also checked the previous `Network.connection`, but that just yielded an empty object.

```
platform.ready()
            .then(name => {
                    this.listenForConnectivity();
            });

protected listenForConnectivity() {
        let connectSubscription = Network.onConnect()
            .subscribe(() => {
                setTimeout(() => {
                    console.info('CONNECTION', Network.type);
                    //console.info('CONNECTION', Network.connection);
                    if (Network.type === 'wifi') {
                        console.log('we got a wifi connection, woohoo!');
                    }
                }, 3000);
            });
    }
```

**Comment by oddcb** [comment]
Anyone found a solution or workaround? I have the same issue with ionic 2.2 and Ionic Native 2.4.1

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.7.3
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by oddcb** [comment]
Sorry, it all boiled down to the plugin missing from cordovaPlugins in `package.json`. It was present in config.xml after `ionic plugin add cordova-plugin-network-information`, but when doing a ionic state reset I noticed it not being installed. Added it manually to `package.json` and now its working here at least.

**Comment by FanYeeChok** [comment]
Temporary solution is downgrade the version. Our package.json

```
...
    "ionic-angular": "2.0.0",
    "ionic-native": "2.2.11",
...
```

**Comment by gabeta** [comment]
Temporary solution is downgrade the version. Our package.json

`...
    "ionic-angular": "2.0.0",
    "ionic-native": "2.2.11",
...`

I have same problem

**Comment by theomathieubhvr** [comment]
I confirm the same issue with ionic native 3.5.0
