### ISSUE TITLE
SQLite selfTest

### ISSUE THREAD

**Issue by brodybits** [ionic-team/ionic-native#963]
First I would like to thank your team for supporting sqlite in general. I think it is one of the harder plugins to support.

I did notice that sqlite.ts supports the echoTest function. I think it would be great if you can support selfTest as well. The echoTest verifies basic plugin installation and that the code does wait for the `deviceready` event. The selfTest function also verifies that the sqlite plugin can actually create a database, execute the CRUD (create, read, update, and delete) operations, and verify the results.

In addition it would be nice if the documentation can describe how the user should use echoTest (and selfTest) and *why* (verify basic installation, etc).

**Comment by brodybits** [comment]
> added: 241f073

Does this actually call selfTest on cordova-sqlite-storage plugin?

**Comment by danielsogl** [comment]
Sure!
